import type { PublicLocale } from "../../../lib/public-locale";

/** English counterparts of the owner-supplied Japanese event copy. */
const english = {
  "受付・環境確認": "Check-in and setup check",
  "IBM Quantum、Qiskit、Google Colab等を確認": "Check IBM Quantum, Qiskit, Google Colab, and other tools.",
  "開会": "Opening",
  "イベント趣旨と2日間の流れを説明": "Introduction to the event and the two-day program.",
  "Quanmatic講演": "Quanmatic talk",
  "齋藤善仁氏": "齋藤善仁",
  "質疑応答": "Q&A",
  "休憩": "Break",
  "Blueqat講演": "Blueqat talk",
  "湊雄一郎氏": "湊雄一郎",
  "昼食": "Lunch",
  "Qiskit 101": "Qiskit 101",
  "QiskitとIBM Quantumの基本操作": "Basic operations in Qiskit and IBM Quantum.",
  "SQDハンズオン": "SQD hands-on workshop",
  "課題・審査基準説明": "Challenge and judging briefing",
  "課題、提出物、評価項目を説明": "Overview of the challenges, deliverables, and judging criteria.",
  "最適化ハンズオン": "Optimization hands-on workshop",
  "最適化課題の立て方と実装の進め方を学ぶ": "Learn how to frame and implement an optimization challenge.",
  "チーム編成": "Team formation",
  "テーマ選択、役割分担": "Choose a theme and assign roles.",
  "ハッカソン準備": "Hackathon preparation",
  "テーマと実験計画を整理し、開発環境を準備": "Choose a theme, plan your experiments, and prepare your development environment.",
  "ハッカソン": "Hackathon",
  "チェックポイント": "Checkpoint",
  "進捗と質問事項をフォームで提出": "Submit progress and questions through a form.",
  "小山尚彦先生 講演・質疑": "小山尚彦 — Talk and Q&A",
  "IBM Quantum渡邉毅氏講演・質疑": "IBM Quantum: 渡邉毅 — Talk and Q&A",
  "田中宗先生 講演・質疑": "田中宗 — Talk and Q&A",
  "希望チームは作業継続可能": "Teams may continue working if they wish.",
  "最終提出締切": "Final submission deadline",
  "Notebook、成果物URL、発表用スライドを提出": "Submit your notebook, project URL, and presentation slides.",
  "提出確認": "Submission check",
  "リンクの閲覧可否のみ確認": "Check only that submitted links are accessible.",
  "チーム発表・質疑": "Team presentations and Q&A",
  "最大10チーム、各4分": "Up to 10 teams, 4 minutes each.",
  "審査": "Judging",
  "15分間で採点を集計": "Tally scores in 15 minutes.",
  "表彰・閉会式・記念撮影": "Awards, closing ceremony, and group photo",
  "受賞発表、講評、閉会と記念撮影": "Award announcements, feedback, closing, and group photo.",
  "スケジュールは変更になる場合があります。": "The schedule is subject to change.",

  "2026年10月17日・18日、慶應義塾大学AICで開催。講演、Qiskitハンズオン、チームで取り組むミニハッカソン。初心者歓迎。": "October 17–18, 2026 at Keio University AIC. Talks, hands-on Qiskit workshops, and a team mini hackathon. Beginners welcome.",
  "回路をつくる": "Build a circuit",
  "Qiskitで量子ビットとゲートを組み合わせ、自分の量子回路を作成します。": "Combine qubits and gates in Qiskit to build your own quantum circuit.",
  "動かして、確かめる": "Run it. See what happens.",
  "IBM Quantum PlatformやGoogle Colabを使う演習を予定しています。実行環境は事前にご案内します。": "Exercises using IBM Quantum Platform and Google Colab are planned. We will share setup instructions before the event.",
  "チームで試す": "Experiment together",
  "ガイド付き演習のあとはミニハッカソンへ。仲間とアイデアを持ち寄り、コードにします。": "Follow guided exercises with a mini hackathon. Bring your ideas together and turn them into code.",
  "成果を共有する": "Share what you discover",
  "取り組んだテーマや実装、そこから得た発見を発表します。": "Present your project, your implementation, and what you learned along the way.",
  "量子コンピュータを初めて学びます。参加できますか？": "I am new to quantum computing. Can I join?",
  "初心者歓迎です。ガイド付きのQiskit演習を予定しています。必要なPythonや数学の知識、事前学習については準備が整い次第ご案内します。": "Beginners are welcome. Guided Qiskit exercises are planned. We will share any Python, math, and preparation requirements once they are ready.",
  "慶應義塾大学以外の学生や、社会人も参加できますか？": "Can students from other universities and working professionals join?",
  "参加対象は調整中です。確定次第、このページでお知らせします。": "Eligibility details are being finalized. They will be published on this page once confirmed.",
  "どちらか1日だけでも参加できますか？": "Can I attend just one day?",
  "1日だけの参加が可能かどうかは調整中です。登録フォームでは、参加を希望する日をお伺いする予定です。": "Single-day attendance is still being considered. The registration form is expected to ask which days you would like to attend.",
  "参加費はいくらですか？": "How much does it cost?",
  "参加費は無料です。": "Attendance is free.",
  "チームを組んでから申し込む必要がありますか？": "Do I need a team before registering?",
  "ミニハッカソンはチームでの参加を予定しています。事前にチームを組む必要があるかなど、詳しい参加方法は確定次第ご案内します。": "A team mini hackathon is planned. Team sizes and the formation process will be announced once confirmed.",
  "会場で写真や動画の撮影はありますか？": "Will there be photography or filming?",
  "参加登録時に、写真・動画の撮影に同意するかをお伺いする予定です。撮影の範囲や利用目的、撮影を希望しない方への対応は、登録フォームでご案内します。": "We plan to ask for photo and video consent during registration. The form will explain what will be recorded, how it will be used, and the arrangements for those who do not consent.",
  "本文へ移動": "Skip to content",
  "IBM Quantum — イベントの先頭へ": "IBM Quantum — back to event top",
  "イベント内ナビゲーション": "Event navigation",
  "イベント概要": "About",
  "プログラム": "Program",
  "会場": "Venue",
  "参加登録": "Register",
  "土": "Sat",
  "日": "Sun",
  "慶應義塾大学 AIC": "Keio University AIC",
  "対面開催": "In person",
  "参加条件をご確認のうえ、お申し込みください。": "Please review the eligibility requirements before registering.",
  "参加登録は準備中です。": "Registration is being prepared.",
  "つくる。試す。": "Build. Experiment.",
  "量子で考える。": "Think quantum.",
  "はじめの一歩から、": "From your first steps",
  "ひとつのアイデアへ。": "to an idea of your own.",
  "量子コンピューティングに興味がある。": "Curious about quantum computing?",
  "そんな方に向けた、2日間のイベントです。": "That is your starting point for these two days.",
  "講演で量子計算の研究や活用事例を知り、Qiskitの実習でコードを書きます。ミニハッカソンではチームで課題に取り組み、成果を発表します。慶應義塾大学AICで、一緒に量子計算を体験しましょう。": "Explore research and real-world practice through talks, then write code in hands-on Qiskit workshops. Work together in a mini hackathon and present what you tried. Experience quantum computing with us at Keio University AIC.",
  "開催形式": "Format",
  "対面": "In person",
  "必要な経験": "Experience",
  "初心者歓迎": "Beginners welcome",
  "定員": "Capacity",
  "40〜50名": "40–50 people",
  "予定": "Planned",
  "2日間のプログラム": "The two-day program",
  "基礎講義からハンズオン、チームでの制作と成果発表まで。": "From the fundamentals to hands-on workshops, team projects, and presentations.",
  "ガイド付きミニハッカソン": "Guided mini hackathon",
  "1チーム4〜5名、最大10チームでの実施を予定しています。講義や実習で学んだことを生かし、メンターに相談しながらコードを動かして、結果と考察をノートブックにまとめます。": "We plan to form up to 10 teams of 4–5 people. Apply what you learn in the lectures and workshops, with mentor support, to produce a working notebook and discuss your findings.",
  "課題候補 · どちらか1つを選択": "Proposed challenges · Choose one track",
  "SQD実験": "SQD experiments",
  "サンプル数などの条件を変え、推定結果や計算量の違いを比較します。結果をグラフで示し、考察とあわせてノートブックにまとめます。": "Vary conditions such as sample count and compare estimates and computational cost. Summarize your work in a notebook with comparison plots and discussion.",
  "最適化への応用": "Optimization applications",
  "小規模な配送や割り当てを題材に、仮想の問題を数式で表し、解法を比較します。目的関数、制約条件、比較結果をノートブックに整理します。": "Formulate a small hypothetical routing or assignment problem and compare solution methods. Document the objective, constraints, and results in a notebook.",
  "課題の詳細と提出方法は当日ご案内します。内容は変更になる場合があります。": "Challenge details and submission instructions will be provided at the event. Content is subject to change.",
  "アイデアからコードまで。": "From idea to code.",
  "演習で使用予定": "Planned for the workshops",
  "会場と参加の準備": "Venue and preparation",
  "キャンパス・建物・部屋番号、会場までの経路は、確定次第ご案内します。": "The campus, building, room, and directions will be announced once confirmed.",
  "アクセスを見る": "View directions",
  "持ち物・パソコンの準備": "What to bring",
  "ノートパソコンと充電器": "A laptop and charger",
  "演習に使うブラウザー": "A browser setup suitable for the workshops",
  "必要に応じて筆記用具": "Something to take notes with, if needed",
  "対応OSや必要なソフトウェア、アカウントなど、事前に準備していただく内容は後日ご案内します。": "We will share supported operating systems, software, required accounts, and other setup details before the event.",
  "この秋は、": "This fall,",
  "量子計算に挑戦。": "explore quantum computing.",
  "2026年10月17日（土）・18日（日）": "Saturday, October 17 & Sunday, October 18, 2026",
  "慶應義塾大学 AIC / 定員40〜50名（予定）": "Keio University AIC / Planned capacity: 40–50",
  "参加条件をご確認のうえ、登録フォームへお進みください。": "Review the eligibility requirements, then continue to the registration form.",
  "参加登録フォームへ": "Open registration form",
  "登録受付は準備中です": "Registration is being prepared",
  "受付開始まで、もうしばらくお待ちください。": "Please check back when registration opens.",
  "受付開始をお待ちください": "Registration coming soon",
  "登録フォームでは、氏名、所属、メールアドレス、経験、参加希望日をご記入のうえ、撮影に同意するかどうかをお選びください。": "The form asks for your name, affiliation, email, experience, preferred attendance days, and photo/video consent.",
  "よくある質問": "Frequently asked questions",
  "行動指針とお問い合わせ": "Code of Conduct and contact",
  "行動指針": "Our community guidelines",
  "背景や経験の違いを尊重し、互いの学びを支える場を目指します。ハラスメント、差別的な言動、同意のない撮影や情報公開は認めません。困ったことがあれば、当日の運営スタッフにご相談ください。": "We aim to support each other's learning and respect different backgrounds and experience levels. Harassment, discrimination, and recording or sharing information without consent are not permitted. Please contact event staff if you need help.",
  "行動指針の詳細": "Read the guidelines",
  "参加者・登壇者・運営スタッフを含む、本イベントに関わるすべての方に、この行動指針を守っていただきます。相手の発言や作業を尊重してください。": "Everyone involved, including participants, speakers, and staff, must follow these guidelines. Respect other people's contributions and work.",
  "不適切な行為を見聞きした際や、対応に困った際は、当日の運営スタッフ、または以下のメールアドレスへご相談ください。": "If you experience or witness inappropriate behavior, or are unsure how to respond, contact event staff or email the address below.",
  "お問い合わせ": "Contact",
  "イベント専用の問い合わせ先は準備中です。": "An event contact address is being prepared.",
  "確定次第、こちらに掲載します。": "It will be published here once confirmed.",
  "主催・協力": "Organizers and supporters",
  "主催": "Organizers",
  "協力": "Supported by",
  "Leona Quantum ホーム": "Leona Quantum home",
  "ページの先頭へ ↑": "Back to top ↑",
  "慶應義塾大学": "Keio University",
  "基礎講義とハンズオンで学び、チームで最初の実験に取り組みます。": "Learn through introductory lectures and hands-on workshops, then start your first team experiments.",
  "量子ビット数制約下における部分グローバー適応探索手法": "Adaptive partial Grover search under qubit-count constraints",
  "登壇予定 / 仮題": "Planned appearance / Provisional title",
  "講演内容調整中": "Talk details to be announced",
  "講演内容：調整中": "Talk details: to be announced",
  "登壇予定": "Planned appearance",
  "講演で知識を深め、チームでの実験・実装を進めます。最後に、取り組んだ内容と結果を発表します。": "Broaden your perspective through talks, continue your project, and present your experiments and results.",
  "慶應義塾大学教授": "Professor, Keio University",
  "Bio2Q 特任教授": "Project Professor, Bio2Q",
  "量子アニーリングについて": "Quantum annealing",
  "登壇予定 / 内容調整中": "Planned appearance / Details being finalized",
  "量子機械学習について": "Quantum machine learning",
  "表示する開催日": "Choose a program day",
  "当日の流れ": "Day schedule",
  "登壇者・講演内容は変更になる場合があります。確定次第、このページでお知らせします。": "Speakers and talk details are subject to change. Updates will be published on this page.",
  "登壇予定の講演者": "Meet the speakers",
  "研究や産業応用に携わる5名が、2日間にわたって講演する予定です。": "Five planned speakers across two days, sharing perspectives from research and industry.",
  "講演者": "Speakers",
  "言語": "Language"
} as const;

export function eventText(locale: PublicLocale, text: keyof typeof english): string {
  return locale === "en" ? english[text] : text;
}
