/**
 * Japanese names for the field labels records carry in `resources` (the
 * record page's at-a-glance rows) and in `metadata` (its facts table, which lists
 * both).
 *
 * The corpus writes these labels in English and the record page translates
 * them here. Until 2026-09-22 this map held 32 of the 262 labels in use, so a
 * Japanese reader saw "Record type" on 170 records, "Circuit" on 133 and
 * "Reported cost" on 90, beside Japanese chrome. `scripts/check-repository-data.mjs`
 * now fails on any `resources` or `metadata` label missing here, so a batch that adds a label
 * adds its translation in the same change.
 *
 * The values name the field, not its content: the recorded values stay as the
 * records wrote them.
 */
export const DATA_LABELS_JA: Readonly<Record<string, string>> = {
  "Qubits": "量子ビット",
  "Depth": "深さ",
  "Outcomes": "測定結果",
  "Shots": "ショット",
  "Queries": "クエリ数",
  "Phase": "位相",
  "Rotation layers": "回転レイヤー",
  "Gate family": "ゲート系統",
  "Bit order": "ビット順",
  "Export": "エクスポート",
  "Matrix": "行列",
  "Rotation": "回転",
  "Square": "二乗",
  "Power": "累乗",
  "Family": "系統",
  "Control": "制御",
  "Target": "対象",
  "Universal role": "普遍量子計算での役割",
  "Native form": "ネイティブ形式",
  "Decomposition": "分解",
  "Role": "役割",
  "Promise": "前提条件",
  "Quantum queries": "量子クエリ",
  "Classical queries": "古典クエリ",
  "Function": "関数",
  "Input register": "入力レジスタ",
  "Output register": "出力レジスタ",
  "Samples": "サンプル数",
  "Constraint": "制約",
  "Encoding": "符号化",
  "Transmission": "送信",
  "Readout": "読み出し",
  "Record type": "記録の種類",
  "Circuit": "回路",
  "Complexity basis": "計算量の根拠",
  "Reported cost": "報告されたコスト",
  "Primary source on the speedup": "高速化に関する一次資料",
  "Speedup class": "高速化の分類",
  "Speedup class (secondary source)": "高速化の分類（二次資料）",
  "Instance data": "インスタンスのデータ",
  "Representative form": "代表的な形",
  "Evidence": "根拠",
  "Conversion": "変換",
  "Execution": "実行",
  "Reference implementation": "参照実装",
  "Measurement": "測定",
  "Circuit model": "回路モデル",
  "Framework exports": "フレームワークへの出力",
  "Operations": "演算",
  "Parameter": "パラメータ",
  "Output": "出力",
  "State": "状態",
  "Hamiltonian": "ハミルトニアン",
  "Read depth": "読み出しの深さ",
  "Input": "入力",
  "Generator": "生成子",
  "Primary source": "一次資料",
  "Self-inverse": "自己逆",
  "Symmetry": "対称性",
  "Terms": "項",
  "Access": "アクセス",
  "Operator": "演算子",
  "Rotation axis": "回転軸",
  "Sites": "サイト",
  "Truth table": "真理値表",
  "Classical baseline": "古典的な比較基準",
  "Classical bits": "古典ビット",
  "Classical post": "古典後処理",
  "Commutation": "交換関係",
  "Decoder": "復号器",
  "Eigenvalues": "固有値",
  "Entangling gate": "もつれを作るゲート",
  "Excitations": "励起",
  "Formula": "式",
  "Free parameter": "自由パラメータ",
  "Inverse of": "逆演算の対象",
  "Locality": "局所性",
  "Metric": "指標",
  "Order": "次数",
  "Outcome": "測定結果",
  "Paper about this operator": "この演算子を扱う論文",
  "Shared resource": "共有リソース",
  "Signal": "信号",
  "Special case": "特別な場合",
  "Stabilizer generators": "スタビライザー生成子",
  "T-count": "Tゲート数",
  "Topology": "トポロジー",
  "1-RDM consistency": "1-RDM の整合性",
  "2-RDM consistency": "2-RDM の整合性",
  "2-step distribution": "2ステップ後の分布",
  "Acceptance": "受理の条件",
  "Algebra": "代数",
  "Ancilla": "補助量子ビット",
  "Ancilla qubits": "補助量子ビット",
  "Ancillas": "補助量子ビット",
  "Angular momentum": "角運動量",
  "Approximate variant": "近似版",
  "Approximation": "近似",
  "Assumption": "仮定",
  "Baseline": "比較基準",
  "Basis": "基底",
  "Basis set": "基底関数系",
  "Bloch vector": "ブロッホベクトル",
  "Bond length": "結合長",
  "Built from": "構成要素",
  "Circuit depth": "回路の深さ",
  "Claim": "主張",
  "Classical": "古典",
  "Classical deterministic": "古典の決定的手法",
  "Classical role": "古典側の役割",
  "Classical step": "古典ステップ",
  "Code family": "符号の系統",
  "Coefficients": "係数",
  "Coin": "コイン",
  "Consequence": "帰結",
  "Conserved": "保存量",
  "Conserved quantity": "保存量",
  "Contrast": "対比",
  "Control 0 block": "制御が0のときのブロック",
  "Control 1 block": "制御が1のときのブロック",
  "Controlled-U calls": "制御U の呼び出し回数",
  "Convention": "規約",
  "Core": "中核",
  "Core primitive": "中核となるプリミティブ",
  "Corrects": "訂正できる誤り",
  "Cost it replaces": "置き換えるコスト",
  "Cost per fermionic gate": "フェルミオンゲート1個あたりのコスト",
  "Counterexample": "反例",
  "Counting precision": "カウントの精度",
  "Coverage": "対象範囲",
  "Critical point": "臨界点",
  "Data qubits": "データ量子ビット",
  "Definition cited to": "定義の出典",
  "Degree": "次数",
  "Deployment": "導入状況",
  "Derivation": "導出",
  "Distillation ratio": "蒸留の比率",
  "Distinction": "違い",
  "Eigenphase relation": "固有位相との関係",
  "Eigenvalue": "固有値",
  "Entangled region": "もつれている領域",
  "Entanglement class": "もつれの分類",
  "Entropy": "エントロピー",
  "Equivalence": "等価性",
  "Error scaling": "誤差のスケーリング",
  "Evolution": "時間発展",
  "Exact gate count": "正確なゲート数",
  "Exact target (t=π/(2√2))": "厳密な目標（t=π/(2√2)）",
  "Failure mode": "失敗の仕方",
  "Feedback": "フィードバック",
  "Fixed points": "固定点",
  "Free route": "無料で使える経路",
  "Gate count (n=3)": "ゲート数（n=3）",
  "Gate locality": "ゲートの局所性",
  "General scaling": "一般のスケーリング",
  "Graph": "グラフ",
  "Ground-state splitting": "基底状態の分裂",
  "Heisenberg limit": "ハイゼンベルク限界",
  "Higher order": "高次",
  "Historical origin": "歴史的な由来",
  "Ideal P(00)": "理想的な P(00)",
  "Ideal P(11)": "理想的な P(11)",
  "Ideal support": "理想的な台",
  "Initial Hamiltonian": "初期ハミルトニアン",
  "Invariance": "不変性",
  "Iterations to certainty (a=1/4)": "確実に成功するまでの反復回数（a=1/4）",
  "Key task": "主な処理",
  "LHV region (projective, Werner 1989)": "局所隠れ変数で説明できる領域（射影測定、Werner 1989）",
  "Logical": "論理",
  "Loop": "ループ",
  "Main limitation": "主な制約",
  "Main metric": "主な指標",
  "Main risk": "主なリスク",
  "Mapping": "写像",
  "Model": "モデル",
  "Modes": "モード",
  "Name in the paper": "論文での名称",
  "Near misses": "惜しくも当てはまらない例",
  "No-cloning": "複製不可能性",
  "Noise": "ノイズ",
  "Normalization": "正規化",
  "Not an equivalence relation": "同値関係ではない理由",
  "Observable": "観測量",
  "Optimizer": "最適化器",
  "Oracle": "オラクル",
  "Order dependence": "順序への依存",
  "Paper's method": "論文の手法",
  "Paper's symbols": "論文の記号",
  "Parameters": "パラメータ",
  "Particle number": "粒子数",
  "Pauli terms": "パウリ項",
  "Phase scaling": "位相のスケーリング",
  "Phase transition driver": "相転移を起こす要因",
  "Physical": "物理",
  "Physical layer": "物理層",
  "Precision": "精度",
  "Primitive": "プリミティブ",
  "Problem Hamiltonian": "問題ハミルトニアン",
  "Problem posed by": "問題の提起者",
  "Problem studied in the paper": "論文が扱う問題",
  "Problem term": "問題項",
  "Purity": "純度",
  "P²": "P²",
  "QAOA depth": "QAOA の深さ",
  "Quantum": "量子",
  "Quantum core": "量子の中核部分",
  "Quantum output": "量子側の出力",
  "Quantum role": "量子側の役割",
  "Qubit overhead": "量子ビットのオーバーヘッド",
  "Query complexity": "クエリ計算量",
  "Query cost": "クエリコスト",
  "Readiness": "実用化の段階",
  "Reference": "参照",
  "Regime (this entry)": "適用領域（この項目）",
  "Registers": "レジスタ",
  "Relation": "関係",
  "Relation to CX": "CXとの関係",
  "Relation to RX": "RXとの関係",
  "Relation to RZ": "RZとの関係",
  "Relation to SWAP": "SWAPとの関係",
  "Risk": "リスク",
  "Robustness": "頑健性",
  "Rotation angle": "回転角",
  "Rounds (bits of precision)": "ラウンド数（精度のビット数）",
  "Schedule": "スケジュール",
  "Seed": "シード",
  "Separable region": "分離可能な領域",
  "Shift": "シフト",
  "Signal proxy": "信号の代理指標",
  "Sites × spins": "サイト数 × スピン",
  "Special case of": "特別な場合にあたる対象",
  "Special cases": "特別な場合",
  "Spectrum": "スペクトル",
  "Speedup claimed by the abstract": "要旨が主張する高速化",
  "Spreading": "広がり方",
  "Stabilizer": "スタビライザー",
  "Stabilizer group size": "スタビライザー群の大きさ",
  "Standard quantum limit": "標準量子限界",
  "Stated guarantee": "述べられている保証",
  "Step depth": "1ステップの深さ",
  "Steps shown": "表示しているステップ",
  "Strong-coupling limit": "強結合極限",
  "Success": "成功",
  "Success after k iters": "k回反復後の成功確率",
  "Success condition": "成功の条件",
  "Support": "台",
  "Syndrome": "シンドローム",
  "Threatened": "脅かされる対象",
  "Time step": "時間刻み",
  "Topological phase": "トポロジカル相",
  "Total N": "合計 N",
  "Toy instance": "小さな例",
  "Toy phase": "例に使う位相",
  "Transformed object": "変換される対象",
  "Trotter steps": "トロッターステップ数",
  "Tunable parameter": "調整できるパラメータ",
  "T→0 limit": "T→0 の極限",
  "T→∞ limit of": "T→∞ の極限",
  "Unpaired modes": "対を作らないモード",
  "Uses": "用途",
  "What it is": "内容",
  "Why 1-body is easy": "1体の場合が易しい理由",
  "|+⟩": "|+⟩",
  "|−⟩": "|−⟩",
  "Δ=1 point": "Δ=1 の点",
};
