import type { PublicRepositoryCitation, PublicRepositoryComparisonMetric, PublicRepositoryEntry } from "./types";

/**
 * Post-hoc enrichment for legacy records: long-form Markdown/TeX explanations,
 * literature, comparisons, and explicit verification classifications land here
 * keyed by slug instead of editing the large legacy data module in place. The
 * barrel merges these over the raw entry before normalization.
 */
export type EntryEnrichment = Partial<
  Pick<
    PublicRepositoryEntry,
    | "explanationMd"
    | "explanationMdJa"
    | "literature"
    | "classicalComparison"
    | "industryUseCases"
    | "industryUseCasesJa"
    | "verificationMethods"
  >
> & {
  /**
   * Numeric classical-vs-quantum table merged INTO the entry's existing
   * comparison (see the barrel). Only added where the figures are
   * textbook-precise complexities, not heuristics.
   */
  comparisonMetrics?: PublicRepositoryComparisonMetric[];
};

// Shared literature entries for legacy records that predate the `literature`
// field. Only attached to slugs whose raw entry in entries-legacy.ts has no
// literature array of its own (attaching here would otherwise be silently
// overwritten by the barrel's shallow spread merge for entries that already
// carry citations).
const NIELSEN_CHUANG: PublicRepositoryCitation = {
  title: "Quantum Computation and Quantum Information",
  authors: "Michael A. Nielsen, Isaac L. Chuang",
  year: "2010 (10th anniversary edition)",
  url: "https://doi.org/10.1017/CBO9780511976667",
  relevance:
    "Standard graduate textbook covering the single- and two-qubit gate definitions, matrix identities, and circuit primitives this record states.",
  relevanceJa:
    "この項目が示す1・2量子ビットゲートの定義、行列恒等式、回路プリミティブを扱う標準的な大学院教科書です。",
};

const BELL_1964: PublicRepositoryCitation = {
  title: "On the Einstein Podolsky Rosen Paradox",
  authors: "John S. Bell",
  year: "1964",
  url: "https://doi.org/10.1103/PhysicsPhysiqueFizika.1.195",
  relevance:
    "Introduces the Bell inequality that distinguishes entangled correlations, such as the Bell state, from any local hidden-variable model.",
  relevanceJa: "ベル状態のようなエンタングルした相関を局所隠れ変数モデルと区別するベル不等式の原論文です。",
};

const COPPERSMITH_APPROX_QFT: PublicRepositoryCitation = {
  title: "An approximate Fourier transform useful in quantum factoring",
  authors: "Don Coppersmith",
  year: "2002",
  url: "https://arxiv.org/abs/quant-ph/0201067",
  relevance: "Analyzes an approximate QFT construction and the gate-count/precision trade-off this record describes.",
  relevanceJa: "近似QFT構成と、この項目が説明するゲート数・精度のトレードオフを分析します。",
};

const BENNETT_WIESNER_1992: PublicRepositoryCitation = {
  title: "Communication via one- and two-particle operators on Einstein-Podolsky-Rosen states",
  authors: "Charles H. Bennett, Stephen J. Wiesner",
  year: "1992",
  url: "https://doi.org/10.1103/PhysRevLett.69.2881",
  relevance: "Original superdense-coding protocol: encoding two classical bits into one transmitted qubit using a shared entangled pair.",
  relevanceJa: "共有エンタングル対を使い、1量子ビットの送信で2古典ビットを符号化する超密符号化の原論文です。",
};

export const ENTRY_ENRICHMENT: Record<string, EntryEnrichment> = {
  // Metrics-only enrichments: these slugs already carry prose comparisons in
  // their raw data; the barrel merges the table in (Owner Inbox 2026-07-19).
  "quantum-fourier-transform": {
    comparisonMetrics: [
      { label: "Operation count", labelJa: "演算数", classical: "O(N log N) — FFT", quantum: "O(n²) = O(log²N)" },
      { label: "Register size", labelJa: "レジスタ規模", classical: "N complex values", quantum: "n = log₂N qubits" },
      { label: "Output access", labelJa: "出力へのアクセス", classical: "full vector", quantum: "sampled amplitudes only" },
    ],
  },
  "amplitude-amplification": {
    comparisonMetrics: [
      { label: "Query complexity (good-state prob. a)", labelJa: "クエリ計算量(良状態確率 a)", classical: "O(1/a)", quantum: "O(1/√a)" },
      { label: "Asymptotic speedup", labelJa: "漸近的な高速化", classical: "baseline", quantum: "quadratic" },
    ],
  },
  "hadamard-gate": {
    explanationMd: String.raw`Hadamard is the single-qubit unitary $H = \frac{1}{\sqrt{2}}\begin{pmatrix}1 & 1\\ 1 & -1\end{pmatrix}$. It sends $|0\rangle \mapsto \frac{1}{\sqrt2}(|0\rangle+|1\rangle)$ and $|1\rangle \mapsto \frac{1}{\sqrt2}(|0\rangle-|1\rangle)$, so a computational-basis measurement always returns $0$ or $1$ with probability $1/2$ regardless of which state it acted on — the difference is the relative sign in front of $|1\rangle$, a phase that only becomes visible once another gate lets the two branches interfere. $H$ is both Hermitian and unitary, so $H^\dagger = H = H^{-1}$, and direct matrix multiplication gives $H^2 = I$, exactly the identity this record's matrix check confirms. Geometrically $H$ is a $\pi$ rotation of the Bloch sphere about the axis $(\hat x + \hat z)/\sqrt2$, exchanging the $Z$ and $X$ eigenbases. It is the standard way to open superposition-based circuits such as Bell states, GHZ states, Grover diffusion, and the QFT.`,
    explanationMdJa: String.raw`アダマールゲートは1量子ビットのユニタリ演算 $H = \frac{1}{\sqrt2}\begin{pmatrix}1&1\\1&-1\end{pmatrix}$ です。$|0\rangle \mapsto \frac{1}{\sqrt2}(|0\rangle+|1\rangle)$、$|1\rangle \mapsto \frac{1}{\sqrt2}(|0\rangle-|1\rangle)$ となるため、計算基底で測定すると入力によらず0と1がそれぞれ確率$1/2$で得られます。違いは$|1\rangle$の前の相対符号だけで、後続ゲートで2つの分岐が干渉して初めて意味を持ちます。$H$はエルミートかつユニタリで $H^\dagger = H = H^{-1}$、直接計算すると $H^2 = I$ となり、これがこの項目の行列チェックが確認する恒等式です。ブロッホ球上では軸$(\hat x + \hat z)/\sqrt2$周りの$\pi$回転にあたり、$Z$基底と$X$基底を入れ替えます。ベル状態、GHZ状態、Groverの拡散演算子、QFTなど重ね合わせを使う回路の出発点として使われます。`,
    literature: [NIELSEN_CHUANG],
  },
  "pauli-x-operator": {
    explanationMd: String.raw`Pauli-$X$ is the bit-flip operator $X = \begin{pmatrix}0&1\\1&0\end{pmatrix}$, the quantum analogue of a classical NOT gate. On computational basis states it acts exactly as a truth table: $X|0\rangle=|1\rangle$ and $X|1\rangle=|0\rangle$, which is the identity this record's basis-state simulation checks directly rather than inferring from a general formula. $X$ is Hermitian and unitary with $X^2=I$, so it is its own inverse, and its eigenstates are $|+\rangle=\frac{1}{\sqrt2}(|0\rangle+|1\rangle)$ and $|-\rangle=\frac{1}{\sqrt2}(|0\rangle-|1\rangle)$ with eigenvalues $+1$ and $-1$. Geometrically, $X$ is a $\pi$ rotation of the Bloch sphere about the $x$-axis. Because $X$, together with $Y$ and $Z$, generates the full single-qubit Pauli group ($XY=iZ$ and cyclic permutations), it anchors error models, stabilizer codes, and controlled two-qubit gates such as CNOT.`,
    explanationMdJa: String.raw`パウリ$X$はビット反転演算子 $X=\begin{pmatrix}0&1\\1&0\end{pmatrix}$ で、古典NOTゲートの量子版です。計算基底では真理値表そのものの動作をし、$X|0\rangle=|1\rangle$、$X|1\rangle=|0\rangle$ となります。これは一般公式からの推測ではなく、基底状態シミュレーションで直接確認できる恒等式です。$X$はエルミートかつユニタリで $X^2=I$、つまり自分自身の逆演算です。固有状態は$|+\rangle=\frac{1}{\sqrt2}(|0\rangle+|1\rangle)$と$|-\rangle=\frac{1}{\sqrt2}(|0\rangle-|1\rangle)$で、固有値はそれぞれ$+1$、$-1$です。幾何学的にはブロッホ球の$x$軸周りの$\pi$回転にあたります。$Y$、$Z$とともに1量子ビットのパウリ群を生成し($XY=iZ$とその巡回)、ビット反転誤りモデルやスタビライザー符号、CNOTのような制御ゲートの基礎になります。`,
    literature: [NIELSEN_CHUANG],
  },
  "pauli-y-gate": {
    explanationMd: String.raw`Pauli-$Y$ is $Y=\begin{pmatrix}0&-i\\ i&0\end{pmatrix}$, combining a bit flip with a phase. Directly: $Y|0\rangle = i|1\rangle$ and $Y|1\rangle = -i|0\rangle$, matching this record's basis-action check. Up to convention $Y = iXZ$ (equivalently $-iZX$), which is why it behaves as the "odd one out" when composing $X$ and $Z$. $Y$ is Hermitian and unitary with $Y^2 = I$, so like $X$ and $Z$ it is its own inverse — the identity this record's matrix square verifies. Its eigenstates $|{\pm}i\rangle = \frac{1}{\sqrt2}(|0\rangle \pm i|1\rangle)$ have eigenvalues $\pm1$ and correspond to a $\pi$ rotation of the Bloch sphere about the $y$-axis. The imaginary prefactors are invisible to a single computational-basis measurement but matter as soon as $Y$ acts inside a superposition where relative phase drives interference, e.g. inside $Y$-basis stabilizer measurements.`,
    explanationMdJa: String.raw`パウリ$Y$は $Y=\begin{pmatrix}0&-i\\ i&0\end{pmatrix}$ で、ビット反転と位相を組み合わせます。直接計算すると $Y|0\rangle = i|1\rangle$、$Y|1\rangle = -i|0\rangle$ となり、この項目の基底作用チェックと一致します。規約上 $Y=iXZ$($-iZX$と同値)と表せ、$X$と$Z$を合成する際に「特殊な」演算子として現れます。$Y$はエルミートかつユニタリで $Y^2=I$、$X$や$Z$と同様に自分自身の逆演算であり、これがこの項目の行列二乗チェックが確認する内容です。固有状態 $|{\pm}i\rangle = \frac{1}{\sqrt2}(|0\rangle \pm i|1\rangle)$ の固有値は$\pm1$で、ブロッホ球の$y$軸周りの$\pi$回転に対応します。虚数の係数は単一の計算基底測定では見えませんが、重ね合わせの中で相対位相が干渉を左右する場面、例えば$Y$基底でのスタビライザー測定では重要になります。`,
    literature: [NIELSEN_CHUANG],
  },
  "pauli-z-gate": {
    explanationMd: String.raw`Pauli-$Z$ is the phase-flip operator $Z=\begin{pmatrix}1&0\\0&-1\end{pmatrix}$. On the computational basis, $Z|0\rangle=|0\rangle$ and $Z|1\rangle=-|1\rangle$, exactly the identity checked here by comparing the matrix action against both basis states directly. Because a measurement in the computational basis cannot distinguish $|1\rangle$ from $-|1\rangle$ (both give outcome "1" with probability 1), $Z$ is invisible on a bare basis state; its effect only shows up once the qubit is in a superposition, where the flipped sign changes how later amplitudes interfere — the point the entry's own explanation makes. $Z$ is Hermitian and unitary with $Z^2=I$, so it is its own inverse, and it is a $\pi$ rotation of the Bloch sphere about the $z$-axis. $Z$ underlies the phase-kickback trick used in Deutsch–Jozsa-style oracles and phase-flip error models in stabilizer codes.`,
    explanationMdJa: String.raw`パウリ$Z$は位相反転演算子 $Z=\begin{pmatrix}1&0\\0&-1\end{pmatrix}$ です。計算基底では $Z|0\rangle=|0\rangle$、$Z|1\rangle=-|1\rangle$ となり、これは両方の基底状態に対する行列作用を直接比較して確認する恒等式です。計算基底での測定は$|1\rangle$と$-|1\rangle$を区別できない(どちらも確率1で「1」)ため、$Z$は単体の基底状態には見えず、重ね合わせの中で初めて符号の反転が後の干渉に現れます。これはこの項目の説明が指摘している点です。$Z$はエルミートかつユニタリで $Z^2=I$、自分自身の逆演算であり、ブロッホ球の$z$軸周りの$\pi$回転に相当します。$Z$はDeutsch–Jozsa型オラクルで使われる位相キックバックや、スタビライザー符号における位相反転誤りモデルの基礎になります。`,
    literature: [NIELSEN_CHUANG],
  },
  "s-phase-gate": {
    explanationMd: String.raw`The $S$ gate (phase gate) is $S=\begin{pmatrix}1&0\\0&i\end{pmatrix}$, applying a $\pi/2$ phase to $|1\rangle$: $S|0\rangle=|0\rangle$, $S|1\rangle=i|1\rangle$. Squaring the matrix gives $S^2=\begin{pmatrix}1&0\\0&-1\end{pmatrix}=Z$, and applying it four times returns the identity, $S^4=I$ — exactly the power relations this record verifies by direct computation. $S$ is unitary but not Hermitian ($S^\dagger=S^{-1}=S^3\neq S$), and it is a Clifford gate: conjugating Pauli $X$ by $S$ gives $SXS^\dagger=Y$ up to sign convention, so $S$ maps the $X$/$Z$ stabilizer picture onto $Y$. Because $S=\sqrt Z$, it is the natural bridge between the Pauli group and finer phase rotations; composed with Hadamard it builds a $Y$-basis change of basis and, together with $T=\sqrt S$, generates approximately universal single-qubit rotations.`,
    explanationMdJa: String.raw`$S$ゲート(位相ゲート)は $S=\begin{pmatrix}1&0\\0&i\end{pmatrix}$ で、$|1\rangle$に$\pi/2$の位相を与えます: $S|0\rangle=|0\rangle$、$S|1\rangle=i|1\rangle$。行列を二乗すると $S^2=\begin{pmatrix}1&0\\0&-1\end{pmatrix}=Z$ となり、4回適用すると恒等演算 $S^4=I$ に戻ります。これはこの項目が直接計算で確認するべき乗関係そのものです。$S$はユニタリですがエルミートではなく($S^\dagger=S^{-1}=S^3\neq S$)、クリフォードゲートの一つです。$S$で$X$を共役すると符号規約により $SXS^\dagger=Y$ となり、$X$/$Z$のスタビライザー描像を$Y$に写します。$S=\sqrt Z$であるため、パウリ群とより細かい位相回転をつなぐ自然な橋渡しであり、アダマールと組み合わせて$Y$基底への変換を作り、$T=\sqrt S$とともに近似的に万能な1量子ビット回転を生成します。`,
    literature: [NIELSEN_CHUANG],
  },
  "t-phase-gate": {
    explanationMd: String.raw`The $T$ gate is $T=\begin{pmatrix}1&0\\0&e^{i\pi/4}\end{pmatrix}$, applying a $\pi/4$ phase: $T|0\rangle=|0\rangle$, $T|1\rangle=e^{i\pi/4}|1\rangle$. Since $\left(e^{i\pi/4}\right)^2=e^{i\pi/2}=i$, direct matrix multiplication gives $T^2=S$ and $T^8=I$, exactly the power relations this record checks. Unlike $H$, $S$, $X$, $Y$, $Z$, $T$ is **not** a Clifford gate: conjugating $X$ by $T$ does not map it to another Pauli operator, which is precisely why $\{H, T\}$ is universal for quantum computation while Clifford-only circuits are efficiently classically simulable (Gottesman–Knill). This makes $T$ the standard "expensive" non-Clifford resource in fault-tolerant compilation: magic-state distillation exists specifically to produce high-fidelity $T$ gates from many noisy ones, since — as this record's own caveat notes — the ideal unitary identity above says nothing about a given device's hardware fidelity or noise.`,
    explanationMdJa: String.raw`$T$ゲートは $T=\begin{pmatrix}1&0\\0&e^{i\pi/4}\end{pmatrix}$ で、$\pi/4$の位相を与えます: $T|0\rangle=|0\rangle$、$T|1\rangle=e^{i\pi/4}|1\rangle$。$\left(e^{i\pi/4}\right)^2=e^{i\pi/2}=i$ なので、直接計算で $T^2=S$、$T^8=I$ が得られ、これがこの項目が確認するべき乗関係です。$H$、$S$、$X$、$Y$、$Z$と異なり、$T$はクリフォードゲートではありません。$T$で$X$を共役しても別のパウリ演算子にはならず、これが$\{H,T\}$が量子計算にとって万能である一方、クリフォードのみの回路は効率的に古典シミュレートできる(Gottesman–Knill)理由です。このためフォールトトレラント実装では$T$が高コストな非クリフォード資源として扱われ、多数のノイズ入り$T$から高忠実度な$T$を作るマジック状態蒸留が使われます。この項目自身の注記の通り、上記の理想ユニタリ恒等式は特定デバイスのハードウェア忠実度やノイズについては何も主張しません。`,
    literature: [NIELSEN_CHUANG],
  },
  "controlled-x-gate": {
    explanationMd: String.raw`Controlled-$X$ (CNOT) acts on two qubits as $\mathrm{CX}|c,t\rangle = |c, t\oplus c\rangle$: the target flips exactly when the control is $|1\rangle$, the truth table this record checks directly against the four computational-basis inputs. In matrix form, $\mathrm{CX}=|0\rangle\langle0|\otimes I + |1\rangle\langle1|\otimes X$, a $4\times4$ permutation matrix that is its own inverse, $\mathrm{CX}^2=I$. Applied after a Hadamard on the control, $\mathrm{CX}(H\otimes I)|00\rangle = \frac{1}{\sqrt2}(|00\rangle+|11\rangle)$, the Bell state this catalog's entangling-action check reproduces — the second half of the verification claim. CNOT is a maximally entangling two-qubit gate: together with arbitrary single-qubit rotations it forms a universal gate set, and physically it is the standard native (or compiled) two-qubit interaction most hardware backends expose, making it the workhorse for building larger controlled operations.`,
    explanationMdJa: String.raw`制御$X$(CNOT)は2量子ビットに対し $\mathrm{CX}|c,t\rangle = |c, t\oplus c\rangle$ と作用します。つまり制御が$|1\rangle$のときだけ対象が反転し、これは4つの計算基底入力に対して直接確認できる真理値表です。行列表現では $\mathrm{CX}=|0\rangle\langle0|\otimes I + |1\rangle\langle1|\otimes X$ という$4\times4$の置換行列で、自分自身の逆 $\mathrm{CX}^2=I$ を満たします。制御側にHadamardをかけた後に適用すると $\mathrm{CX}(H\otimes I)|00\rangle = \frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ となり、これがこのカタログのエンタングル作用チェックが再現するベル状態、つまり検証主張の後半です。CNOTは最大限にエンタングルする2量子ビットゲートで、任意の1量子ビット回転と組み合わせると万能ゲート集合になり、物理的にもほとんどのハードウェアが提供するネイティブ(または合成された)2量子ビット相互作用として、より大きな制御演算を組み立てる基礎になります。`,
    literature: [NIELSEN_CHUANG],
  },
  "swap-gate": {
    explanationMd: String.raw`SWAP exchanges the states of two qubits: $\mathrm{SWAP}|a,b\rangle=|b,a\rangle$ for every computational basis input, exactly the check this record performs across all four inputs. As a matrix, $\mathrm{SWAP}=\begin{pmatrix}1&0&0&0\\0&0&1&0\\0&1&0&0\\0&0&0&1\end{pmatrix}$ in the $\{|00\rangle,|01\rangle,|10\rangle,|11\rangle\}$ basis, and $\mathrm{SWAP}^2=I$. Algebraically SWAP decomposes into three CNOTs, $\mathrm{SWAP}=\mathrm{CX}_{12}\,\mathrm{CX}_{21}\,\mathrm{CX}_{12}$, which is what a compiler emits when SWAP is not a native two-qubit interaction. SWAP does not create or destroy entanglement between the qubits it moves; it relocates existing correlations to different wires. In practice SWAP is a routing/connectivity primitive: transpilers insert it to move a logical qubit's state across a hardware coupling graph so a two-qubit gate can be applied between qubits that are not physically adjacent, at the cost of extra circuit depth.`,
    explanationMdJa: String.raw`SWAPは2つの量子ビットの状態を交換します。任意の計算基底入力に対し $\mathrm{SWAP}|a,b\rangle=|b,a\rangle$ となり、これが4つの入力すべてに対してこの項目が行うチェックです。行列表現では $\{|00\rangle,|01\rangle,|10\rangle,|11\rangle\}$ 基底で $\mathrm{SWAP}=\begin{pmatrix}1&0&0&0\\0&0&1&0\\0&1&0&0\\0&0&0&1\end{pmatrix}$ となり、$\mathrm{SWAP}^2=I$です。代数的にはSWAPは3つのCNOTに分解でき、$\mathrm{SWAP}=\mathrm{CX}_{12}\,\mathrm{CX}_{21}\,\mathrm{CX}_{12}$、これはSWAPがネイティブな2量子ビット相互作用でない場合にコンパイラが出力する形です。SWAPは移動する量子ビット間のエンタングルメントを生成も破壊もせず、既存の相関を別のワイヤに移すだけです。実用上はルーティング・接続性のプリミティブであり、物理的に隣接しない量子ビット間で2量子ビットゲートを適用できるよう、トランスパイラがハードウェアの結合グラフ上で論理量子ビットの状態を移動させるために挿入し、その分だけ回路深さが増えます。`,
    literature: [NIELSEN_CHUANG],
  },
  "bell-state-qiskit": {
    explanationMd: String.raw`The Bell state $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ is prepared by $H$ on qubit 0 followed by $\mathrm{CX}_{0\to1}$: starting from $|00\rangle$, $H\otimes I$ gives $\frac{1}{\sqrt2}(|00\rangle+|10\rangle)$, and CX then copies the control's value onto the target, $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ — exactly the statevector this record's exact-state check compares against. Measuring both qubits in the computational basis yields $00$ or $11$ each with probability $1/2$ and never $01$ or $10$: the two outcomes are perfectly correlated even though neither qubit's individual outcome is determined before measurement, the operational signature of entanglement (this state violates a Bell/CHSH inequality; it cannot be reproduced by any local hidden-variable model tossing independent coins). Because it is the smallest circuit exhibiting genuine quantum correlation, the Bell state anchors teleportation, superdense coding, and entanglement-verification protocols throughout this catalog.`,
    explanationMdJa: String.raw`ベル状態 $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ は、量子ビット0への$H$の後に $\mathrm{CX}_{0\to1}$ を適用して作ります。$|00\rangle$から出発すると $H\otimes I$ で $\frac{1}{\sqrt2}(|00\rangle+|10\rangle)$ になり、CXが制御の値を対象にコピーして $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ となります。これがこの項目の厳密な状態チェックが比較する状態ベクトルです。両量子ビットを計算基底で測定すると00または11がそれぞれ確率$1/2$で得られ、01や10は現れません。測定前にどちらの結果も個別には決まっていないにもかかわらず2つの結果は完全に相関しており、これがエンタングルメントの操作的な特徴です(この状態はベル/CHSH不等式を破り、独立なコイン投げによる局所隠れ変数モデルでは再現できません)。真の量子相関を示す最小の回路であるため、ベル状態はこのカタログ全体でテレポーテーションや超密符号化、エンタングルメント検証プロトコルの基礎になっています。`,
    literature: [BELL_1964, NIELSEN_CHUANG],
  },
  "ghz-state-pennylane": {
    explanationMd: String.raw`The GHZ state on $n=4$ wires, $\frac{1}{\sqrt2}(|0000\rangle+|1111\rangle)$, extends the Bell-state pattern: one Hadamard on wire 0 creates the branch, $\frac{1}{\sqrt2}(|0000\rangle+|1000\rangle)$, and CNOTs fan it from wire 0 to wires 1, 2, 3 in turn, each spreading the correlation until all four qubits agree. This record's check confirms the circuit structure and the ideal simulator support — probability mass only on $0000$ and $1111$ — which is what the entry's own caveat scopes: simulator evidence, not a hardware noise measurement. Unlike the Bell state, GHZ correlations are fragile: a single bit- or phase-flip error on any one of the four qubits during preparation collapses the perfect two-outcome distribution, which is exactly why GHZ fidelity is used as a standard multi-qubit benchmark for characterizing crosstalk and coherence on real devices — distinct from the ideal-circuit claim made here.`,
    explanationMdJa: String.raw`4本のワイヤ上のGHZ状態 $\frac{1}{\sqrt2}(|0000\rangle+|1111\rangle)$ は、ベル状態のパターンを拡張したものです。ワイヤ0へのHadamardで分岐を作り $\frac{1}{\sqrt2}(|0000\rangle+|1000\rangle)$ となった後、CNOTをワイヤ0から1、2、3へ順に適用し、相関を次々と広げて最終的に4量子ビットすべてを一致させます。この項目のチェックが確認するのは回路構造と、確率が0000と1111にのみ乗る理想シミュレータでの分布であり、これはエントリ自身の注記が範囲とする「シミュレータのみの証拠」です。ベル状態と異なり、GHZ相関は壊れやすく、準備中に4量子ビットのいずれか1つでビット反転や位相反転誤りが起きるだけで完璧な2状態分布は崩れます。だからこそGHZ忠実度は実機のクロストークやコヒーレンスを特徴づける標準的な多量子ビットベンチマークとして使われますが、それはここで主張する理想回路の結果とは別の話です。`,
    literature: [NIELSEN_CHUANG],
  },
  "quantum-teleportation": {
    explanationMd: String.raw`Teleportation moves an unknown state $|\psi\rangle=\alpha|0\rangle+\beta|1\rangle$ from Alice to Bob using one shared Bell pair and two classical bits. Alice holds $|\psi\rangle$ and her half of $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$; she applies CX then $H$ to the pair and measures both in the computational basis, obtaining classical bits $(m_1,m_2)$. Before measurement the three-qubit state can be written as an equal superposition over Alice's four outcomes, each pairing a Bell-basis result with a specific Pauli acting on Bob's qubit: $\frac{1}{2}\sum_{m_1,m_2}|m_1 m_2\rangle\otimes Z^{m_1}X^{m_2}|\psi\rangle$. Bob applies $X^{m_2}Z^{m_1}$ to undo that Pauli and recovers $|\psi\rangle$ exactly — the ideal-circuit result this record checks on a toy state. No information travels faster than light: Bob's qubit is maximally mixed until the two classical bits arrive, and the protocol consumes (does not clone) the input state, consistent with the no-cloning theorem.`,
    explanationMdJa: String.raw`テレポーテーションは、共有ベル対1組と2古典ビットを使って未知の状態 $|\psi\rangle=\alpha|0\rangle+\beta|1\rangle$ をAliceからBobへ移します。Aliceは$|\psi\rangle$とベル対$\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$の片方を持ち、そのペアにCXとHを適用してから両方を計算基底で測定し、古典ビット$(m_1,m_2)$を得ます。測定前、3量子ビット状態はAliceの4つの結果それぞれにBobの量子ビットへのパウリ演算を対応させた等重ね合わせとして $\frac{1}{2}\sum_{m_1,m_2}|m_1 m_2\rangle\otimes Z^{m_1}X^{m_2}|\psi\rangle$ と書けます。Bobは$X^{m_2}Z^{m_1}$を適用してそのパウリを打ち消し、$|\psi\rangle$を厳密に復元します。これがこの項目がトイ状態で確認する理想回路の結果です。情報が光速を超えて伝わることはなく、2ビットが届くまでBobの量子ビットは最大混合状態のままで、プロトコルは入力状態を複製せず消費するため、ノークローニング定理と整合します。`,
  },
  "superdense-coding-circuit": {
    explanationMd: String.raw`Superdense coding sends two classical bits using one qubit, given a pre-shared Bell pair $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$. To send message $m_1m_2\in\{00,01,10,11\}$, Alice applies $Z^{m_1}X^{m_2}$ to her half only, mapping the shared state to one of four orthogonal Bell states. She sends her single qubit to Bob, who now holds both halves and applies $\mathrm{CX}$ then $H$ to disentangle the pair into a computational basis state that decodes exactly to $m_1m_2$ — the decoding circuit this record checks. Only one physical qubit travels, but the protocol depends on the Bell pair having been distributed beforehand; it does not transmit two arbitrary qubits' worth of quantum information over one qubit, matching the entry's own caveat that a pre-shared entangled resource, not raw channel capacity, is what is being spent.`,
    explanationMdJa: String.raw`超密符号化は、事前に共有したベル対 $\frac{1}{\sqrt2}(|00\rangle+|11\rangle)$ を使い、1量子ビットの送信で2古典ビットを伝えます。メッセージ$m_1m_2\in\{00,01,10,11\}$を送るため、Aliceは自分の半分だけに$Z^{m_1}X^{m_2}$を適用し、共有状態を4つの直交するベル状態のいずれかに写します。Aliceは自分の1量子ビットだけをBobに送り、両半分を持つBobがCXとHを適用してペアを解きほぐし、$m_1m_2$を正しく復号する計算基底状態にします。これがこの項目が確認する復号回路です。物理的に移動するのは1量子ビットのみですが、事前にベル対が配布されていることが前提であり、任意の2量子ビット分の量子情報を1量子ビットで送るわけではない点が、このエントリ自身の注記、すなわち消費されるのは生のチャネル容量ではなく事前共有されたエンタングルメント資源であるという点と一致します。`,
    literature: [BENNETT_WIESNER_1992, NIELSEN_CHUANG],
  },
  "qaoa-maxcut-ring": {
    explanationMd: String.raw`QAOA at depth $p=1$ prepares $|\gamma,\beta\rangle = e^{-i\beta H_M}e^{-i\gamma H_C}H^{\otimes n}|0\rangle^{\otimes n}$, alternating a problem (cost) unitary and a mixer unitary. For MaxCut on a graph $G=(V,E)$, the cost Hamiltonian is $H_C=\sum_{(j,k)\in E}\frac{1}{2}(I-Z_jZ_k)$, whose expectation counts cut edges, and the mixer is $H_M=\sum_j X_j$, whose exponential is a product of independent $X$-rotations letting the state explore bitstrings. For this record's 5-node ring, $H_C$ sums five such terms around the cycle. The reported acceptance is empirical, not a matrix identity: the sampled 4096-shot distribution (seed 42) is compared with the reference simulator using total variation distance, giving $\mathrm{TVD}=0.0088$ against a $\delta\le0.05$ threshold — evidence that the *sampled circuit* matches its own noiseless simulation, not a claim that $p=1$ finds the graph's true maximum cut.`,
    explanationMdJa: String.raw`深さ$p=1$のQAOAは $|\gamma,\beta\rangle = e^{-i\beta H_M}e^{-i\gamma H_C}H^{\otimes n}|0\rangle^{\otimes n}$ を準備し、問題(コスト)ユニタリとミキサーユニタリを交互に適用します。グラフ$G=(V,E)$上のMaxCutでは、コストハミルトニアンは $H_C=\sum_{(j,k)\in E}\frac{1}{2}(I-Z_jZ_k)$ で、その期待値がカット辺数を数え、ミキサーは $H_M=\sum_j X_j$ で、その指数は独立な$X$回転の積となりビット列の探索を可能にします。この項目の5ノードリングでは、$H_C$はサイクルに沿った5つの項の和です。報告されている受入結果は行列恒等式ではなく実測的なもので、4096ショット(シード42)のサンプル分布を参照シミュレータと全変動距離で比較し、$\mathrm{TVD}=0.0088$を閾値$\delta\le0.05$と比べています。これは「サンプリングされた回路が自身の理想シミュレーションと一致する」ことの証拠であり、$p=1$がグラフの真の最大カットを見つけるという主張ではありません。`,
  },
  "grover-unstructured-search": {
    comparisonMetrics: [
      { label: "Query complexity", labelJa: "クエリ計算量", classical: "O(N)", quantum: "O(√N)" },
      { label: "Queries (1 of N marked)", labelJa: "クエリ数(N中1件)", classical: "~N/2 avg", quantum: "⌊(π/4)√N⌋" },
      { label: "Register (N = 2ⁿ)", labelJa: "レジスタ (N = 2ⁿ)", classical: "n bits", quantum: "n qubits" },
      { label: "Asymptotic speedup", labelJa: "漸近的な高速化", classical: "baseline", quantum: "quadratic" },
    ],
    explanationMd: String.raw`For an unstructured search space of size $N$ with a single marked item, Grover's algorithm reaches the marked state with high probability using $O(\sqrt N)$ oracle queries, versus $O(N)$ expected queries for classical exhaustive search — a quadratic query-complexity separation, not a claim about wall-clock time on any given hardware. The construction alternates an oracle $U_f$ that flips the sign of the marked amplitude with the diffusion operator $2|s\rangle\langle s|-I$; each pass rotates the state by $2\theta$ (where $\sin\theta=1/\sqrt N$) toward the marked subspace, and the success amplitude after $k$ iterations is $\sin\big((2k+1)\theta\big)$, so overshooting past the optimal $k\approx\frac{\pi}{4}\sqrt N$ actually reduces success probability. This record's two-qubit ($N=4$) toy oracle and diffusion layer are checked against the ideal circuit — small-instance evidence for the construction — while the $O(\sqrt N)$ asymptotic claim rests on the cited literature and assumes a coherent oracle where oracle calls, not classical readout, dominate cost.`,
    explanationMdJa: String.raw`サイズ$N$の非構造化探索空間に対象が1つあるとき、Groverのアルゴリズムは$O(\sqrt N)$回のオラクル呼び出しで高確率に対象状態に到達します。これは古典的な全探索の期待$O(N)$回に対する二次的なクエリ計算量の分離であり、特定ハードウェア上の実時間についての主張ではありません。構成はオラクル$U_f$(対象振幅の符号反転)と拡散演算子$2|s\rangle\langle s|-I$を交互に適用し、各回で状態を対象部分空間へ向けて角度$2\theta$($\sin\theta=1/\sqrt N$)回転させ、$k$回反復後の成功振幅は$\sin\big((2k+1)\theta\big)$になるため、最適な$k\approx\frac{\pi}{4}\sqrt N$を超えると成功確率はむしろ下がります。この項目の2量子ビット($N=4$)トイオラクルと拡散層は理想回路と照合されており、構成についての小規模インスタンス証拠です。一方$O(\sqrt N)$という漸近的主張自体は引用文献に基づき、オラクル呼び出しが古典的読み出しではなくコストを支配するコヒーレントなオラクルアクセスを前提とします。`,
  },
  "shor-period-finding": {
    comparisonMetrics: [
      { label: "Time complexity", labelJa: "時間計算量", classical: "sub-exponential", quantum: "polynomial in log N" },
      { label: "Scaling (b = log₂N)", labelJa: "スケーリング (b = log₂N)", classical: "exp(Õ(b^⅓))", quantum: "Õ(b³)" },
      { label: "Logical qubits (2048-bit)", labelJa: "論理量子ビット(2048ビット)", classical: "—", quantum: "~few thousand" },
      { label: "Impact", labelJa: "影響", classical: "RSA / ECC assumed hard", quantum: "breaks RSA / ECC" },
    ],
    explanationMd: String.raw`Shor's algorithm reduces factoring $N$ to finding the period $r$ of $f(x)=a^x \bmod N$ for a random $a$ coprime to $N$: once $r$ is known, $\gcd(a^{r/2}\pm1, N)$ yields a nontrivial factor with good probability (when $r$ is even and $a^{r/2}\not\equiv -1$). The quantum step estimates $r$ via phase estimation: preparing a superposition over the exponent register, applying controlled modular exponentiation $U_a^{2^j}$, and reading out with an inverse QFT gives a phase close to $s/r$ for random integer $s$; a classical continued-fraction expansion then recovers $r$. This record documents that circuit motif — controlled-$U$ powers feeding an inverse QFT — and keeps the quantum (period-extraction) and classical (continued-fraction) halves visible as separate steps, consistent with its own status: a reviewable reference, not a resource-estimated fault-tolerant implementation, since a cryptographically relevant instance needs thousands of logical qubits and deep modular-arithmetic circuits.`,
    explanationMdJa: String.raw`Shorのアルゴリズムは、$N$と互いに素なランダムな$a$に対する $f(x)=a^x \bmod N$ の周期$r$を求める問題に因数分解を帰着させます。$r$が分かれば、$\gcd(a^{r/2}\pm1, N)$が(rが偶数で$a^{r/2}\not\equiv -1$のとき)高確率で非自明な因数を与えます。量子部分は位相推定で$r$を推定します。指数レジスタを重ね合わせにし、制御剰余べき乗$U_a^{2^j}$を適用し、逆QFTで読み出すとランダムな整数$s$に対して$s/r$に近い位相が得られ、古典的な連分数展開でその位相から$r$を復元します。この項目は、制御$U$べき乗が逆QFTに入るというこの回路のモチーフを記録し、量子(周期抽出)部分と古典(連分数)部分を別のステップとして明示しており、これはこの項目自身のステータス、すなわちレビュー可能な参照であってリソース見積り済みのフォールトトレラント実装ではないという位置づけと整合します。暗号的に意味のある規模には数千の論理量子ビットと深い剰余算術回路が必要だからです。`,
  },
  "amplitude-estimation": {
    comparisonMetrics: [
      { label: "Query complexity (error ε)", labelJa: "クエリ計算量(誤差 ε)", classical: "O(1/ε²)", quantum: "O(1/ε)" },
      { label: "Cost model", labelJa: "コストモデル", classical: "Monte Carlo samples", quantum: "coherent oracle calls" },
      { label: "Asymptotic speedup", labelJa: "漸近的な高速化", classical: "baseline", quantum: "quadratic" },
    ],
    explanationMd: String.raw`Amplitude estimation extracts the amplitude $a$ hidden in a state $\mathcal A|0\rangle=\sqrt{1-a}\,|0\rangle|\phi_0\rangle+\sqrt a\,|1\rangle|\phi_1\rangle$ prepared by a state-preparation operator $\mathcal A$, where $a$ is typically a success probability or expectation of interest. The original construction runs phase estimation on the Grover-style operator $Q=-\mathcal A S_0 \mathcal A^\dagger S_\chi$ built from $\mathcal A$ and two reflections; $Q$'s eigenphases encode $a=\sin^2\theta$, so measuring $m$ phase-register qubits yields an estimate $\hat a$ with error scaling as $O(2^{-m})=O(1/\varepsilon)$ *queries* to $\mathcal A$, compared with $O(1/\varepsilon^2)$ independent classical samples needed for the same error via a Chernoff/Hoeffding bound — a quadratic query reduction assuming coherent access to $\mathcal A$. This record checks a small Bernoulli-amplitude toy circuit against repeated classical sampling; the query-count advantage, as the entry's caveat states, depends entirely on state-preparation and oracle-access costs a toy circuit cannot certify.`,
    explanationMdJa: String.raw`振幅推定は、状態準備演算子$\mathcal A$が用意する状態 $\mathcal A|0\rangle=\sqrt{1-a}\,|0\rangle|\phi_0\rangle+\sqrt a\,|1\rangle|\phi_1\rangle$ に埋め込まれた振幅$a$(典型的には興味のある成功確率や期待値)を抽出します。原構成は$\mathcal A$と2つの鏡映から作るGrover型演算子$Q=-\mathcal A S_0 \mathcal A^\dagger S_\chi$に対して位相推定を行い、$Q$の固有位相は$a=\sin^2\theta$を符号化するため、$m$個の位相レジスタ量子ビットを測定すると誤差が$O(2^{-m})=O(1/\varepsilon)$回の$\mathcal A$へのクエリでスケーリングする推定$\hat a$が得られます。これはChernoff/Hoeffding限界で同じ誤差に必要な$O(1/\varepsilon^2)$回の独立な古典サンプルと比較され、$\mathcal A$へのコヒーレントアクセスを前提とした二次的なクエリ削減です。この項目は小さなベルヌーイ振幅のトイ回路を反復古典サンプリングと比較して確認しており、クエリ数の優位性自体は、このエントリの注記の通り、トイ回路では保証できない状態準備とオラクルアクセスのコストに完全に依存します。`,
  },
  "vqe-ground-state-energy": {
    explanationMd: String.raw`VQE estimates a ground-state energy using the variational principle: for any normalized trial state $|\psi(\theta)\rangle=U(\theta)|0\rangle$ and Hamiltonian $H$, the Rayleigh quotient obeys $\langle\psi(\theta)|H|\psi(\theta)\rangle \ge E_0$, the true ground energy, with equality only when $|\psi(\theta)\rangle$ is an exact ground eigenstate. The circuit prepares $|\psi(\theta)\rangle$ with a parameterized ansatz $U(\theta)$, measures each Pauli term of $H=\sum_k c_k P_k$ to build $\langle H\rangle(\theta)$, and hands that scalar to a classical optimizer that updates $\theta$ to push the energy down — a hybrid quantum/classical loop repeated to convergence. This record checks that expectation-value loop for a small Pauli Hamiltonian against exact diagonalization, matching its own caveat: the variational *bound* is guaranteed by the math above, but reaching a chemically useful energy still depends on ansatz expressivity, optimizer convergence, and shot noise this toy fixture does not certify.`,
    explanationMdJa: String.raw`VQEは変分原理を使って基底状態エネルギーを推定します。正規化された試行状態$|\psi(\theta)\rangle=U(\theta)|0\rangle$とハミルトニアン$H$に対し、Rayleigh商は $\langle\psi(\theta)|H|\psi(\theta)\rangle \ge E_0$(真の基底エネルギー)を満たし、等号は$|\psi(\theta)\rangle$が厳密な基底固有状態のときだけ成立します。回路はパラメータ付きansatz $U(\theta)$で$|\psi(\theta)\rangle$を準備し、$H=\sum_k c_k P_k$の各パウリ項を測定して$\langle H\rangle(\theta)$を構成し、そのスカラーを古典最適化器に渡してエネルギーを下げる方向に$\theta$を更新します。これを収束まで繰り返すハイブリッド量子・古典ループです。この項目は、この期待値ループを小さなパウリハミルトニアンについて厳密対角化と比較しており、このエントリ自身の注記と一致します。上記の数学が保証するのは変分「上限」であり、化学的に有用なエネルギーに到達できるかはansatzの表現力、最適化の収束、ショットノイズに依存し、このトイの検証はそれらを保証しません。`,
  },
  "quantum-phase-estimation": {
    explanationMd: String.raw`Quantum phase estimation extracts the phase $\varphi\in[0,1)$ of an eigenvalue $e^{2\pi i\varphi}$ for a unitary $U$ acting on an eigenstate $U|\psi\rangle=e^{2\pi i\varphi}|\psi\rangle$. With $m$ phase-register qubits prepared in $|+\rangle^{\otimes m}$, applying controlled powers $c\text{-}U^{2^j}$ for $j=0,\dots,m-1$ and an inverse QFT concentrates the register's amplitude near the $m$-bit binary expansion of $\varphi$, with success probability $\ge4/\pi^2$ for the nearest $m$-bit estimate and error shrinking as $O(2^{-m})$ — precision scales with the *coherent* circuit depth needed to apply $U^{2^{m-1}}$. This record checks a single-qubit phase rotation with a known eigenstate against the inverse-QFT readout — a controlled setting where $\varphi$ is known in advance — matching the entry's caveat: applying QPE to an unknown Hamiltonian's eigenstate additionally requires state overlap and enough coherent evolution time to reach the desired precision.`,
    explanationMdJa: String.raw`量子位相推定は、固有状態 $U|\psi\rangle=e^{2\pi i\varphi}|\psi\rangle$ を持つユニタリ$U$の固有値の位相$\varphi\in[0,1)$を抽出します。$m$個の位相レジスタ量子ビットを$|+\rangle^{\otimes m}$に用意し、$j=0,\dots,m-1$について制御べき乗$c\text{-}U^{2^j}$を適用してから逆QFTをかけると、位相レジスタの振幅は$\varphi$の$m$ビット2進展開付近に集中し、最近傍の$m$ビット推定に対する成功確率は$\ge4/\pi^2$、誤差は$O(2^{-m})$で縮小します。つまり精度は$U^{2^{m-1}}$を適用するのに必要な「コヒーレントな」回路深さにスケールします。この項目は既知の固有状態を持つ1量子ビット位相回転を逆QFT読み出しと照合しており、$\varphi$が事前に分かっている制御された設定です。これはこのエントリの注記と一致します。未知のハミルトニアンの固有状態にQPEを適用するには、さらにその固有状態との重なりと、所望の精度に達するための十分なコヒーレント発展時間が必要です。`,
  },
  "hhl-linear-systems": {
    comparisonMetrics: [
      { label: "Dependence on N", labelJa: "N への依存", classical: "poly(N)", quantum: "O(log N)" },
      { label: "Condition-number cost", labelJa: "条件数コスト", classical: "O(s κ)", quantum: "O(s κ² log(1/ε))" },
      { label: "Output", labelJa: "出力", classical: "full solution x", quantum: "|x⟩ (observable only)" },
      { label: "Impact", labelJa: "影響", classical: "baseline", quantum: "exp. in N (with caveats)" },
    ],
    explanationMd: String.raw`HHL estimates an observable of the solution $|x\rangle\propto A^{-1}|b\rangle$ to a linear system $Ax=b$ for Hermitian, $s$-sparse $A$ (or made Hermitian via a standard block embedding). The circuit encodes $A$'s eigenvalues into a phase register via quantum phase estimation on $e^{iAt}$, applies a controlled rotation proportional to $\lambda^{-1}$ on an ancilla, and uncomputes the phase register, leaving $|x\rangle$ entangled with an ancilla flag. Under the coherent access model, circuit cost scales roughly as $O(s\,\kappa^2\log(1/\epsilon))$ where $\kappa=|\lambda_{\max}|/|\lambda_{\min}|$ is $A$'s condition number and $\epsilon$ the target precision — versus roughly $O(s\kappa)$ for classical conjugate gradient, so the advantage narrows as $\kappa$ grows. Crucially, $|x\rangle$ is a quantum state: reading out every component costs $O(N)$ measurements and erases any speedup, so — matching this record's caveat — HHL is only useful when a single scalar observable of $x$, not the full vector, is the actual goal.`,
    explanationMdJa: String.raw`HHLは、エルミートで$s$疎な$A$(あるいは標準的なブロック埋め込みでエルミート化した$A$)についての線形方程式$Ax=b$の解$|x\rangle\propto A^{-1}|b\rangle$のある観測量を推定します。回路は$e^{iAt}$に対する量子位相推定で$A$の固有値を位相レジスタに符号化し、補助量子ビットに$\lambda^{-1}$に比例した制御回転をかけ、位相レジスタを非計算化して、$|x\rangle$を補助フラグとエンタングルさせたまま残します。コヒーレントアクセスモデルの下では回路コストはおおよそ $O(s\,\kappa^2\log(1/\epsilon))$ でスケールします($\kappa=|\lambda_{\max}|/|\lambda_{\min}|$は$A$の条件数、$\epsilon$は目標精度)。これは古典共役勾配法のおよそ$O(s\kappa)$のコストと比較され、$\kappa$が大きくなるほど優位性は縮小します。重要なのは$|x\rangle$が量子状態であることで、全成分を読み出すには$O(N)$回の測定が必要になり優位性が消えるため、この項目の注記の通り、HHLはベクトル全体ではなく$x$の単一のスカラー観測量が目的の場合にのみ有用です。`,
  },
  "quantum-kernel-svm": {
    explanationMd: String.raw`A quantum kernel maps a classical input $x$ to a quantum state $|\phi(x)\rangle=U(x)|0\rangle$ via a feature-map circuit $U(x)$, and defines a kernel via the state overlap $K(x,y)=|\langle\phi(x)|\phi(y)\rangle|^2$. The circuit estimates $K(x,y)$ by applying $U(x)$ then $U(y)^\dagger$ and measuring the probability of returning to $|0\rangle^{\otimes n}$: $\Pr[0^n] = |\langle 0|U(y)^\dagger U(x)|0\rangle|^2 = K(x,y)$, so each entry of the kernel matrix costs repeated circuit shots rather than a closed-form evaluation. The resulting Gram matrix $K$ is handed to a standard classical SVM, which still performs the convex optimization over Lagrange multipliers — the quantum circuit only changes the feature map, not the learning algorithm. This record checks that $K$ is symmetric and numerically positive-semidefinite (within tolerance) on a small dataset; as its own caveat states, whether a given feature map's kernel actually separates a dataset better than a tuned classical kernel is a separate, data-dependent question this toy check does not answer.`,
    explanationMdJa: String.raw`量子カーネルは、特徴写像回路$U(x)$によって古典入力$x$を量子状態$|\phi(x)\rangle=U(x)|0\rangle$に写し、状態の重なり $K(x,y)=|\langle\phi(x)|\phi(y)\rangle|^2$ でカーネルを定義します。回路は$U(x)$の後に$U(y)^\dagger$を適用し、$|0\rangle^{\otimes n}$に戻る確率を測定して$K(x,y)$を推定します: $\Pr[0^n] = |\langle 0|U(y)^\dagger U(x)|0\rangle|^2 = K(x,y)$。つまりカーネル行列の各要素は閉形式の計算ではなく反復ショットのコストがかかります。得られたグラム行列$K$は通常の古典SVMに渡され、ラグランジュ乗数についての凸最適化は古典SVM側が行います。量子回路が変えるのは特徴写像のみで、学習アルゴリズムではありません。この項目は小規模データセットで$K$が対称かつ(許容誤差内で)半正定値であることを確認しますが、その注記の通り、ある特徴写像のカーネルが調整済みの古典カーネルより実際にデータをよく分離するかは、この小規模な確認では答えられないデータ依存の別の問題です。`,
  },
  "shor-code-error-correction": {
    explanationMd: String.raw`Shor's nine-qubit code protects one logical qubit against an arbitrary single-qubit Pauli error by nesting two three-qubit repetition codes in complementary bases. First, $|\psi\rangle=\alpha|0\rangle+\beta|1\rangle$ is encoded phase-flip-style into $\alpha|{+}{+}{+}\rangle+\beta|{-}{-}{-}\rangle$ using $H$ and CNOTs, then each of those three qubits is bit-flip-encoded via $|0\rangle\to|000\rangle$, $|1\rangle\to|111\rangle$, giving nine physical qubits. Ancilla-assisted stabilizer measurements ($Z_iZ_j$ within each triple, and $X$-type parity across triples) identify which error class occurred — bit flip, phase flip, or both — without collapsing the encoded logical amplitudes $\alpha,\beta$, and a decoder applies the matching Pauli correction. This record documents that stabilizer structure as a code-level reference, matching its own caveat: whether encoding nine noisy physical qubits actually beats one bare qubit depends on the calibrated noise model, since encoding, syndrome extraction, and ancilla errors can outweigh the protection on small noisy devices.`,
    explanationMdJa: String.raw`Shorの9量子ビット符号は、相補的な基底の3量子ビット反復符号を入れ子にすることで、任意の単一量子ビットパウリ誤りから1論理量子ビットを保護します。まず $|\psi\rangle=\alpha|0\rangle+\beta|1\rangle$ を$H$とCNOTを使って位相反転型に $\alpha|{+}{+}{+}\rangle+\beta|{-}{-}{-}\rangle$ と符号化し、続いてその3量子ビットそれぞれを $|0\rangle\to|000\rangle$、$|1\rangle\to|111\rangle$ でビット反転型に符号化して9物理量子ビットを得ます。補助量子ビットを使ったスタビライザー測定(各3つ組内の$Z_iZ_j$と、3つ組をまたぐ$X$型パリティ)は、符号化された論理振幅$\alpha,\beta$を崩さずにビット反転・位相反転・その両方のどの誤りクラスが起きたかを特定し、デコーダが対応するパウリ補正を適用します。この項目はこのスタビライザー構造を符号レベルの参照として記録しており、これはこのエントリ自身の注記と一致します。9個のノイズ入り物理量子ビットの符号化が実際に符号化していない1量子ビットに勝るかは校正済みノイズモデルに依存し、符号化・シンドローム抽出・補助量子ビットの誤りが小さなノイズのあるデバイスでは保護効果を上回り得るからです。`,
  },
  "surface-code-memory": {
    explanationMd: String.raw`Surface codes protect a logical qubit using only local stabilizer checks on a 2D lattice: data qubits sit on edges or vertices, and repeated measurement of local $X$-type and $Z$-type stabilizer operators produces a syndrome without ever measuring the encoded logical state directly. Stacking syndrome rounds over time traces out a space-time syndrome graph; a decoder (typically minimum-weight perfect matching or a neural/tensor-network decoder) infers the most likely error chain consistent with that graph, and the logical observable fails only when the true error and the inferred correction differ by a nontrivial logical operator — an event whose rate drops super-linearly below the physical error rate once the code operates below its threshold. The XZZX variant this record cites reshapes the stabilizers so that a biased (e.g. dephasing-dominated) physical noise channel is matched more efficiently than the standard surface code, without needing a higher weight. This record documents the syndrome-round and logical-observable workflow as an architecture reference; it makes no hardware threshold claim of its own, and — per its caveat — decoder quality, leakage, measurement error, and connectivity determine the useful operating point.`,
    explanationMdJa: String.raw`表面符号は、2次元格子上の局所的なスタビライザー検査だけで論理量子ビットを保護します。データ量子ビットは辺または頂点に配置され、局所的な$X$型・$Z$型スタビライザー演算子を反復測定することで、符号化された論理状態を直接測ることなくシンドロームが得られます。時間方向にシンドロームラウンドを重ねると時空間シンドロームグラフが得られ、デコーダ(典型的には最小重み完全マッチングやニューラル・テンソルネットワーク型デコーダ)がそのグラフと整合する最も尤もらしいエラー鎖を推定します。論理観測量が失敗するのは、真の誤りと推定した補正が非自明な論理演算子だけ異なる場合であり、符号が閾値以下で動作していれば、符号距離を大きくするにつれて論理誤り率を急速に下げられます。この項目が引用するXZZX変種は、標準的な表面符号よりも重みを増やさずに偏った(例えば位相減衰が支配的な)物理ノイズチャネルに効率よく適合するようスタビライザーを再構成したものです。この項目はシンドロームラウンドと論理観測量のワークフローをアーキテクチャ参照として記録しており、それ自体はハードウェア閾値を主張せず、注記の通りデコーダの質、リーケージ、測定誤り、接続性が実用上の動作点を決めます。`,
  },
  "qft-resource-screen": {
    explanationMd: String.raw`The QFT maps computational basis states to a Fourier basis: $\mathrm{QFT}|j\rangle=\frac{1}{\sqrt{2^n}}\sum_{k=0}^{2^n-1}e^{2\pi i jk/2^n}|k\rangle$ for an $n$-qubit register. The standard circuit applies a Hadamard on the top qubit, then controlled phase rotations $R_k=\mathrm{diag}(1,e^{2\pi i/2^k})$ from every later qubit into it, repeats for each qubit in turn, and optionally reverses qubit order with a final SWAP layer depending on bit-order convention — the layer this record's metadata keeps explicit. The circuit uses $n$ Hadamards and $\binom{n}{2}$ controlled-phase gates, giving $O(n^2)$ total gates versus the classical FFT's $O(N\log N)=O(2^n\cdot n)$ arithmetic operations on a full amplitude vector — an exponential gate-count saving, but only over quantum amplitudes that must then be sampled, not a free classical output vector. This record's check is a parser/compile-compatibility comparison across the export path, not a numerical circuit-correctness proof.`,
    explanationMdJa: String.raw`QFTは計算基底状態をフーリエ基底に写します: $n$量子ビットレジスタに対し $\mathrm{QFT}|j\rangle=\frac{1}{\sqrt{2^n}}\sum_{k=0}^{2^n-1}e^{2\pi i jk/2^n}|k\rangle$。標準的な回路は最上位量子ビットにHadamardをかけ、後続の各量子ビットから制御位相回転$R_k=\mathrm{diag}(1,e^{2\pi i/2^k})$をそこへ適用し、これを各量子ビットについて繰り返した後、ビット順の規約次第で最後にSWAP層で順序を反転します。この層はこの項目のメタデータが明示している部分です。回路は$n$個のHadamardと$\binom{n}{2}$個の制御位相ゲート、合計$O(n^2)$ゲートを使い、古典FFTが振幅ベクトル全体に対して行う$O(N\log N)=O(2^n\cdot n)$回の算術演算と比べて指数的にゲート数が少なくて済みますが、それは測定(サンプリング)しなければならない量子振幅に対してであり、追加コストなしで得られる古典的な出力ベクトルではありません。この項目のチェックはエクスポート経路を通したパーサ・コンパイル互換性の比較であり、数値的な回路正当性の証明ではありません。`,
    literature: [COPPERSMITH_APPROX_QFT, NIELSEN_CHUANG],
  },
  "deutsch-jozsa-cirq": {
    explanationMd: String.raw`The Deutsch–Jozsa problem promises that $f:\{0,1\}^n\to\{0,1\}$ is either constant or balanced (outputs 0 and 1 equally often), and asks which. The circuit prepares the output qubit in $|-\rangle=\frac{1}{\sqrt2}(|0\rangle-|1\rangle)$ and the input register in $H^{\otimes n}|0\rangle^{\otimes n}$, queries the reversible oracle $U_f:|x\rangle|y\rangle\mapsto|x\rangle|y\oplus f(x)\rangle$ once, and applies $H^{\otimes n}$ again to the input register before measuring. Phase kickback turns each query into a sign $(-1)^{f(x)}$ on $|x\rangle$ rather than touching the output qubit, and interference across the $2^n$ branches makes the input register collapse to $|0\rangle^{\otimes n}$ exactly when $f$ is constant, and to a nonzero string when $f$ is balanced — one query suffices, versus up to $2^{n-1}+1$ classical queries in the worst case for a deterministic algorithm. This record reviews the phase-kickback circuit for a two-bit input against that construction; it stores one small educational oracle instance, not a general-$n$ benchmark.`,
    explanationMdJa: String.raw`Deutsch–Jozsa問題は $f:\{0,1\}^n\to\{0,1\}$ が定数関数かバランス関数(0と1が同数出力される)のいずれかであることを約束し、どちらかを問います。回路は出力量子ビットを$|-\rangle=\frac{1}{\sqrt2}(|0\rangle-|1\rangle)$に、入力レジスタを$H^{\otimes n}|0\rangle^{\otimes n}$に用意し、可逆オラクル$U_f:|x\rangle|y\rangle\mapsto|x\rangle|y\oplus f(x)\rangle$を1回呼び出した後、測定前に入力レジスタへ再び$H^{\otimes n}$を適用します。位相キックバックにより各クエリは出力量子ビットではなく$|x\rangle$への符号$(-1)^{f(x)}$として現れ、$2^n$個の分岐にわたる干渉により、$f$が定数のとき入力レジスタは厳密に$|0\rangle^{\otimes n}$に、バランスのときは非ゼロのビット列に収束します。決定的な古典アルゴリズムが最悪$2^{n-1}+1$回のクエリを要するのに対し、量子では1回のクエリで十分です。この項目は2ビット入力についての位相キックバック回路をこの構成と照らしてレビューしたものであり、一般の$n$についてのベンチマークではなく、小さな教育用オラクルの一例を保存しています。`,
    literature: [NIELSEN_CHUANG],
  },
  "bernstein-vazirani-qiskit": {
    explanationMd: String.raw`Bernstein–Vazirani recovers a hidden bit string $s\in\{0,1\}^n$ from an oracle for the parity function $f(x)=s\cdot x=\bigoplus_i s_i x_i \bmod 2$. The circuit prepares the output qubit in $|-\rangle$ and the input register in superposition, queries $U_f$ once — phase kickback writes $(-1)^{s\cdot x}$ onto $|x\rangle$ — and applies $H^{\otimes n}$ to the input register, which by the Hadamard/Fourier identity collapses it exactly to the basis state $|s\rangle$: measuring returns $s$ with certainty in the ideal circuit. Classically, determining an $n$-bit $s$ from black-box parity queries requires $n$ queries (one per standard basis vector), so the quantum circuit gives an $n$-to-$1$ query reduction under this promise, not a general search speedup. This record reviews the CX-based parity-oracle construction and its Deutsch–Jozsa-style readout; the one-query claim is scoped to this query/promise model, and oracle-construction and state-preparation costs stay visible rather than folded into the count.`,
    explanationMdJa: String.raw`Bernstein–Vaziraniは、パリティ関数 $f(x)=s\cdot x=\bigoplus_i s_i x_i \bmod 2$ のオラクルから隠れたビット列$s\in\{0,1\}^n$を復元します。回路は出力量子ビットを$|-\rangle$に、入力レジスタを重ね合わせに用意し、$U_f$を1回呼び出します(位相キックバックにより$|x\rangle$に$(-1)^{s\cdot x}$が書き込まれます)。その後入力レジスタに$H^{\otimes n}$を適用すると、Hadamard/フーリエ恒等式により、レジスタは厳密に基底状態$|s\rangle$へ収束し、理想回路では測定すると確実に$s$が得られます。古典的には、ブラックボックスのパリティクエリから$n$ビットの$s$を決定するには標準基底ベクトルごとに1回、計$n$回のクエリが必要です。したがって量子回路はこの約束の下で$n$対$1$のクエリ削減を与えますが、一般的な探索の高速化ではありません。この項目は、CXベースのパリティオラクル構成とそのDeutsch–Jozsa型読み出しをレビューしたものです。1回のクエリという主張はこのクエリ・約束モデルに限定されており、オラクル構成と状態準備のコストはクエリ数に埋め込まれず明示されたままです。`,
    literature: [NIELSEN_CHUANG],
  },
};
