import type { PublicRepositoryEntry } from "./types";
import { makeReferenceEntry } from "./factory";

// Populated by the catalog-expansion batches (2026-07-16 Owner Inbox: grow the
// public repository to 60+ records). Entries use makeReferenceEntry from
// ./factory; scripts/check-repository-data.mjs validates every record.

const NIELSEN_CHUANG = {
  title: "Quantum Computation and Quantum Information: 10th Anniversary Edition",
  authors: "Michael A. Nielsen and Isaac L. Chuang",
  year: "2010",
  url: "https://www.cambridge.org/highereducation/books/quantum-computation-and-quantum-information/01E10196D0A682A6AEFFEA52D53BE9AE",
  relevance: "Standard reference for single- and multi-qubit gate matrices, Euler-angle decomposition, and universal gate sets.",
  relevanceJa: "単一・複数量子ビットゲートの行列、オイラー角分解、万能ゲート集合に関する標準的な参考文献です。",
};

const BARENCO_1995 = {
  title: "Elementary gates for quantum computation",
  authors:
    "Adriano Barenco, Charles H. Bennett, Richard Cleve, David P. DiVincenzo, Norman Margolus, Peter Shor, Tycho Sleator, John A. Smolin, Harald Weinfurter",
  year: "1995",
  url: "https://arxiv.org/abs/quant-ph/9503016",
  relevance: "Shows that single-qubit U(2) gates plus CNOT are universal and gives explicit decompositions for controlled-U, Toffoli, and Fredkin gates.",
  relevanceJa: "単一量子ビットU(2)ゲートとCNOTが万能であることを示し、制御U・Toffoli・Fredkinゲートの明示的な分解を与えます。",
};

const OPENQASM3_PAPER = {
  title: "OpenQASM 3: A broader and deeper quantum assembly language",
  authors: "Andrew W. Cross, Ali Javadi-Abhari, Thomas Alexander, et al.",
  year: "2021",
  url: "https://arxiv.org/abs/2104.14722",
  relevance: "Defines the standard gate library (rx, ry, rz, p, u3-equivalent U, sx) used natively by the code snippets on this record.",
  relevanceJa: "この項目のコードで使うrx・ry・rz・p・U（u3相当）・sxなどの標準ゲートライブラリを定義します。",
};

const MCKAY_2017 = {
  title: "Efficient Z gates for quantum computing",
  authors: "David C. McKay, Christopher J. Wood, Sarah Sheldon, Jerry M. Chow, Jay M. Gambetta",
  year: "2017",
  url: "https://arxiv.org/abs/1612.00858",
  relevance: "Shows how a fixed physical X_{π/2} pulse (the SX gate) combined with zero-duration virtual Z rotations synthesizes any single-qubit unitary on superconducting hardware.",
  relevanceJa: "固定の物理的X_{π/2}パルス（SXゲート）と、実行時間ゼロの仮想Z回転を組み合わせることで、超伝導ハードウェア上で任意の単一量子ビットユニタリを合成できることを示します。",
};

const SMOLIN_DIVINCENZO_1996 = {
  title: "Five two-bit quantum gates are sufficient to implement the quantum Fredkin gate",
  authors: "John A. Smolin, David P. DiVincenzo",
  year: "1996",
  url: "https://link.aps.org/doi/10.1103/PhysRevA.53.2855",
  relevance: "Gives a five two-qubit-gate construction of the Fredkin (CSWAP) gate, improving on the naive CNOT–Toffoli–CNOT sandwich.",
  relevanceJa: "素朴なCNOT–Toffoli–CNOTの構成を改善する、5個の2量子ビットゲートによるFredkin（CSWAP）ゲートの構成を示します。",
};

const SCHUCH_SIEWERT_2003 = {
  title: "Natural two-qubit gate for quantum computation using the XY interaction",
  authors: "Norbert Schuch, Jens Siewert",
  year: "2003",
  url: "https://arxiv.org/abs/quant-ph/0209035",
  relevance: "Analyzes the iSWAP-family gate that arises naturally from an XY-type two-qubit interaction, the physical basis gate on several superconducting platforms.",
  relevanceJa: "XY型の2量子ビット相互作用から自然に生じるiSWAP系ゲートを解析します。これは複数の超伝導プラットフォームで物理的な基本ゲートです。",
};

export const GATE_ENTRIES: PublicRepositoryEntry[] = [
  makeReferenceEntry({
    slug: "rx-rotation-gate",
    title: "RX rotation gate",
    titleJa: "RX回転ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Rotation gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Unitary equivalence · RX(θ) matches exp(-iθX/2)",
    method:
      "Expand exp(-iθX/2) as a Pauli-basis Taylor series and compare the closed form against the parametrized RX matrix; separately check RX(π) against X up to global phase.",
    result: "Pass · RX(θ) = cos(θ/2)·I - i·sin(θ/2)·X for all tested θ, and RX(π) = -iX.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A parametrized single-qubit rotation about the Bloch-sphere X axis, one of the two generators (with RZ) used to synthesize arbitrary single-qubit unitaries.",
    descriptionJa: "ブロッホ球のX軸周りのパラメータ化された単一量子ビット回転で、RZとともに任意の単一量子ビットユニタリを合成する2つの生成子の一つです。",
    introduction:
      "RX(θ) generalizes the Pauli-X gate into a continuous one-parameter family, letting a circuit dial in any rotation angle instead of only the π flip.",
    introductionJa: "RX(θ)はパウリXゲートを連続的な1パラメータ族に一般化し、回路はπ回転だけでなく任意の回転角を設定できます。",
    explanation:
      "RX(θ) = cos(θ/2)·I - i·sin(θ/2)·X, generated by exponentiating the Pauli-X operator. At θ = π it reduces to X up to a global phase of -i.",
    explanationJa: "RX(θ) = cos(θ/2)·I - i·sin(θ/2)·X で、パウリX演算子の指数化により生成されます。θ = πでは大域位相-iを除いてXに一致します。",
    explanationMd: `## Definition

The $R_X$ gate rotates a single qubit about the $X$ axis of the Bloch sphere by an angle $\\theta$:

$$
R_X(\\theta) = e^{-i\\theta X/2} = \\begin{pmatrix} \\cos(\\theta/2) & -i\\sin(\\theta/2) \\\\ -i\\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}
$$

This follows from the operator-exponential identity $e^{-i\\theta X/2} = \\cos(\\theta/2)\\,I - i\\sin(\\theta/2)\\,X$, which holds because $X^2 = I$, so the Taylor series splits into even and odd powers of $X$ that resum to cosine and sine respectively.

## Action on basis states

$$
R_X(\\theta)|0\\rangle = \\cos(\\theta/2)|0\\rangle - i\\sin(\\theta/2)|1\\rangle, \\qquad R_X(\\theta)|1\\rangle = -i\\sin(\\theta/2)|0\\rangle + \\cos(\\theta/2)|1\\rangle
$$

At $\\theta = \\pi/2$ this produces an equal superposition with a relative phase of $-i$ rather than the $+$ that $H$ produces — the two gates land on different points of the Bloch-sphere equator.

## Key identities

- $R_X(\\pi) = -iX$: a full $\\pi$ rotation reproduces the Pauli-X flip up to the global phase $-i$, unobservable in isolation but relevant inside controlled operations.
- $R_X(\\theta_1)R_X(\\theta_2) = R_X(\\theta_1 + \\theta_2)$: rotations about the same axis compose additively, so $R_X$ forms a one-parameter subgroup of $SU(2)$.
- $R_X(\\theta) = H\\,R_Z(\\theta)\\,H$: since $HXH = Z$, conjugating $R_Z$ by Hadamard swaps the rotation axis from $Z$ to $X$ — the standard way a $Z$-rotation-native compiler synthesizes $R_X$.
- Together with $R_Z$, $R_X$ generates arbitrary single-qubit unitaries via Euler decomposition, e.g. $R_Z(\\alpha)R_X(\\beta)R_Z(\\gamma)$ up to a global phase.`,
    explanationMdJa: `## 定義

$R_X$ゲートは、量子ビットをブロッホ球の$X$軸周りに角度$\\theta$だけ回転させます。

$$
R_X(\\theta) = e^{-i\\theta X/2} = \\begin{pmatrix} \\cos(\\theta/2) & -i\\sin(\\theta/2) \\\\ -i\\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}
$$

これは演算子指数の恒等式$e^{-i\\theta X/2} = \\cos(\\theta/2)\\,I - i\\sin(\\theta/2)\\,X$から従います。$X^2 = I$なので、テイラー級数が$X$の偶数次と奇数次に分かれ、それぞれコサインとサインに再和されるためです。

## 基底状態への作用

$$
R_X(\\theta)|0\\rangle = \\cos(\\theta/2)|0\\rangle - i\\sin(\\theta/2)|1\\rangle, \\qquad R_X(\\theta)|1\\rangle = -i\\sin(\\theta/2)|0\\rangle + \\cos(\\theta/2)|1\\rangle
$$

$\\theta = \\pi/2$のとき、等しい重ね合わせが生成されますが、相対位相は$H$が作る「+」ではなく「$-i$」です。両ゲートはブロッホ球の赤道上の異なる点に対応します。

## 主要な恒等式

- $R_X(\\pi) = -iX$: πの全回転は、大域位相$-i$を除いてパウリXの反転を再現します。この位相は単独では観測できませんが、制御演算の中では意味を持ちます。
- $R_X(\\theta_1)R_X(\\theta_2) = R_X(\\theta_1 + \\theta_2)$: 同じ軸周りの回転は加法的に合成されるため、$R_X$は$SU(2)$の1パラメータ部分群をなします。
- $R_X(\\theta) = H\\,R_Z(\\theta)\\,H$: $HXH = Z$なので、$R_Z$をアダマールで共役すると回転軸が$Z$から$X$に変わります。これは$Z$回転のみをネイティブに持つコンパイラが$R_X$を合成する標準的な方法です。
- $R_Z$と合わせて、$R_X$はオイラー分解（大域位相を除き例えば$R_Z(\\alpha)R_X(\\beta)R_Z(\\gamma)$）によって任意の単一量子ビットユニタリを生成します。`,
    tags: ["rotation gate", "single qubit", "parametrized"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Parameter", value: "θ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "[[cos(θ/2), -i sin(θ/2)], [-i sin(θ/2), cos(θ/2)]]" },
      { label: "Rotation axis", value: "X" },
      { label: "Generator", value: "exp(-iθX/2)" },
      { label: "Gate family", value: "Non-Clifford (generic θ)" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "RX(π/2)", qubits: [0], tone: "accent" }],
    outcomes: [
      { label: "P(|0⟩) at θ=π/2", probability: 0.5 },
      { label: "P(|1⟩) at θ=π/2", probability: 0.5 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nrx(pi/2) q;`,
    filename: "rx-rotation.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "rx_rotation.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(1)\nqc.rx(np.pi / 2, 0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "rx_rotation.py",
        code: `import cirq\nimport numpy as np\n\nq = cirq.LineQubit(0)\ncircuit = cirq.Circuit(cirq.rx(np.pi / 2).on(q))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["ry-rotation-gate", "rz-rotation-gate", "pauli-x-operator", "u3-universal-gate"],
    literature: [NIELSEN_CHUANG, OPENQASM3_PAPER],
  }),

  makeReferenceEntry({
    slug: "ry-rotation-gate",
    title: "RY rotation gate",
    titleJa: "RY回転ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Rotation gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Unitary equivalence · RY(θ) matches exp(-iθY/2)",
    method:
      "Expand exp(-iθY/2) as a Pauli-basis Taylor series and compare against the parametrized RY matrix; check that all matrix entries stay real for real θ.",
    result: "Pass · RY(θ) = cos(θ/2)·I - i·sin(θ/2)·Y, and every entry is a real number for real θ.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A parametrized single-qubit rotation about the Bloch-sphere Y axis whose matrix entries are always real, making it the standard tool for encoding real-valued amplitudes.",
    descriptionJa: "ブロッホ球のY軸周りのパラメータ化された単一量子ビット回転で、行列要素が常に実数であるため実数値振幅の符号化に標準的に使われます。",
    introduction:
      "RY(θ) is the gate of choice whenever a circuit needs to move probability amplitude between |0⟩ and |1⟩ without introducing a complex relative phase.",
    introductionJa: "RY(θ)は、複素の相対位相を導入せずに|0⟩と|1⟩の間で確率振幅を移動させたいときに選ばれるゲートです。",
    explanation:
      "RY(θ) = cos(θ/2)·I - i·sin(θ/2)·Y. Because Y is purely imaginary off-diagonal, the -i factor cancels and the resulting 2x2 matrix is real and orthogonal — a genuine rotation, not just a unitary.",
    explanationJa: "RY(θ) = cos(θ/2)·I - i·sin(θ/2)·Y です。Yは非対角成分が純虚数なので-i因子が打ち消し合い、結果の2x2行列は実数の直交行列になります。ユニタリというだけでなく、真の回転です。",
    explanationMd: `## Definition

$$
R_Y(\\theta) = e^{-i\\theta Y/2} = \\begin{pmatrix} \\cos(\\theta/2) & -\\sin(\\theta/2) \\\\ \\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}
$$

Unlike $R_X$ or $R_Z$, every entry of $R_Y(\\theta)$ is a real number for real $\\theta$: the $-i$ prefactor from the exponential exactly cancels the $\\pm i$ entries of $Y = \\begin{pmatrix}0 & -i \\\\ i & 0\\end{pmatrix}$, leaving a real $2\\times 2$ rotation matrix — the same form as a classical rotation matrix in the $(|0\\rangle, |1\\rangle)$ plane.

## Action on basis states

$$
R_Y(\\theta)|0\\rangle = \\cos(\\theta/2)|0\\rangle + \\sin(\\theta/2)|1\\rangle, \\qquad R_Y(\\theta)|1\\rangle = -\\sin(\\theta/2)|0\\rangle + \\cos(\\theta/2)|1\\rangle
$$

At $\\theta = \\pi/2$, $R_Y(\\pi/2)|0\\rangle = \\tfrac{1}{\\sqrt2}(|0\\rangle + |1\\rangle)$ — the same state Hadamard produces on $|0\\rangle$, but $R_Y(\\pi/2)|1\\rangle = \\tfrac{1}{\\sqrt2}(-|0\\rangle + |1\\rangle)$ differs from $H|1\\rangle$ by an overall sign.

## Key identities

- $R_Y(\\pi) = -iY$: a full $\\pi$ rotation reproduces the Pauli-Y flip up to global phase $-i$.
- $X R_Y(\\theta) X = R_Y(-\\theta)$: since $XYX = -Y$, conjugating by $X$ reverses the rotation direction.
- Because its output amplitudes are real, $R_Y(\\theta)$ is the standard primitive for amplitude encoding — loading a classical probability vector $(\\cos(\\theta/2), \\sin(\\theta/2))$ into a qubit — and for the mixer layers of variational circuits such as hardware-efficient ansätze.
- $R_Y(\\theta) = R_Z(-\\pi/2)\\,R_X(\\theta)\\,R_Z(\\pi/2)$: an axis change from $X$ to $Y$ via conjugation by a $Z$ rotation, mirroring the $H$-conjugation identity that relates $R_X$ and $R_Z$.`,
    explanationMdJa: `## 定義

$$
R_Y(\\theta) = e^{-i\\theta Y/2} = \\begin{pmatrix} \\cos(\\theta/2) & -\\sin(\\theta/2) \\\\ \\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}
$$

$R_X$や$R_Z$と異なり、実数の$\\theta$に対して$R_Y(\\theta)$のすべての要素は実数です。指数の$-i$係数が$Y = \\begin{pmatrix}0 & -i \\\\ i & 0\\end{pmatrix}$の$\\pm i$要素とちょうど打ち消し合い、実数の$2\\times 2$回転行列が残ります。これは$(|0\\rangle, |1\\rangle)$平面における古典的な回転行列と同じ形です。

## 基底状態への作用

$$
R_Y(\\theta)|0\\rangle = \\cos(\\theta/2)|0\\rangle + \\sin(\\theta/2)|1\\rangle, \\qquad R_Y(\\theta)|1\\rangle = -\\sin(\\theta/2)|0\\rangle + \\cos(\\theta/2)|1\\rangle
$$

$\\theta = \\pi/2$のとき、$R_Y(\\pi/2)|0\\rangle = \\tfrac{1}{\\sqrt2}(|0\\rangle + |1\\rangle)$となり、これはアダマールが$|0\\rangle$に作る状態と同じです。しかし$R_Y(\\pi/2)|1\\rangle = \\tfrac{1}{\\sqrt2}(-|0\\rangle + |1\\rangle)$は、$H|1\\rangle$と全体の符号だけ異なります。

## 主要な恒等式

- $R_Y(\\pi) = -iY$: πの全回転は、大域位相$-i$を除いてパウリYの反転を再現します。
- $X R_Y(\\theta) X = R_Y(-\\theta)$: $XYX = -Y$なので、Xによる共役は回転方向を反転させます。
- 出力振幅が実数であるため、$R_Y(\\theta)$は振幅エンコーディング（古典的な確率ベクトル$(\\cos(\\theta/2), \\sin(\\theta/2))$を量子ビットに読み込むこと）や、ハードウェア効率的アンザッツなど変分回路のミキサー層の標準的な部品です。
- $R_Y(\\theta) = R_Z(-\\pi/2)\\,R_X(\\theta)\\,R_Z(\\pi/2)$: $Z$回転による共役で回転軸を$X$から$Y$へ変える恒等式で、$R_X$と$R_Z$を結ぶ$H$共役の恒等式に対応します。`,
    tags: ["rotation gate", "single qubit", "real amplitude"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Parameter", value: "θ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "[[cos(θ/2), -sin(θ/2)], [sin(θ/2), cos(θ/2)]]" },
      { label: "Rotation axis", value: "Y" },
      { label: "Generator", value: "exp(-iθY/2)" },
      { label: "Gate family", value: "Non-Clifford (generic θ), real-valued" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "RY(π/2)", qubits: [0], tone: "accent" }],
    outcomes: [
      { label: "P(|0⟩) at θ=π/2", probability: 0.5 },
      { label: "P(|1⟩) at θ=π/2", probability: 0.5 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nry(pi/2) q;`,
    filename: "ry-rotation.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "ry_rotation.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(1)\nqc.ry(np.pi / 2, 0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "ry_rotation.py",
        code: `import cirq\nimport numpy as np\n\nq = cirq.LineQubit(0)\ncircuit = cirq.Circuit(cirq.ry(np.pi / 2).on(q))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["rx-rotation-gate", "rz-rotation-gate", "u3-universal-gate", "hadamard-gate"],
    literature: [NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "rz-rotation-gate",
    title: "RZ rotation gate",
    titleJa: "RZ回転ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Rotation gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Unitary equivalence · RZ(θ) matches diag(e^{-iθ/2}, e^{iθ/2})",
    method:
      "Compare the parametrized RZ matrix against the diagonal exponential form diag(e^{-iθ/2}, e^{iθ/2}) and confirm it leaves computational-basis probabilities unchanged.",
    result: "Pass · RZ(θ) = diag(e^{-iθ/2}, e^{iθ/2}) exactly; |⟨0|RZ(θ)|0⟩|² = |⟨1|RZ(θ)|1⟩|² = 1 for all θ.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A parametrized single-qubit rotation about the Z axis that adds a relative phase between |0⟩ and |1⟩ without changing measurement probabilities in the computational basis.",
    descriptionJa: "Z軸周りのパラメータ化された単一量子ビット回転で、計算基底での測定確率を変えずに|0⟩と|1⟩の間に相対位相を加えます。",
    introduction:
      "RZ(θ) is often the cheapest gate on real hardware — on superconducting devices it can be implemented as a zero-duration frame change rather than a physical pulse.",
    introductionJa: "RZ(θ)は実機で最も安価なゲートであることが多く、超伝導デバイスでは物理パルスではなく実行時間ゼロのフレーム変更として実装できます。",
    explanation:
      "RZ(θ) = diag(e^{-iθ/2}, e^{iθ/2}). Applied to |0⟩ or |1⟩ alone it only changes an unobservable global phase; applied inside a superposition it changes the relative phase that later interference can detect.",
    explanationJa: "RZ(θ) = diag(e^{-iθ/2}, e^{iθ/2}) です。|0⟩や|1⟩単独に適用すると観測不能な大域位相しか変わりませんが、重ね合わせの中では後の干渉で検出できる相対位相が変わります。",
    explanationMd: `## Definition

$$
R_Z(\\theta) = e^{-i\\theta Z/2} = \\begin{pmatrix} e^{-i\\theta/2} & 0 \\\\ 0 & e^{i\\theta/2} \\end{pmatrix}
$$

$R_Z$ is diagonal in the computational basis, so it commutes with any other $R_Z(\\phi)$ and with measurement in the $Z$ basis.

## Action on basis states

$$
R_Z(\\theta)|0\\rangle = e^{-i\\theta/2}|0\\rangle, \\qquad R_Z(\\theta)|1\\rangle = e^{i\\theta/2}|1\\rangle
$$

Each basis state only picks up a phase, so $|\\langle 0|R_Z(\\theta)|0\\rangle|^2 = |\\langle 1|R_Z(\\theta)|1\\rangle|^2 = 1$ for every $\\theta$ — a $Z$ rotation is invisible to a $Z$-basis measurement on its own. Its effect only shows up on a qubit already in superposition, e.g. $R_Z(\\theta)\\tfrac{1}{\\sqrt2}(|0\\rangle+|1\\rangle) = \\tfrac{1}{\\sqrt2}(e^{-i\\theta/2}|0\\rangle + e^{i\\theta/2}|1\\rangle)$, which differs from the input by a relative phase of $e^{i\\theta}$.

## Key identities

- $P(\\lambda) = e^{i\\lambda/2}R_Z(\\lambda)$: the OpenQASM phase gate $P$ is $R_Z$ up to an overall phase — $P$ fixes the $|0\\rangle$ amplitude at exactly $1$ instead of splitting the phase symmetrically.
- $S = R_Z(\\pi/2)$ and $T = R_Z(\\pi/4)$ up to global phase, so $R_Z$ generalizes the whole Clifford/non-Clifford phase-gate ladder to a continuous parameter.
- $R_X(\\theta) = H R_Z(\\theta) H$ and $R_Y(\\theta) = R_Z(-\\pi/2) R_X(\\theta) R_Z(\\pi/2)$: composing conjugations by $H$ and by $R_Z(\\pm\\pi/2)$ lets a compiler reach any rotation axis from $R_Z$ alone.
- On superconducting hardware, $R_Z(\\theta)$ is frequently realized as a *virtual* zero-duration frame update rather than a physical microwave pulse, making it effectively free and noiseless compared to $R_X$/$R_Y$.`,
    explanationMdJa: `## 定義

$$
R_Z(\\theta) = e^{-i\\theta Z/2} = \\begin{pmatrix} e^{-i\\theta/2} & 0 \\\\ 0 & e^{i\\theta/2} \\end{pmatrix}
$$

$R_Z$は計算基底で対角なので、他の$R_Z(\\phi)$や$Z$基底での測定と可換です。

## 基底状態への作用

$$
R_Z(\\theta)|0\\rangle = e^{-i\\theta/2}|0\\rangle, \\qquad R_Z(\\theta)|1\\rangle = e^{i\\theta/2}|1\\rangle
$$

各基底状態は位相だけを受け取るため、任意の$\\theta$について$|\\langle 0|R_Z(\\theta)|0\\rangle|^2 = |\\langle 1|R_Z(\\theta)|1\\rangle|^2 = 1$です。つまり$Z$回転はそれ単独では$Z$基底測定に対して不可視です。その効果は、すでに重ね合わせにある量子ビットにのみ現れます。例えば$R_Z(\\theta)\\tfrac{1}{\\sqrt2}(|0\\rangle+|1\\rangle) = \\tfrac{1}{\\sqrt2}(e^{-i\\theta/2}|0\\rangle + e^{i\\theta/2}|1\\rangle)$は、入力と$e^{i\\theta}$の相対位相だけ異なります。

## 主要な恒等式

- $P(\\lambda) = e^{i\\lambda/2}R_Z(\\lambda)$: OpenQASMの位相ゲート$P$は、大域位相を除けば$R_Z$です。$P$は$|0\\rangle$振幅をちょうど$1$に固定し、位相を対称に分割しません。
- 大域位相を除き$S = R_Z(\\pi/2)$、$T = R_Z(\\pi/4)$なので、$R_Z$はクリフォード・非クリフォードの位相ゲート系列全体を連続パラメータへ一般化します。
- $R_X(\\theta) = H R_Z(\\theta) H$、$R_Y(\\theta) = R_Z(-\\pi/2) R_X(\\theta) R_Z(\\pi/2)$: $H$と$R_Z(\\pm\\pi/2)$による共役を組み合わせることで、コンパイラは$R_Z$だけから任意の回転軸に到達できます。
- 超伝導ハードウェアでは、$R_Z(\\theta)$は物理的なマイクロ波パルスではなく、実行時間ゼロの「仮想」フレーム更新として実現されることが多く、$R_X$/$R_Y$と比べて実質無コストかつノイズなしです。`,
    tags: ["rotation gate", "single qubit", "phase", "virtual z"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate (often 0-duration on hardware)" },
      { label: "Parameter", value: "θ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "diag(e^{-iθ/2}, e^{iθ/2})" },
      { label: "Rotation axis", value: "Z" },
      { label: "Generator", value: "exp(-iθZ/2)" },
      { label: "Gate family", value: "Diagonal / phase, commutes with Z measurement" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "RZ(π/2)", qubits: [0], tone: "accent" }],
    outcomes: [
      { label: "P(|0⟩) unchanged", probability: 1 },
      { label: "P(|1⟩) unchanged", probability: 0 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nrz(pi/2) q;`,
    filename: "rz-rotation.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "rz_rotation.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(1)\nqc.rz(np.pi / 2, 0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "rz_rotation.py",
        code: `import cirq\nimport numpy as np\n\nq = cirq.LineQubit(0)\ncircuit = cirq.Circuit(cirq.rz(np.pi / 2).on(q))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["rx-rotation-gate", "ry-rotation-gate", "phase-gate-p", "s-phase-gate", "t-phase-gate"],
    literature: [NIELSEN_CHUANG, MCKAY_2017],
  }),

  makeReferenceEntry({
    slug: "phase-gate-p",
    title: "P phase gate",
    titleJa: "P位相ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Single-qubit gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Unitary equivalence · P(λ) matches diag(1, e^{iλ}) and its special cases",
    method:
      "Compare the parametrized P matrix against diag(1, e^{iλ}) and evaluate it at λ = π/2, π/4, π to check agreement with S, T, and Z.",
    result: "Pass · P(π/2) = S, P(π/4) = T, and P(π) = Z, all exactly.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "The generalized phase gate that fixes the |0⟩ amplitude at 1 and applies e^{iλ} to |1⟩, unifying S, T, and Z as special cases of one continuous parameter.",
    descriptionJa: "|0⟩振幅を1に固定し、|1⟩にe^{iλ}を適用する一般化位相ゲートで、S・T・Zを1つの連続パラメータの特殊な場合として統一します。",
    introduction:
      "P(λ) is the OpenQASM 3 standard-library phase gate and the natural way to express a whole family of fixed phase gates with a single parametrized definition.",
    introductionJa: "P(λ)はOpenQASM 3標準ライブラリの位相ゲートで、固定位相ゲートの系列全体を単一のパラメータ化された定義で表す自然な方法です。",
    explanation:
      "P(λ) = diag(1, e^{iλ}) leaves |0⟩ exactly fixed and multiplies |1⟩ by e^{iλ}. Unlike RZ, it does not split the phase symmetrically, so P(λ) = e^{iλ/2}RZ(λ) differs from RZ only by an overall phase.",
    explanationJa: "P(λ) = diag(1, e^{iλ}) は|0⟩をそのまま保ち、|1⟩にe^{iλ}を掛けます。RZと異なり位相を対称に分割しないため、P(λ) = e^{iλ/2}RZ(λ) はRZと全体の位相だけ異なります。",
    explanationMd: `## Definition

$$
P(\\lambda) = \\begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\\lambda} \\end{pmatrix}
$$

$P$ fixes the $|0\\rangle$ amplitude at exactly $1$ and rotates only the $|1\\rangle$ amplitude by $\\lambda$ — a convention choice, since any diagonal unitary is determined by its two phases up to an overall factor.

## Action on basis states

$$
P(\\lambda)|0\\rangle = |0\\rangle, \\qquad P(\\lambda)|1\\rangle = e^{i\\lambda}|1\\rangle
$$

Applied to a superposition $\\alpha|0\\rangle+\\beta|1\\rangle$, only the relative phase between the two amplitudes changes, by exactly $\\lambda$.

## Key identities and special cases

$$
P(\\pi/2) = S, \\qquad P(\\pi/4) = T, \\qquad P(\\pi) = Z, \\qquad P(2\\pi) = I
$$

so $P$ is the continuous parent of the entire discrete phase-gate ladder $\\{I, T, S, Z\\}$ built from repeated $\\pi/4$ steps.

- $P(\\lambda) = e^{i\\lambda/2}R_Z(\\lambda)$: $P$ and $R_Z$ implement the same rotation up to a global phase; $P$ is the more convenient convention when composing controlled-phase gates, since a controlled-$P$ needs no extra correction for the global phase (a controlled-$R_Z$ does).
- $P(\\lambda_1)P(\\lambda_2) = P(\\lambda_1+\\lambda_2)$: phases add, so repeated $P$ gates telescope into one gate at synthesis time.
- Controlled-$P(\\lambda)$ is the entangling phase primitive used at every stage of the quantum Fourier transform, where the angles are $\\pi/2, \\pi/4, \\pi/8, \\dots$.`,
    explanationMdJa: `## 定義

$$
P(\\lambda) = \\begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\\lambda} \\end{pmatrix}
$$

$P$は|0⟩振幅をちょうど$1$に固定し、|1⟩振幅だけを$\\lambda$だけ回転させます。任意の対角ユニタリは全体の係数を除いて2つの位相で決まるため、これは規約上の選択です。

## 基底状態への作用

$$
P(\\lambda)|0\\rangle = |0\\rangle, \\qquad P(\\lambda)|1\\rangle = e^{i\\lambda}|1\\rangle
$$

重ね合わせ$\\alpha|0\\rangle+\\beta|1\\rangle$に適用すると、2つの振幅間の相対位相だけがちょうど$\\lambda$変化します。

## 主要な恒等式と特殊な場合

$$
P(\\pi/2) = S, \\qquad P(\\pi/4) = T, \\qquad P(\\pi) = Z, \\qquad P(2\\pi) = I
$$

したがって$P$は、π/4刻みで構成される離散的な位相ゲート系列$\\{I, T, S, Z\\}$全体の連続的な親と言えます。

- $P(\\lambda) = e^{i\\lambda/2}R_Z(\\lambda)$: $P$と$R_Z$は大域位相を除いて同じ回転を実装します。制御位相ゲートを合成する際は$P$の規約の方が便利です。制御$P$は大域位相の補正が不要ですが、制御$R_Z$は必要になるためです。
- $P(\\lambda_1)P(\\lambda_2) = P(\\lambda_1+\\lambda_2)$: 位相は加算されるため、連続する$P$ゲートは合成時に1つのゲートへまとめられます。
- 制御$P(\\lambda)$は、量子フーリエ変換の各段階で使われるエンタングルする位相の基本演算で、角度は$\\pi/2, \\pi/4, \\pi/8, \\dots$です。`,
    tags: ["phase", "parametrized", "single qubit"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Parameter", value: "λ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "diag(1, e^{iλ})" },
      { label: "Special cases", value: "P(π/2)=S, P(π/4)=T, P(π)=Z" },
      { label: "Relation to RZ", value: "P(λ) = e^{iλ/2} RZ(λ)" },
      { label: "Gate family", value: "Clifford at λ=π/2,π; non-Clifford otherwise" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "P(π/4)", qubits: [0], tone: "accent" }],
    outcomes: [
      { label: "P(|0⟩) unchanged", probability: 1 },
      { label: "P(|1⟩) unchanged", probability: 0 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\np(pi/4) q;`,
    filename: "phase-p.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "phase_p.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(1)\nqc.p(np.pi / 4, 0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "phase_p.py",
        code: `import cirq\n\nq = cirq.LineQubit(0)\n# Z**t applies phase e^{i*pi*t} to |1>; t=0.25 gives e^{i*pi/4}\ncircuit = cirq.Circuit(cirq.ZPowGate(exponent=0.25).on(q))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["rz-rotation-gate", "s-phase-gate", "t-phase-gate", "controlled-phase-gate"],
    literature: [OPENQASM3_PAPER, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "u3-universal-gate",
    title: "U3 universal single-qubit gate",
    titleJa: "U3万能単一量子ビットゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Universal single-qubit gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Unitary equivalence · U3(θ,φ,λ) reproduces H, X, RX, RY, and P at fixed parameters",
    method:
      "Evaluate the general U3 matrix at parameter values known to reduce to standard gates (X, H, RX, RY, P) and compare each against its reference matrix.",
    result: "Pass · U3(π,0,π)=X, U3(π/2,0,π)=H (up to global phase), U3(θ,-π/2,π/2)=RX(θ), U3(0,0,λ)=P(λ).",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "The three-parameter gate that can reach any single-qubit unitary up to global phase, used as the universal target when a compiler synthesizes one-qubit operations from Euler angles.",
    descriptionJa: "大域位相を除いて任意の単一量子ビットユニタリに到達できる3パラメータゲートで、コンパイラがオイラー角から単一量子ビット演算を合成する際の万能な目標として使われます。",
    introduction:
      "U3 packages the Euler-angle decomposition of SU(2) into one gate definition, so every single-qubit gate in a circuit — Pauli, Hadamard, phase, or arbitrary rotation — can be expressed as one U3 call.",
    introductionJa: "U3はSU(2)のオイラー角分解を1つのゲート定義にまとめており、回路中のあらゆる単一量子ビットゲート（パウリ、アダマール、位相、任意回転）を1回のU3呼び出しとして表現できます。",
    explanation:
      "U3(θ,φ,λ) rotates by θ about an axis set by φ and applies phases parametrized by φ and λ; concretely it equals RZ(φ)RY(θ)RZ(λ) up to a global phase, so any three real parameters reach any point in SU(2)/phase.",
    explanationJa: "U3(θ,φ,λ) はφで決まる軸周りにθだけ回転し、φとλでパラメータ化された位相を適用します。具体的には大域位相を除きRZ(φ)RY(θ)RZ(λ)に等しく、3つの実数パラメータでSU(2)/位相の任意の点に到達できます。",
    explanationMd: `## Definition

$$
U_3(\\theta,\\varphi,\\lambda) = \\begin{pmatrix} \\cos(\\theta/2) & -e^{i\\lambda}\\sin(\\theta/2) \\\\ e^{i\\varphi}\\sin(\\theta/2) & e^{i(\\varphi+\\lambda)}\\cos(\\theta/2) \\end{pmatrix}
$$

Every $2\\times 2$ unitary can be written, up to an overall global phase, as some $U_3(\\theta,\\varphi,\\lambda)$: $\\theta$ sets the polar angle on the Bloch sphere and $\\varphi,\\lambda$ set the two phases needed to fix the axis and the relative phase.

## Euler-angle decomposition

$$
U_3(\\theta,\\varphi,\\lambda) = e^{i(\\varphi+\\lambda)/2}\\, R_Z(\\varphi)\\, R_Y(\\theta)\\, R_Z(\\lambda)
$$

This is the ZYZ Euler decomposition used by every gate-synthesis pass that targets a native $\\{R_Z, R_Y\\}$ or $\\{R_Z, R_X\\}$ gate set: any single-qubit unitary is first written as $U_3$, then compiled into three native rotations plus a tracked global phase.

## Special cases

$$
U_3(\\pi,0,\\pi) = X, \\qquad U_3\\!\\left(\\tfrac{\\pi}{2},0,\\pi\\right) \\doteq H, \\qquad U_3(\\theta,0,0) \\doteq R_Y(\\theta), \\qquad U_3(0,0,\\lambda) = P(\\lambda)
$$

(the $\\doteq$ marks equality up to an unobservable global phase). Because it subsumes every other single-qubit gate in this catalog as a special case, $U_3$ is the natural "universal" record to compare them against.

## Practical note

Modern Qiskit exposes this gate as the generic $U$ gate (qc.u(theta, phi, lam, qubit)) — the historical name u3 referred to the same three-parameter definition before Qiskit's gate-naming cleanup.`,
    explanationMdJa: `## 定義

$$
U_3(\\theta,\\varphi,\\lambda) = \\begin{pmatrix} \\cos(\\theta/2) & -e^{i\\lambda}\\sin(\\theta/2) \\\\ e^{i\\varphi}\\sin(\\theta/2) & e^{i(\\varphi+\\lambda)}\\cos(\\theta/2) \\end{pmatrix}
$$

任意の$2\\times 2$ユニタリは、全体の大域位相を除いてある$U_3(\\theta,\\varphi,\\lambda)$として書けます。$\\theta$はブロッホ球上の極角を定め、$\\varphi,\\lambda$は軸と相対位相を固定するために必要な2つの位相を定めます。

## オイラー角分解

$$
U_3(\\theta,\\varphi,\\lambda) = e^{i(\\varphi+\\lambda)/2}\\, R_Z(\\varphi)\\, R_Y(\\theta)\\, R_Z(\\lambda)
$$

これはZYZオイラー分解で、ネイティブな$\\{R_Z, R_Y\\}$や$\\{R_Z, R_X\\}$ゲート集合を目標とするあらゆるゲート合成パスで使われます。任意の単一量子ビットユニタリはまず$U_3$として書かれ、その後3つのネイティブ回転と追跡された大域位相へコンパイルされます。

## 特殊な場合

$$
U_3(\\pi,0,\\pi) = X, \\qquad U_3\\!\\left(\\tfrac{\\pi}{2},0,\\pi\\right) \\doteq H, \\qquad U_3(\\theta,0,0) \\doteq R_Y(\\theta), \\qquad U_3(0,0,\\lambda) = P(\\lambda)
$$

（$\\doteq$は観測不能な大域位相を除く等価を表します）。このカタログの他のあらゆる単一量子ビットゲートを特殊な場合として含むため、$U_3$はそれらと比較するための自然な「万能」記録です。

## 実務上の注記

現在のQiskitではこのゲートは汎用の$U$ゲート（qc.u(theta, phi, lam, qubit)）として公開されています。歴史的な名称u3は、Qiskitのゲート命名整理以前の同じ3パラメータ定義を指していました。`,
    tags: ["universal gate", "single qubit", "euler angles"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Parameters", value: "θ, φ, λ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "[[cos(θ/2), -e^{iλ}sin(θ/2)], [e^{iφ}sin(θ/2), e^{i(φ+λ)}cos(θ/2)]]" },
      { label: "Decomposition", value: "e^{i(φ+λ)/2} RZ(φ) RY(θ) RZ(λ)" },
      { label: "Coverage", value: "Any single-qubit unitary up to global phase" },
      { label: "Gate family", value: "Universal (Clifford and non-Clifford as special cases)" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "U3(π/2, 0, π)", qubits: [0], tone: "accent" }],
    outcomes: [
      { label: "P(|0⟩) at H-equivalent params", probability: 0.5 },
      { label: "P(|1⟩) at H-equivalent params", probability: 0.5 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nU(pi/2, 0, pi) q;`,
    filename: "u3-universal.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "u3_universal.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(1)\n# Modern Qiskit exposes this as the generic U gate (formerly u3)\nqc.u(np.pi / 2, 0, np.pi, 0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "u3_universal.py",
        code: `import cirq\nimport numpy as np\n\nq = cirq.LineQubit(0)\n# ZYZ decomposition: U3(theta, phi, lam) = Rz(phi) Ry(theta) Rz(lam) up to global phase\ntheta, phi, lam = np.pi / 2, 0.0, np.pi\ncircuit = cirq.Circuit(\n    cirq.rz(lam).on(q),\n    cirq.ry(theta).on(q),\n    cirq.rz(phi).on(q),\n)\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["rx-rotation-gate", "ry-rotation-gate", "rz-rotation-gate", "phase-gate-p", "hadamard-gate"],
    literature: [BARENCO_1995, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "sx-sqrt-x-gate",
    title: "SX (√X) gate",
    titleJa: "SX（√X）ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Single-qubit gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "textbook_citation"],
    verification: "Square check · SX·SX = X",
    method: "Multiply the SX matrix by itself and compare the product against the Pauli-X matrix.",
    result: "Pass · SX² = X exactly, confirming SX is a genuine matrix square root of X.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A Clifford square root of the Pauli-X gate that is the native physical single-qubit gate (an X_{π/2} pulse) on most superconducting hardware.",
    descriptionJa: "パウリXゲートのクリフォード的な平方根であり、ほとんどの超伝導ハードウェアでネイティブな物理単一量子ビットゲート（X_{π/2}パルス）です。",
    introduction:
      "SX matters less as an algorithmic primitive and more as a hardware fact: many transmon-qubit backends implement exactly one calibrated single-qubit pulse, and SX is that pulse.",
    introductionJa: "SXはアルゴリズム上の基本要素としてよりも、ハードウェア上の事実として重要です。多くのトランズモン量子ビットのバックエンドは較正された単一量子ビットパルスを1種類だけ実装しており、SXがそのパルスです。",
    explanation:
      "SX = (1/2)[[1+i,1-i],[1-i,1+i]] squares to X. Up to a global phase e^{iπ/4}, SX equals RX(π/2), so two SX pulses back to back implement a full X flip.",
    explanationJa: "SX = (1/2)[[1+i,1-i],[1-i,1+i]] はXへの平方根です。大域位相e^{iπ/4}を除きSXはRX(π/2)に等しく、SXパルスを2回連続で適用すると完全なXの反転になります。",
    explanationMd: `## Definition

$$
\\sqrt{X} \\equiv SX = \\frac{1}{2}\\begin{pmatrix} 1+i & 1-i \\\\ 1-i & 1+i \\end{pmatrix}
$$

Squaring the matrix directly confirms $SX \\cdot SX = X$: it is a genuine matrix square root of the Pauli-X gate, and one of exactly four square roots of $X$ up to global phase (the others being $-SX$, $SX^\\dagger$ scaled, etc.).

## Action on basis states

$$
SX|0\\rangle = \\tfrac12\\big[(1+i)|0\\rangle + (1-i)|1\\rangle\\big], \\qquad SX|1\\rangle = \\tfrac12\\big[(1-i)|0\\rangle + (1+i)|1\\rangle\\big]
$$

Both outcomes are measured with equal probability $1/2$; the gate's effect is entirely in the phase relationship between the two amplitudes, which a second $SX$ resolves back into a deterministic bit flip.

## Key identities

- $SX = e^{i\\pi/4} R_X(\\pi/2)$: up to global phase, $SX$ is precisely the $R_X$ rotation halfway to a full $X$ flip.
- $SX$ is a Clifford gate: conjugating any Pauli operator by $SX$ returns a Pauli operator (up to sign), e.g. $SX \\cdot Z \\cdot SX^\\dagger = -Y$. This is why $SX$, together with $R_Z$ and $\\mathrm{CX}$, forms a common native gate set for Clifford-heavy compilation.
- $SX^\\dagger \\cdot SX = I$ and $SX \\cdot SX = X$, so $SX^4 = X^2 = I$ — $SX$ has order 4.
- Combined with virtual $R_Z$ frame changes, two calibrated $SX$ pulses (an $R_X(\\pi/2)$–$R_Z$–$R_X(\\pi/2)$ sequence) synthesize *any* single-qubit unitary, which is why $SX$ rather than a general $R_X(\\theta)$ is the physically native gate on many devices.`,
    explanationMdJa: `## 定義

$$
\\sqrt{X} \\equiv SX = \\frac{1}{2}\\begin{pmatrix} 1+i & 1-i \\\\ 1-i & 1+i \\end{pmatrix}
$$

行列を直接二乗すると$SX \\cdot SX = X$が確認できます。これはパウリXゲートの真の行列平方根であり、大域位相を除けば$X$のちょうど4つの平方根の1つです（他には$-SX$やスケールされた$SX^\\dagger$など）。

## 基底状態への作用

$$
SX|0\\rangle = \\tfrac12\\big[(1+i)|0\\rangle + (1-i)|1\\rangle\\big], \\qquad SX|1\\rangle = \\tfrac12\\big[(1-i)|0\\rangle + (1+i)|1\\rangle\\big]
$$

どちらの結果も確率$1/2$で測定されます。ゲートの効果はもっぱら2つの振幅間の位相関係にあり、2回目の$SX$がそれを決定論的なビット反転へと解消します。

## 主要な恒等式

- $SX = e^{i\\pi/4} R_X(\\pi/2)$: 大域位相を除けば、$SX$はちょうど完全な$X$反転の半分の$R_X$回転です。
- $SX$はクリフォードゲートです。任意のパウリ演算子を$SX$で共役すると（符号を除いて）パウリ演算子に戻ります。例: $SX \\cdot Z \\cdot SX^\\dagger = -Y$。これが$SX$が$R_Z$および$\\mathrm{CX}$とともに、クリフォード中心のコンパイルにおける一般的なネイティブゲート集合を構成する理由です。
- $SX^\\dagger \\cdot SX = I$ かつ $SX \\cdot SX = X$ なので $SX^4 = X^2 = I$ となり、$SX$の位数は4です。
- 仮想的な$R_Z$フレーム変更と組み合わせることで、較正された2回の$SX$パルス（$R_X(\\pi/2)$–$R_Z$–$R_X(\\pi/2)$のシーケンス）で*任意の*単一量子ビットユニタリを合成できます。これが、多くのデバイスで一般的な$R_X(\\theta)$ではなく$SX$が物理的にネイティブなゲートである理由です。`,
    tags: ["clifford", "single qubit", "hardware native"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Order", value: "4 (SX⁴ = I)" },
    ],
    metadata: [
      { label: "Matrix", value: "(1/2)[[1+i, 1-i], [1-i, 1+i]]" },
      { label: "Square", value: "SX² = X" },
      { label: "Relation to RX", value: "SX = e^{iπ/4} RX(π/2)" },
      { label: "Gate family", value: "Clifford" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [
      { label: "SX", qubits: [0], tone: "accent" },
      { label: "SX", qubits: [0], tone: "accent" },
    ],
    outcomes: [
      { label: "P(|0⟩) after SX", probability: 0.5 },
      { label: "P(|1⟩) after SX", probability: 0.5 },
      { label: "P(|1⟩) after SX·SX (=X)", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nsx q;`,
    filename: "sx-sqrt-x.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "sx_sqrt_x.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(1)\nqc.sx(0)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "sx_sqrt_x.py",
        code: `import cirq\n\nq = cirq.LineQubit(0)\n# X ** 0.5 is Cirq's built-in square-root-of-X gate\ncircuit = cirq.Circuit((cirq.X ** 0.5).on(q))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["rx-rotation-gate", "pauli-x-operator", "rz-rotation-gate"],
    literature: [MCKAY_2017, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "controlled-z-gate",
    title: "Controlled-Z gate",
    titleJa: "制御Zゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Controlled gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["truth_table", "unitary_equivalence", "textbook_citation"],
    verification: "Truth-table and symmetry check · CZ is diag(1,1,1,-1)",
    method: "Apply CZ to all four computational-basis inputs and confirm the matrix is diagonal and symmetric under control/target exchange.",
    result: "Pass · CZ|11⟩ = -|11⟩ and all other basis states are unchanged; swapping control and target leaves the gate identical.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A diagonal two-qubit entangling gate that applies a -1 phase exactly when both qubits are |1⟩, and is symmetric between the two qubits it acts on.",
    descriptionJa: "両方の量子ビットが|1⟩のときにちょうど-1の位相を適用する対角な2量子ビットエンタングルゲートで、作用する2つの量子ビットに関して対称です。",
    introduction:
      "CZ is the phase-only sibling of CX: instead of routing information from control to target, it marks the |11⟩ configuration, which makes it the natural entangling gate for graph-state and measurement-based constructions.",
    introductionJa: "CZはCXの位相のみの兄弟分です。制御から対象へ情報を送る代わりに|11⟩の配置に印を付けるため、グラフ状態や測定型計算の構成において自然なエンタングルゲートです。",
    explanation:
      "CZ = diag(1,1,1,-1) in the |00⟩,|01⟩,|10⟩,|11⟩ basis. Because the matrix is symmetric, CZ(a,b) = CZ(b,a) — unlike CX, it makes no difference which qubit is labeled control.",
    explanationJa: "CZは|00⟩,|01⟩,|10⟩,|11⟩基底でdiag(1,1,1,-1)です。行列が対称なのでCZ(a,b) = CZ(b,a)であり、CXと異なりどちらの量子ビットを制御と呼ぶかは関係ありません。",
    explanationMd: `## Definition

$$
\\mathrm{CZ} = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&1&0\\\\0&0&0&-1 \\end{pmatrix}
$$

in the ordered basis $\\{|00\\rangle,|01\\rangle,|10\\rangle,|11\\rangle\\}$. The matrix is diagonal and, unlike $\\mathrm{CX}$, symmetric under exchanging the two qubits: $\\mathrm{CZ}$ has no distinguished "control" wire.

## Action on basis states

$$
\\mathrm{CZ}|c,t\\rangle = (-1)^{c\\cdot t}|c,t\\rangle
$$

Only the $|11\\rangle$ component picks up a sign; all other basis states are untouched. Applied to a product of superpositions it creates entanglement by correlating the relative phase with both qubits simultaneously, e.g. $\\mathrm{CZ}\\big(\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}\\otimes\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}\\big) = \\tfrac12(|00\\rangle+|01\\rangle+|10\\rangle-|11\\rangle)$.

## Key identities

- $\\mathrm{CZ} = (I\\otimes H)\\,\\mathrm{CX}\\,(I\\otimes H)$: conjugating the target of $\\mathrm{CX}$ by Hadamard converts the bit-flip entangler into the phase-flip entangler and vice versa.
- $\\mathrm{CZ}^2 = I\\otimes I$: $\\mathrm{CZ}$ is its own inverse (it is a Clifford involution).
- $\\mathrm{CZ}$ is the $\\lambda=\\pi$ special case of the controlled-phase gate $\\mathrm{CP}(\\lambda)$.
- Applying $\\mathrm{CZ}$ to every edge of a graph on qubits initialized in $|+\\rangle$ prepares the corresponding cluster/graph state, the resource state for measurement-based quantum computation.`,
    explanationMdJa: `## 定義

$$
\\mathrm{CZ} = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&1&0\\\\0&0&0&-1 \\end{pmatrix}
$$

順序付き基底$\\{|00\\rangle,|01\\rangle,|10\\rangle,|11\\rangle\\}$においてこの行列は対角であり、CXと異なり2つの量子ビットを入れ替えても対称です。CZには区別された「制御」側の配線がありません。

## 基底状態への作用

$$
\\mathrm{CZ}|c,t\\rangle = (-1)^{c\\cdot t}|c,t\\rangle
$$

|11⟩成分だけが符号を受け取り、他の基底状態はそのままです。重ね合わせの積に適用すると、両方の量子ビットに同時に相対位相を相関させることでエンタングルメントを作ります。例: $\\mathrm{CZ}\\big(\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}\\otimes\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}\\big) = \\tfrac12(|00\\rangle+|01\\rangle+|10\\rangle-|11\\rangle)$。

## 主要な恒等式

- $\\mathrm{CZ} = (I\\otimes H)\\,\\mathrm{CX}\\,(I\\otimes H)$: CXの対象をアダマールで共役すると、ビット反転型エンタングラーが位相反転型エンタングラーに変わります（逆も同様）。
- $\\mathrm{CZ}^2 = I\\otimes I$: CZは自分自身の逆演算です（クリフォードの対合）。
- CZは制御位相ゲート$\\mathrm{CP}(\\lambda)$の$\\lambda=\\pi$の特殊な場合です。
- |+⟩に初期化された量子ビット上のグラフの各辺にCZを適用すると、対応するクラスター状態／グラフ状態が準備されます。これは測定型量子計算のリソース状態です。`,
    tags: ["controlled gate", "entanglement", "two qubit", "clifford"],
    resources: [
      { label: "Qubits", value: "2" },
      { label: "Depth", value: "1 gate" },
      { label: "Outcomes", value: "phase-only, basis-preserving" },
    ],
    metadata: [
      { label: "Matrix", value: "diag(1, 1, 1, -1)" },
      { label: "Symmetry", value: "Symmetric under q0 ↔ q1" },
      { label: "Relation to CX", value: "CZ = (I⊗H)·CX·(I⊗H)" },
      { label: "Gate family", value: "Clifford" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "CZ", qubits: [0, 1], tone: "ok" }],
    outcomes: [
      { label: "|11⟩ phase-flipped", probability: 1 },
      { label: "|00⟩, |01⟩, |10⟩ unchanged", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[2] q;\ncz q[0], q[1];`,
    filename: "controlled-z.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "controlled_z.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(2)\nqc.cz(0, 1)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "controlled_z.py",
        code: `import cirq\n\nq0, q1 = cirq.LineQubit.range(2)\ncircuit = cirq.Circuit(cirq.CZ(q0, q1))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["controlled-x-gate", "controlled-phase-gate", "hadamard-gate", "swap-gate"],
    literature: [NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "controlled-phase-gate",
    title: "Controlled-phase gate (CP)",
    titleJa: "制御位相ゲート（CP）",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Controlled gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["truth_table", "unitary_equivalence", "textbook_citation"],
    verification: "Truth-table and special-case check · CP(λ) matches diag(1,1,1,e^{iλ}) and reduces to CZ at λ=π",
    method: "Apply CP(λ) to all four computational-basis inputs and evaluate the general matrix at λ=π against the CZ reference matrix.",
    result: "Pass · CP(λ)|11⟩ = e^{iλ}|11⟩ for all λ tested, and CP(π) = CZ exactly.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A parametrized entangling gate that applies e^{iλ} exactly when both qubits are |1⟩, generalizing CZ and forming the entangling primitive of the quantum Fourier transform.",
    descriptionJa: "両方の量子ビットが|1⟩のときにちょうどe^{iλ}を適用するパラメータ化されたエンタングルゲートで、CZを一般化し量子フーリエ変換のエンタングルする基本演算を構成します。",
    introduction:
      "CP(λ) is what a controlled-P gate looks like once the target's phase gate is promoted to a genuine two-qubit operation — the workhorse of QFT-based algorithms.",
    introductionJa: "CP(λ)は、対象の位相ゲートを真の2量子ビット演算に昇格させた制御Pゲートの姿であり、QFTに基づくアルゴリズムの主力です。",
    explanation:
      "CP(λ) = diag(1,1,1,e^{iλ}) is symmetric between its two qubits, just like CZ, of which it is the λ=π special case. In the QFT, successive CP gates with angles π/2, π/4, π/8, … encode binary fractions of phase between qubit pairs.",
    explanationJa: "CP(λ) = diag(1,1,1,e^{iλ}) はCZと同様に2つの量子ビットに関して対称で、CZはその λ=π の特殊な場合です。QFTでは、角度π/2, π/4, π/8, … を持つ連続したCPゲートが、量子ビット対の間で位相の二進小数を符号化します。",
    explanationMd: `## Definition

$$
\\mathrm{CP}(\\lambda) = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&1&0\\\\0&0&0&e^{i\\lambda} \\end{pmatrix}
$$

Like $\\mathrm{CZ}$, this matrix is symmetric under exchanging the two qubits, so "control" and "target" are interchangeable labels rather than a physical asymmetry.

## Action on basis states

$$
\\mathrm{CP}(\\lambda)|c,t\\rangle = e^{i\\lambda\\, c\\cdot t}|c,t\\rangle
$$

Only the $|11\\rangle$ amplitude picks up a phase of $e^{i\\lambda}$; every other computational-basis input is unaffected.

## Key identities

- $\\mathrm{CP}(\\pi) = \\mathrm{CZ}$: the controlled-$Z$ gate is the $\\lambda=\\pi$ special case of the controlled-phase family.
- $\\mathrm{CP}(\\lambda_1)\\,\\mathrm{CP}(\\lambda_2) = \\mathrm{CP}(\\lambda_1+\\lambda_2)$: controlled phases with the same qubit pair compose additively.
- General controlled-$U$ construction (Barenco et al. 1995): any single-qubit controlled-$U$ can be built from two CNOTs and three single-qubit gates $A,B,C$ satisfying $ABC = I$ and $AXBXC = U$ up to phase; $\\mathrm{CP}(\\lambda)$ is the special case where $U = P(\\lambda)$ is already diagonal, so no CNOTs are needed at all — it is native.
- The quantum Fourier transform on $n$ qubits applies $\\mathrm{CP}(\\pi/2^{k})$ between qubit pairs at increasing separation $k$, making $\\mathrm{CP}$ the single most-used two-qubit gate in QFT-based algorithms (phase estimation, Shor's algorithm, HHL).`,
    explanationMdJa: `## 定義

$$
\\mathrm{CP}(\\lambda) = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&1&0\\\\0&0&0&e^{i\\lambda} \\end{pmatrix}
$$

CZと同様、この行列は2つの量子ビットの入れ替えに対して対称であり、「制御」と「対象」は物理的な非対称性ではなく交換可能なラベルです。

## 基底状態への作用

$$
\\mathrm{CP}(\\lambda)|c,t\\rangle = e^{i\\lambda\\, c\\cdot t}|c,t\\rangle
$$

|11⟩振幅だけが$e^{i\\lambda}$の位相を受け取り、他の計算基底の入力はすべて影響を受けません。

## 主要な恒等式

- $\\mathrm{CP}(\\pi) = \\mathrm{CZ}$: 制御Zゲートは、制御位相族の$\\lambda=\\pi$の特殊な場合です。
- $\\mathrm{CP}(\\lambda_1)\\,\\mathrm{CP}(\\lambda_2) = \\mathrm{CP}(\\lambda_1+\\lambda_2)$: 同じ量子ビット対に対する制御位相は加法的に合成されます。
- 一般的な制御U構成（Barenco et al. 1995）: 単一量子ビットの制御Uは、$ABC = I$かつ$AXBXC = U$（位相を除く）を満たす2つのCNOTと3つの単一量子ビットゲート$A,B,C$から構成できます。$\\mathrm{CP}(\\lambda)$は$U = P(\\lambda)$がすでに対角である特殊な場合なので、CNOTはまったく不要です。つまりネイティブです。
- $n$量子ビットの量子フーリエ変換は、間隔$k$が大きくなる量子ビット対の間に$\\mathrm{CP}(\\pi/2^{k})$を適用します。これにより、CPはQFTに基づくアルゴリズム（位相推定、Shorのアルゴリズム、HHL）で最も多用される2量子ビットゲートとなっています。`,
    tags: ["controlled gate", "phase", "two qubit", "qft"],
    resources: [
      { label: "Qubits", value: "2" },
      { label: "Depth", value: "1 gate" },
      { label: "Parameter", value: "λ (radians)" },
    ],
    metadata: [
      { label: "Matrix", value: "diag(1, 1, 1, e^{iλ})" },
      { label: "Special case", value: "CP(π) = CZ" },
      { label: "Role", value: "Entangling primitive of the QFT" },
      { label: "Gate family", value: "Non-Clifford (generic λ)" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "CP(π/2)", qubits: [0, 1], tone: "accent" }],
    outcomes: [
      { label: "|11⟩ phase-shifted by π/2", probability: 1 },
      { label: "|00⟩, |01⟩, |10⟩ unchanged", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[2] q;\ncp(pi/2) q[0], q[1];`,
    filename: "controlled-phase.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "controlled_phase.py",
        code: `from qiskit import QuantumCircuit\nimport numpy as np\n\nqc = QuantumCircuit(2)\nqc.cp(np.pi / 2, 0, 1)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "controlled_phase.py",
        code: `import cirq\n\nq0, q1 = cirq.LineQubit.range(2)\n# CZPowGate(t) applies phase e^{i*pi*t} to |11>; t=0.5 gives e^{i*pi/2}\ncircuit = cirq.Circuit(cirq.CZPowGate(exponent=0.5).on(q0, q1))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["controlled-z-gate", "phase-gate-p", "qft-resource-screen", "quantum-phase-estimation"],
    literature: [BARENCO_1995, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "controlled-hadamard-gate",
    title: "Controlled-Hadamard gate",
    titleJa: "制御アダマールゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Controlled gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["truth_table", "unitary_equivalence", "textbook_citation"],
    verification: "Block-diagonal check · CH applies I to the control-0 subspace and H to the control-1 subspace",
    method: "Apply CH to all four computational-basis inputs and confirm the target block for control=0 is identity and the block for control=1 is the Hadamard matrix.",
    result: "Pass · CH|0,t⟩ = |0,t⟩ and CH|1,t⟩ = |1⟩⊗H|t⟩ for both target values.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A controlled version of the Hadamard gate that puts the target into superposition only when the control qubit is |1⟩, a canonical example of promoting a single-qubit gate to a controlled operation.",
    descriptionJa: "制御量子ビットが|1⟩のときにのみ対象を重ね合わせにする、アダマールゲートの制御版です。単一量子ビットゲートを制御演算に昇格させる代表的な例です。",
    introduction:
      "CH is a useful teaching record because H is not diagonal and not a Pauli, so building its controlled version requires the general controlled-U machinery rather than a one-line native gate.",
    introductionJa: "Hは対角でもパウリでもないため、その制御版を作るには単純なネイティブゲートではなく一般的な制御U構成が必要です。CHはこのことを示す有用な教材的記録です。",
    explanation:
      "CH acts as the identity on the control-0 subspace and as H on the control-1 subspace: block-diagonal with I₂ and H as the two 2x2 blocks. Because H is neither diagonal nor a Pauli operator, CH cannot be written as a single native two-qubit gate on most hardware and is compiled via the general controlled-U recipe.",
    explanationJa: "CHは制御が0の部分空間では恒等として、制御が1の部分空間ではHとして作用します。すなわちI₂とHを2つの2x2ブロックとするブロック対角行列です。Hは対角でもパウリ演算子でもないため、CHはほとんどのハードウェアで単一のネイティブな2量子ビットゲートとしては書けず、一般的な制御U構成を通じてコンパイルされます。",
    explanationMd: `## Definition

$$
\\mathrm{CH} = |0\\rangle\\langle 0|\\otimes I + |1\\rangle\\langle 1|\\otimes H = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&\\tfrac{1}{\\sqrt2}&\\tfrac{1}{\\sqrt2}\\\\0&0&\\tfrac{1}{\\sqrt2}&-\\tfrac{1}{\\sqrt2} \\end{pmatrix}
$$

with the control as the first (leftmost) qubit. Unlike $\\mathrm{CZ}$ or $\\mathrm{CP}$, this matrix is not diagonal, and unlike $\\mathrm{CX}$, the applied operation $H$ is not a Pauli matrix.

## Action on basis states

$$
\\mathrm{CH}|0,t\\rangle = |0,t\\rangle, \\qquad \\mathrm{CH}|1,0\\rangle = |1\\rangle\\otimes\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}, \\qquad \\mathrm{CH}|1,1\\rangle = |1\\rangle\\otimes\\tfrac{|0\\rangle-|1\\rangle}{\\sqrt2}
$$

When the control is $|0\\rangle$ the target is left completely untouched; when the control is $|1\\rangle$ the target is put into superposition exactly as a bare $H$ would.

## Decomposition

Because $H$ is neither diagonal nor Pauli, $\\mathrm{CH}$ is not directly native on most hardware and is built with the general controlled-$U$ recipe of Barenco et al. (1995): find single-qubit gates $A,B,C$ with

$$
ABC = I, \\qquad AXBXC = H \\text{ (up to global phase)}
$$

and implement controlled-$H$ as $C$–CNOT–$B$–CNOT–$A$ on the target, conditioned on the control via two CNOTs. A common concrete choice uses $A = R_Y(\\pi/4)$, $B = R_Y(-\\pi/4)$, and a compensating phase gate for $C$, giving a 2-CNOT circuit.

## Key identities

- $\\mathrm{CH}^2 = I$: applying the same controlled-Hadamard twice restores the input, since $H^2 = I$.
- $\\mathrm{CH}$ conditioned on $|+\\rangle$ on the control produces genuine entanglement between control and target, unlike $\\mathrm{CZ}$/$\\mathrm{CP}$ acting on product states, because $H$ mixes the target's basis rather than only phasing it.`,
    explanationMdJa: `## 定義

$$
\\mathrm{CH} = |0\\rangle\\langle 0|\\otimes I + |1\\rangle\\langle 1|\\otimes H = \\begin{pmatrix} 1&0&0&0\\\\0&1&0&0\\\\0&0&\\tfrac{1}{\\sqrt2}&\\tfrac{1}{\\sqrt2}\\\\0&0&\\tfrac{1}{\\sqrt2}&-\\tfrac{1}{\\sqrt2} \\end{pmatrix}
$$

制御を先頭（左側）の量子ビットとします。CZやCPと異なりこの行列は対角ではなく、CXと異なり適用される演算Hはパウリ行列ではありません。

## 基底状態への作用

$$
\\mathrm{CH}|0,t\\rangle = |0,t\\rangle, \\qquad \\mathrm{CH}|1,0\\rangle = |1\\rangle\\otimes\\tfrac{|0\\rangle+|1\\rangle}{\\sqrt2}, \\qquad \\mathrm{CH}|1,1\\rangle = |1\\rangle\\otimes\\tfrac{|0\\rangle-|1\\rangle}{\\sqrt2}
$$

制御が|0⟩のとき対象はまったく変化しません。制御が|1⟩のとき、対象は単独のHがするのとちょうど同じように重ね合わせにされます。

## 分解

Hは対角でもパウリでもないため、CHはほとんどのハードウェアで直接ネイティブではなく、Barenco et al.（1995）の一般的な制御U構成で構築されます。単一量子ビットゲート$A,B,C$を

$$
ABC = I, \\qquad AXBXC = H \\text{（大域位相を除く）}
$$

を満たすように見つけ、制御を2つのCNOTを介して条件付けしつつ対象に対して$C$–CNOT–$B$–CNOT–$A$として制御Hを実装します。具体的な一般的な選択として$A = R_Y(\\pi/4)$、$B = R_Y(-\\pi/4)$、および$C$の補正位相ゲートを使い、2-CNOT回路になります。

## 主要な恒等式

- $\\mathrm{CH}^2 = I$: $H^2 = I$なので、同じ制御アダマールを2回適用すると入力に戻ります。
- 制御に|+⟩を条件とした$\\mathrm{CH}$は、制御と対象の間に真のエンタングルメントを生成します。CZ/CPが積状態に作用する場合と異なり、Hは対象の位相を変えるだけでなく基底を混ぜるためです。`,
    tags: ["controlled gate", "two qubit", "superposition"],
    resources: [
      { label: "Qubits", value: "2" },
      { label: "Depth", value: "1 native / 2 CNOT decomposition" },
      { label: "Outcomes", value: "conditional superposition" },
    ],
    metadata: [
      { label: "Matrix", value: "block-diag(I₂, H)" },
      { label: "Decomposition", value: "2 CNOTs + single-qubit A,B,C (Barenco et al. 1995)" },
      { label: "Control 0 block", value: "Identity" },
      { label: "Control 1 block", value: "H" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "CH", qubits: [0, 1], tone: "accent" }],
    outcomes: [
      { label: "Control 0 → target unchanged", probability: 1 },
      { label: "Control 1 → P(target 0)", probability: 0.5 },
      { label: "Control 1 → P(target 1)", probability: 0.5 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[2] q;\nch q[0], q[1];`,
    filename: "controlled-hadamard.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "controlled_hadamard.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(2)\nqc.ch(0, 1)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "controlled_hadamard.py",
        code: `import cirq\n\nq0, q1 = cirq.LineQubit.range(2)\n# Any Cirq gate can be promoted to its controlled version with .controlled()\ncircuit = cirq.Circuit(cirq.H.controlled().on(q0, q1))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["controlled-x-gate", "controlled-z-gate", "hadamard-gate", "u3-universal-gate"],
    literature: [BARENCO_1995, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "toffoli-ccx-gate",
    title: "Toffoli (CCX) gate",
    titleJa: "トフォリ（CCX）ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Multi-controlled gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["truth_table", "unitary_equivalence", "research_paper", "textbook_citation"],
    verification: "Exhaustive truth table · CCX flips the target iff both controls are |1⟩",
    method: "Apply CCX to all eight computational-basis inputs and confirm the target flips only for the |11⟩ control pair.",
    result: "Pass · CCX|1,1,t⟩ = |1,1,1-t⟩ and CCX leaves all other seven basis states unchanged.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "The three-qubit doubly-controlled NOT gate that implements reversible classical AND/NAND logic and is universal for classical reversible computation.",
    descriptionJa: "可逆な古典AND/NAND論理を実装する3量子ビットの二重制御NOTゲートで、古典可逆計算にとって万能です。",
    introduction:
      "Toffoli is the standard bridge between quantum circuits and classical reversible logic: it is exactly a reversible AND gate, and its decomposition cost (CNOTs and T gates) is a recurring resource-counting benchmark for fault-tolerant compilation.",
    introductionJa: "トフォリは量子回路と古典可逆論理をつなぐ標準的な橋渡しです。まさに可逆なANDゲートであり、その分解コスト（CNOTとTゲート）はフォールトトレラント・コンパイルにおける資源計算の代表的なベンチマークです。",
    explanation:
      "CCX flips the target qubit exactly when both control qubits are |1⟩, implementing target ⊕= (c1 AND c2). It has no native two-qubit hardware equivalent and is compiled from 6 CNOT gates plus 7 single-qubit T/T†/H gates in the standard construction.",
    explanationJa: "CCXは両方の制御量子ビットが|1⟩のときにのみ対象量子ビットを反転させ、target ⊕= (c1 AND c2) を実装します。ネイティブな2量子ビットハードウェアの等価物はなく、標準的な構成では6つのCNOTゲートと7つの単一量子ビットT/T†/Hゲートから合成されます。",
    explanationMd: `## Definition

The Toffoli gate acts on the computational basis as

$$
\\mathrm{CCX}|c_1,c_2,t\\rangle = |c_1,c_2,\\, t \\oplus (c_1 \\wedge c_2)\\rangle
$$

flipping the target bit exactly when *both* controls are $1$. As an $8\\times 8$ permutation matrix it is the identity everywhere except the $|110\\rangle \\leftrightarrow |111\\rangle$ swap.

## Reversible classical logic

$\\mathrm{CCX}$ is the quantum realization of a reversible AND gate: with the target ancilla initialized to $|0\\rangle$, $\\mathrm{CCX}|c_1,c_2,0\\rangle = |c_1,c_2,\\,c_1\\wedge c_2\\rangle$ computes the logical AND while remaining unitary and reversible, unlike a classical AND gate which discards information. Nielsen and Chuang show this makes $\\{\\mathrm{CCX}\\}$ alone universal for reversible classical computation, and $\\{\\mathrm{CCX}, H\\}$ (or $\\{\\mathrm{CCX}\\}$ plus any basis-changing single-qubit gate) universal for quantum computation.

## Decomposition

$\\mathrm{CCX}$ has no native two-qubit hardware analogue and is not itself Clifford. The standard circuit (Barenco et al. 1995; also Nielsen & Chuang Fig. 4.9) decomposes it into

$$
6\\ \\text{CNOT gates} \\;+\\; 2\\ H \\;+\\; 4\\ T \\;+\\; 3\\ T^\\dagger
$$

for a total $T$-count of 7 — the standard resource figure quoted when estimating the fault-tolerant cost of a circuit that uses Toffolis, since $T$ gates (not Clifford gates) dominate magic-state distillation cost.

## Key identities

- $\\mathrm{CCX}$ is Hermitian and self-inverse: $\\mathrm{CCX}^2 = I$.
- $\\mathrm{CCX}$ is symmetric in its two control qubits but not in the target: swapping the two controls leaves the gate unchanged, swapping a control with the target does not.
- Multi-controlled-$X$ gates on more qubits ($C^nX$) are built recursively from Toffolis and ancilla qubits, making $\\mathrm{CCX}$ the base case for the whole family used in Grover diffusion operators and reversible arithmetic circuits.`,
    explanationMdJa: `## 定義

トフォリゲートは計算基底に対して次のように作用します。

$$
\\mathrm{CCX}|c_1,c_2,t\\rangle = |c_1,c_2,\\, t \\oplus (c_1 \\wedge c_2)\\rangle
$$

*両方の*制御が$1$のときにのみ対象ビットを反転させます。$8\\times 8$の置換行列としては、$|110\\rangle \\leftrightarrow |111\\rangle$の交換を除いてすべて恒等です。

## 可逆な古典論理

CCXは可逆ANDゲートの量子的実現です。対象の補助量子ビットを$|0\\rangle$に初期化すると、$\\mathrm{CCX}|c_1,c_2,0\\rangle = |c_1,c_2,\\,c_1\\wedge c_2\\rangle$は論理ANDを計算しつつ、情報を捨てる古典ANDゲートと異なりユニタリかつ可逆のままです。Nielsen and Chuangは、これにより$\\{\\mathrm{CCX}\\}$単独で古典可逆計算にとって万能であり、$\\{\\mathrm{CCX}, H\\}$（または$\\{\\mathrm{CCX}\\}$と任意の基底変換単一量子ビットゲート）が量子計算にとって万能であることを示しています。

## 分解

CCXにはネイティブな2量子ビットハードウェアの類似物がなく、それ自体クリフォードでもありません。標準的な回路（Barenco et al. 1995、およびNielsen & Chuang図4.9）はこれを

$$
6\\ \\text{個のCNOTゲート} \\;+\\; 2\\ \\text{個のH} \\;+\\; 4\\ \\text{個のT} \\;+\\; 3\\ \\text{個のT}^\\dagger
$$

へと分解し、合計T数は7です。これはToffoliを使う回路のフォールトトレラントコストを見積もる際に引用される標準的な資源指標です。マジック状態蒸留のコストを支配するのは（クリフォードゲートではなく）Tゲートだからです。

## 主要な恒等式

- CCXはエルミートかつ自己逆演算です: $\\mathrm{CCX}^2 = I$。
- CCXは2つの制御量子ビットに関して対称ですが、対象に関しては対称ではありません。2つの制御を入れ替えてもゲートは変わりませんが、制御と対象を入れ替えると変わります。
- より多くの量子ビットに対する多重制御Xゲート（$C^nX$）は、Toffoliと補助量子ビットから再帰的に構成されます。これによりCCXは、Groverの拡散演算子や可逆算術回路で使われるこの系列全体の基本ケースとなります。`,
    tags: ["toffoli", "reversible logic", "three qubit", "universal"],
    resources: [
      { label: "Qubits", value: "3" },
      { label: "Depth", value: "1 native / 6 CNOT decomposition" },
      { label: "T-count", value: "7 (4 T, 3 T†)" },
    ],
    metadata: [
      { label: "Truth table", value: "target ⊕= (c1 AND c2)" },
      { label: "Decomposition", value: "6 CNOT + 2 H + 4 T + 3 T†" },
      { label: "Self-inverse", value: "CCX² = I" },
      { label: "Gate family", value: "Non-Clifford, classically universal" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]", "q[2]"],
    operations: [{ label: "CCX", qubits: [0, 1, 2], tone: "warn" }],
    outcomes: [
      { label: "|110⟩ → |111⟩", probability: 1 },
      { label: "all other 7 inputs unchanged", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[3] q;\nx q[0];\nx q[1];\nccx q[0], q[1], q[2];`,
    filename: "toffoli-ccx.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "toffoli_ccx.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3)\nqc.x([0, 1])\nqc.ccx(0, 1, 2)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "toffoli_ccx.py",
        code: `import cirq\n\nq0, q1, q2 = cirq.LineQubit.range(3)\ncircuit = cirq.Circuit(\n    cirq.X(q0), cirq.X(q1),\n    cirq.TOFFOLI(q0, q1, q2),\n)\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["controlled-x-gate", "fredkin-cswap-gate", "controlled-hadamard-gate"],
    literature: [BARENCO_1995, NIELSEN_CHUANG],
  }),

  makeReferenceEntry({
    slug: "fredkin-cswap-gate",
    title: "Fredkin (CSWAP) gate",
    titleJa: "フレドキン（CSWAP）ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Multi-controlled gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["truth_table", "unitary_equivalence", "research_paper"],
    verification: "Exhaustive truth table · CSWAP exchanges the two targets iff the control is |1⟩",
    method: "Apply CSWAP to all eight computational-basis inputs and confirm the two target bits exchange exactly when the control is |1⟩, and are unchanged when it is |0⟩.",
    result: "Pass · CSWAP|1,a,b⟩ = |1,b,a⟩ and CSWAP|0,a,b⟩ = |0,a,b⟩ for all four (a,b) pairs.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A three-qubit controlled-swap gate that conditionally exchanges two target qubits, useful for reversible routing logic and as a component of the SWAP test for state overlap.",
    descriptionJa: "2つの対象量子ビットを条件付きで交換する3量子ビット制御SWAPゲートで、可逆なルーティング論理や状態の重なりを求めるSWAPテストの構成要素として使われます。",
    introduction:
      "Fredkin is the conditional-routing counterpart to Toffoli's conditional-logic: instead of computing a Boolean function it moves data, and unlike Toffoli it is also conservative (it preserves the total Hamming weight of the two target bits).",
    introductionJa: "フレドキンはトフォリの条件付き論理に対する条件付きルーティングの対応物です。ブール関数を計算する代わりにデータを移動させ、トフォリと異なり保存的でもあります（2つの対象ビットの合計ハミング重みを保存します）。",
    explanation:
      "CSWAP exchanges the states of the two target qubits exactly when the control is |1⟩, and does nothing when the control is |0⟩. Because a swap of two bits never changes how many of them are 1, CSWAP conserves the number of 1s among its two targets — a property with no Toffoli analogue.",
    explanationJa: "CSWAPは制御が|1⟩のときにのみ2つの対象量子ビットの状態を交換し、制御が|0⟩のときは何もしません。2ビットの交換はそのうち1である個数を決して変えないため、CSWAPは2つの対象の中の1の個数を保存します。これはトフォリには対応物のない性質です。",
    explanationMd: `## Definition

$$
\\mathrm{CSWAP}|c,a,b\\rangle = |c,\\, (1-c)a + cb,\\, (1-c)b + ca\\rangle = \\begin{cases} |c,a,b\\rangle & c=0 \\\\ |c,b,a\\rangle & c=1 \\end{cases}
$$

As an $8\\times 8$ permutation matrix, $\\mathrm{CSWAP}$ is the identity on the four $c=0$ basis states and the identity except for exchanging $|101\\rangle\\leftrightarrow|110\\rangle$ on the $c=1$ block (the $|100\\rangle$ and $|111\\rangle$ states, having $a=b$, are unaffected by the swap).

## Action and conservation law

Unlike Toffoli, which computes a genuinely new bit (the AND), $\\mathrm{CSWAP}$ only ever permutes its two target bits. This makes it *conservative*: the Hamming weight of the two target qubits is invariant under $\\mathrm{CSWAP}$, a structural property Fredkin and Toffoli's original 1982 paper on conservative reversible logic used to model computation with a fixed particle count.

## Decomposition

The naive decomposition is a CNOT–Toffoli–CNOT sandwich (target $b$ CNOT-copied onto $a$'s role, a Toffoli implementing the conditional exchange, then the CNOT undone) — 2 CNOTs plus 1 Toffoli, which itself costs 6 more CNOTs. Smolin and DiVincenzo (1996) improved on this with an explicit five-two-qubit-gate construction, showing the naive count is not optimal and giving numerical evidence that five is minimal.

## Key identities

- $\\mathrm{CSWAP}^2 = I$: applying the same controlled-swap twice restores the input.
- $\\mathrm{CSWAP}$ is the core primitive of the *SWAP test*: preparing a control qubit in $|+\\rangle$, applying $\\mathrm{CSWAP}$ between two unknown states, then measuring the control in the $X$ basis estimates $|\\langle\\psi|\\phi\\rangle|^2$ without ever measuring $|\\psi\\rangle$ or $|\\phi\\rangle$ directly.
- Like Toffoli, $\\mathrm{CSWAP}$ has no native two-qubit hardware realization and must be compiled from the elementary gate set for execution.`,
    explanationMdJa: `## 定義

$$
\\mathrm{CSWAP}|c,a,b\\rangle = |c,\\, (1-c)a + cb,\\, (1-c)b + ca\\rangle = \\begin{cases} |c,a,b\\rangle & c=0 \\\\ |c,b,a\\rangle & c=1 \\end{cases}
$$

$8\\times 8$の置換行列として、CSWAPは$c=0$の4つの基底状態では恒等であり、$c=1$のブロックでは$|101\\rangle\\leftrightarrow|110\\rangle$の交換を除いて恒等です（$|100\\rangle$と$|111\\rangle$は$a=b$なので交換の影響を受けません）。

## 作用と保存則

新しいビット（AND）を実際に計算するトフォリと異なり、CSWAPは2つの対象ビットを置換するだけです。これによりCSWAPは「保存的」です。2つの対象量子ビットのハミング重みはCSWAPの下で不変であり、この構造的性質はFredkinとToffoliが1982年の保存的可逆論理に関する原論文で、固定された粒子数で計算をモデル化するために使いました。

## 分解

素朴な分解は CNOT–Toffoli–CNOT のサンドイッチです（対象$b$を$a$の役割にCNOTでコピーし、条件付き交換を実装するToffoliを適用し、その後CNOTを元に戻す）。これは2つのCNOTと1つのToffoli（それ自体さらに6つのCNOTを要する）です。Smolin and DiVincenzo（1996）は明示的な5個の2量子ビットゲートによる構成でこれを改善し、素朴な数え方が最適ではないこと、そして5個が最小であるという数値的証拠を示しました。

## 主要な恒等式

- $\\mathrm{CSWAP}^2 = I$: 同じ制御SWAPを2回適用すると入力に戻ります。
- CSWAPは「SWAPテスト」の中核的な基本演算です。制御量子ビットを|+⟩に準備し、2つの未知の状態の間にCSWAPを適用してから制御をX基底で測定すると、$|\\psi\\rangle$や$|\\phi\\rangle$を直接測定することなく$|\\langle\\psi|\\phi\\rangle|^2$を推定できます。
- トフォリと同様、CSWAPにもネイティブな2量子ビットハードウェア実現はなく、実行のために基本ゲート集合からコンパイルする必要があります。`,
    tags: ["fredkin", "conditional swap", "three qubit", "conservative logic"],
    resources: [
      { label: "Qubits", value: "3" },
      { label: "Depth", value: "1 native / 5 two-qubit gates (Smolin–DiVincenzo)" },
      { label: "Conserved quantity", value: "Hamming weight of targets" },
    ],
    metadata: [
      { label: "Truth table", value: "swap(a,b) iff c=1" },
      { label: "Decomposition", value: "5 two-qubit gates (Smolin & DiVincenzo 1996)" },
      { label: "Self-inverse", value: "CSWAP² = I" },
      { label: "Gate family", value: "Non-Clifford, conservative" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]", "q[2]"],
    operations: [{ label: "CSWAP", qubits: [0, 1, 2], tone: "warn" }],
    outcomes: [
      { label: "control=1: |1,0,1⟩ → |1,1,0⟩", probability: 1 },
      { label: "control=0: targets unchanged", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[3] q;\nx q[0];\nx q[2];\ncswap q[0], q[1], q[2];`,
    filename: "fredkin-cswap.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "fredkin_cswap.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3)\nqc.x([0, 2])\nqc.cswap(0, 1, 2)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "fredkin_cswap.py",
        code: `import cirq\n\nq0, q1, q2 = cirq.LineQubit.range(3)\ncircuit = cirq.Circuit(\n    cirq.X(q0), cirq.X(q2),\n    cirq.CSWAP(q0, q1, q2),\n)\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["toffoli-ccx-gate", "swap-gate", "quantum-kernel-svm"],
    literature: [SMOLIN_DIVINCENZO_1996, BARENCO_1995],
  }),

  makeReferenceEntry({
    slug: "iswap-gate",
    title: "iSWAP gate",
    titleJa: "iSWAPゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Two-qubit gate",
    framework: "OpenQASM 3.0",
    verificationMethods: ["unitary_equivalence", "direct_math", "research_paper"],
    verification: "Unitary equivalence · iSWAP matches the XY-interaction evolution exp(iπ/4 (XX+YY))",
    method: "Compare the iSWAP matrix against exp(iπ(XX+YY)/4) and apply it to the four computational-basis states to check the exchange-with-phase pattern.",
    result: "Pass · iSWAP|01⟩ = i|10⟩, iSWAP|10⟩ = i|01⟩, and |00⟩, |11⟩ are fixed, matching the closed-form XY-interaction evolution exactly.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-16",
    description:
      "A two-qubit gate that swaps |01⟩ and |10⟩ while attaching a factor of i, arising naturally from XY-type physical couplings and native to several superconducting and photonic platforms.",
    descriptionJa: "|01⟩と|10⟩を交換しつつiの因子を付与する2量子ビットゲートで、XY型の物理的結合から自然に生じ、複数の超伝導・光量子プラットフォームでネイティブです。",
    introduction:
      "iSWAP matters because it is often what the hardware gives you for free: an always-on or easily-pulsed XY coupling between two qubits generates iSWAP (or a family member) directly, making it a common native two-qubit gate rather than something compiled from CNOT.",
    introductionJa: "iSWAPが重要なのは、しばしばハードウェアが「ただで」与えてくれるものだからです。2つの量子ビット間の常時オンまたは容易にパルス化できるXY結合は、iSWAP（またはその系列の一種）を直接生成し、CNOTから合成されるのではなく一般的なネイティブ2量子ビットゲートとなります。",
    explanation:
      "iSWAP exchanges |01⟩ and |10⟩ while multiplying each by i, and leaves |00⟩ and |11⟩ untouched. It is generated by time evolution under an XY-type (isotropic exchange) two-qubit Hamiltonian, which is why it appears as the native entangler on hardware built from that coupling.",
    explanationJa: "iSWAPは|01⟩と|10⟩を交換しつつそれぞれにiを掛け、|00⟩と|11⟩はそのままにします。XY型（等方交換）の2量子ビットハミルトニアンによる時間発展から生成されるため、その結合から構築されたハードウェアではネイティブなエンタングラーとして現れます。",
    explanationMd: `## Definition

$$
\\mathrm{iSWAP} = \\begin{pmatrix} 1&0&0&0\\\\0&0&i&0\\\\0&i&0&0\\\\0&0&0&1 \\end{pmatrix}
$$

in the $\\{|00\\rangle,|01\\rangle,|10\\rangle,|11\\rangle\\}$ basis — a SWAP gate with an extra factor of $i$ attached to the states it actually exchanges.

## Action on basis states

$$
\\mathrm{iSWAP}|00\\rangle = |00\\rangle,\\quad \\mathrm{iSWAP}|01\\rangle = i|10\\rangle,\\quad \\mathrm{iSWAP}|10\\rangle = i|01\\rangle,\\quad \\mathrm{iSWAP}|11\\rangle = |11\\rangle
$$

Unlike plain SWAP, iSWAP entangles superposition inputs: $\\mathrm{iSWAP}\\,\\tfrac{|01\\rangle+|10\\rangle}{\\sqrt2} = i\\,\\tfrac{|01\\rangle+|10\\rangle}{\\sqrt2}$ (an eigenstate, only a phase), but $\\mathrm{iSWAP}\\,\\tfrac{|01\\rangle+|11\\rangle}{\\sqrt2} = \\tfrac{i|10\\rangle+|11\\rangle}{\\sqrt2}$, which is entangled even though the input was a product state.

## Physical origin

$\\mathrm{iSWAP}$ is exactly the time evolution generated by the isotropic $XY$ exchange interaction:

$$
\\mathrm{iSWAP} = \\exp\\!\\Big(i\\frac{\\pi}{4}(X\\otimes X + Y\\otimes Y)\\Big)
$$

Schuch and Siewert (2003) analyze this family of gates and show that, unlike an Ising ($ZZ$) coupling which needs single-qubit gates to reach a CNOT-equivalent, the $XY$ interaction alone already yields an entangling gate — but reaching full CNOT-equivalence still needs single-qubit rotations layered around it, since $\\mathrm{iSWAP}$ and $\\mathrm{CNOT}$ are only locally equivalent, not identical.

## Key identities

- $\\mathrm{iSWAP}^2 = -\\,\\mathrm{SWAP}$: two iSWAPs give minus the ordinary swap (the two accumulated factors of $i$ multiply to $-1$).
- $\\mathrm{iSWAP} = \\mathrm{SWAP}\\cdot \\mathrm{CZ}$-like phase structure: iSWAP and CNOT are related by a "magic basis" change and are both maximally entangling, but not identical — a $\\sqrt{\\mathrm{iSWAP}}$ combined with single-qubit gates is itself sometimes used as a native entangling gate on hardware where a full iSWAP pulse is harder to calibrate than a half-angle one.`,
    explanationMdJa: `## 定義

$$
\\mathrm{iSWAP} = \\begin{pmatrix} 1&0&0&0\\\\0&0&i&0\\\\0&i&0&0\\\\0&0&0&1 \\end{pmatrix}
$$

$\\{|00\\rangle,|01\\rangle,|10\\rangle,|11\\rangle\\}$基底において、これは実際に交換する状態に追加のiの因子が付いたSWAPゲートです。

## 基底状態への作用

$$
\\mathrm{iSWAP}|00\\rangle = |00\\rangle,\\quad \\mathrm{iSWAP}|01\\rangle = i|10\\rangle,\\quad \\mathrm{iSWAP}|10\\rangle = i|01\\rangle,\\quad \\mathrm{iSWAP}|11\\rangle = |11\\rangle
$$

通常のSWAPと異なり、iSWAPは重ね合わせの入力をエンタングルさせます。$\\mathrm{iSWAP}\\,\\tfrac{|01\\rangle+|10\\rangle}{\\sqrt2} = i\\,\\tfrac{|01\\rangle+|10\\rangle}{\\sqrt2}$（固有状態で位相のみ）ですが、$\\mathrm{iSWAP}\\,\\tfrac{|01\\rangle+|11\\rangle}{\\sqrt2} = \\tfrac{i|10\\rangle+|11\\rangle}{\\sqrt2}$は、入力が積状態であったにもかかわらずエンタングルしています。

## 物理的起源

iSWAPは、等方的な$XY$交換相互作用が生成する時間発展そのものです。

$$
\\mathrm{iSWAP} = \\exp\\!\\Big(i\\frac{\\pi}{4}(X\\otimes X + Y\\otimes Y)\\Big)
$$

Schuch and Siewert（2003）はこのゲート系列を解析し、CNOT等価に達するために単一量子ビットゲートを必要とするIsing（$ZZ$）結合と異なり、$XY$相互作用単独ですでにエンタングルするゲートを与えることを示しています。しかし完全なCNOT等価に達するには、その周りに単一量子ビット回転を重ねる必要があります。iSWAPとCNOTは局所的に等価であるだけで、同一ではないためです。

## 主要な恒等式

- $\\mathrm{iSWAP}^2 = -\\,\\mathrm{SWAP}$: 2回のiSWAPは通常のswapのマイナスを与えます（蓄積された2つのiの因子を掛けると-1になります）。
- iSWAPとCNOTは「マジック基底」変換によって関係し、どちらも最大限にエンタングルするゲートですが同一ではありません。完全なiSWAPパルスより半角のものの方が較正しやすいハードウェアでは、$\\sqrt{\\mathrm{iSWAP}}$と単一量子ビットゲートの組み合わせ自体がネイティブなエンタングルゲートとして使われることがあります。`,
    tags: ["iswap", "two qubit", "hardware native", "xy interaction"],
    resources: [
      { label: "Qubits", value: "2" },
      { label: "Depth", value: "1 gate" },
      { label: "Generator", value: "exp(iπ/4 (XX+YY))" },
    ],
    metadata: [
      { label: "Matrix", value: "swap block with i off-diagonal entries" },
      { label: "Fixed points", value: "|00⟩, |11⟩" },
      { label: "Relation to SWAP", value: "iSWAP² = -SWAP" },
      { label: "Gate family", value: "Non-Clifford, maximally entangling" },
    ],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "iSWAP", qubits: [0, 1], tone: "accent" }],
    outcomes: [
      { label: "|01⟩ → i|10⟩", probability: 1 },
      { label: "|00⟩, |11⟩ unchanged", probability: 1 },
    ],
    code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[2] q;\nx q[0];\niswap q[0], q[1];`,
    filename: "iswap.qasm",
    language: "openqasm",
    extraVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "iswap.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(2)\nqc.x(0)\nqc.iswap(0, 1)\n\nFINAL_CIRCUIT = qc`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "iswap.py",
        code: `import cirq\n\nq0, q1 = cirq.LineQubit.range(2)\ncircuit = cirq.Circuit(cirq.X(q0), cirq.ISWAP(q0, q1))\n\nFINAL_CIRCUIT = circuit`,
      },
    ],
    relatedSlugs: ["swap-gate", "controlled-z-gate", "superdense-coding-circuit"],
    literature: [SCHUCH_SIEWERT_2003, NIELSEN_CHUANG],
  }),
];
