import type { PublicRepositoryEntry } from "./types";
import { makeReferenceEntry } from "./factory";

const qiskitBell = `from qiskit import QuantumCircuit

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])`;

const openqasmBell = `OPENQASM 3.0;
include "stdgates.inc";
bit[2] c;
qubit[2] q;
h q[0];
cx q[0], q[1];
c = measure q;`;

const pennyLaneGhz = `import pennylane as qml

dev = qml.device("default.qubit", wires=4)

@qml.qnode(dev)
def ghz_state():
    qml.Hadamard(wires=0)
    for wire in range(1, 4):
        qml.CNOT(wires=[0, wire])
    return qml.probs(wires=range(4))`;

const qiskitGhz = `from qiskit import QuantumCircuit

qc = QuantumCircuit(4)
qc.h(0)
for wire in range(1, 4):
    qc.cx(0, wire)`;

const cirqQft = `import cirq
import sympy

qubits = cirq.LineQubit.range(4)
theta = sympy.pi / 2
circuit = cirq.Circuit()
for index, qubit in enumerate(qubits):
    circuit.append(cirq.H(qubit))
    for offset, control in enumerate(qubits[index + 1:], start=2):
        circuit.append(cirq.CZPowGate(exponent=theta / (2 ** offset))(control, qubit))`;

export const RAW_PUBLIC_REPOSITORY_ENTRIES: PublicRepositoryEntry[] = [
  {
    slug: "hadamard-gate",
    title: "Hadamard gate",
    titleJa: "アダマールゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Single-qubit gate",
    framework: "OpenQASM 3.0",
    status: "verified",
    verification: "Unitary matrix check · canonical basis vectors preserved",
    verificationDetails: {
      method: "Exact matrix comparison against H = 1/√2 [[1, 1], [1, -1]].",
      result: "Pass · global phase and basis-state amplitudes match.",
    },
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-14",
    description: "The smallest useful reference for putting a qubit into an equal superposition.",
    descriptionJa: "量子ビットを等しい重ね合わせに置くための、最小の参照例です。",
    introduction:
      "Hadamard is a good first record because its behavior is easy to inspect mathematically and in a measured distribution.",
    introductionJa:
      "アダマールゲートは、数式と測定分布の両方で挙動を確認しやすい、最も基本的な例です。",
    explanation:
      "Applied to |0⟩, H produces (|0⟩ + |1⟩)/√2. Applied to |1⟩, it produces (|0⟩ − |1⟩)/√2. The relative sign matters when later gates interfere amplitudes.",
    explanationJa:
      "|0⟩にHを適用すると(|0⟩ + |1⟩)/√2、|1⟩では(|0⟩ − |1⟩)/√2になります。後続ゲートの干渉では相対位相が重要です。",
    tags: ["superposition", "single qubit", "foundations"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Outcomes", value: "2" },
    ],
    metadata: [
      { label: "Input", value: "|0⟩ or |1⟩" },
      { label: "Output", value: "Equal-amplitude superposition" },
      { label: "Measurement", value: "P(0) = P(1) = 0.5" },
    ],
    source: {
      kind: "curated_reference",
      title: "OpenQASM 3 standard gate set",
      url: "https://openqasm.com/language/gates.html",
      reviewedBy: "LeonaQ curation pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]"],
      operations: [{ label: "H", qubits: [0], tone: "accent" }],
      outcomes: [
        { label: "0", probability: 0.5 },
        { label: "1", probability: 0.5 },
      ],
    },
    codeVariants: [
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "hadamard.qasm",
        code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nh q;`,
      },
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "hadamard.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(1)\nqc.h(0)`,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "hadamard.py",
        code: `import cirq\n\nqubit = cirq.LineQubit(0)\ncircuit = cirq.Circuit(cirq.H(qubit))`,
      },
    ],
    relatedSlugs: ["bell-state-qiskit", "ghz-state-pennylane"],
  },
  {
    slug: "pauli-x-operator",
    title: "Pauli-X operator",
    titleJa: "パウリX演算子",
    category: "operators",
    categoryLabel: "Operators",
    categoryLabelJa: "演算子",
    algorithmFamily: "Pauli operator",
    framework: "OpenQASM 3.0",
    status: "verified",
    verification: "Truth-table check · |0⟩ and |1⟩ exchanged",
    verificationDetails: {
      method: "Exact basis-state simulation with computational-basis measurement.",
      result: "Pass · X|0⟩ = |1⟩ and X|1⟩ = |0⟩.",
    },
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-14",
    description: "A bit-flip operator that makes the relationship between a circuit and its truth table explicit.",
    descriptionJa: "回路と真理値表の関係を明確にするビット反転演算子です。",
    introduction:
      "Pauli-X is the quantum analogue of a classical NOT gate and a useful anchor for operator-level explanations.",
    introductionJa:
      "パウリXは古典的なNOTゲートに対応し、演算子レベルの説明の基準になります。",
    explanation:
      "X swaps the computational basis states. On a Bloch sphere it is a π rotation around the x axis; on a classical-looking input it behaves as a deterministic bit flip.",
    explanationJa:
      "Xは計算基底状態を入れ替えます。ブロッホ球ではx軸周りのπ回転で、古典的に見える入力では決定的なビット反転として動作します。",
    tags: ["pauli", "bit flip", "foundations"],
    resources: [
      { label: "Qubits", value: "1" },
      { label: "Depth", value: "1 gate" },
      { label: "Outcomes", value: "1 per input" },
    ],
    metadata: [
      { label: "Matrix", value: "[[0, 1], [1, 0]]" },
      { label: "Rotation", value: "π around X" },
      { label: "Input", value: "Computational basis" },
    ],
    source: {
      kind: "curated_reference",
      title: "OpenQASM 3 standard gate set",
      url: "https://openqasm.com/language/gates.html",
      reviewedBy: "LeonaQ curation pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]"],
      operations: [{ label: "X", qubits: [0], tone: "ok" }],
      outcomes: [{ label: "1 from |0⟩", probability: 1 }],
    },
    codeVariants: [
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "pauli-x.qasm",
        code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit q;\nx q;`,
      },
      {
        framework: "PennyLane",
        status: "native",
        language: "python",
        filename: "pauli-x.py",
        code: `import pennylane as qml\n\ndev = qml.device("default.qubit", wires=1)\n\n@qml.qnode(dev)\ndef flip():\n    qml.PauliX(wires=0)\n    return qml.probs(wires=0)`,
      },
    ],
    relatedSlugs: ["hadamard-gate", "bell-state-qiskit"],
  },
  {
    slug: "bell-state-qiskit",
    title: "Bell state measurement",
    titleJa: "ベル状態の測定",
    category: "states",
    categoryLabel: "States",
    categoryLabelJa: "状態",
    algorithmFamily: "Bell / entanglement",
    framework: "Qiskit",
    status: "verified",
    verification: "Exact state check · return contract passed",
    verificationDetails: {
      method: "Statevector and sampled distribution compared with the ideal Bell-state support.",
      result: "Pass · only 00 and 11 appear in the ideal measurement distribution.",
    },
    exportStatus: "OpenQASM 3 available · lossless gate mapping",
    provenance: "Verified starter",
    updatedAt: "2026-07-10",
    description: "A two-qubit entanglement example with a return contract and distribution check.",
    descriptionJa: "出力形式と分布を確認できる、2量子ビットのエンタングルメント例です。",
    introduction:
      "The Bell state is compact enough for a first experiment and rich enough to show that measurement outcomes can be correlated without choosing a classical bit in advance.",
    introductionJa:
      "ベル状態は最初の実験に十分コンパクトでありながら、測定前に古典ビットを選ばずに相関が現れることを示せます。",
    explanation:
      "H creates a superposition on q0, and CNOT copies the correlation into q1. Measuring the pair gives 00 or 11 with equal probability in the ideal circuit.",
    explanationJa:
      "Hでq0を重ね合わせ、CNOTでq1に相関を作ります。理想回路では測定結果は00または11に等確率で現れます。",
    tags: ["entanglement", "intro", "verification"],
    resources: [
      { label: "Qubits", value: "2" },
      { label: "Depth", value: "2 gates" },
      { label: "Outcomes", value: "00 / 11" },
    ],
    metadata: [
      { label: "State", value: "(|00⟩ + |11⟩)/√2" },
      { label: "Ideal P(00)", value: "0.5" },
      { label: "Ideal P(11)", value: "0.5" },
    ],
    source: {
      kind: "verified_run",
      title: "LeonaQ starter verification fixture",
      url: "https://qiskit.org/learn/",
      contributor: "LeonaQ public reference set",
      reviewedBy: "LeonaQ verification pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]", "q[1]"],
      operations: [
        { label: "H", qubits: [0], tone: "accent" },
        { label: "CX", qubits: [0, 1], tone: "ok" },
      ],
      outcomes: [
        { label: "00", probability: 0.5 },
        { label: "11", probability: 0.5 },
      ],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "bell_state.py",
        code: qiskitBell,
      },
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "bell_state.qasm",
        code: openqasmBell,
      },
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "bell_state.py",
        code: `import cirq\n\nq0, q1 = cirq.LineQubit.range(2)\ncircuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1))`,
      },
    ],
    relatedSlugs: ["hadamard-gate", "ghz-state-pennylane"],
  },
  {
    slug: "ghz-state-pennylane",
    title: "GHZ state preparation",
    titleJa: "GHZ状態の準備",
    category: "states",
    categoryLabel: "States",
    categoryLabelJa: "状態",
    algorithmFamily: "GHZ / entanglement",
    framework: "PennyLane",
    status: "verified_caveats",
    verification: "Structural checks passed · simulator-only caveat",
    verificationDetails: {
      method: "Circuit structure and ideal simulator probabilities checked for four wires.",
      result: "Pass · support is 0000 and 1111 in the ideal simulator.",
      caveat: "This public reference does not claim hardware noise validation.",
    },
    exportStatus: "Native PennyLane and Qiskit · OpenQASM conversion classified",
    provenance: "Framework example",
    updatedAt: "2026-07-09",
    description: "A reusable GHZ state preparation circuit with simulator-only evidence.",
    descriptionJa: "シミュレータで検証した範囲を明示した、再利用可能なGHZ状態準備回路です。",
    introduction:
      "GHZ preparation extends the Bell-state pattern to a small register and makes the distinction between local operations and global correlation visible.",
    introductionJa:
      "GHZ準備はベル状態のパターンを小さなレジスタに拡張し、局所操作と全体相関の違いを示します。",
    explanation:
      "One Hadamard creates the branch, then CNOTs fan that branch from q0 to the remaining wires. In the ideal model, all measured bits agree.",
    explanationJa:
      "1つのHで分岐を作り、CNOTをq0から他のワイヤへ広げます。理想モデルでは測定ビットがすべて一致します。",
    tags: ["state preparation", "pennylane", "simulator", "entanglement"],
    resources: [
      { label: "Qubits", value: "4" },
      { label: "Depth", value: "2 layers" },
      { label: "Outcomes", value: "0000 / 1111" },
    ],
    metadata: [
      { label: "State", value: "(|0000⟩ + |1111⟩)/√2" },
      { label: "Ideal support", value: "2 of 16 outcomes" },
      { label: "Evidence", value: "Simulator only" },
    ],
    source: {
      kind: "curated_reference",
      title: "PennyLane quantum operations reference",
      url: "https://docs.pennylane.ai/en/stable/introduction/circuits.html",
      reviewedBy: "LeonaQ curation pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]", "q[1]", "q[2]", "q[3]"],
      operations: [
        { label: "H", qubits: [0], tone: "accent" },
        { label: "CX", qubits: [0, 1], tone: "ok" },
        { label: "CX", qubits: [0, 2], tone: "ok" },
        { label: "CX", qubits: [0, 3], tone: "ok" },
      ],
      outcomes: [
        { label: "0000", probability: 0.5 },
        { label: "1111", probability: 0.5 },
      ],
    },
    codeVariants: [
      {
        framework: "PennyLane",
        status: "native",
        language: "python",
        filename: "ghz_state.py",
        code: pennyLaneGhz,
      },
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "ghz_state.py",
        code: qiskitGhz,
      },
    ],
    relatedSlugs: ["bell-state-qiskit", "hadamard-gate"],
  },
  {
    slug: "qaoa-maxcut-ring",
    title: "QAOA MaxCut on a 5-node ring",
    titleJa: "5ノードリングのQAOA MaxCut",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "QAOA",
    framework: "Qiskit",
    status: "verified",
    verification: "Statistical TVD 0.0088 ≤ δ 0.05 · seed 42 · 4096 shots",
    verificationDetails: {
      method: "Sampled distribution compared with the reference simulator using total variation distance.",
      result: "Pass · TVD 0.0088 is below the 0.05 acceptance threshold.",
    },
    exportStatus: "OpenQASM 3 available · parameter binding retained",
    provenance: "Verified run",
    updatedAt: "2026-07-12",
    description: "A p=1 QAOA circuit with a classical MaxCut comparison and reproducible simulation evidence.",
    descriptionJa: "古典MaxCutとの比較と、再現可能なシミュレーション結果を備えたp=1 QAOA回路です。",
    introduction:
      "This record moves from primitives to a small optimization workload: the objective, circuit, sampling boundary, and acceptance metric stay visible together.",
    introductionJa:
      "目的関数、回路、サンプリング条件、判定基準を一緒に確認できる小規模な最適化例です。",
    explanation:
      "The cost Hamiltonian encodes the edges of a five-node ring. At p=1, the circuit is intentionally small; the public claim is about the recorded distribution check, not a hardware optimum claim.",
    explanationJa:
      "コストハミルトニアンは5ノードリングの辺を符号化します。p=1で回路を小さく保ち、実機上の最適性は主張せず、記録した分布の確認結果のみを示します。",
    tags: ["optimization", "maxcut", "qaoa", "simulation"],
    resources: [
      { label: "Qubits", value: "5" },
      { label: "Depth", value: "14 gates" },
      { label: "Shots", value: "4096" },
    ],
    metadata: [
      { label: "Graph", value: "5-node ring" },
      { label: "QAOA depth", value: "p = 1" },
      { label: "Acceptance", value: "TVD ≤ 0.05" },
      { label: "Seed", value: "42" },
    ],
    source: {
      kind: "verified_run",
      title: "LeonaQ live evaluation record",
      url: "https://github.com/EshMis/majorana",
      contributor: "LeonaQ evaluation harness",
      reviewedBy: "LeonaQ verification pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]", "q[1]", "q[2]", "q[3]", "q[4]"],
      operations: [
        { label: "H×5", qubits: [0, 1, 2, 3, 4], tone: "accent" },
        { label: "Cost", qubits: [0, 1], tone: "warn" },
        { label: "Mixer", qubits: [0, 1, 2, 3, 4], tone: "ok" },
      ],
      outcomes: [
        { label: "Best cut family", probability: 0.72 },
        { label: "Other bitstrings", probability: 0.28 },
      ],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "qaoa_maxcut_ring.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(5, 5)\nqc.h(range(5))\n# p=1 cost and mixer layers\nfor edge in ((0, 1), (1, 2), (2, 3), (3, 4), (4, 0)):\n    qc.cx(*edge)\nqc.measure(range(5), range(5))`,
        note: "The public snippet keeps the graph structure readable; the verified run stores the full parameterized circuit.",
      },
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "qaoa_maxcut_ring.qasm",
        code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nbit[5] c;\nqubit[5] q;\nh q;\n// Cost and mixer layers are parameter-bound in the full record.`,
      },
    ],
    relatedSlugs: ["bell-state-qiskit", "qft-resource-screen"],
    literature: [
      {
        title: "A Quantum Approximate Optimization Algorithm",
        authors: "Edward Farhi, Jeffrey Goldstone, Sam Gutmann",
        year: "2014",
        url: "https://arxiv.org/abs/1411.4028",
        relevance: "Introduces QAOA for approximate combinatorial optimization and analyzes MaxCut at fixed depth.",
        relevanceJa: "固定深さのMaxCutを含む、組合せ最適化の近似アルゴリズムとしてQAOAを導入します。",
      },
      {
        title: "The QAOA for MaxCut: a fermionic view",
        authors: "Wang, Hadfield, Jiang, Rieffel",
        year: "2018",
        url: "https://doi.org/10.1103/PhysRevA.97.022304",
        relevance: "Analyzes parameter setting and the ring-of-disagrees instance used by this record.",
        relevanceJa: "この項目と同じリング型の問題とパラメータ設定を分析します。",
      },
    ],
    classicalComparison: {
      baseline: "Exact enumeration for the five-node fixture; Goemans–Williamson or MILP for larger MaxCut instances.",
      baselineJa: "5ノードの検証用グラフでは全列挙、大規模MaxCutではGoemans–WilliamsonやMILPを比較対象にします。",
      quantumClaim: "The circuit samples candidate cuts; it does not replace the classical optimizer or certify a global optimum by itself.",
      quantumClaimJa: "回路は候補カットをサンプリングしますが、古典最適化器を置き換えたり、大域最適を単独で保証したりはしません。",
      practicalRead: "Report approximation ratio, success probability, optimizer cost, shots, and wall-clock time against the same instance and budget.",
      practicalReadJa: "同じ問題と予算で、近似比、成功確率、最適化コスト、ショット数、実時間を比較してください。",
    },
    industryUseCases: ["Portfolio and scheduling heuristics", "Routing and graph partitioning", "Constraint-aware resource allocation"],
    industryUseCasesJa: ["ポートフォリオとスケジューリングのヒューリスティクス", "経路探索とグラフ分割", "制約付きリソース配分"],
  },
  {
    slug: "grover-unstructured-search",
    title: "Grover unstructured search",
    titleJa: "Grover非構造化探索",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Amplitude amplification",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Toy oracle structure checked · asymptotic claim is literature-backed",
    verificationDetails: {
      method: "Two-qubit marked-state oracle and diffusion layer checked against the ideal circuit.",
      result: "Pass for the toy fixture · no hardware speedup claim.",
      caveat: "The asymptotic advantage assumes a coherent oracle and a cost model where oracle calls dominate.",
    },
    exportStatus: "Native Qiskit · framework conversions available as review requests",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "The canonical search primitive, paired with the linear classical baseline it is meant to improve.",
    descriptionJa: "改善対象である線形な古典ベースラインと対にした、代表的な探索プリミティブです。",
    introduction: "Grover amplifies the amplitude of marked states using an oracle and a diffusion step. It is useful for testing whether a claimed speedup includes oracle construction and readout costs.",
    introductionJa: "Groverはオラクルと拡散ステップで対象状態の振幅を増幅します。オラクル構築と読み出しコストを含む主張か確認するための基礎例です。",
    explanation: "For an unstructured domain of size N with one marked item, the ideal query count scales as O(√N), versus O(N) classical queries. It is a query-complexity statement, not a blanket wall-clock guarantee.",
    explanationJa: "サイズNで対象が1つの非構造化領域では理想クエリ数がO(√N)で、古典のO(N)と対比されます。これはクエリ計算量であり、実時間の一律保証ではありません。",
    tags: ["search", "oracle", "amplitude amplification", "query complexity"],
    resources: [
      { label: "Qubits", value: "2 toy" },
      { label: "Depth", value: "Oracle + diffusion" },
      { label: "Claim", value: "O(√N) queries" },
    ],
    metadata: [
      { label: "Oracle", value: "One marked state" },
      { label: "Classical baseline", value: "Linear search" },
      { label: "Readout", value: "Measure candidate" },
    ],
    source: {
      kind: "curated_reference",
      title: "A fast quantum mechanical algorithm for database search",
      url: "https://arxiv.org/abs/quant-ph/9605043",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["q[0]", "q[1]"],
      operations: [
        { label: "H×2", qubits: [0, 1], tone: "accent" },
        { label: "Oracle", qubits: [0, 1], tone: "warn" },
        { label: "Diffusion", qubits: [0, 1], tone: "ok" },
      ],
      outcomes: [{ label: "Marked state", probability: 0.75 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "grover_search.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(2)\nqc.h([0, 1])\n# Oracle marks one basis state.\nqc.cz(0, 1)\nqc.h([0, 1])\nqc.x([0, 1])\nqc.cz(0, 1)\nqc.x([0, 1])\nqc.h([0, 1])`,
        note: "The oracle is intentionally small so the circuit can be inspected. Scaling claims belong to the cited query-complexity result.",
      },
    ],
    relatedSlugs: ["amplitude-estimation", "hadamard-gate"],
    literature: [
      {
        title: "A fast quantum mechanical algorithm for database search",
        authors: "Lov K. Grover",
        year: "1996",
        url: "https://arxiv.org/abs/quant-ph/9605043",
        relevance: "Original search algorithm and the O(√N) query comparison with classical search.",
        relevanceJa: "探索アルゴリズムと古典探索とのO(√N)クエリ比較を示す原論文です。",
      },
    ],
    classicalComparison: {
      baseline: "Linear scan or a classical indexed data structure, depending on whether the oracle is already available.",
      baselineJa: "オラクルが既にあるかに応じて、線形走査または古典インデックス構造を比較対象にします。",
      quantumClaim: "Quadratic improvement in oracle queries for an unstructured search problem.",
      quantumClaimJa: "非構造化探索でオラクルクエリ数を二次的に改善する主張です。",
      practicalRead: "Include oracle synthesis, state preparation, error correction, measurement repetitions, and data-loading costs before calling it an application speedup.",
      practicalReadJa: "応用の高速化と呼ぶ前に、オラクル合成、状態準備、誤り訂正、測定反復、データ投入のコストを含めます。",
    },
    industryUseCases: ["Search over a costly implicit predicate", "Amplitude amplification inside Monte Carlo workflows", "Constraint and satisfiability subroutines"],
    industryUseCasesJa: ["高コストな暗黙述語の探索", "モンテカルロ処理内の振幅増幅", "制約充足・SATサブルーチン"],
  },
  {
    slug: "shor-period-finding",
    title: "Shor period finding",
    titleJa: "Shor周期発見",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Hidden-period / factoring",
    framework: "Qiskit",
    status: "community_review",
    verification: "Circuit motif documented · fault-tolerant resource estimate pending",
    verificationDetails: {
      method: "The order-finding and inverse-QFT structure is represented as a literature-oriented reference record.",
      result: "Reviewable reference · not a claim of practical cryptanalysis.",
      caveat: "A useful implementation requires large, fault-tolerant resources and careful classical post-processing.",
    },
    exportStatus: "Conceptual Qiskit path · OpenQASM conversion requires resource-aware decomposition",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "The cryptography-facing quantum algorithm record, with the assumptions that make its security relevance precise.",
    descriptionJa: "暗号に関わる量子アルゴリズムと、その安全性の前提を説明します。",
    introduction: "Shor's algorithm reduces factoring and discrete logarithms to period finding. It is industry-relevant primarily as a migration and risk-planning reference today, not as a near-term production attack.",
    introductionJa: "Shorのアルゴリズムは因数分解と離散対数を周期発見に帰着します。現在の主な産業的意義は、直近の攻撃ではなく移行とリスク計画です。",
    explanation: "Quantum phase estimation extracts a period from modular arithmetic; the classical continued-fraction step turns that period into candidate factors. The record keeps those quantum and classical halves separate.",
    explanationJa: "量子位相推定で剰余算術の周期を抽出し、古典の連分数処理で因数候補に変換します。量子部分と古典部分を分けて扱います。",
    tags: ["cryptography", "factoring", "period finding", "fault tolerant"],
    resources: [
      { label: "Quantum core", value: "Order finding" },
      { label: "Classical post", value: "Continued fractions" },
      { label: "Readiness", value: "FTQC required" },
    ],
    metadata: [
      { label: "Threatened", value: "RSA / finite-field DLP" },
      { label: "Quantum output", value: "Period samples" },
      { label: "Deployment", value: "Migration planning" },
    ],
    source: {
      kind: "curated_reference",
      title: "Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer",
      url: "https://arxiv.org/abs/quant-ph/9508027",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference sketch",
    },
    visualization: {
      wires: ["work register", "phase register", "classical post-processing"],
      operations: [
        { label: "U_f", qubits: [0], tone: "warn" },
        { label: "QPE", qubits: [0, 1], tone: "accent" },
        { label: "QFT†", qubits: [1], tone: "ok" },
      ],
      outcomes: [{ label: "Period r", probability: 0.5 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "shor_period_finding.py",
        code: `from qiskit import QuantumCircuit\n\n# Reference skeleton: modular multiplication is problem-specific.\nqc = QuantumCircuit(6)\nqc.h(range(3))\n# controlled-U^(2^j) blocks feed inverse QFT.\nqc.barrier()`,
        note: "This is a conceptual skeleton, not a production factoring implementation or security benchmark.",
      },
    ],
    relatedSlugs: ["quantum-phase-estimation", "qft-resource-screen", "shor-code-error-correction"],
    literature: [
      {
        title: "Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer",
        authors: "Peter W. Shor",
        year: "1994/1995",
        url: "https://arxiv.org/abs/quant-ph/9508027",
        relevance: "Original factoring and discrete-logarithm algorithm based on quantum period finding.",
        relevanceJa: "量子周期発見に基づく因数分解・離散対数アルゴリズムの原論文です。",
      },
    ],
    classicalComparison: {
      baseline: "General number-field sieve for factoring and classical discrete-logarithm algorithms under the same security parameter.",
      baselineJa: "同じ安全性パラメータで、因数分解には一般数体篩、離散対数には古典アルゴリズムを比較します。",
      quantumClaim: "Polynomial-time asymptotic factoring and discrete logarithms in the fault-tolerant query/gate model.",
      quantumClaimJa: "フォールトトレラントなクエリ・ゲートモデルで、因数分解と離散対数を多項式時間で行う漸近的主張です。",
      practicalRead: "Compare logical qubits, T gates, error-correction overhead, runtime, and key sizes; never collapse a mathematical threat into a current hardware claim.",
      practicalReadJa: "論理量子ビット、Tゲート、誤り訂正オーバーヘッド、実時間、鍵サイズを比較し、数学的脅威を現行ハードウェアの主張に短絡させないでください。",
    },
    industryUseCases: ["Post-quantum cryptography migration planning", "PKI and long-lived secret inventory", "Quantum-safe protocol testing"],
    industryUseCasesJa: ["耐量子暗号への移行計画", "PKIと長期秘密情報の棚卸し", "量子安全プロトコルのテスト"],
  },
  {
    slug: "amplitude-estimation",
    title: "Quantum amplitude estimation",
    titleJa: "量子振幅推定",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Amplitude estimation",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Bernoulli toy estimator checked · oracle assumptions explicit",
    verificationDetails: {
      method: "Small-probability amplitude circuit compared with repeated classical sampling.",
      result: "Pass for the toy estimator · asymptotic advantage remains assumption-sensitive.",
      caveat: "State preparation, coherent oracle access, and error tolerance determine the actual resource picture.",
    },
    exportStatus: "Native Qiskit concept · iterative variants should be labeled separately",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A finance- and Monte-Carlo-facing primitive that makes the oracle and error model visible.",
    descriptionJa: "金融やモンテカルロ処理に関係する、オラクルと誤差モデルを明示するプリミティブです。",
    introduction: "Amplitude estimation estimates the success probability embedded in a quantum state. It is attractive for risk, option pricing, and integration models, but only after state preparation and oracle costs are included.",
    introductionJa: "振幅推定は量子状態に埋め込まれた成功確率を推定します。リスクやオプション価格、積分モデルで魅力がありますが、状態準備とオラクルのコストを含めて評価します。",
    explanation: "The original construction uses phase estimation around a Grover iterate and gives an O(1/ε) query scaling versus O(1/ε²) samples for classical Monte Carlo under its access model.",
    explanationJa: "原構成はGrover反復に対する位相推定を使い、アクセスモデルの下で古典モンテカルロのO(1/ε²)サンプルに対しO(1/ε)クエリを与えます。",
    tags: ["finance", "monte carlo", "risk", "probability estimation"],
    resources: [
      { label: "Output", value: "Probability estimate" },
      { label: "Target", value: "Error ε" },
      { label: "Access", value: "Coherent oracle" },
    ],
    metadata: [
      { label: "Classical", value: "Monte Carlo sampling" },
      { label: "Quantum", value: "Amplitude / phase" },
      { label: "Readout", value: "Estimate a scalar" },
    ],
    source: {
      kind: "curated_reference",
      title: "Quantum Amplitude Amplification and Estimation",
      url: "https://arxiv.org/abs/quant-ph/0005055",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["state preparation", "good/bad ancilla", "phase register"],
      operations: [
        { label: "A", qubits: [0], tone: "accent" },
        { label: "Q", qubits: [0, 1], tone: "warn" },
        { label: "QPE", qubits: [1, 2], tone: "ok" },
      ],
      outcomes: [{ label: "â", probability: 0.84 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "amplitude_estimation.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3)\n# A prepares a Bernoulli amplitude.\nqc.ry(0.7, 0)\n# Grover iterate and phase-estimation controls follow.\nqc.barrier()`,
        note: "The circuit is a readable access-model sketch; benchmark data must state the estimator variant and oracle cost.",
      },
    ],
    relatedSlugs: ["grover-unstructured-search", "quantum-phase-estimation", "vqe-ground-state-energy"],
    literature: [
      {
        title: "Quantum Amplitude Amplification and Estimation",
        authors: "Gilles Brassard, Peter Høyer, Michele Mosca, Alain Tapp",
        year: "2000",
        url: "https://arxiv.org/abs/quant-ph/0005055",
        relevance: "Introduces amplitude amplification and the amplitude-estimation scaling used in Monte Carlo applications.",
        relevanceJa: "モンテカルロ応用で使われる振幅増幅と振幅推定のスケーリングを導入します。",
      },
    ],
    classicalComparison: {
      baseline: "Classical Monte Carlo with independent samples and a confidence interval for the same scalar quantity.",
      baselineJa: "同じスカラー量に対する独立サンプルの古典モンテカルロと信頼区間を比較します。",
      quantumClaim: "Quadratic reduction in query/sample complexity under coherent state-preparation and oracle access.",
      quantumClaimJa: "コヒーレントな状態準備とオラクルアクセスの下で、クエリ・サンプル計算量を二次的に削減する主張です。",
      practicalRead: "State the confidence interval, estimator variant, data-loading circuit, and total repetitions; a lower query count alone is not a business speedup.",
      practicalReadJa: "信頼区間、推定器の種類、データ投入回路、総反復回数を示し、クエリ数だけを事業上の高速化と見なさないでください。",
    },
    industryUseCases: ["Value-at-risk and expected-loss estimation", "Option pricing and derivative payoffs", "Rare-event and reliability simulation"],
    industryUseCasesJa: ["バリュー・アット・リスクと期待損失の推定", "オプション価格とデリバティブペイオフ", "稀な事象と信頼性のシミュレーション"],
  },
  {
    slug: "vqe-ground-state-energy",
    title: "Variational quantum eigensolver for ground-state energy",
    titleJa: "基底状態エネルギーの変分量子固有値ソルバー",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Variational quantum algorithm",
    framework: "PennyLane",
    status: "verified_caveats",
    verification: "Hamiltonian expectation fixture checked · chemistry accuracy not claimed",
    verificationDetails: {
      method: "A small Pauli Hamiltonian expectation is compared with exact diagonalization while the classical optimizer is visible.",
      result: "Pass for the toy Hamiltonian · molecular benchmark remains a separate dataset and basis-set decision.",
      caveat: "Noise, ansatz expressivity, optimizer convergence, measurement grouping, and mapping choices dominate practical outcomes.",
    },
    exportStatus: "Native PennyLane · Qiskit conversion is straightforward for Pauli terms",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A hybrid chemistry workflow that compares a quantum expectation loop with classical eigensolvers.",
    descriptionJa: "量子期待値ループと古典固有値ソルバーを比較する、ハイブリッドな化学ワークフローです。",
    introduction: "VQE combines a parameterized state, repeated measurements of a Hamiltonian, and a classical optimizer. It remains an important NISQ-era chemistry pattern because it trades deep coherent evolution for repeated shallow experiments.",
    introductionJa: "VQEはパラメータ付き状態、ハミルトニアンの反復測定、古典最適化器を組み合わせます。深いコヒーレント発展を浅い実験の反復に置き換えるため、NISQ時代の化学パターンとして重要です。",
    explanation: "The variational principle guarantees an energy upper bound for a normalized trial state. Reaching a useful answer still requires a good encoding, ansatz, optimizer, and measurement budget.",
    explanationJa: "変分原理により、正規化された試行状態のエネルギーは上限になります。実用的な答えには符号化、ansatz、最適化器、測定予算が必要です。",
    tags: ["chemistry", "vqe", "ground state", "hybrid"],
    resources: [
      { label: "Qubits", value: "Problem mapped" },
      { label: "Loop", value: "Quantum + classical" },
      { label: "Output", value: "Energy estimate" },
    ],
    metadata: [
      { label: "Hamiltonian", value: "Pauli sum" },
      { label: "Optimizer", value: "Classical" },
      { label: "Reference", value: "Exact diagonalization" },
      { label: "Main risk", value: "Convergence + shots" },
    ],
    source: {
      kind: "curated_reference",
      title: "A variational eigenvalue solver on a quantum processor",
      url: "https://arxiv.org/abs/1304.3061",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["ansatz state", "Pauli measurements", "classical optimizer"],
      operations: [
        { label: "U(θ)", qubits: [0], tone: "accent" },
        { label: "⟨H⟩", qubits: [0, 1], tone: "ok" },
        { label: "θ ← opt", qubits: [1], tone: "warn" },
      ],
      outcomes: [{ label: "Energy", probability: 0.92 }],
    },
    codeVariants: [
      {
        framework: "PennyLane",
        status: "native",
        language: "python",
        filename: "vqe_energy.py",
        code: `import pennylane as qml\nfrom pennylane import numpy as np\n\ndev = qml.device("default.qubit", wires=2)\nH = qml.Hamiltonian([0.5, 0.5], [qml.PauliZ(0), qml.PauliZ(1)])\n\n@qml.qnode(dev)\ndef energy(theta):\n    qml.RY(theta[0], wires=0)\n    qml.CNOT(wires=[0, 1])\n    return qml.expval(H)`,
        note: "The fixture demonstrates the hybrid loop shape; it is not a molecular chemistry benchmark.",
      },
    ],
    relatedSlugs: ["quantum-phase-estimation", "ghz-state-pennylane", "amplitude-estimation"],
    literature: [
      {
        title: "A variational eigenvalue solver on a quantum processor",
        authors: "Alberto Peruzzo et al.",
        year: "2013/2014",
        url: "https://arxiv.org/abs/1304.3061",
        relevance: "Original VQE proposal and photonic demonstration for a small chemistry problem.",
        relevanceJa: "小さな化学問題でのVQE提案とフォトニック実証を示す原論文です。",
      },
      {
        title: "Optimization of the Variational Quantum Eigensolver for Quantum Chemistry Applications",
        authors: "de Keijzer, Colussi, Škorić, Kokkelmans",
        year: "2021",
        url: "https://arxiv.org/abs/2102.01781",
        relevance: "Surveys optimizer, ansatz, and measurement choices that affect chemistry-oriented VQE runs.",
        relevanceJa: "化学向けVQEで効く最適化器、ansatz、測定設計を比較します。",
      },
    ],
    classicalComparison: {
      baseline: "Exact diagonalization for small Hamiltonians; coupled-cluster, DMRG, tensor networks, or other electronic-structure methods at scale.",
      baselineJa: "小さなハミルトニアンでは厳密対角化、大きな系ではCC、DMRG、テンソルネットワーク等を比較します。",
      quantumClaim: "VQE can estimate a variational energy using shallow circuits plus a classical optimizer, not an automatic advantage over mature chemistry software.",
      quantumClaimJa: "VQEは浅い回路と古典最適化器で変分エネルギーを推定しますが、成熟した化学ソフトウェアに対する自動的な優位性ではありません。",
      practicalRead: "Compare energy error, total shots, circuit depth, optimizer calls, basis/mapping choices, and classical wall-clock time.",
      practicalReadJa: "エネルギー誤差、総ショット数、回路深さ、最適化呼び出し数、基底・写像、古典実時間を比較します。",
    },
    industryUseCases: ["Molecular ground states and reaction energies", "Materials and catalyst screening", "Hybrid quantum chemistry prototyping"],
    industryUseCasesJa: ["分子基底状態と反応エネルギー", "材料・触媒スクリーニング", "ハイブリッド量子化学プロトタイピング"],
  },
  {
    slug: "quantum-phase-estimation",
    title: "Quantum phase estimation",
    titleJa: "量子位相推定",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Eigenvalue estimation",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Known-eigenphase toy circuit checked · coherent controlled-U required",
    verificationDetails: {
      method: "A single-qubit phase rotation with an exact eigenstate is compared with the inverse-QFT readout.",
      result: "Pass for the toy phase · practical applications require controlled powers of U and precision budgeting.",
      caveat: "State preparation overlap, coherent evolution, approximation error, and fault tolerance are first-order constraints.",
    },
    exportStatus: "Native Qiskit pattern · OpenQASM export is decomposition-dependent",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "The eigenphase-estimation primitive behind chemistry, simulation, and period-finding workflows.",
    descriptionJa: "化学、シミュレーション、周期発見の基礎となる固有位相推定プリミティブです。",
    introduction: "QPE converts an eigenvalue phase into a classical bit string using controlled powers of a unitary and an inverse QFT. It is powerful, but its coherent-depth and state-overlap requirements are much stronger than a small demo suggests.",
    introductionJa: "QPEはユニタリの制御べき乗と逆QFTで固有位相を古典ビット列に変換します。小さなデモより、コヒーレント深さと状態重なりの要件がはるかに強い点に注意します。",
    explanation: "If U|ψ⟩ = e^{2πiφ}|ψ⟩, the phase register estimates φ. In Hamiltonian simulation, the phase is related to an energy after choosing a time scale and evolution operator.",
    explanationJa: "U|ψ⟩ = e^{2πiφ}|ψ⟩なら、位相レジスタがφを推定します。ハミルトニアンシミュレーションでは時間スケールと発展演算子を選び、位相をエネルギーに対応させます。",
    tags: ["phase", "eigenvalue", "chemistry", "simulation"],
    resources: [
      { label: "Registers", value: "Phase + eigenstate" },
      { label: "Precision", value: "Bits of phase" },
      { label: "Core", value: "Controlled-U" },
    ],
    metadata: [
      { label: "Input", value: "Approximate eigenstate" },
      { label: "Output", value: "Eigenphase bits" },
      { label: "Classical post", value: "Phase interpretation" },
    ],
    source: {
      kind: "curated_reference",
      title: "Quantum measurements and the Abelian Stabilizer Problem",
      url: "https://arxiv.org/abs/quant-ph/9511026",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["phase[0..m]", "eigenstate |ψ⟩"],
      operations: [
        { label: "H", qubits: [0], tone: "accent" },
        { label: "c-U²ʲ", qubits: [0, 1], tone: "warn" },
        { label: "QFT†", qubits: [0], tone: "ok" },
      ],
      outcomes: [{ label: "φ bits", probability: 0.9 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "phase_estimation.py",
        code: `from qiskit import QuantumCircuit\nfrom qiskit.circuit.library import QFT\n\nqc = QuantumCircuit(3)\nqc.h([0, 1])\n# Controlled powers of U occupy the problem-specific block.\nqc.cp(0.5, 0, 2)\nqc.cp(1.0, 1, 2)\nqc.append(QFT(2, inverse=True), [0, 1])`,
        note: "The controlled-U block is a phase-rotation toy, not a Hamiltonian simulation implementation.",
      },
    ],
    relatedSlugs: ["qft-resource-screen", "vqe-ground-state-energy", "shor-period-finding"],
    literature: [
      {
        title: "Quantum measurements and the Abelian Stabilizer Problem",
        authors: "Alexei Kitaev",
        year: "1995",
        url: "https://arxiv.org/abs/quant-ph/9511026",
        relevance: "Foundational quantum measurement setting associated with phase estimation and hidden subgroup structure.",
        relevanceJa: "位相推定と隠れ部分群構造に関係する量子測定の基礎文献です。",
      },
      {
        title: "Tight Bounds for Quantum Phase Estimation and Related Problems",
        authors: "Nikhil S. Mande, Ronald de Wolf",
        year: "2023",
        url: "https://arxiv.org/abs/2305.04908",
        relevance: "Provides modern precision and error-cost bounds for phase estimation.",
        relevanceJa: "位相推定の精度と誤差に関する現代的なコスト境界を示します。",
      },
    ],
    classicalComparison: {
      baseline: "Classical diagonalization, Lanczos/Krylov methods, or Fourier analysis when the operator has exploitable structure.",
      baselineJa: "構造を利用できる場合は、古典対角化、Lanczos/Krylov法、フーリエ解析を比較します。",
      quantumClaim: "Estimates eigenphases with precision tied to controlled-U evolution time in the coherent access model.",
      quantumClaimJa: "コヒーレントアクセスモデルで、制御Uの発展時間に結びついた精度で固有位相を推定します。",
      practicalRead: "Report eigenstate overlap, evolution cost, precision, repetitions, and the classical method used to interpret the result.",
      practicalReadJa: "固有状態重なり、発展コスト、精度、反復回数、結果の解釈に使う古典手法を報告します。",
    },
    industryUseCases: ["Molecular and materials spectra", "Hamiltonian simulation", "Period finding and cryptographic subroutines"],
    industryUseCasesJa: ["分子・材料スペクトル", "ハミルトニアンシミュレーション", "周期発見と暗号サブルーチン"],
  },
  {
    slug: "hhl-linear-systems",
    title: "HHL linear-systems reference",
    titleJa: "HHL線形方程式ソルバー参照",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Quantum linear algebra",
    framework: "Qiskit",
    status: "community_review",
    verification: "Algorithm boundary documented · end-to-end application benchmark pending",
    verificationDetails: {
      method: "A two-dimensional Hermitian system is represented as a phase-estimation plus controlled-rotation reference.",
      result: "Reviewable algorithm sketch · output readout and condition-number costs remain explicit.",
      caveat: "HHL outputs a quantum state proportional to the solution; extracting all vector components can remove the theoretical benefit.",
    },
    exportStatus: "Conceptual Qiskit path · problem-specific block encoding required",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A linear-algebra reference that forces the catalog to show input loading, conditioning, and output observability.",
    descriptionJa: "入力データの読み込み、条件数、出力として取得できる情報を明示した線形代数の参考例です。",
    introduction: "HHL is often cited for quantum linear systems, but it is best used as a requirements checklist: sparse access, a well-conditioned system, a state-preparation model, and an observable—not a free classical vector output.",
    introductionJa: "HHLは量子線形方程式の代表例ですが、疎性、条件数、状態準備、観測量を確認する要件チェックリストとして扱います。古典ベクトルを無料で出すものではありません。",
    explanation: "The algorithm estimates eigenvalue-dependent rotations via phase estimation and encodes solution amplitudes into a quantum state. The useful business question is which observable is needed, not whether every xᵢ can be printed.",
    explanationJa: "位相推定で固有値に依存する回転を行い、解の振幅を量子状態に符号化します。重要なのは全xᵢを出力できるかではなく、必要な観測量は何かです。",
    tags: ["linear systems", "PDE", "finance", "condition number"],
    resources: [
      { label: "Input", value: "Sparse A, |b⟩" },
      { label: "Output", value: "|x⟩ state" },
      { label: "Risk", value: "Readout cost" },
    ],
    metadata: [
      { label: "Assumption", value: "Sparse / well-conditioned" },
      { label: "Access", value: "Block encoding or oracle" },
      { label: "Observable", value: "Problem-specific" },
    ],
    source: {
      kind: "curated_reference",
      title: "Quantum algorithm for linear systems of equations",
      url: "https://arxiv.org/abs/0811.3171",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference sketch",
    },
    visualization: {
      wires: ["|b⟩", "phase register", "solution ancilla"],
      operations: [
        { label: "QPE(A)", qubits: [0, 1], tone: "accent" },
        { label: "λ⁻¹", qubits: [1, 2], tone: "warn" },
        { label: "Uncompute", qubits: [0, 1], tone: "ok" },
      ],
      outcomes: [{ label: "Observable of x", probability: 0.7 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "hhl_reference.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3)\n# Prepare |b⟩ and encode a small Hermitian A.\nqc.h(0)\n# QPE(A), controlled reciprocal rotation, and uncompute\nqc.barrier()`,
        note: "This is a requirements-oriented skeleton; it does not claim a full HHL implementation or application speedup.",
      },
    ],
    relatedSlugs: ["quantum-phase-estimation", "amplitude-estimation", "vqe-ground-state-energy"],
    literature: [
      {
        title: "Quantum algorithm for linear systems of equations",
        authors: "Aram W. Harrow, Avinatan Hassidim, Seth Lloyd",
        year: "2009",
        url: "https://arxiv.org/abs/0811.3171",
        relevance: "Original HHL linear-systems algorithm and its sparse-access/output-observable assumptions.",
        relevanceJa: "HHL線形方程式アルゴリズムと、疎性・出力観測量の前提を示す原論文です。",
      },
    ],
    classicalComparison: {
      baseline: "Conjugate gradient, sparse direct solvers, preconditioned iterative methods, or classical PDE solvers.",
      baselineJa: "共役勾配法、疎行列直接法、前処理付き反復法、古典PDEソルバーを比較します。",
      quantumClaim: "Potentially favorable scaling for estimating selected observables of a sparse, well-conditioned system under a quantum input/output model.",
      quantumClaimJa: "量子入力・出力モデルで、疎で条件の良い系の特定観測量を推定するスケーリング上の可能性があります。",
      practicalRead: "Account for condition number, sparsity, state preparation, block encoding, precision, and the cost of extracting the desired observable.",
      practicalReadJa: "条件数、疎性、状態準備、ブロックエンコーディング、精度、目的観測量の抽出コストを含めます。",
    },
    industryUseCases: ["PDE and computational fluid dynamics observables", "Risk and portfolio linear algebra", "Finite-element and inverse-problem prototypes"],
    industryUseCasesJa: ["PDEと数値流体の観測量", "リスクとポートフォリオの線形代数", "有限要素・逆問題のプロトタイプ"],
  },
  {
    slug: "quantum-kernel-svm",
    title: "Quantum kernel support-vector classifier",
    titleJa: "量子カーネルSVM分類器",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Quantum machine learning",
    framework: "PennyLane",
    status: "community_review",
    verification: "Kernel matrix toy check · application-level advantage not claimed",
    verificationDetails: {
      method: "A fidelity-style kernel is checked for symmetry and positive-semidefinite tolerance on a small dataset.",
      result: "Pass for the toy matrix · classifier quality depends on data encoding and kernel choice.",
      caveat: "Quantum feature maps do not automatically outperform a tuned classical kernel or remove data-loading costs.",
    },
    exportStatus: "Native PennyLane reference · Qiskit/Cirq conversions are circuit-level requests",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A quantum feature-map record paired with a classical SVM so model quality and data costs stay visible.",
    descriptionJa: "モデルの性能とデータ準備コストを比較するため、量子特徴写像と古典SVMを組み合わせた例です。",
    introduction: "Quantum kernels use a circuit to map inputs into a feature space and estimate similarities, then hand the kernel matrix to a classical learner. The meaningful benchmark is end-to-end predictive performance and cost.",
    introductionJa: "量子カーネルは回路で入力を特徴空間に写像し類似度を推定した後、カーネル行列を古典学習器に渡します。重要な比較は予測性能と総コストです。",
    explanation: "The circuit prepares |φ(x)⟩ and uses overlap or a related measurement to estimate K(x, y). The classical SVM still performs the optimization; the quantum part changes the feature map.",
    explanationJa: "回路で|φ(x)⟩を準備し、重なりなどを測定してK(x,y)を推定します。最適化は古典SVMが行い、量子部分は特徴写像を変えます。",
    tags: ["machine learning", "kernel", "classification", "feature map"],
    resources: [
      { label: "Quantum role", value: "Kernel estimate" },
      { label: "Classical role", value: "SVM optimizer" },
      { label: "Main metric", value: "Held-out score" },
    ],
    metadata: [
      { label: "Input", value: "Encoded feature vector" },
      { label: "Output", value: "Kernel matrix" },
      { label: "Baseline", value: "RBF / polynomial SVM" },
    ],
    source: {
      kind: "curated_reference",
      title: "Quantum classifier with tailored quantum kernel",
      url: "https://arxiv.org/abs/1909.02611",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["features x", "features y", "kernel measurement"],
      operations: [
        { label: "U(x)", qubits: [0], tone: "accent" },
        { label: "U†(y)", qubits: [0, 1], tone: "ok" },
        { label: "⟨0|", qubits: [1], tone: "warn" },
      ],
      outcomes: [{ label: "K(x,y)", probability: 0.63 }],
    },
    codeVariants: [
      {
        framework: "PennyLane",
        status: "native",
        language: "python",
        filename: "quantum_kernel.py",
        code: `import pennylane as qml\nfrom pennylane import numpy as np\n\ndev = qml.device("default.qubit", wires=2)\n\ndef feature_map(x):\n    qml.AngleEmbedding(x, wires=[0, 1])\n\n@qml.qnode(dev)\ndef kernel(x, y):\n    feature_map(x)\n    qml.adjoint(feature_map)(y)\n    return qml.probs(wires=[0, 1])[0]`,
        note: "This returns a toy overlap estimate; training and held-out evaluation are intentionally separate from the circuit record.",
      },
    ],
    relatedSlugs: ["vqe-ground-state-energy", "hadamard-gate", "bell-state-qiskit"],
    literature: [
      {
        title: "Quantum classifier with tailored quantum kernel",
        authors: "Carsten Blank, Daniel K. Park, June-Koo Kevin Rhee, Francesco Petruccione",
        year: "2019",
        url: "https://arxiv.org/abs/1909.02611",
        relevance: "Connects quantum-state fidelity kernels to a classifier and discusses a hardware demonstration.",
        relevanceJa: "量子状態忠実度カーネルと分類器を結びつけ、ハードウェア実証も議論します。",
      },
      {
        title: "Application of Quantum Machine Learning using the Quantum Kernel Algorithm on High Energy Physics Analysis at the LHC",
        authors: "Wu et al.",
        year: "2021",
        url: "https://arxiv.org/abs/2104.05059",
        relevance: "A domain application that reports quantum-kernel performance alongside classical counterparts.",
        relevanceJa: "量子カーネルの性能を古典手法と並べて報告するドメイン応用です。",
      },
    ],
    classicalComparison: {
      baseline: "Tuned RBF, polynomial, linear, random-feature, or deep-kernel SVMs with the same train/test split.",
      baselineJa: "同じ学習・テスト分割で、調整済みRBF、polynomial、linear、random-feature、deep-kernel SVMを比較します。",
      quantumClaim: "A quantum feature map may define a useful kernel for a dataset; it does not imply universal classification advantage.",
      quantumClaimJa: "量子特徴写像が有用なカーネルを定義する可能性はありますが、普遍的な分類優位を意味しません。",
      practicalRead: "Report data encoding, kernel-estimation shots, matrix conditioning, training time, test metrics, and classical hyperparameter budget.",
      practicalReadJa: "データ符号化、カーネル推定ショット、行列条件、学習時間、テスト指標、古典ハイパーパラメータ予算を報告します。",
    },
    industryUseCases: ["High-energy physics classification", "Small-data materials or sensor classification", "Feature-map and kernel research"],
    industryUseCasesJa: ["高エネルギー物理の分類", "小規模データの材料・センサー分類", "特徴写像・カーネル研究"],
  },
  {
    slug: "quantum-teleportation",
    title: "Quantum teleportation",
    titleJa: "量子テレポーテーション",
    category: "states",
    categoryLabel: "States",
    categoryLabelJa: "状態",
    algorithmFamily: "Entanglement and communication",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "State-transfer circuit checked · classical two-bit channel remains required",
    verificationDetails: {
      method: "Bell-pair preparation, Bell-basis measurement, and classically controlled corrections are checked on a toy state.",
      result: "Pass · the receiver recovers the input state in the ideal circuit.",
      caveat: "Teleportation transfers an unknown quantum state; it does not copy it or transmit information faster than light.",
    },
    exportStatus: "Native Qiskit · direct gate-level export",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A communication primitive that makes entanglement, measurement, and classical feed-forward explicit.",
    descriptionJa: "エンタングルメント、測定、古典フィードフォワードを明示する通信プリミティブです。",
    introduction: "Teleportation moves an unknown qubit state using a shared Bell pair and two classical bits. The protocol is a foundation for quantum networking and gate teleportation, not a replacement for classical communication.",
    introductionJa: "テレポーテーションは共有ベル対と2ビットの古典通信で未知の量子ビット状態を移します。量子ネットワークとゲートテレポーテーションの基礎ですが、古典通信の代替ではありません。",
    explanation: "The sender measures the input and one half of the Bell pair. The two classical outcomes select X/Z corrections at the receiver, and the original state is consumed rather than copied.",
    explanationJa: "送信者が入力とベル対の片方を測定し、2つの古典結果で受信側のX/Z補正を選びます。元の状態は消費され、コピーされません。",
    tags: ["communication", "entanglement", "networking", "feed-forward"],
    resources: [
      { label: "Qubits", value: "3" },
      { label: "Classical bits", value: "2" },
      { label: "Shared resource", value: "Bell pair" },
    ],
    metadata: [
      { label: "Input", value: "Unknown |ψ⟩" },
      { label: "Output", value: "Recovered |ψ⟩" },
      { label: "No-cloning", value: "Input consumed" },
    ],
    source: {
      kind: "curated_reference",
      title: "Teleporting an unknown quantum state via dual classical and EPR channels",
      url: "https://doi.org/10.1103/PhysRevLett.70.1895",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference implementation",
    },
    visualization: {
      wires: ["input |ψ⟩", "Alice Bell half", "Bob Bell half"],
      operations: [
        { label: "Bell", qubits: [1, 2], tone: "accent" },
        { label: "Bell meas.", qubits: [0, 1], tone: "warn" },
        { label: "X/Z feed-forward", qubits: [2], tone: "ok" },
      ],
      outcomes: [{ label: "Fidelity", probability: 1 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "teleportation.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3, 2)\n# Prepare an input state and a shared Bell pair.\nqc.h(1)\nqc.cx(1, 2)\nqc.cx(0, 1)\nqc.h(0)\nqc.measure([0, 1], [0, 1])\n# Apply classically controlled corrections to q2.`,
        note: "The final corrections are shown as a boundary because the exact dynamic-circuit syntax varies by backend.",
      },
    ],
    relatedSlugs: ["bell-state-qiskit", "hadamard-gate", "surface-code-memory"],
    literature: [
      {
        title: "Teleporting an unknown quantum state via dual classical and EPR channels",
        authors: "Charles H. Bennett et al.",
        year: "1993",
        url: "https://doi.org/10.1103/PhysRevLett.70.1895",
        relevance: "Original teleportation protocol using an entangled pair and two classical bits.",
        relevanceJa: "エンタングルした対と2ビットの古典通信によるテレポーテーションの原論文です。",
      },
    ],
    classicalComparison: {
      baseline: "Direct classical transmission of a known description, or physical transport of a classical bit; an unknown quantum state cannot be copied into a classical message of fixed size.",
      baselineJa: "既知の記述の古典送信や古典ビットの物理搬送が比較対象です。未知の量子状態を固定長の古典メッセージにコピーはできません。",
      quantumClaim: "Transfers an unknown qubit state using one shared entangled pair and two classical bits, with the input state consumed.",
      quantumClaimJa: "共有エンタングルメント1対と2ビットの古典通信で未知の量子ビット状態を移しますが、入力は消費されます。",
      practicalRead: "Network latency, entanglement generation, memory lifetime, fidelity, and feed-forward control are the real system metrics.",
      practicalReadJa: "実システムの指標はネットワーク遅延、エンタングルメント生成、メモリ寿命、忠実度、フィードフォワード制御です。",
    },
    industryUseCases: ["Quantum repeater and network protocols", "Remote gates and distributed quantum computing", "Error-correction and lattice-surgery primitives"],
    industryUseCasesJa: ["量子リピータとネットワークプロトコル", "遠隔ゲートと分散量子計算", "誤り訂正・格子手術プリミティブ"],
  },
  {
    slug: "shor-code-error-correction",
    title: "Shor nine-qubit error-correction code",
    titleJa: "Shor 9量子ビット誤り訂正符号",
    category: "operators",
    categoryLabel: "Operators",
    categoryLabelJa: "演算子",
    algorithmFamily: "Quantum error correction",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Stabilizer structure documented · net logical improvement requires a noise model",
    verificationDetails: {
      method: "Bit-flip and phase-flip syndrome structure is represented as a code-level reference.",
      result: "Pass as a structural reference · no blanket hardware threshold claim.",
      caveat: "Encoding, syndrome extraction, recovery, and ancilla errors can outweigh the protection on small noisy devices.",
    },
    exportStatus: "Native Qiskit-style construction · decoder and noise model are separate records",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A foundational code record that compares quantum protection with the narrower classical repetition-code idea.",
    descriptionJa: "量子保護と、より限定的な古典反復符号を比較する基礎的な誤り訂正レコードです。",
    introduction: "Shor's code encodes one logical qubit into nine physical qubits and combines protection against bit-flip and phase-flip errors. It is a teaching and architecture reference, not a claim that adding qubits automatically improves a current device.",
    introductionJa: "Shor符号は1論理量子ビットを9物理量子ビットに符号化し、ビット反転と位相反転への保護を組み合わせます。教育・アーキテクチャ参照であり、量子ビットを増やせば現行デバイスが自動的に改善するという主張ではありません。",
    explanation: "The code nests repetition-style encodings in complementary bases. Syndrome measurements identify an error class without directly measuring the logical state, and a decoder chooses the recovery.",
    explanationJa: "相補的な基底で反復型符号を入れ子にします。シンドローム測定は論理状態を直接測らずにエラー種別を特定し、デコーダが回復操作を選びます。",
    tags: ["error correction", "stabilizer", "fault tolerant", "syndrome"],
    resources: [
      { label: "Logical", value: "1 qubit" },
      { label: "Physical", value: "9 qubits" },
      { label: "Corrects", value: "1-qubit Pauli error" },
    ],
    metadata: [
      { label: "Code family", value: "Concatenated repetition" },
      { label: "Syndrome", value: "Ancilla measurements" },
      { label: "Decoder", value: "Noise-model dependent" },
    ],
    source: {
      kind: "curated_reference",
      title: "Scheme for reducing decoherence in quantum computer memory",
      url: "https://doi.org/10.1103/PhysRevA.52.R2493",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference sketch",
    },
    visualization: {
      wires: ["logical q", "bit-flip block", "phase-flip block"],
      operations: [
        { label: "Encode", qubits: [0], tone: "accent" },
        { label: "Syndrome", qubits: [0, 1], tone: "warn" },
        { label: "Recover", qubits: [0, 1], tone: "ok" },
      ],
      outcomes: [{ label: "Logical fidelity", probability: 0.9 }],
    },
    codeVariants: [
      {
        framework: "Qiskit",
        status: "native",
        language: "python",
        filename: "shor_code_reference.py",
        code: `from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(9)\n# Encode a logical qubit with bit- and phase-flip repetition blocks.\nqc.cx(0, 1)\nqc.cx(0, 2)\nqc.h([0, 1, 2])\n# Syndrome extraction and recovery depend on the chosen decoder.`,
        note: "The construction is intentionally a code-level reference; a useful benchmark must add a calibrated noise channel and decoder.",
      },
    ],
    relatedSlugs: ["surface-code-memory", "bell-state-qiskit", "shor-period-finding"],
    literature: [
      {
        title: "Scheme for reducing decoherence in quantum computer memory",
        authors: "Peter W. Shor",
        year: "1995",
        url: "https://doi.org/10.1103/PhysRevA.52.R2493",
        relevance: "Introduces an early quantum error-correction scheme for reducing decoherence in memory.",
        relevanceJa: "メモリのデコヒーレンスを低減する初期の量子誤り訂正方式を導入します。",
      },
      {
        title: "Good Quantum Error-Correcting Codes Exist",
        authors: "Calderbank and Shor",
        year: "1996",
        url: "https://arxiv.org/abs/quant-ph/9512032",
        relevance: "Places quantum codes in a broader rate and distance framework.",
        relevanceJa: "量子符号をレートと距離のより広い枠組みに位置づけます。",
      },
    ],
    classicalComparison: {
      baseline: "A three-bit classical repetition code can correct a bit flip under an independent noise model, but it does not protect an unknown qubit phase.",
      baselineJa: "3ビット古典反復符号は独立ノイズ下のビット反転を訂正できますが、未知の量子位相は保護しません。",
      quantumClaim: "Uses redundant quantum degrees of freedom and syndrome information to protect against a single-qubit Pauli error in the idealized code model.",
      quantumClaimJa: "冗長な量子自由度とシンドローム情報により、理想化した符号モデルで単一量子ビットのパウリ誤りを保護します。",
      practicalRead: "Compare logical error rate with and without encoding under the same calibrated noise, including all syndrome and recovery operations.",
      practicalReadJa: "同じ校正済みノイズで、シンドロームと回復操作をすべて含め、符号化あり・なしの論理誤り率を比較します。",
    },
    industryUseCases: ["Fault-tolerant architecture education", "Decoder and noise-model evaluation", "Logical-memory experiments"],
    industryUseCasesJa: ["フォールトトレラント構成の教育", "デコーダとノイズモデルの評価", "論理メモリ実験"],
  },
  {
    slug: "surface-code-memory",
    title: "Surface-code memory and biased-noise decoding",
    titleJa: "表面符号メモリと偏りノイズデコーディング",
    category: "operators",
    categoryLabel: "Operators",
    categoryLabelJa: "演算子",
    algorithmFamily: "Quantum error correction",
    framework: "OpenQASM 3.0",
    status: "community_review",
    verification: "Stabilizer-check workflow documented · threshold is noise-model dependent",
    verificationDetails: {
      method: "Syndrome rounds and logical-observable framing are documented for a small surface-code-style memory.",
      result: "Reviewable architecture reference · no hardware threshold claim.",
      caveat: "Decoder, leakage, measurement errors, connectivity, and bias determine the useful operating point.",
    },
    exportStatus: "OpenQASM-oriented stabilizer checks · hardware layout not universal",
    provenance: "Literature reference",
    updatedAt: "2026-07-14",
    description: "A fault-tolerance record for comparing physical error, syndrome extraction, decoder choice, and logical failure.",
    descriptionJa: "物理誤り、シンドローム抽出、デコーダ、論理故障を比較するためのフォールトトレランス項目です。",
    introduction: "Surface-code families are central to scalable fault tolerance because they use local stabilizer checks and planar connectivity. The XZZX variant illustrates why matching a code to biased noise can matter as much as the code name.",
    introductionJa: "表面符号系は局所シンドローム検査と平面接続を使うため、スケーラブルなフォールトトレランスの中心です。XZZXはノイズの偏りに符号を合わせる重要性を示します。",
    explanation: "Repeated stabilizer measurements produce a space-time syndrome. A decoder infers likely error chains, and the logical observable fails when the inferred correction differs by a nontrivial logical operator.",
    explanationJa: "反復シンドローム測定が時空間シンドロームを作り、デコーダがエラー鎖を推定します。推定回復が非自明な論理演算子と異なると論理観測量が失敗します。",
    tags: ["surface code", "fault tolerance", "biased noise", "decoder"],
    resources: [
      { label: "Signal", value: "Syndrome rounds" },
      { label: "Decoder", value: "Noise-aware" },
      { label: "Metric", value: "Logical error rate" },
    ],
    metadata: [
      { label: "Physical layer", value: "Local stabilizers" },
      { label: "Noise", value: "Pauli / biased" },
      { label: "Output", value: "Logical failure" },
    ],
    source: {
      kind: "curated_reference",
      title: "The XZZX surface code",
      url: "https://arxiv.org/abs/2009.07851",
      reviewedBy: "LeonaQ literature curation pass",
      license: "Public bibliographic link; code is an original reference sketch",
    },
    visualization: {
      wires: ["data patch", "XZZX checks", "decoder"],
      operations: [
        { label: "Prepare", qubits: [0], tone: "accent" },
        { label: "Syndrome×d", qubits: [0, 1], tone: "warn" },
        { label: "Decode", qubits: [1, 2], tone: "ok" },
      ],
      outcomes: [{ label: "Logical pass", probability: 0.97 }],
    },
    codeVariants: [
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "surface_code_round.qasm",
        code: `OPENQASM 3.0;\ninclude "stdgates.inc";\n// A stabilizer round is layout- and decoder-specific.\nqubit[5] data;\nqubit[4] ancilla;\n// Prepare, entangle, measure ancilla, then decode.`,
        note: "The reference keeps syndrome and decoder boundaries visible rather than pretending a universal hardware layout.",
      },
    ],
    relatedSlugs: ["shor-code-error-correction", "quantum-teleportation", "bell-state-qiskit"],
    literature: [
      {
        title: "The XZZX surface code",
        authors: "Bonilla Ataides et al.",
        year: "2021",
        url: "https://arxiv.org/abs/2009.07851",
        relevance: "Shows how a surface-code variant can exploit structure in biased Pauli noise and decoder design.",
        relevanceJa: "偏ったパウリノイズとデコーダ設計の構造を活用する表面符号の変種を示します。",
      },
      {
        title: "Scheme for reducing decoherence in quantum computer memory",
        authors: "Peter W. Shor",
        year: "1995",
        url: "https://doi.org/10.1103/PhysRevA.52.R2493",
        relevance: "Provides a foundational contrast between early block-code protection and scalable local-check architectures.",
        relevanceJa: "初期のブロック符号とスケーラブルな局所検査構成を比較する基礎文献です。",
      },
    ],
    classicalComparison: {
      baseline: "Classical parity-check codes and decoders provide an intuition for syndrome processing, but they do not preserve an unknown quantum phase.",
      baselineJa: "古典パリティ検査符号とデコーダはシンドローム処理の直感を与えますが、未知の量子位相は保存しません。",
      quantumClaim: "A local quantum code can suppress logical errors below physical errors when the full architecture operates below its threshold.",
      quantumClaimJa: "全アーキテクチャが閾値以下で動作すれば、局所量子符号で論理誤りを物理誤りより抑えられる可能性があります。",
      practicalRead: "Benchmark physical-versus-logical error rates, qubit and gate overhead, measurement rounds, decoder latency, and noise bias.",
      practicalReadJa: "物理・論理誤り率、量子ビットとゲートのオーバーヘッド、測定ラウンド、デコーダ遅延、ノイズ偏りを比較します。",
    },
    industryUseCases: ["Fault-tolerant quantum processor design", "Decoder co-design and calibration", "Logical qubit memory experiments"],
    industryUseCasesJa: ["フォールトトレラント量子プロセッサ設計", "デコーダとキャリブレーションの協調設計", "論理量子ビットメモリ実験"],
  },
  {
    slug: "qft-resource-screen",
    title: "QFT resource screen",
    titleJa: "QFTリソース評価",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Quantum Fourier transform",
    framework: "Cirq",
    status: "verified",
    verification: "QASM parse · compilation compatibility passed",
    verificationDetails: {
      method: "Circuit parser and gate-count comparison across the reference export path.",
      result: "Pass · phase rotation structure and qubit count are preserved.",
    },
    exportStatus: "Lossless export classified · native Cirq and OpenQASM views",
    provenance: "Curated reference",
    updatedAt: "2026-07-07",
    description: "A resource-focused QFT construction with a readable compile comparison.",
    descriptionJa: "読みやすいコンパイル比較を備えた、リソース重視のQFT構成です。",
    introduction:
      "The QFT record emphasizes the metadata researchers need before reuse: wire count, phase-rotation structure, and what the export check actually covers.",
    introductionJa:
      "QFTでは、再利用前に量子ビット数、位相回転の構造、書き出し時に確認した範囲を重視します。",
    explanation:
      "Hadamards create the Fourier basis and controlled phase rotations encode relative phase relationships. The final swap layer is optional depending on bit-order convention, so the catalog keeps that choice explicit.",
    explanationJa:
      "Hでフーリエ基底を作り、制御位相回転で相対位相を表現します。最後のswapはビット順の規約で任意になるため、カタログでは選択を明示します。",
    tags: ["resource estimate", "cirq", "qft", "phase"],
    resources: [
      { label: "Qubits", value: "4" },
      { label: "Depth", value: "18 gates" },
      { label: "Rotation layers", value: "4" },
    ],
    metadata: [
      { label: "Gate family", value: "H + controlled phase" },
      { label: "Bit order", value: "Swap layer explicit" },
      { label: "Export", value: "QASM parse checked" },
    ],
    source: {
      kind: "curated_reference",
      title: "Cirq circuit construction reference",
      url: "https://quantumai.google/cirq",
      reviewedBy: "LeonaQ curation pass",
      license: "CC BY 4.0-compatible reference metadata",
    },
    visualization: {
      wires: ["q[0]", "q[1]", "q[2]", "q[3]"],
      operations: [
        { label: "H", qubits: [0], tone: "accent" },
        { label: "CP", qubits: [0, 1], tone: "ok" },
        { label: "CP", qubits: [0, 2], tone: "ok" },
        { label: "CP", qubits: [0, 3], tone: "ok" },
        { label: "SWAP?", qubits: [0, 3], tone: "neutral" },
      ],
      outcomes: [
        { label: "Phase-resolved basis", probability: 0.75 },
        { label: "Other", probability: 0.25 },
      ],
    },
    codeVariants: [
      {
        framework: "Cirq",
        status: "native",
        language: "python",
        filename: "qft_resource_screen.py",
        code: cirqQft,
      },
      {
        framework: "OpenQASM 3.0",
        status: "native",
        language: "openqasm",
        filename: "qft_resource_screen.qasm",
        code: `OPENQASM 3.0;\ninclude "stdgates.inc";\nqubit[4] q;\nh q[0];\ncp(pi/2) q[1], q[0];\ncp(pi/4) q[2], q[0];\ncp(pi/8) q[3], q[0];`,
      },
    ],
    relatedSlugs: ["qaoa-maxcut-ring", "hadamard-gate"],
  },
];

export const ADDITIONAL_PUBLIC_REPOSITORY_ENTRIES: PublicRepositoryEntry[] = [
  makeReferenceEntry({
    slug: "pauli-y-gate",
    title: "Pauli-Y gate",
    titleJa: "パウリYゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Pauli operator",
    framework: "OpenQASM 3.0",
    verification: "Exact matrix check · Y² = I",
    method: "Compare the standard Pauli-Y matrix with the basis-state action and verify its unitary inverse.",
    result: "Pass · Y maps |0⟩ to i|1⟩ and |1⟩ to -i|0⟩ up to the expected phase.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "The Pauli gate that combines a bit flip with a phase rotation around the y axis.",
    descriptionJa: "ビット反転とY軸周りの位相回転を組み合わせるパウリゲートです。",
    introduction: "Pauli-Y rounds out the three Pauli generators and makes phase-sensitive basis changes explicit.",
    introductionJa: "パウリYは3つのパウリ生成子をそろえ、位相に依存する基底変換を明示します。",
    explanation: "Y = iXZ up to convention. Its square is identity, while the i and -i phases are important when amplitudes interfere.",
    explanationJa: "Yは規約上iXZとして表せます。二乗は恒等ですが、振幅が干渉するときiと-iの位相が重要です。",
    tags: ["pauli", "phase", "single qubit"],
    resources: [{ label: "Qubits", value: "1" }, { label: "Depth", value: "1 gate" }, { label: "Outcomes", value: "1 per input" }],
    metadata: [{ label: "Matrix", value: "[[0, -i], [i, 0]]" }, { label: "Rotation", value: "π around Y" }, { label: "Square", value: "I" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "Y", qubits: [0], tone: "accent" }],
    outcomes: [{ label: "1 from |0⟩", probability: 1 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit q;\ny q;",
    filename: "pauli-y.qasm",
    language: "openqasm",
    relatedSlugs: ["pauli-x-operator", "pauli-z-gate"],
  }),
  makeReferenceEntry({
    slug: "pauli-z-gate",
    title: "Pauli-Z gate",
    titleJa: "パウリZゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Pauli operator",
    framework: "OpenQASM 3.0",
    verification: "Exact matrix check · Z² = I",
    method: "Compare the standard Pauli-Z matrix with its computational-basis action.",
    result: "Pass · |0⟩ is unchanged and |1⟩ receives a phase of -1.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "A phase-flip gate whose behavior is invisible to a basis measurement until interference is introduced.",
    descriptionJa: "基底測定だけでは見えず、干渉で現れる位相反転ゲートです。",
    introduction: "Pauli-Z is the smallest useful record for explaining why phase is operational even when probabilities look unchanged.",
    introductionJa: "パウリZは、確率が変わらなくても位相が操作可能な情報であることを説明する最小の記録です。",
    explanation: "Z|0⟩ = |0⟩ and Z|1⟩ = -|1⟩. Applied inside a superposition, the relative phase changes later interference.",
    explanationJa: "Z|0⟩ = |0⟩、Z|1⟩ = -|1⟩です。重ね合わせの中では相対位相が変わり、後の干渉に現れます。",
    tags: ["pauli", "phase flip", "single qubit"],
    resources: [{ label: "Qubits", value: "1" }, { label: "Depth", value: "1 gate" }, { label: "Outcomes", value: "basis-preserving" }],
    metadata: [{ label: "Matrix", value: "[[1, 0], [0, -1]]" }, { label: "Rotation", value: "π around Z" }, { label: "Square", value: "I" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "Z", qubits: [0], tone: "ok" }],
    outcomes: [{ label: "Basis probabilities preserved", probability: 1 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit q;\nz q;",
    filename: "pauli-z.qasm",
    language: "openqasm",
    relatedSlugs: ["pauli-y-gate", "hadamard-gate"],
  }),
  makeReferenceEntry({
    slug: "s-phase-gate",
    title: "S phase gate",
    titleJa: "S位相ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Single-qubit gate",
    framework: "OpenQASM 3.0",
    verification: "Power relation check · S² = Z and S⁴ = I",
    method: "Evaluate the standard phase matrix and its repeated powers.",
    result: "Pass · S applies a π/2 phase to |1⟩ and composes to Z after two applications.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "A quarter-turn phase gate that exposes the difference between global and relative phase.",
    descriptionJa: "グローバル位相と相対位相の違いを示す、4分の1回転の位相ゲートです。",
    introduction: "The S gate is a compact bridge from Pauli operators to controlled phase and Fourier-style circuits.",
    introductionJa: "Sゲートは、パウリ演算子から制御位相やフーリエ型回路へつなぐ小さな橋渡しです。",
    explanation: "S|0⟩ = |0⟩ and S|1⟩ = i|1⟩. Because S² = Z, its phase convention can be checked without a large circuit.",
    explanationJa: "S|0⟩ = |0⟩、S|1⟩ = i|1⟩です。S² = Zなので、大きな回路なしに位相規約を確認できます。",
    tags: ["phase", "clifford", "single qubit"],
    resources: [{ label: "Qubits", value: "1" }, { label: "Depth", value: "1 gate" }, { label: "Phase", value: "π/2" }],
    metadata: [{ label: "Matrix", value: "[[1, 0], [0, i]]" }, { label: "Power", value: "S² = Z" }, { label: "Family", value: "Clifford" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "S", qubits: [0], tone: "accent" }],
    outcomes: [{ label: "Phase-resolved", probability: 1 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit q;\ns q;",
    filename: "s-phase.qasm",
    language: "openqasm",
    relatedSlugs: ["pauli-z-gate", "t-phase-gate"],
  }),
  makeReferenceEntry({
    slug: "t-phase-gate",
    title: "T phase gate",
    titleJa: "T位相ゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Single-qubit gate",
    framework: "OpenQASM 3.0",
    status: "verified_caveats",
    verification: "Power relation check · T² = S and T⁸ = I",
    method: "Evaluate the standard π/4 phase matrix and repeated powers.",
    result: "Pass · T applies a π/4 phase to |1⟩.",
    caveat: "This record verifies the ideal unitary relation; hardware fidelity and noise are not claimed.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "A non-Clifford phase gate that marks the boundary between a compact Clifford set and universal synthesis.",
    descriptionJa: "クリフォード集合と普遍ゲート合成における位置づけを示す、非クリフォード位相ゲートです。",
    introduction: "T is useful in resource discussions because its ideal matrix is simple while fault-tolerant cost can dominate.",
    introductionJa: "Tは理想行列が単純でもフォールトトレラントなコストが支配的になり得るため、リソース議論に有用です。",
    explanation: "T|0⟩ = |0⟩ and T|1⟩ = e^(iπ/4)|1⟩. Two T gates make S, and eight make the identity.",
    explanationJa: "T|0⟩ = |0⟩、T|1⟩ = e^(iπ/4)|1⟩です。Tを2回でS、8回で恒等になります。",
    tags: ["phase", "non-clifford", "fault tolerant"],
    resources: [{ label: "Qubits", value: "1" }, { label: "Depth", value: "1 gate" }, { label: "Phase", value: "π/4" }],
    metadata: [{ label: "Matrix", value: "[[1, 0], [0, e^(iπ/4)]]" }, { label: "Power", value: "T² = S" }, { label: "Family", value: "Non-Clifford" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]"],
    operations: [{ label: "T", qubits: [0], tone: "warn" }],
    outcomes: [{ label: "Phase-resolved", probability: 1 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit q;\nt q;",
    filename: "t-phase.qasm",
    language: "openqasm",
    relatedSlugs: ["s-phase-gate", "qft-resource-screen"],
  }),
  makeReferenceEntry({
    slug: "controlled-x-gate",
    title: "Controlled-X gate",
    titleJa: "制御Xゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Controlled gate",
    framework: "OpenQASM 3.0",
    verification: "Truth-table and entangling action check",
    method: "Compare the computational-basis truth table and Bell-state construction.",
    result: "Pass · target flips exactly when the control is |1⟩.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "The canonical two-qubit controlled operation used to create correlation and entanglement.",
    descriptionJa: "相関とエンタングルメントを作る、代表的な2量子ビット制御演算です。",
    introduction: "Controlled-X is the bridge between a single-qubit operation and a multi-qubit circuit contract.",
    introductionJa: "制御Xは、単一量子ビット演算と多量子ビット回路の契約をつなぎます。",
    explanation: "CX leaves the target unchanged for control 0 and applies X for control 1. With H on the control, it creates the Bell-state pattern.",
    explanationJa: "CXは制御0なら対象を変えず、制御1ならXを適用します。制御側にHを置くとベル状態の構造になります。",
    tags: ["controlled gate", "entanglement", "two qubit"],
    resources: [{ label: "Qubits", value: "2" }, { label: "Depth", value: "1 gate" }, { label: "Outcomes", value: "conditional" }],
    metadata: [{ label: "Control", value: "q[0]" }, { label: "Target", value: "q[1]" }, { label: "Universal role", value: "Entangling basis gate" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "CX", qubits: [0, 1], tone: "ok" }],
    outcomes: [{ label: "Control 0", probability: 0.5 }, { label: "Control 1", probability: 0.5 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit[2] q;\ncx q[0], q[1];",
    filename: "controlled-x.qasm",
    language: "openqasm",
    relatedSlugs: ["bell-state-qiskit", "swap-gate"],
  }),
  makeReferenceEntry({
    slug: "swap-gate",
    title: "SWAP gate",
    titleJa: "SWAPゲート",
    category: "gates",
    categoryLabel: "Gates",
    categoryLabelJa: "ゲート",
    algorithmFamily: "Two-qubit gate",
    framework: "OpenQASM 3.0",
    verification: "Basis-state exchange check",
    method: "Apply SWAP to all four computational-basis inputs and compare output labels.",
    result: "Pass · q[0] and q[1] exchange states without changing amplitudes.",
    exportStatus: "Native OpenQASM 3 · direct framework snippets available",
    provenance: "Curated reference",
    updatedAt: "2026-07-15",
    description: "A routing primitive that exchanges two qubit states and makes hardware connectivity explicit.",
    descriptionJa: "2つの量子ビット状態を交換し、ハードウェア接続性を明示するルーティング演算です。",
    introduction: "SWAP belongs in a practical catalog because moving a state is often a compilation concern, not an algorithmic one.",
    introductionJa: "SWAPは、状態の移動がアルゴリズムではなくコンパイル時の課題になることを示す実用的な例です。",
    explanation: "SWAP exchanges the amplitudes associated with q[0] and q[1]. A compiler may decompose it into three CX gates when SWAP is not native.",
    explanationJa: "SWAPはq[0]とq[1]に対応する振幅を交換します。ネイティブでなければ、コンパイラは3つのCXに分解できます。",
    tags: ["routing", "two qubit", "connectivity"],
    resources: [{ label: "Qubits", value: "2" }, { label: "Depth", value: "1 native / 3 CX" }, { label: "Outcomes", value: "states exchanged" }],
    metadata: [{ label: "Native form", value: "SWAP" }, { label: "Decomposition", value: "CX · CX · CX" }, { label: "Role", value: "Routing" }],
    sourceTitle: "OpenQASM 3 standard gate set",
    sourceUrl: "https://openqasm.com/language/gates.html",
    wires: ["q[0]", "q[1]"],
    operations: [{ label: "SWAP", qubits: [0, 1], tone: "accent" }],
    outcomes: [{ label: "|01⟩ → |10⟩", probability: 1 }],
    code: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\nqubit[2] q;\nswap q[0], q[1];",
    filename: "swap.qasm",
    language: "openqasm",
    relatedSlugs: ["controlled-x-gate", "qft-resource-screen"],
  }),
  makeReferenceEntry({
    slug: "deutsch-jozsa-cirq",
    title: "Deutsch–Jozsa query circuit",
    titleJa: "Deutsch–Jozsaクエリ回路",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Quantum query algorithm",
    framework: "Cirq",
    status: "verified_caveats",
    verification: "Constant / balanced oracle structure reviewed",
    method: "Inspect the phase-kickback circuit for a two-bit input and one oracle-output qubit.",
    result: "The ideal circuit distinguishes the supplied constant and balanced oracle families with one query.",
    caveat: "The catalog stores a small educational oracle instance, not a universal application benchmark.",
    exportStatus: "Native Cirq · framework-specific oracle boundary retained",
    provenance: "Official framework tutorial",
    updatedAt: "2026-07-15",
    description: "A one-query promise-problem circuit that separates constant from balanced Boolean oracles.",
    descriptionJa: "定数関数とバランス関数のオラクルを1回のクエリで区別する約束問題の回路です。",
    introduction: "Deutsch–Jozsa is a clean record for showing how phase kickback and interference change the query model.",
    introductionJa: "Deutsch–Jozsaは、位相キックバックと干渉がクエリモデルをどう変えるかを示す明快な記録です。",
    explanation: "Prepare the output qubit in |−⟩, place the input in superposition, query the reversible oracle, then apply Hadamards to read the promise class.",
    explanationJa: "出力量子ビットを|−⟩にし、入力を重ね合わせ、可逆オラクルを1回呼び、Hで約束クラスを読み出します。",
    tags: ["query", "oracle", "phase kickback", "Cirq"],
    resources: [{ label: "Qubits", value: "3" }, { label: "Depth", value: "oracle-dependent" }, { label: "Queries", value: "1" }],
    metadata: [{ label: "Promise", value: "Constant or balanced" }, { label: "Quantum queries", value: "1" }, { label: "Classical deterministic", value: "2^n / 2 + 1" }],
    sourceTitle: "Introduction to Cirq · Deutsch–Jozsa",
    sourceUrl: "https://quantumai.google/cirq/start/intro",
    wires: ["x[0]", "x[1]", "out"],
    operations: [{ label: "H", qubits: [0, 1, 2], tone: "accent" }, { label: "U_f", qubits: [0, 1, 2], tone: "ok" }, { label: "M", qubits: [0, 1], tone: "warn" }],
    outcomes: [{ label: "constant", probability: 0.5 }, { label: "balanced", probability: 0.5 }],
    code: "import cirq\n\nq0, q1, q2 = cirq.LineQubit.range(3)\ncircuit = cirq.Circuit(\n    cirq.X(q2),\n    cirq.H(q0), cirq.H(q1), cirq.H(q2),\n    cirq.CNOT(q0, q2), cirq.CNOT(q1, q2),\n    cirq.H(q0), cirq.H(q1), cirq.H(q2),\n    cirq.measure(q0, q1, key='input'),\n)",
    filename: "deutsch_jozsa.py",
    language: "python",
    relatedSlugs: ["bernstein-vazirani-qiskit", "grover-unstructured-search"],
  }),
  makeReferenceEntry({
    slug: "bernstein-vazirani-qiskit",
    title: "Bernstein–Vazirani hidden-string circuit",
    titleJa: "Bernstein–Vazirani隠れ文字列回路",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Quantum query algorithm",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Secret-string recovery circuit reviewed",
    method: "Construct a parity oracle for a fixed secret string and inspect the Deutsch–Jozsa-style readout.",
    result: "The ideal circuit returns the encoded secret string with one oracle query.",
    caveat: "The one-query claim is for the promise/query model; state preparation, oracle construction, and readout costs remain visible.",
    exportStatus: "Native Qiskit · oracle construction classified separately",
    provenance: "Official learning module",
    updatedAt: "2026-07-15",
    description: "A query circuit that recovers the hidden bit string in f(x) = s · x.",
    descriptionJa: "f(x) = s · xに埋め込まれた隠れたビット列を復元するクエリ回路です。",
    introduction: "Bernstein–Vazirani is a useful companion to Deutsch–Jozsa because it returns the hidden string rather than only its promise class.",
    introductionJa: "Bernstein–Vaziraniは、関数の分類だけでなく隠れた文字列を返すため、Deutsch–Jozsaと比較できる例です。",
    explanation: "A parity oracle applies CX from every secret-bit position set to 1 into the output qubit. Hadamard interference then exposes s in the input register.",
    explanationJa: "パリティオラクルは秘密ビットが1の位置から出力量子ビットへCXを適用します。Hによる干渉で入力レジスタにsが現れます。",
    tags: ["query", "hidden string", "oracle", "Qiskit"],
    resources: [{ label: "Qubits", value: "n + 1" }, { label: "Depth", value: "oracle-dependent" }, { label: "Queries", value: "1" }],
    metadata: [{ label: "Function", value: "f(x) = s · x mod 2" }, { label: "Quantum queries", value: "1" }, { label: "Classical queries", value: "n" }],
    sourceTitle: "IBM Quantum Learning · Bernstein–Vazirani",
    sourceUrl: "https://quantum.cloud.ibm.com/learning/en/courses/fundamentals-of-quantum-algorithms/quantum-query-algorithms/deutsch-jozsa-algorithm",
    wires: ["x[0]", "x[1]", "x[2]", "out"],
    operations: [{ label: "H", qubits: [0, 1, 2, 3], tone: "accent" }, { label: "U_s", qubits: [0, 1, 2, 3], tone: "ok" }, { label: "M", qubits: [0, 1, 2], tone: "warn" }],
    outcomes: [{ label: "secret s", probability: 1 }],
    code: "from qiskit import QuantumCircuit\n\nsecret = '101'\nqc = QuantumCircuit(len(secret) + 1, len(secret))\nqc.x(len(secret))\nqc.h(range(len(secret) + 1))\nfor index, bit in enumerate(reversed(secret)):\n    if bit == '1':\n        qc.cx(index, len(secret))\nqc.h(range(len(secret)))\nqc.measure(range(len(secret)), range(len(secret)))",
    filename: "bernstein_vazirani.py",
    language: "python",
    relatedSlugs: ["deutsch-jozsa-cirq"],
  }),
  makeReferenceEntry({
    slug: "superdense-coding-circuit",
    title: "Superdense coding circuit",
    titleJa: "超密符号化回路",
    category: "algorithms",
    categoryLabel: "Algorithms",
    categoryLabelJa: "アルゴリズム",
    algorithmFamily: "Entanglement and communication",
    framework: "Qiskit",
    status: "verified_caveats",
    verification: "Two-bit message decoding circuit reviewed",
    method: "Prepare a Bell pair, apply the sender's message encoding, then decode with CX and H before measurement.",
    result: "The ideal circuit decodes the selected two classical message bits.",
    caveat: "The protocol uses a pre-shared Bell pair and a two-bit classical readout; it does not transmit two arbitrary qubits.",
    exportStatus: "Native Qiskit · direct gate-level export",
    provenance: "Official course reference",
    updatedAt: "2026-07-15",
    description: "An entanglement-assisted communication protocol that encodes two classical bits into one transmitted qubit.",
    descriptionJa: "エンタングルメントを使い、1量子ビットの送信で2古典ビットを符号化する通信プロトコルです。",
    introduction: "Superdense coding complements teleportation by making the communication direction and resource assumptions visible.",
    introductionJa: "超密符号化はテレポーテーションを補完し、通信方向と共有資源の前提を明示します。",
    explanation: "Alice and Bob first share a Bell pair. Alice applies I, X, Z, or XZ for the message, sends her qubit, and Bob applies CX then H to recover the two-bit label.",
    explanationJa: "AliceとBobがベル対を共有し、Aliceがメッセージに応じてI、X、Z、XZを適用します。送信後、BobがCXとHで2ビットを復元します。",
    tags: ["communication", "entanglement", "dense coding", "Qiskit"],
    resources: [{ label: "Qubits", value: "2" }, { label: "Classical bits", value: "2" }, { label: "Shared resource", value: "Bell pair" }],
    metadata: [{ label: "Encoding", value: "I / X / Z / XZ" }, { label: "Transmission", value: "1 qubit" }, { label: "Readout", value: "2 classical bits" }],
    sourceTitle: "IBM Quantum Learning · Basics of quantum information",
    sourceUrl: "https://quantum.cloud.ibm.com/learning/en/courses/basics-of-quantum-information",
    wires: ["Alice", "Bob"],
    operations: [{ label: "H", qubits: [0], tone: "accent" }, { label: "CX", qubits: [0, 1], tone: "ok" }, { label: "ENC", qubits: [0], tone: "warn" }, { label: "DEC", qubits: [0, 1], tone: "neutral" }],
    outcomes: [{ label: "00 / 01 / 10 / 11", probability: 1 }],
    code: "from qiskit import QuantumCircuit\n\nmessage = '10'\nqc = QuantumCircuit(2, 2)\nqc.h(0)\nqc.cx(0, 1)\nif message[0] == '1': qc.z(0)\nif message[1] == '1': qc.x(0)\nqc.cx(0, 1)\nqc.h(0)\nqc.measure([0, 1], [0, 1])",
    filename: "superdense_coding.py",
    language: "python",
    relatedSlugs: ["quantum-teleportation", "bell-state-qiskit"],
  }),
];
