/**
 * Record -> worked-example links (stage 1 of the Atlas worked-example figure).
 *
 * Stage 2 (a sibling branch) adds `apps/web/lib/worked-examples.ts`, exporting
 * `WORKED_EXAMPLES`, and a record page draws the linked example instead of
 * the hero circuit. This file only carries the verified link data and the
 * lookup — nothing here draws anything.
 *
 * The base map (99 links over 84 records) is the verified map at
 * `~/Developer/ai-ops/desk/leona/plans/studio-atlas-usefulness-20260915/atlas-example-map.json`,
 * copied in unchanged. Each `evidence` string is a verbatim substring of
 * `record[field]` — `scripts/check-worked-example-links.mjs` asserts that
 * against the live corpus, so this file is data, not a claim: the claim is
 * checked, not trusted. `field` supports one level of nesting with a dot
 * (`"verificationDetails.caveat"`), and a `tags` field is checked against the
 * array's own entries rather than a joined string.
 *
 * The base map's method, and its traps (gate cards naming an algorithm in the
 * wrong direction, `shor-code-error-correction` not being Shor's algorithm,
 * `search-with-wildcards` negating the phrases it contains) are in
 * `atlas-example-map.md` beside the JSON. Records affected by those traps are
 * already excluded from the map below.
 *
 * 2026-09-15, second pass (87 links added, 186 total over 170 records): the
 * base map scored zero honest links for the VQE cluster (`atlas-example-map.md`
 * §(c) ranked it the single highest-value gap once `vqe-2q-transverse-ising`
 * existed). Added by the same rule as the base map, applied to two exact
 * record sets rather than a keyword sweep over the whole corpus:
 *   - the 37 VQE-method records (wires `hybrid objective / quantum circuit /
 *     classical update` — the third generic placeholder), `instance`,
 *     `field: "algorithmFamily"`, evidence `"Variational quantum
 *     eigensolver"` (every one of the 37 carries that field verbatim);
 *   - the 50 operator records tagged `"VQE operator"` (wires `definition /
 *     mapping / measurement`), `used-in` (see the third-pass note below),
 *     `field: "explanation"`, evidence `"To use this record in VQE"`.
 * `operator-trotter-product` already carried one link (instance, to
 * ising-trotter-4) and gained this as its second, within the 2-link cap.
 * Excluded on purpose: `projection-based-embedding-vqe` and
 * `coarse-grained-vqe-intermolecular-interactions` share the
 * `algorithmFamily` label but carry the Zoo/Classiq-parity placeholder, not
 * the VQE-method one — outside the 37 this pass was scoped to; flagged in the
 * session report rather than linked without being asked.
 *
 * 2026-09-15, third pass — a direction fix, not new links: the 50 VQE
 * operator links above were first written as `component`, on the reasoning
 * "the operator is used by VQE, so VQE is a component of what this record
 * documents." That is backwards. `component` means the RECORD's own method
 * uses the example as a subroutine (matching the figure's own words,
 * "Worked example of a part THIS METHOD uses") — an operator record's method
 * is "specify / map / group," and it does not use VQE at all; VQE uses the
 * operator. This is exactly the gate-card trap `atlas-example-map.md` §(d)
 * already named ("this gate is used by Grover" is not a Grover component
 * link) — caught here on the record-under-scrutiny side rather than the
 * example side. Fixed by adding a third relation, `used-in`: the example
 * uses THIS record, not the reverse. All 50 VQE operator links moved from
 * `component` to `used-in`. A same-shape sweep of the rest of the 186 links
 * found one more: `tensor-hypercontraction-block-encoding`'s own text says
 * its block encoding is "cheap enough to support phase estimation" and is
 * "combined with phase estimation" by the consuming algorithm — the record
 * is the thing phase estimation uses, not a record whose own method uses
 * phase estimation — moved to `used-in` against `qpe-3-exact`. Every other
 * `component` link was read in full and the direction holds: the record's
 * own text says ITS method uses, applies, combines, invokes, or extends the
 * named technique.
 *
 * 2026-09-17, FOURTH pass (11 links added over 9 records, 197 total over 179
 * records): the target was the 41 records that rendered NOTHING — one of the
 * three stock placeholder diagrams, which is suppressed, and no worked-example
 * link either. A reader got a title, prose, and no figure of any kind.
 *
 * Candidates were generated by matching the 21 examples' techniques against
 * every prose field of those 41 records, and then read by hand — which is the
 * half that matters: **14 of 23 candidates were rejected**, and the rejections
 * are the record of what this map must not contain.
 *
 *   - `search-with-wildcards`: "rests neither on amplitude amplification nor
 *     on a quantum walk" — the phrase is NEGATED. Both rejected. (The same
 *     trap `atlas-example-map.md` already names for this record.)
 *   - `jones-polynomial-approximation`: "QFT" matched inside "TQFT" —
 *     topological quantum field theory, not the Fourier transform. A
 *     substring hit inside an acronym is not a hit.
 *   - `double-bracket-diagonalization`: "at an implementation cost lower than
 *     quantum phase estimation requires" — a COMPARISON to QPE, i.e. this
 *     method avoids it.
 *   - `class-group-of-a-number-field`: "what blocks a direct application of
 *     the standard ... hidden subgroup machinery" — says it does not apply.
 *   - `quantum-kernel-fraud-detection`: "kernel" matched "classical
 *     kernel-based benchmarks", the thing it is compared against.
 *   - `matrix-products-over-semirings`: Grover appears as the trivial bound
 *     to beat, not as a subroutine this record uses.
 *   - `linear-differential-equations`: "turning time evolution into one large
 *     linear-algebra problem" — the opposite of using Hamiltonian simulation.
 *   - `gibbs-state-sampling`: both hits describe how the Zoo GROUPS the
 *     record, not what its algorithm does.
 *
 * Every rejection has one shape: a phrase that names a technique while saying
 * the record does not use it. A keyword sweep cannot tell those apart, and
 * `check-worked-example-links.mjs` cannot either — it checks that the evidence
 * is verbatim, which is a check on transcription, not on direction. The
 * direction is a reading, and it is why this pass is 9 records and not 23.
 *
 * The two records the second pass deliberately left out,
 * `projection-based-embedding-vqe` and
 * `coarse-grained-vqe-intermolecular-interactions`, are linked here — not by
 * the `algorithmFamily` label that pass declined to use on them, but by a
 * sentence in each record's own prose saying its method IS a VQE.
 *
 * 2026-09-17, FIFTH pass (17 links over 17 gate records, 214 total over 196):
 * the gate cards. Every one of the 29 gate records drew a single labelled box
 * and a bar chart, and for a whole family of them that bar chart is the SAME
 * PICTURE — Z, S, T, S-dagger, T-dagger, P, RZ, CZ and CP applied to a
 * superposition move no probability at all. The T-gate page, the S-gate page
 * and a page for doing nothing were, as drawn, indistinguishable.
 *
 * Each of these 17 records is now an `instance` link to a demonstration
 * written for it: the smallest circuit in which that gate does something, plus
 * whatever preparation that takes (a Hadamard first, for the phase family,
 * because on |0⟩ alone a phase gate's effect is global and unobservable).
 * The derived per-step reading and the phase panel then say what happened, and
 * for the phase family they say the thing the bars cannot.
 *
 * `evidence` here is provenance rather than justification: an `instance` link
 * replaces the hero and never renders the note that quotes it. It is still a
 * verbatim substring of the record's `description`, checked like every other.
 *
 * The 12 gate records NOT linked are the ones outside the builder's gate set
 * (CY, CH, iSWAP, CSWAP, SX, ECR, DCX, CCZ, CRZ, RXX, U3) plus the identity
 * gate, which has no builder gate at all. They need a decomposition first, and
 * a demonstration of a gate through its decomposition is a demonstration of
 * something else.
 */


export type WorkedExampleRelation = "instance" | "component" | "used-in";

export interface WorkedExampleLink {
  readonly exampleId: string;
  /**
   * `"instance"` — this record IS what the example demonstrates.
   * `"component"` — this record's OWN method uses the example as a subroutine.
   * `"used-in"` — the reverse: the example's algorithm uses THIS record (an
   * operator, a building block) as one of its own components. Never
   * replaces the hero; gets its own note wording naming the example as the
   * user, not the used.
   */
  readonly relation: WorkedExampleRelation;
  /** A record field name, or a dotted one-level path (e.g. `"verificationDetails.caveat"`). */
  readonly field: string;
  /** A verbatim substring of the named field on the record this key names. */
  readonly evidence: string;
}

/**
 * Exported (not module-private) so `scripts/check-worked-example-links.mjs`
 * can walk every key — including one that does not name a real record, which
 * `workedExampleLinks()` below would otherwise swallow into an empty array.
 */
export const WORKED_EXAMPLE_LINKS: Readonly<Record<string, readonly WorkedExampleLink[]>> =
{
 "abelian-hidden-subgroup": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "component",
   "field": "description",
   "evidence": "order finding"
  },
  {
   "exampleId": "simon-2",
   "relation": "component",
   "field": "description",
   "evidence": "Simon's problem"
  }
 ],
 "adapt-qaoa": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "title",
   "evidence": "QAOA"
  }
 ],
 "amplitude-amplification": [
  {
   "exampleId": "grover-3q-101",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Generalized Grover / amplitude amplification"
  }
 ],
 "amplitude-estimation": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "title",
   "evidence": "amplitude estimation"
  },
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "explanation",
   "evidence": "phase estimation"
  }
 ],
 "asian-option-pricing-karhunen-loeve": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Amplitude estimation"
  }
 ],
 "backtracking-quantum-walk-speedup": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Quantum walk"
  }
 ],
 "bell-state-qiskit": [
  {
   "exampleId": "bell-pair",
   "relation": "instance",
   "field": "title",
   "evidence": "Bell state"
  }
 ],
 "benchmark-bell-pair-ladder-16q": [
  {
   "exampleId": "bell-pair",
   "relation": "instance",
   "field": "tags",
   "evidence": "Bell pair"
  }
 ],
 "benchmark-bell-pair-ladder-4q": [
  {
   "exampleId": "bell-pair",
   "relation": "instance",
   "field": "tags",
   "evidence": "Bell pair"
  }
 ],
 "benchmark-bernstein-vazirani-16q": [
  {
   "exampleId": "bernstein-vazirani-1011",
   "relation": "instance",
   "field": "title",
   "evidence": "Bernstein–Vazirani"
  }
 ],
 "benchmark-bernstein-vazirani-3q": [
  {
   "exampleId": "bernstein-vazirani-1011",
   "relation": "instance",
   "field": "title",
   "evidence": "Bernstein–Vazirani"
  }
 ],
 "benchmark-ghz-chain-16q": [
  {
   "exampleId": "ghz-4",
   "relation": "instance",
   "field": "title",
   "evidence": "GHZ"
  }
 ],
 "benchmark-ghz-chain-3q": [
  {
   "exampleId": "ghz-4",
   "relation": "instance",
   "field": "title",
   "evidence": "GHZ"
  }
 ],
 "benchmark-ising-trotter-16q": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Trotter"
  }
 ],
 "benchmark-ising-trotter-3q": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Trotter"
  }
 ],
 "benchmark-parity-oracle-16q": [
  {
   "exampleId": "deutsch-jozsa-3",
   "relation": "instance",
   "field": "tags",
   "evidence": "Deutsch–Jozsa"
  }
 ],
 "benchmark-parity-oracle-3q": [
  {
   "exampleId": "deutsch-jozsa-3",
   "relation": "instance",
   "field": "tags",
   "evidence": "Deutsch–Jozsa"
  }
 ],
 "benchmark-qaoa-ring-16q": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "QAOA / MaxCut"
  }
 ],
 "benchmark-qaoa-ring-3q": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "QAOA / MaxCut"
  }
 ],
 "bernstein-vazirani-qiskit": [
  {
   "exampleId": "bernstein-vazirani-1011",
   "relation": "instance",
   "field": "title",
   "evidence": "Bernstein–Vazirani"
  }
 ],
 "cooling-systems-optimization": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "QAOA"
  }
 ],
 "counterfeit-coin-problem": [
  {
   "exampleId": "bernstein-vazirani-1011",
   "relation": "component",
   "field": "introduction",
   "evidence": "Bernstein-Vazirani algorithm"
  },
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "amplitude amplification"
  }
 ],
 "decoded-quantum-interferometry": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "component",
   "field": "introduction",
   "evidence": "quantum Fourier transform"
  }
 ],
 "derivative-pricing-resource-threshold": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Amplitude estimation"
  }
 ],
 "deutsch-jozsa-cirq": [
  {
   "exampleId": "deutsch-jozsa-3",
   "relation": "instance",
   "field": "title",
   "evidence": "Deutsch–Jozsa"
  }
 ],
 "discrete-logarithm": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "introduction",
   "evidence": "Shor's paper gives efficient randomized quantum algorithms"
  }
 ],
 "electrical-resistance": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "component",
   "field": "introduction",
   "evidence": "quantum walk"
  },
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "introduction",
   "evidence": "phase estimation"
  }
 ],
 "element-distinctness": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  },
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover's search"
  }
 ],
 "elliptic-curve-discrete-log-resources": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "description",
   "evidence": "Shor's discrete-logarithm algorithm"
  }
 ],
 "environment-assisted-quantum-walk": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walks"
  }
 ],
 "exponential-congruences": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "component",
   "field": "introduction",
   "evidence": "Shor's algorithm"
  },
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover search"
  }
 ],
 "gauss-sum-estimation": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "component",
   "field": "introduction",
   "evidence": "Shor's discrete-logarithm algorithm"
  },
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "amplitude amplification"
  }
 ],
 "ghz-state-pennylane": [
  {
   "exampleId": "ghz-4",
   "relation": "instance",
   "field": "title",
   "evidence": "GHZ state"
  },
  {
   "exampleId": "bell-pair",
   "relation": "component",
   "field": "introduction",
   "evidence": "Bell-state"
  }
 ],
 "graph-collision": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "component",
   "field": "introduction",
   "evidence": "Ambainis's quantum walk"
  }
 ],
 "group-order-and-membership": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "component",
   "field": "verificationDetails.caveat",
   "evidence": "quantum algorithms for discrete log"
  }
 ],
 "grover-unstructured-search": [
  {
   "exampleId": "grover-3q-101",
   "relation": "instance",
   "field": "title",
   "evidence": "Grover"
  }
 ],
 "hamiltonian-simulation-ising": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "product formula"
  }
 ],
 "heat-equation-solver": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "component",
   "field": "introduction",
   "evidence": "amplitude estimation"
  }
 ],
 "hhl-linear-systems": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "explanationMd",
   "evidence": "quantum phase estimation"
  }
 ],
 "hidden-nonlinear-structures": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "component",
   "field": "introduction",
   "evidence": "Fourier transform"
  }
 ],
 "hidden-shift-problem": [
  {
   "exampleId": "hidden-shift-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Hidden shift"
  }
 ],
 "hybrid-hhl-portfolio-optimization": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "explanation",
   "evidence": "phase estimation"
  }
 ],
 "hypercube-dynamic-programming": [
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover's search"
  }
 ],
 "irreducible-representation-matrix-elements": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Quantum Fourier transform"
  }
 ],
 "iterative-phase-estimation": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "instance",
   "field": "title",
   "evidence": "Iterative phase estimation"
  }
 ],
 "low-autocorrelation-binary-sequences-problem": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "title",
   "evidence": "QAOA"
  }
 ],
 "matrix-commutativity-testing": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "matrix-product-verification": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "molecular-energy-phase-estimation": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "instance",
   "field": "title",
   "evidence": "phase estimation"
  }
 ],
 "nand-tree-evaluation": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "component",
   "field": "introduction",
   "evidence": "continuous-time quantum walk"
  }
 ],
 "operator-trotter-product": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Trotter product"
  },
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "option-pricing-amplitude-estimation": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "title",
   "evidence": "amplitude estimation"
  }
 ],
 "pell-equation-regulator": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "introduction",
   "evidence": "period finding"
  }
 ],
 "principal-ideal-problem": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "introduction",
   "evidence": "Shor's discrete-logarithm algorithm"
  }
 ],
 "protein-folding-quantum-walk": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "qaoa-combinatorial-optimization": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "QAOA"
  }
 ],
 "qaoa-in-qaoa": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "title",
   "evidence": "QAOA"
  }
 ],
 "qaoa-maxcut-ring": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "instance",
   "field": "title",
   "evidence": "QAOA"
  }
 ],
 "qft-resource-screen": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "instance",
   "field": "title",
   "evidence": "QFT"
  }
 ],
 "quantum-counting": [
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover's amplitude amplification"
  },
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "introduction",
   "evidence": "phase estimation"
  }
 ],
 "quantum-fourier-transform": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "instance",
   "field": "title",
   "evidence": "Quantum Fourier Transform"
  }
 ],
 "quantum-phase-estimation": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "instance",
   "field": "title",
   "evidence": "Quantum phase estimation"
  },
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "component",
   "field": "introduction",
   "evidence": "inverse QFT"
  }
 ],
 "quantum-primality-test-order-finding": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "title",
   "evidence": "order finding"
  }
 ],
 "quantum-simulated-annealing": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "component",
   "field": "introduction",
   "evidence": "quantum walks"
  }
 ],
 "quantum-teleportation": [
  {
   "exampleId": "teleportation-deferred",
   "relation": "instance",
   "field": "title",
   "evidence": "Quantum teleportation"
  },
  {
   "exampleId": "bell-pair",
   "relation": "component",
   "field": "introduction",
   "evidence": "Bell pair"
  }
 ],
 "quantum-walk-line": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "rainbow-options-amplitude-loading": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Amplitude estimation"
  }
 ],
 "risk-analysis-amplitude-estimation": [
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "instance",
   "field": "title",
   "evidence": "amplitude estimation"
  }
 ],
 "semidefinite-programming": [
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover search"
  },
  {
   "exampleId": "amplitude-estimation-3",
   "relation": "component",
   "field": "introduction",
   "evidence": "amplitude estimation"
  }
 ],
 "shor-period-finding": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "instance",
   "field": "title",
   "evidence": "Shor period finding"
  },
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "explanation",
   "evidence": "Quantum phase estimation"
  }
 ],
 "sparse-matrix-power-diagonal-entries": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "introduction",
   "evidence": "phase estimation"
  }
 ],
 "spectral-sum-estimation": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "introduction",
   "evidence": "phase estimation"
  }
 ],
 "string-pattern-matching": [
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover's algorithm used together with"
  }
 ],
 "subset-finding-quantum-walk": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  },
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "Grover diffusion operators"
  }
 ],
 "subset-sum-quantum-walk": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "superdense-coding-circuit": [
  {
   "exampleId": "superdense-coding",
   "relation": "instance",
   "field": "title",
   "evidence": "Superdense coding"
  },
  {
   "exampleId": "bell-pair",
   "relation": "component",
   "field": "explanation",
   "evidence": "Bell pair"
  }
 ],
 "tensor-hypercontraction-block-encoding": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "used-in",
   "field": "introduction",
   "evidence": "phase estimation"
  }
 ],
 "tensor-principal-component-analysis": [
  {
   "exampleId": "grover-3q-101",
   "relation": "component",
   "field": "introduction",
   "evidence": "amplitude amplification"
  }
 ],
 "top-eigenvector-estimation": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "instance",
   "field": "introduction",
   "evidence": "Gaussian phase estimation"
  }
 ],
 "trotter-suzuki-simulation": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "instance",
   "field": "title",
   "evidence": "Trotter"
  }
 ],
 "viterbi-decoding-convolutional-codes": [
  {
   "exampleId": "grover-3q-101",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Generalized Grover / amplitude amplification"
  }
 ],
 "w-state": [
  {
   "exampleId": "w-state-3",
   "relation": "instance",
   "field": "title",
   "evidence": "W state"
  }
 ],
 "welded-tree-traversal": [
  {
   "exampleId": "quantum-walk-cycle-4",
   "relation": "instance",
   "field": "title",
   "evidence": "quantum walk"
  }
 ],
 "zeta-function-of-a-curve": [
  {
   "exampleId": "shor-order-finding-15",
   "relation": "component",
   "field": "introduction",
   "evidence": "Shor-type Fourier-sampling method"
  }
 ],
 "vqe-objective-loop": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-hardware-efficient-ansatz": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-uccsd-ansatz": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-generalized-excitations": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-k-upccgsd": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-adapt": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-qubit-adapt": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-batched-adapt": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-tetris-adapt": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-qcc": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-iterative-qcc": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-symmetry-preserving": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-particle-conserving": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-spin-adapted": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-orbital-optimized": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-vqd": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-ssvqe": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-mc-vqe": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-folded-spectrum": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-penalty-excited-state": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-quantum-subspace-expansion": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-qeom": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-variance-objective": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-cvar": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-imaginary-time": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-natural-gradient": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-spsa-optimizer": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-gradient-based": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-layerwise-training": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-warm-start": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-active-space": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-qubit-tapering": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-measurement-grouping": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-classical-shadows": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-symmetry-verification": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-zero-noise-extrapolation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "vqe-readout-mitigation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "instance",
   "field": "algorithmFamily",
   "evidence": "Variational quantum eigensolver"
  }
 ],
 "operator-pauli-string": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-weighted-pauli-sum": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-electronic-structure": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-one-body-fermion": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-two-body-fermion": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-creation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-annihilation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-number": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-total-particle-number": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-fermionic-hopping": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-pairing": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-coulomb": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-fermi-hubbard": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-bose-hubbard": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-ising-cost": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-transverse-field-ising": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-xy-model": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-heisenberg": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-xyz-model": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-kitaev-chain": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-maxcut-cost": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-qubo": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-constraint-penalty": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-dipole": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-density": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-spin-x-total": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-spin-y-total": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-spin-z-total": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-total-spin-squared": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-fermion-parity": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-jordan-wigner-creation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-jordan-wigner-number": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-jordan-wigner-hopping": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-parity-mapping": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-bravyi-kitaev-mapping": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-z2-symmetry-generator": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-reference-projector": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-deflation-projector": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-shifted-hamiltonian-square": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-hamiltonian-variance": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-energy-gradient-commutator": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-anti-hermitian-excitation": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-ucc-singles-pool": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-ucc-doubles-pool": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-qubit-adapt-pool": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-pauli-time-evolution": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-commuting-group": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "operator-one-rdm": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ],
 "string-rewriting-derivation-counts": [
  {
   "exampleId": "qpe-3-exact",
   "relation": "component",
   "field": "explanation",
   "evidence": "Hamiltonian simulation and phase estimation can estimate"
  },
  {
   "exampleId": "ising-trotter-4",
   "relation": "component",
   "field": "explanation",
   "evidence": "Hamiltonian simulation and phase estimation"
  }
 ],
 "average-case-lattice-problems-by-filtering": [
  {
   "exampleId": "qft-4q-roundtrip",
   "relation": "component",
   "field": "explanation",
   "evidence": "together with a quantum Fourier transform step"
  }
 ],
 "unit-group-of-a-number-field": [
  {
   "exampleId": "simon-2",
   "relation": "component",
   "field": "explanation",
   "evidence": "generalizes the real-valued hidden subgroup framework"
  }
 ],
 "ising-formulations-np-problems": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "mappings to the Ising model"
  },
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "an Ising Hamiltonian whose ground states are the problem's solutions"
  }
 ],
 "projection-based-embedding-vqe": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "component",
   "field": "explanation",
   "evidence": "combine the variational quantum eigensolver (VQE) with density functional theory"
  }
 ],
 "coarse-grained-vqe-intermolecular-interactions": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "component",
   "field": "introduction",
   "evidence": "determining the ground state of weakly interacting molecules using a variational quantum algorithm"
  }
 ],
 "workflow-scheduling-qubo": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "they develop a novel QUBO formulation"
  }
 ],
 "quantum-vulnerability-analysis": [
  {
   "exampleId": "qaoa-maxcut-4-cycle",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "as a QUBO and solving it with quantum annealing"
  }
 ],
 "wave-equation-simulation": [
  {
   "exampleId": "ising-trotter-4",
   "relation": "component",
   "field": "description",
   "evidence": "using Hamiltonian simulation and quantum linear system algorithms as subroutines"
  }
 ],
 "hadamard-gate": [
  {
   "exampleId": "gate-h-on-zero",
   "relation": "instance",
   "field": "description",
   "evidence": "putting a qubit into an equal superposition"
  }
 ],
 "pauli-y-gate": [
  {
   "exampleId": "gate-y-on-zero",
   "relation": "instance",
   "field": "description",
   "evidence": "combines a bit flip with a phase rotation"
  }
 ],
 "pauli-z-gate": [
  {
   "exampleId": "gate-z-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "invisible to a basis measurement until interference is introduced"
  }
 ],
 "s-phase-gate": [
  {
   "exampleId": "gate-s-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "quarter-turn phase gate that exposes the difference between global and relative phase"
  }
 ],
 "t-phase-gate": [
  {
   "exampleId": "gate-t-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "non-Clifford phase gate"
  }
 ],
 "s-dagger-gate": [
  {
   "exampleId": "gate-sdg-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "applying a -π/2 phase to |1⟩"
  }
 ],
 "t-dagger-gate": [
  {
   "exampleId": "gate-tdg-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "applying a -π/4 phase to |1⟩"
  }
 ],
 "phase-gate-p": [
  {
   "exampleId": "gate-p-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "unifying S, T, and Z as special cases"
  }
 ],
 "rz-rotation-gate": [
  {
   "exampleId": "gate-rz-on-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "adds a relative phase between |0⟩ and |1⟩"
  }
 ],
 "rx-rotation-gate": [
  {
   "exampleId": "gate-rx-on-zero",
   "relation": "instance",
   "field": "description",
   "evidence": "rotation about the Bloch-sphere X axis"
  }
 ],
 "ry-rotation-gate": [
  {
   "exampleId": "gate-ry-on-zero",
   "relation": "instance",
   "field": "description",
   "evidence": "rotation about the Bloch-sphere Y axis"
  }
 ],
 "controlled-x-gate": [
  {
   "exampleId": "gate-cx-on-plus-zero",
   "relation": "instance",
   "field": "description",
   "evidence": "used to create correlation and entanglement"
  }
 ],
 "controlled-z-gate": [
  {
   "exampleId": "gate-cz-on-plus-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "applies a -1 phase exactly when both qubits are |1⟩"
  }
 ],
 "controlled-phase-gate": [
  {
   "exampleId": "gate-cp-on-plus-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "applies e^{iλ} exactly when both qubits are |1⟩"
  }
 ],
 "swap-gate": [
  {
   "exampleId": "gate-swap-on-01",
   "relation": "instance",
   "field": "description",
   "evidence": "exchanges two qubit states"
  }
 ],
 "toffoli-ccx-gate": [
  {
   "exampleId": "gate-ccx-on-11",
   "relation": "instance",
   "field": "description",
   "evidence": "implements reversible classical AND/NAND logic"
  }
 ],
 "rzz-interaction-gate": [
  {
   "exampleId": "gate-rzz-on-plus-plus",
   "relation": "instance",
   "field": "description",
   "evidence": "evolution under the Ising ZZ coupling"
  }
 ],
 "operator-two-rdm": [
  {
   "exampleId": "vqe-2q-transverse-ising",
   "relation": "used-in",
   "field": "explanation",
   "evidence": "To use this record in VQE"
  }
 ]
};

export function workedExampleLinks(slug: string): readonly WorkedExampleLink[] {
  return WORKED_EXAMPLE_LINKS[slug] ?? [];
}
