// GENERATED by scripts/generate-contract-enums.mjs — do not hand-edit.
//
// Runtime companions to the union types in schema.d.ts, which cannot be
// iterated. Regenerate with:
//
//   uv run python -m majorana_contracts.export
//   pnpm --filter @majorana/contracts-gen gen
//
// ci.yml runs that and then `git diff --exit-code packages/ts/contracts-gen`,
// so a stale copy of this file cannot merge.
//
// Each tuple is `as const`, so it is assignable to the matching
// `components["schemas"][...]` union and a consumer gets a compile error rather
// than a silently-wider type. ORDER IS THE CONTRACT'S ORDER — it is what the
// Python enum declares, so anything user-visible should sort or label rather
// than rely on it.

/** Algorithm — 15 members. */
export const ALGORITHM_VALUES = [
  "VQE",
  "QAOA",
  "Grover",
  "Bell",
  "GHZ",
  "QFT",
  "QPE",
  "AmplitudeEstimation",
  "StatePreparation",
  "CircuitSynthesis",
  "GateDecomposition",
  "Transpilation",
  "Simulation",
  "ErrorCorrection",
  "other",
] as const;

/** ArtifactType — 11 members. */
export const ARTIFACT_TYPE_VALUES = [
  "script",
  "function",
  "class",
  "QuantumCircuit",
  "OpenQASM",
  "counts",
  "statevector",
  "operator",
  "clifford",
  "pass_manager",
  "other",
] as const;

/** BaselineKind — 5 members. */
export const BASELINE_KIND_VALUES = [
  "maxcut",
  "qubo",
  "portfolio",
  "hamiltonian",
  "none",
] as const;

/** EvidenceStrength — 2 members. */
export const EVIDENCE_STRENGTH_VALUES = [
  "physical",
  "structural",
] as const;

/** ExportStatus — 4 members. */
export const EXPORT_STATUS_VALUES = [
  "lossless",
  "lossy_with_reason",
  "download_only",
  "unsupported",
] as const;

/** Framework — 6 members. */
export const FRAMEWORK_VALUES = [
  "qiskit",
  "pennylane",
  "cirq",
  "braket",
  "qibo",
  "qulacs",
] as const;

/** MeasurementPolicy — 5 members. */
export const MEASUREMENT_POLICY_VALUES = [
  "none",
  "only_if_requested",
  "measure_all",
  "specified",
  "not_applicable",
] as const;

/** Optimizer — 3 members. */
export const OPTIMIZER_VALUES = [
  "COBYLA",
  "SPSA",
  "L_BFGS_B",
] as const;

/** QpuEstimateBasis — 2 members. */
export const QPU_ESTIMATE_BASIS_VALUES = [
  "vendor_rate_card",
  "free_tier_allowance",
] as const;

/** QpuProvider — 2 members. */
export const QPU_PROVIDER_VALUES = [
  "ibm",
  "braket",
] as const;

/** QpuRunStatus — 5 members. */
export const QPU_RUN_STATUS_VALUES = [
  "queued",
  "running",
  "done",
  "error",
  "cancelled",
] as const;

/** ResourceEstimateBasis — 4 members. */
export const RESOURCE_ESTIMATE_BASIS_VALUES = [
  "exact",
  "estimated",
  "refused",
  "no_circuit",
] as const;

/** RetryTarget — 5 members. */
export const RETRY_TARGET_VALUES = [
  "code_generation",
  "planning",
  "simulation",
  "verification",
  "none",
] as const;

/** Role — 4 members. */
export const ROLE_VALUES = [
  "owner",
  "admin",
  "member",
  "viewer",
] as const;

/** RunMode — 5 members. */
export const RUN_MODE_VALUES = [
  "auto",
  "chat",
  "execute",
  "ideate",
  "explain",
] as const;

/** RunStatus — 5 members. */
export const RUN_STATUS_VALUES = [
  "queued",
  "running",
  "succeeded",
  "failed",
  "cancelled",
] as const;

/** SemanticReviewDecision — 4 members. */
export const SEMANTIC_REVIEW_DECISION_VALUES = [
  "ready",
  "code_repair",
  "replan",
  "inconclusive",
] as const;

/** ShareRole — 2 members. */
export const SHARE_ROLE_VALUES = [
  "viewer",
  "editor",
] as const;

/** Stage — 14 members. */
export const STAGE_VALUES = [
  "plan",
  "generate",
  "screen",
  "resource_estimate",
  "verify",
  "compile",
  "compiled_resource_estimate",
  "finalize",
  "final_execute",
  "baseline",
  "analyze",
  "save",
  "simulate",
  "export",
] as const;

/** TopLevelExecution — 3 members. */
export const TOP_LEVEL_EXECUTION_VALUES = [
  "required",
  "demo_only",
  "forbidden",
] as const;

/** VerificationFailureClass — 6 members. */
export const VERIFICATION_FAILURE_CLASS_VALUES = [
  "candidate_defect",
  "plan_defect",
  "evidence_gap",
  "capability_limit",
  "verifier_failure",
  "evidence_conflict",
] as const;

/** VerificationMethod — 15 members. */
export const VERIFICATION_METHOD_VALUES = [
  "exact",
  "statistical",
  "statistical_native",
  "brute_force",
  "exact_diag",
  "return_contract",
  "qasm_parse",
  "structural",
  "resource_contract",
  "measurement_policy",
  "success_criteria",
  "native_optimization_evidence",
  "bell_state_property",
  "ghz_state_property",
  "statistical_reproducibility",
] as const;

/** VerificationResultKind — 5 members. */
export const VERIFICATION_RESULT_KIND_VALUES = [
  "pass",
  "fail",
  "skipped",
  "unavailable",
  "error",
] as const;

/** VerifierDecision — 3 members. */
export const VERIFIER_DECISION_VALUES = [
  "pass",
  "fail",
  "inconclusive",
] as const;

/** Visibility — 2 members. */
export const VISIBILITY_VALUES = [
  "private",
  "public",
] as const;

/** WorkspaceKind — 3 members. */
export const WORKSPACE_KIND_VALUES = [
  "personal",
  "team",
  "system",
] as const;
