/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Algorithm
         * @enum {string}
         */
        Algorithm: "VQE" | "QAOA" | "Grover" | "Bell" | "GHZ" | "QFT" | "QPE" | "AmplitudeEstimation" | "StatePreparation" | "CircuitSynthesis" | "GateDecomposition" | "Transpilation" | "Simulation" | "ErrorCorrection" | "other";
        /** Artifact */
        Artifact: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Current Version Id
             * @default null
             */
            current_version_id: string | null;
            /**
             * Deleted At
             * @default null
             */
            deleted_at: string | null;
            /** @default null */
            evidence_strength: components["schemas"]["EvidenceStrength"] | null;
            /**
             * Family
             * @description Algorithm category
             */
            family: string;
            framework: components["schemas"]["Framework"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Parent Artifact Id
             * @description Provenance edge
             * @default null
             */
            parent_artifact_id: string | null;
            /**
             * Slug
             * @description Unique; used for public pages
             */
            slug: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** @default null */
            verifier_decision: components["schemas"]["VerifierDecision"] | null;
            visibility: components["schemas"]["Visibility"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ArtifactContract */
        ArtifactContract: {
            artifact_type: components["schemas"]["ArtifactType"];
            /**
             * Entry Point
             * @description Function/class name to implement, if requested
             * @default null
             */
            entry_point: string | null;
            /**
             * Expected Return Type
             * @description e.g. QuantumCircuit, dict[str, int], Statevector
             * @default null
             */
            expected_return_type: string | null;
            measurement_policy: components["schemas"]["MeasurementPolicy"];
            /**
             * Return Shape
             * @description Structural constraints: keys, array length, bitstring format
             * @default null
             */
            return_shape: string | null;
            top_level_execution: components["schemas"]["TopLevelExecution"];
        };
        /** ArtifactSaved */
        ArtifactSaved: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "artifact.saved";
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version Seq */
            version_seq: number;
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "script" | "function" | "class" | "QuantumCircuit" | "OpenQASM" | "counts" | "statevector" | "operator" | "clifford" | "pass_manager" | "other";
        /** ArtifactVersion */
        ArtifactVersion: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Code */
            code: string;
            /** Code Lang */
            code_lang: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Export Reason
             * @default null
             */
            export_reason: string | null;
            export_status: components["schemas"]["ExportStatus"];
            /**
             * Fingerprint
             * @description Digest of the framework and normalized selected-framework source; identical source may share a fingerprint across artifact versions
             */
            fingerprint: string;
            /**
             * Framework Variants
             * @default null
             */
            framework_variants: {
                [key: string]: string;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Limitations
             * @default null
             */
            limitations: string | null;
            /**
             * Metadata
             * @description Canonical-source role, provenance, and legacy migration data
             * @default null
             */
            metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Qasm
             * @description Optional normalized OpenQASM interchange for framework conversion
             * @default null
             */
            qasm: string | null;
            /**
             * Qasm Version
             * @description Optional OpenQASM interchange version
             * @default null
             */
            qasm_version: "3.0" | null;
            /**
             * Resource Estimates
             * @default null
             */
            resource_estimates: {
                [key: string]: unknown;
            } | null;
            /** Seq */
            seq: number;
        } & unknown;
        /**
         * BaselineKind
         * @enum {string}
         */
        BaselineKind: "maxcut" | "qubo" | "portfolio" | "hamiltonian" | "none";
        /** BaselineResult */
        BaselineResult: {
            kind: components["schemas"]["BaselineKind"];
            /**
             * Not Applicable Reason
             * @default null
             */
            not_applicable_reason: string | null;
            /**
             * Result
             * @default null
             */
            result: {
                [key: string]: unknown;
            } | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "baseline.result";
        };
        /**
         * CatalogProvenance
         * @description How a published catalog entry entered the catalog (repository Step 6).
         *
         *     For the ADR-0019 bootstrap corpus this is the pinned-manifest identity: the
         *     import provider, the manifest's pinned source commit, the per-item manifest
         *     identity, and the content hash of the exact source bytes. It anchors the
         *     entry to reproducible provenance without trusting any field inside `record`.
         */
        CatalogProvenance: {
            /**
             * Import Provider
             * @default null
             */
            import_provider: string | null;
            /**
             * Source Blob Sha256
             * @description sha256 of the exact stored source bytes
             * @default null
             */
            source_blob_sha256: string | null;
            /**
             * Upstream Identity
             * @description Per-item manifest identity; equals the public slug
             * @default null
             */
            upstream_identity: string | null;
            /**
             * Upstream Ref
             * @description Pinned upstream ref (e.g. the manifest source commit)
             * @default null
             */
            upstream_ref: string | null;
        };
        /** ChatCompleted */
        ChatCompleted: {
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Text */
            text: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.completed";
        };
        /**
         * ChatDelta
         * @description A provider-native chat fragment; no stage or output schema is imposed.
         */
        ChatDelta: {
            /**
             * Kind
             * @default output
             * @enum {string}
             */
            kind: "reasoning" | "output";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Text */
            text: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.delta";
        };
        /** ChatError */
        ChatError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.error";
        };
        /** CodeFinalized */
        CodeFinalized: {
            /** Code */
            code: string;
            /** Compilation Applied */
            compilation_applied: boolean;
            /** Conversion Options */
            conversion_options?: string[];
            /** Execution Options */
            execution_options?: ("simulate" | "qpu")[];
            /**
             * Export Reason
             * @default null
             */
            export_reason: string | null;
            export_status: components["schemas"]["ExportStatus"];
            /**
             * Finalization Reason
             * @default null
             */
            finalization_reason: string | null;
            /** Framework Variants */
            framework_variants?: {
                [key: string]: components["schemas"]["CodeVariant"];
            };
            /** Language */
            language: string;
            /** Qpu Available */
            qpu_available: boolean;
            /** Revision */
            revision: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Simulation Plausible */
            simulation_plausible: boolean;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code.finalized";
        };
        /** CodeGenerated */
        CodeGenerated: {
            /** Code */
            code: string;
            /** Language */
            language: string;
            /**
             * Revision
             * @description 1 = first generation; +1 per repair iteration
             */
            revision: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code.generated";
        };
        /**
         * CodeVariant
         * @description A deterministic, copyable selected-framework source variant.
         */
        CodeVariant: {
            /** Code */
            code: string;
            /**
             * Export Reason
             * @default null
             */
            export_reason: string | null;
            export_status: components["schemas"]["ExportStatus"];
            /** Language */
            language: string;
        };
        /** CompilationResult */
        CompilationResult: {
            /** Accepted */
            accepted: boolean;
            /** @default null */
            after: components["schemas"]["ResourceMetrics"] | null;
            /** @default null */
            before: components["schemas"]["ResourceMetrics"] | null;
            /** Compatibility */
            compatibility?: {
                [key: string]: unknown;
            };
            /**
             * Compiled Fingerprint
             * @default null
             */
            compiled_fingerprint: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "not_applicable" | "unchanged" | "transpiled" | "compressed" | "rejected";
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Source Fingerprint
             * @default null
             */
            source_fingerprint: string | null;
            /**
             * Target
             * @default null
             */
            target: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "compilation.result";
        };
        /**
         * EvidenceStrength
         * @description What a passing run's verdict was actually proved by.
         *
         *     Deliberately *not* a fourth VerifierDecision value. A run whose only check was
         *     `return_contract` — "does the result dict have a `counts` key?" — is a real pass:
         *     nothing it claimed was contradicted. It is just not the same claim as a run whose
         *     reported distribution was compared against the circuit's Born distribution to
         *     1.8e-16, and until 2026-07-20 both printed the single word "Verified".
         *
         *     Every consumer compares `verifier_decision == "pass"`, the eval harness included,
         *     so the decision stays `pass` and the strength rides alongside it.
         * @enum {string}
         */
        EvidenceStrength: "physical" | "structural";
        /** ExportClassified */
        ExportClassified: {
            /** Qasm Available */
            qasm_available: boolean;
            /**
             * Reason
             * @description Required when status is lossy_with_reason
             * @default null
             */
            reason: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            status: components["schemas"]["ExportStatus"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "export.classified";
        };
        /**
         * ExportStatus
         * @enum {string}
         */
        ExportStatus: "lossless" | "lossy_with_reason" | "download_only" | "unsupported";
        /**
         * Framework
         * @enum {string}
         */
        Framework: "qiskit" | "pennylane" | "cirq";
        /**
         * LlmCall
         * @description One completed LLM call; every call is logged with token counts (ADR-0009).
         */
        LlmCall: {
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            stage: components["schemas"]["Stage"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "llm.call";
        };
        /**
         * LlmDelta
         * @description Streaming text fragment for live UI rendering; not required for replay
         *     correctness (the terminal events carry the full state).
         */
        LlmDelta: {
            /**
             * Kind
             * @default output
             * @enum {string}
             */
            kind: "reasoning" | "output";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            stage: components["schemas"]["Stage"];
            /** Text */
            text: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "llm.delta";
        };
        /**
         * MeasurementPolicy
         * @enum {string}
         */
        MeasurementPolicy: "none" | "only_if_requested" | "measure_all" | "specified" | "not_applicable";
        /**
         * Optimizer
         * @enum {string}
         */
        Optimizer: "COBYLA" | "SPSA" | "L_BFGS_B";
        /** Plan */
        Plan: {
            algorithm: components["schemas"]["Algorithm"];
            /** Algorithm Rationale */
            algorithm_rationale: string;
            /** @default null */
            artifact_contract: components["schemas"]["ArtifactContract"] | null;
            /**
             * Domain
             * @description Problem domain: chemistry, finance, ...
             */
            domain: string;
            /**
             * Expected Output Keys
             * @description Keys the executed code prints in its result dict
             */
            expected_output_keys: string[];
            /** Expected Runtime Sec */
            expected_runtime_sec: number;
            framework: components["schemas"]["Framework"];
            parameters: components["schemas"]["PlanParameters"];
            /** Problem Summary */
            problem_summary: string;
            /**
             * Qubits Estimate
             * @description Planned qubit count; 27 is the default sandbox lane ceiling
             */
            qubits_estimate: number;
            success_criteria: components["schemas"]["SuccessCriteria"];
            /** @default null */
            verification_plan: components["schemas"]["VerificationPlan"] | null;
        };
        /** PlanParameters */
        PlanParameters: {
            /**
             * Custom
             * @description Domain-specific free parameters, e.g. {molecule: 'H2', bond_length: 0.735}
             * @default null
             */
            custom: {
                [key: string]: unknown;
            } | null;
            /**
             * Max Iterations
             * @default null
             */
            max_iterations: number | null;
            /** @default null */
            optimizer: components["schemas"]["Optimizer"] | null;
            /**
             * Seed
             * @description Random seed for sampling. When present, the generated code must seed the framework's sampler with exactly this value so the run reproduces.
             * @default null
             */
            seed: number | null;
            /**
             * Shots
             * @default null
             */
            shots: number | null;
        };
        /** PlanProduced */
        PlanProduced: {
            plan: components["schemas"]["Plan"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "plan.produced";
        };
        /**
         * PublicCatalogEntry
         * @description A published catalog record served to anonymous readers (repository Step 6).
         *
         *     The typed fields are database-authoritative facts: the stable public `slug`
         *     (the pinned manifest identity), the honest `execution_state`, the update
         *     timestamp, and reproducible `provenance`. `record` carries the pinned
         *     catalog source blob verbatim — the rich presentation entry (algorithm
         *     family, category, classical comparisons, verification prose, code variants,
         *     localized copy). Everything in `record` is *asserted catalog metadata from
         *     the pinned source*, NOT passing-run evidence or legal approval (ADR-0019);
         *     clients must render it as a claim. Only accepted+public records are returned.
         */
        PublicCatalogEntry: {
            /**
             * Execution State
             * @description Authoritative honest lifecycle state; the bootstrap corpus is template_only
             */
            execution_state: string;
            /** @default null */
            provenance: components["schemas"]["CatalogProvenance"] | null;
            /**
             * Record
             * @description Pinned catalog source record (the rich presentation entry). A source claim from the pinned manifest, not execution evidence or legal approval.
             * @default null
             */
            record: {
                [key: string]: unknown;
            } | null;
            /**
             * Slug
             * @description Stable public identity (pinned manifest identity)
             */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * QasmEmission
         * @description Provenance for optional OpenQASM interchange from a protected sandbox result.
         *
         *     ``sandbox_epilogue`` is Majorana's observed serialization of ``FINAL_CIRCUIT``;
         *     ``model_stdout`` is retained only for replaying legacy events.
         */
        QasmEmission: {
            /** Available */
            available: boolean;
            /** Epilogue Applied */
            epilogue_applied: boolean;
            /**
             * Epilogue Error
             * @description Exception type only; raw sandbox exception text is never persisted here.
             * @default null
             */
            epilogue_error: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sandbox_epilogue" | "model_stdout" | "missing";
        };
        /**
         * ResearchCitation
         * @description A bounded public reference shown as provenance for the planning decision.
         */
        ResearchCitation: {
            /** Excerpt */
            excerpt: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ResearchCompleted */
        ResearchCompleted: {
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Query */
            query: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Sources */
            sources?: components["schemas"]["ResearchCitation"][];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "research.completed";
        };
        /** ResourceEstimateResult */
        ResourceEstimateResult: {
            metrics: components["schemas"]["ResourceMetrics"];
            /** Notes */
            notes?: string[];
            /**
             * Phase
             * @enum {string}
             */
            phase: "pre_verify" | "compiled";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Source
             * @enum {string}
             */
            source: "plan_static" | "openqasm" | "compiler";
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resource.estimate";
        };
        /**
         * ResourceMetrics
         * @description Comparable circuit-resource measurements for selected-framework source.
         */
        ResourceMetrics: {
            /**
             * Depth
             * @default null
             */
            depth: number | null;
            /**
             * Estimated Runtime Ms
             * @default null
             */
            estimated_runtime_ms: number | null;
            /**
             * Gate Count
             * @default null
             */
            gate_count: number | null;
            /**
             * Measurement Count
             * @default null
             */
            measurement_count: number | null;
            /** Qubits */
            qubits: number;
            /**
             * Two Qubit Gate Count
             * @default null
             */
            two_qubit_gate_count: number | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /** Run */
        Run: {
            /**
             * Artifact Version Id
             * @default null
             */
            artifact_version_id: string | null;
            /**
             * Baseline
             * @description Baseline result, or {not_applicable_reason}
             * @default null
             */
            baseline: {
                [key: string]: unknown;
            } | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finished At
             * @default null
             */
            finished_at: string | null;
            /**
             * Folder Id
             * @default null
             */
            folder_id: string | null;
            framework: components["schemas"]["Framework"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            mode: components["schemas"]["RunMode"];
            /**
             * Residual Risks
             * @default null
             */
            residual_risks: string | null;
            /**
             * Sandbox Meta
             * @description Duration, memory, exit code as reported by the provider
             * @default null
             */
            sandbox_meta: {
                [key: string]: unknown;
            } | null;
            /**
             * Sandbox Provider
             * @default null
             */
            sandbox_provider: string | null;
            /**
             * Seed
             * @default null
             */
            seed: number | null;
            /**
             * Shots
             * @default null
             */
            shots: number | null;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Task Prompt */
            task_prompt: string;
            /**
             * Timeout S
             * @default null
             */
            timeout_s: number | null;
            /**
             * Tolerances
             * @default null
             */
            tolerances: {
                [key: string]: number;
            } | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** @default null */
            verifier_decision: components["schemas"]["VerifierDecision"] | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** RunAnalysis */
        RunAnalysis: {
            /** Comparison */
            comparison?: {
                [key: string]: unknown;
            };
            /** Interpretation */
            interpretation: string;
            /**
             * Residual Risks
             * @default null
             */
            residual_risks: string | null;
            /** Results */
            results?: {
                [key: string]: unknown;
            };
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Summary */
            summary: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.analysis";
        };
        /**
         * RunBestEffort
         * @description The best candidate a run produced when it ended without one passing
         *     verification.
         *
         *     Emitted instead of nothing. The loop pays for up to four candidates, ranks them
         *     against each other nowhere, and used to end a spent budget with a bare failure —
         *     the worst possible output for a user who waited. This carries the code anyway,
         *     with the evidence that stopped it.
         *
         *     Budget exhaustion is the case it was built for, but it is emitted on any agent
         *     failure that left candidates behind: a run that died some other way still leaves
         *     the user with the same nothing. `exhausted_budget` is therefore nullable and
         *     carries whatever the runtime recorded, which is not always a budget.
         *
         *     It is deliberately NOT an artifact and never becomes one: `verified` is a literal
         *     False, publication still requires a verification PASS, and nothing here is
         *     written to the Vault. The event says "this is the closest we got, and here is
         *     exactly what is wrong with it", which is a different claim from "this works".
         */
        RunBestEffort: {
            /** Candidates Considered */
            candidates_considered: number;
            /** Code */
            code: string;
            /**
             * Critic Summary
             * @default null
             */
            critic_summary: string | null;
            /**
             * Exhausted Budget
             * @description Why the loop gave up, usually a budget, e.g. candidate_budget_exhausted. Null when the runtime recorded no reason.
             * @default null
             */
            exhausted_budget: string | null;
            /** Failed Checks */
            failed_checks?: string[];
            /** Language */
            language: string;
            /** Residual Risks */
            residual_risks?: string[];
            /** Revision */
            revision: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.best_effort";
            /**
             * Verified
             * @default false
             * @constant
             */
            verified: false;
        };
        /** RunDiagnosed */
        RunDiagnosed: {
            /** Attempt */
            attempt: number;
            /** Code */
            code: string;
            failed_stage: components["schemas"]["Stage"];
            /** Message */
            message: string;
            /** @default null */
            restart_from: components["schemas"]["Stage"] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.diagnosed";
        };
        /** RunErrorEvent */
        RunErrorEvent: {
            /**
             * Code
             * @description Machine-readable error code (RFC 9457 style)
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** @default null */
            stage: components["schemas"]["Stage"] | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.error";
        };
        /**
         * RunEvent
         * @description Discriminated union of all run event types (class name sets the schema id).
         */
        RunEvent: components["schemas"]["RunQueued"] | components["schemas"]["RunStarted"] | components["schemas"]["RunModeResolved"] | components["schemas"]["StageStarted"] | components["schemas"]["StageFinished"] | components["schemas"]["PlanProduced"] | components["schemas"]["ResearchCompleted"] | components["schemas"]["LlmCall"] | components["schemas"]["LlmDelta"] | components["schemas"]["ChatDelta"] | components["schemas"]["ChatCompleted"] | components["schemas"]["ChatError"] | components["schemas"]["CodeGenerated"] | components["schemas"]["ScreenResult"] | components["schemas"]["ResourceEstimateResult"] | components["schemas"]["CompilationResult"] | components["schemas"]["CodeFinalized"] | components["schemas"]["SandboxResult"] | components["schemas"]["VerificationResult"] | components["schemas"]["BaselineResult"] | components["schemas"]["ExportClassified"] | components["schemas"]["ArtifactSaved"] | components["schemas"]["RunAnalysis"] | components["schemas"]["RunDiagnosed"] | components["schemas"]["RunRestarted"] | components["schemas"]["RunBestEffort"] | components["schemas"]["RunErrorEvent"] | components["schemas"]["RunFinished"];
        /** RunFinished */
        RunFinished: {
            /** @default null */
            evidence_strength: components["schemas"]["EvidenceStrength"] | null;
            /**
             * Residual Risks
             * @default null
             */
            residual_risks: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            status: components["schemas"]["RunStatus"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.finished";
            /** @default null */
            verifier_decision: components["schemas"]["VerifierDecision"] | null;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "auto" | "chat" | "execute" | "ideate" | "explain";
        /**
         * RunModeResolved
         * @description How a run's requested mode became the mode it actually ran in.
         *
         *     Emitted whenever the worker's intent router had a say — including when it
         *     left the requested mode alone. Without this the resolution is invisible: a
         *     "hi" that quietly answered as chat and a quantum task that quietly skipped
         *     the pipeline look identical from the outside.
         */
        RunModeResolved: {
            /** Reason */
            reason: string;
            requested: components["schemas"]["RunMode"];
            resolved: components["schemas"]["RunMode"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Source
             * @enum {string}
             */
            source: "passthrough" | "heuristic" | "classifier" | "fallback";
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.mode_resolved";
        };
        /** RunQueued */
        RunQueued: {
            framework: components["schemas"]["Framework"];
            mode: components["schemas"]["RunMode"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.queued";
        };
        /** RunRestarted */
        RunRestarted: {
            /** Attempt */
            attempt: number;
            from_stage: components["schemas"]["Stage"];
            /** Reason */
            reason: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.restarted";
        };
        /** RunStarted */
        RunStarted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** SandboxResult */
        SandboxResult: {
            /** Duration Ms */
            duration_ms: number;
            /** Exit Code */
            exit_code: number;
            /**
             * Memory Mb
             * @default null
             */
            memory_mb: number | null;
            /**
             * Phase
             * @default verification
             * @enum {string}
             */
            phase: "verification" | "final";
            /** @default null */
            qasm_emission: components["schemas"]["QasmEmission"] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /** Stderr */
            stderr: string;
            /** Stdout */
            stdout: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sandbox.result";
        };
        /** Scope */
        Scope: {
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ScreenResult */
        ScreenResult: {
            /** Diagnostics */
            diagnostics?: string[];
            /** Lint Ok */
            lint_ok: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "screen.result";
            /** Typecheck Ok */
            typecheck_ok: boolean;
        };
        /**
         * Stage
         * @description Pipeline stages in execution order; the orchestrator owns transitions.
         * @enum {string}
         */
        Stage: "plan" | "generate" | "screen" | "resource_estimate" | "verify" | "compile" | "compiled_resource_estimate" | "finalize" | "final_execute" | "baseline" | "analyze" | "save" | "simulate" | "export";
        /** StageFinished */
        StageFinished: {
            /** Duration Ms */
            duration_ms: number;
            /** Ok */
            ok: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            stage: components["schemas"]["Stage"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage.finished";
        };
        /** StageStarted */
        StageStarted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            stage: components["schemas"]["Stage"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage.started";
        };
        /** SuccessCriteria */
        SuccessCriteria: {
            /**
             * Additional Notes
             * @default null
             */
            additional_notes: string[] | null;
            /**
             * Expected Range
             * @description Bound on primary_metric's value, checked with the literal keys "min" and/or "max", e.g. {"min": 0.99} or {"min": 0.0, "max": 0.15}. Either key may be omitted to leave that side unbounded; any other key is ignored by the evaluator, so do not invent named bounds.
             * @default null
             */
            expected_range: {
                [key: string]: number;
            } | null;
            /**
             * Primary Metric
             * @description Key extracted from the run's result dict, e.g. ground_state_energy_Ha
             */
            primary_metric: string;
        };
        /**
         * TopLevelExecution
         * @enum {string}
         */
        TopLevelExecution: "required" | "demo_only" | "forbidden";
        /**
         * VerificationMethod
         * @enum {string}
         */
        VerificationMethod: "exact" | "statistical" | "statistical_native" | "brute_force" | "exact_diag" | "return_contract" | "qasm_parse";
        /** VerificationPlan */
        VerificationPlan: {
            /**
             * Expected Metrics
             * @description Metrics the verification result dict must contain
             * @default null
             */
            expected_metrics: string[] | null;
            /**
             * Feedback Policy
             * @description What to minimally fix and re-verify on failure
             * @default null
             */
            feedback_policy: string | null;
            /**
             * Forbidden Operations
             * @description APIs/side effects the code must not use
             * @default null
             */
            forbidden_operations: string[] | null;
            /**
             * Methods
             * @description Verification primitives to run against the generated code
             */
            methods: ("exact" | "statistical" | "return_contract")[];
            /**
             * Reference Method
             * @description Independent reference, e.g. exact diagonalization
             * @default null
             */
            reference_method: string | null;
            /**
             * Reference Qasm
             * @description OpenQASM 2 or 3 source for the circuit the generated code must match, required when reference_source is 'plan_declared'. Write the canonical textbook construction, not a copy of the code you expect. Measurements are ignored: only the unitary is compared.
             * @default null
             */
            reference_qasm: string | null;
            /**
             * Reference Source
             * @description Where the 'exact' check gets the circuit it compares against. 'plan_declared' means you supply reference_qasm below. 'parent_artifact' means the already-verified circuit this run revises is the reference — choose it only when the request is to optimize, transpile, or refactor that circuit WITHOUT changing what it computes, and only when you were told this run has a parent artifact.
             * @default null
             */
            reference_source: ("plan_declared" | "parent_artifact") | null;
            /**
             * Required Invariants
             * @description Invariants that must survive any repair iteration
             * @default null
             */
            required_invariants: string[] | null;
            /**
             * Thresholds
             * @description Pass thresholds per metric, e.g. {fidelity_min: 0.999}
             * @default null
             */
            thresholds: {
                [key: string]: number;
            } | null;
        };
        /** VerificationRecord */
        VerificationRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            method: components["schemas"]["VerificationMethod"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
            result: components["schemas"]["VerificationResultKind"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** VerificationResult */
        VerificationResult: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            method: components["schemas"]["VerificationMethod"];
            result: components["schemas"]["VerificationResultKind"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Seq
             * @description Unique per run; powers replay and SSE Last-Event-ID
             */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "verification.result";
        };
        /**
         * VerificationResultKind
         * @description PASS and FAIL are judgements about the code. SKIPPED is not a judgement at
         *     all: the check was incapable of evaluating this circuit (e.g. the statistical
         *     check's statevector path against a circuit with mid-circuit measurement and
         *     classical control flow — production run 019f7e46-d688), so it produced no
         *     evidence in either direction. A skipped check never blocks a candidate and
         *     never lifts `evidence_strength_of` — a run whose only physical check was
         *     skipped passes as `structural`, which states exactly what was proved.
         * @enum {string}
         */
        VerificationResultKind: "pass" | "fail" | "skipped";
        /**
         * VerifierDecision
         * @enum {string}
         */
        VerifierDecision: "pass" | "fail" | "inconclusive";
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "private" | "public";
        /** Workspace */
        Workspace: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Deleted At
             * @default null
             */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["WorkspaceKind"];
            /** Name */
            name: string;
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /** Plan */
            plan: string;
        };
        /** WorkspaceFolder */
        WorkspaceFolder: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * WorkspaceKind
         * @enum {string}
         */
        WorkspaceKind: "personal" | "team" | "system";
        /** WorkspaceMember */
        WorkspaceMember: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Display Name
             * @default null
             */
            display_name: string | null;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** WorkspaceOverview */
        WorkspaceOverview: {
            /** Artifact Count */
            artifact_count: number;
            /** Members */
            members: components["schemas"]["WorkspaceMember"][];
            /** Run Count */
            run_count: number;
            workspace: components["schemas"]["Workspace"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
