"""Persistence protocol used by the runtime and tool broker."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from majorana_agent.models import (
    AgentState,
    CandidateRevision,
    ConversionEvidence,
    ExecutionEvidence,
    PlanRevision,
    PlanRecord,
    PublishedArtifact,
    SemanticReviewEvidence,
    StrictVerificationAttempt,
    ToolCall,
    ToolResult,
    VerificationEvidence,
)


class AgentStore(Protocol):
    async def state(self, run_id: UUID) -> AgentState: ...

    async def set_state(self, run_id: UUID, state: AgentState) -> None: ...

    async def completed_tool_call(self, run_id: UUID, tool_call_id: str) -> ToolResult | None: ...

    async def tool_call(self, run_id: UUID, tool_call_id: str) -> ToolCall | None: ...

    async def begin_tool_call(self, run_id: UUID, call: ToolCall) -> None: ...

    async def finish_tool_call(self, run_id: UUID, result: ToolResult) -> None: ...

    async def list_tool_results(self, run_id: UUID) -> list[ToolResult]: ...

    async def add_plan(self, record: PlanRecord) -> None: ...

    async def plan(self, run_id: UUID, plan_id: UUID) -> PlanRecord: ...

    async def latest_plan(self, run_id: UUID) -> PlanRecord | None: ...

    async def append_plan_revision(self, record: PlanRevision) -> None: ...

    async def plan_revision(self, run_id: UUID, plan_id: UUID) -> PlanRevision: ...

    async def current_plan_revision(self, run_id: UUID) -> PlanRevision | None: ...

    async def select_current_plan(self, run_id: UUID, plan_id: UUID) -> None: ...

    async def add_candidate(self, candidate: CandidateRevision) -> None: ...

    async def set_candidate_status(self, run_id: UUID, candidate_id: UUID, status: str) -> None: ...

    async def candidate(self, run_id: UUID, candidate_id: UUID) -> CandidateRevision: ...

    async def candidate_for_tool_call(
        self, run_id: UUID, tool_call_id: str
    ) -> CandidateRevision | None: ...

    async def latest_candidate(self, run_id: UUID) -> CandidateRevision | None: ...

    async def list_candidates(self, run_id: UUID) -> list[CandidateRevision]: ...

    async def add_execution(self, evidence: ExecutionEvidence) -> None: ...

    async def execution_for(self, run_id: UUID, candidate_id: UUID) -> ExecutionEvidence | None: ...

    async def add_verification(self, evidence: VerificationEvidence) -> None: ...

    async def verification_for(
        self, run_id: UUID, candidate_id: UUID
    ) -> VerificationEvidence | None: ...

    async def append_semantic_review(self, evidence: SemanticReviewEvidence) -> None: ...

    async def latest_semantic_review(
        self, run_id: UUID, candidate_id: UUID
    ) -> SemanticReviewEvidence | None: ...

    async def append_strict_verification(self, attempt: StrictVerificationAttempt) -> None: ...

    async def latest_strict_verification(
        self, run_id: UUID, candidate_id: UUID
    ) -> StrictVerificationAttempt | None: ...

    async def add_conversion(self, evidence: ConversionEvidence) -> None: ...

    async def conversion_for(
        self, run_id: UUID, candidate_id: UUID
    ) -> ConversionEvidence | None: ...

    async def add_publication(self, publication: PublishedArtifact) -> None: ...

    async def publication_for(
        self, run_id: UUID, candidate_id: UUID
    ) -> PublishedArtifact | None: ...
