"""majorana-contracts: source of truth for every cross-boundary type (ADR-0008).
Pydantic models → OpenAPI (openapi.json) → generated TS (packages/ts/contracts-gen)."""

from .enums import (
    Algorithm,
    ArtifactType,
    BaselineKind,
    ExportStatus,
    Framework,
    JobStatus,
    MeasurementPolicy,
    Optimizer,
    Role,
    RunMode,
    RunStatus,
    Stage,
    TopLevelExecution,
    UsageKind,
    VerificationMethod,
    VerificationResultKind,
    VerifierDecision,
    Visibility,
    WorkspaceKind,
)
from .events import (
    ArtifactSaved,
    BaselineResult,
    CodeGenerated,
    ExportClassified,
    LlmCall,
    LlmDelta,
    PlanProduced,
    RunErrorEvent,
    RunEvent,
    RunFinished,
    RunQueued,
    RunStarted,
    SandboxResult,
    StageFinished,
    StageStarted,
    VerificationResult,
    run_event_adapter,
)
from .models import Artifact, ArtifactVersion, Run, VerificationRecord, Workspace
from .plan import (
    ArtifactContract,
    BaselinePlan,
    Plan,
    PlanParameters,
    SuccessCriteria,
    VerificationPlan,
)
from .scope import Scope

CONTRACTS_VERSION = "1.0.0"

__all__ = [
    "CONTRACTS_VERSION",
    "Algorithm",
    "Artifact",
    "ArtifactContract",
    "ArtifactSaved",
    "ArtifactType",
    "ArtifactVersion",
    "BaselineKind",
    "BaselinePlan",
    "BaselineResult",
    "CodeGenerated",
    "ExportClassified",
    "ExportStatus",
    "Framework",
    "JobStatus",
    "LlmCall",
    "LlmDelta",
    "MeasurementPolicy",
    "Optimizer",
    "Plan",
    "PlanParameters",
    "PlanProduced",
    "Role",
    "Run",
    "RunErrorEvent",
    "RunEvent",
    "RunFinished",
    "RunMode",
    "RunQueued",
    "RunStarted",
    "RunStatus",
    "SandboxResult",
    "Scope",
    "Stage",
    "StageFinished",
    "StageStarted",
    "SuccessCriteria",
    "TopLevelExecution",
    "UsageKind",
    "VerificationMethod",
    "VerificationPlan",
    "VerificationRecord",
    "VerificationResult",
    "VerificationResultKind",
    "VerifierDecision",
    "Visibility",
    "Workspace",
    "WorkspaceKind",
    "run_event_adapter",
]
