"""majorana-contracts: source of truth for every cross-boundary type (ADR-0008).
Pydantic models → OpenAPI (openapi.json) → generated TS (packages/ts/contracts-gen)."""

from .enums import (
    Algorithm,
    ArtifactKind,
    ArtifactType,
    BaselineKind,
    CitationRelation,
    ExecutionState,
    ExportStatus,
    Framework,
    ImportItemState,
    ImportJobStatus,
    ImportProvider,
    JobStatus,
    LicenseAssertionKind,
    LicenseDecision,
    LicenseScope,
    MeasurementPolicy,
    Optimizer,
    PlannableVerificationMethod,
    PublicationState,
    ReviewState,
    Role,
    RunMode,
    RunStatus,
    SourceKind,
    Stage,
    TopLevelExecution,
    UsageKind,
    VerificationMethod,
    VerificationResultKind,
    VerifierDecision,
    Visibility,
    WorkspaceKind,
)
from .events import (
    ArtifactSaved,
    BaselineResult,
    CodeFinalized,
    CodeVariant,
    CodeGenerated,
    CompilationResult,
    ChatCompleted,
    ChatDelta,
    ChatError,
    ExportClassified,
    LlmCall,
    LlmDelta,
    PlanProduced,
    QasmEmission,
    ResearchCitation,
    ResearchCompleted,
    RunErrorEvent,
    RunEvent,
    RunAnalysis,
    RunDiagnosed,
    RunFinished,
    RunQueued,
    RunRestarted,
    RunStarted,
    SandboxResult,
    ResourceEstimateResult,
    ScreenResult,
    StageFinished,
    StageStarted,
    VerificationResult,
    run_event_adapter,
)
from .models import (
    Artifact,
    ArtifactVersion,
    CatalogProvenance,
    PublicCatalogEntry,
    ResourceMetrics,
    Run,
    VerificationRecord,
    Workspace,
    Conversation,
    ConversationTurn,
    WorkspaceFolder,
    WorkspaceMember,
    WorkspaceOverview,
)
from .plan import (
    ArtifactContract,
    Plan,
    PlanParameters,
    SuccessCriteria,
    VerificationPlan,
)
from .scope import Scope
from .lifecycle import (
    IllegalImportItemTransition,
    IllegalPublicationTransition,
    IllegalReviewTransition,
    IllegalTransition,
    IMPORT_ITEM_TERMINAL_STATES,
    TERMINAL_STATUSES,
    assert_import_item_transition,
    assert_publication_transition,
    assert_review_transition,
    assert_transition,
    is_terminal,
)

# Versioning convention (see AGENTS.md "Versioning"): backward-compatible
# additions (new enum values, new models, new optional fields) bump minor;
# breaking changes bump major. Bump lands in the same PR as the change.
# 1.1.0: Steps 2-5a additions — WorkspaceKind "system"; ArtifactKind /
# ExecutionState / ReviewState / PublicationState; review + import-item
# lifecycles; ImportProvider / ImportJobStatus / ImportItemState.
# 1.2.0: Step 6 (Neon cutover Slice C) — PublicCatalogEntry / CatalogProvenance
# response models; publication-state lifecycle (assert_publication_transition).
CONTRACTS_VERSION = "1.2.0"

__all__ = [
    "CONTRACTS_VERSION",
    "Algorithm",
    "Artifact",
    "ArtifactContract",
    "ArtifactKind",
    "ArtifactSaved",
    "ArtifactType",
    "ArtifactVersion",
    "BaselineKind",
    "BaselineResult",
    "CatalogProvenance",
    "CodeFinalized",
    "CodeVariant",
    "CodeGenerated",
    "CompilationResult",
    "ChatCompleted",
    "ChatDelta",
    "ChatError",
    "CitationRelation",
    "ExecutionState",
    "ExportClassified",
    "ExportStatus",
    "Framework",
    "ImportItemState",
    "ImportJobStatus",
    "ImportProvider",
    "IMPORT_ITEM_TERMINAL_STATES",
    "JobStatus",
    "IllegalImportItemTransition",
    "IllegalPublicationTransition",
    "IllegalReviewTransition",
    "IllegalTransition",
    "LicenseAssertionKind",
    "LicenseDecision",
    "LicenseScope",
    "LlmCall",
    "LlmDelta",
    "MeasurementPolicy",
    "Optimizer",
    "Plan",
    "PlanParameters",
    "PlanProduced",
    "PublicCatalogEntry",
    "PlannableVerificationMethod",
    "PublicationState",
    "QasmEmission",
    "ResearchCitation",
    "ResearchCompleted",
    "ReviewState",
    "Role",
    "Run",
    "RunErrorEvent",
    "RunEvent",
    "RunAnalysis",
    "RunDiagnosed",
    "RunFinished",
    "RunMode",
    "RunQueued",
    "RunRestarted",
    "RunStarted",
    "RunStatus",
    "SandboxResult",
    "ResourceEstimateResult",
    "ResourceMetrics",
    "ScreenResult",
    "Scope",
    "SourceKind",
    "Stage",
    "StageFinished",
    "StageStarted",
    "SuccessCriteria",
    "TopLevelExecution",
    "TERMINAL_STATUSES",
    "UsageKind",
    "VerificationMethod",
    "VerificationPlan",
    "VerificationRecord",
    "VerificationResult",
    "VerificationResultKind",
    "VerifierDecision",
    "Visibility",
    "Workspace",
    "Conversation",
    "ConversationTurn",
    "WorkspaceFolder",
    "WorkspaceMember",
    "WorkspaceOverview",
    "WorkspaceKind",
    "run_event_adapter",
    "assert_import_item_transition",
    "assert_publication_transition",
    "assert_review_transition",
    "assert_transition",
    "is_terminal",
]
