"""A course: many notebooks as one plan, from one prompt.

`curriculum.py` builds a repository from `.nb.py` sources somebody authored. This
module is the other half — it turns a **generated** `CoursePlan` into exactly the
source tree `build_curriculum` expects, so the product's own courses and the
hand-authored Quanmatic curriculum go through one builder rather than two.

What lives here:

- `plan_prompt` / `revise_plan_prompt` — what the planner model is told. The
  framework facts are IMPORTED from `prompts.py`, never restated: a second copy is a
  second thing to get wrong, and a wrong framework fact ships a failing cell to every
  reader.
- `check_plan` — the failable checks on a returned plan, as readable sentences the
  worker can hand straight back to the model on its one retry.
- `course_to_curriculum_sources` / `export_course_zip` — the plan plus its generated
  notebooks, rendered as a curriculum source tree and zipped through
  `build_curriculum`.
- `COURSE_STARTERS` — starting points the composer offers before the reader types.

The one thing a module's `brief` must do, and the reason it is repeated in three
places below: a module is generated by `notebook.generate` ALONE, with no sight of
its siblings. Everything the notebook needs to know about what came before has to be
inside its own brief.
"""

from __future__ import annotations

import io
import json
import tempfile
import zipfile
from pathlib import Path

import yaml

from majorana_contracts.courses import (
    MAX_COURSE_MODULES,
    MAX_MODULE_MINUTES,
    CoursePlan,
    PlannedModule,
)

from leona_notebooks.curriculum import build_curriculum
from leona_notebooks.source import render_source
from leona_notebooks.spec import Audience, Framework, NotebookKind, NotebookSpec, Style

__all__ = [
    "COURSE_STARTERS",
    "PLAN_SYSTEM_PROMPT",
    "REVISE_PLAN_SYSTEM_PROMPT",
    "check_plan",
    "course_to_curriculum_sources",
    "export_course_zip",
    "plan_prompt",
    "revise_plan_prompt",
]

#: One `.nb.py` file per module, named for the module's kind. Kinds outside this map
#: are authored as a lesson file — the kind still rides in the source's YAML header,
#: so `build_curriculum` compiles the right builds either way; only the filename is
#: normalised.
_FILENAME_FOR_KIND: dict[NotebookKind, str] = {
    NotebookKind.LAB: "lab",
    NotebookKind.LESSON: "lesson",
    NotebookKind.CHALLENGE: "challenge",
    NotebookKind.QUIZ: "quiz",
    NotebookKind.DEMO: "demo",
    NotebookKind.WALKTHROUGH: "walkthrough",
    NotebookKind.HARDWARE: "hardware",
    NotebookKind.BENCHMARK: "benchmark",
    NotebookKind.PROJECT: "project",
}


def module_filename(kind: NotebookKind) -> str:
    """The `.nb.py` filename a module of this kind is authored as."""
    return f"{_FILENAME_FOR_KIND.get(kind, 'lesson')}.nb.py"


# --------------------------------------------------------------------------- planning


PLAN_SYSTEM_PROMPT = """\
You are Nala, Leona Quantum's teaching assistant. You plan whole COURSES: an ordered
sequence of Jupyter notebooks that takes one reader from where they are to what they
asked to be able to do. Return JSON only — one `CoursePlan` object, nothing else.

What a good plan is:
1. Ordered by dependency, not by topic tidiness. Module N may assume only what modules
   1..N-1 established, and says so in `prerequisites`.
2. Each module is ONE sitting: a single notebook a reader finishes in the time given.
   If an idea does not fit in one, split it across two modules rather than compressing it.
3. Each module ends with something that runs — a `deliverable` the reader can point at.
4. The reader's own preferences (level, analogies, maths, language, framework, how long,
   which topics) are requirements. Honour them; where you cannot, say so in the summary.
5. Later modules revisit earlier ones deliberately: the plan should say, in a module's
   brief, what the reader already built that this module extends.

The `brief` field is the load-bearing one. Each module's brief is handed ON ITS OWN to
a notebook generator that cannot see the other modules and has never read this plan. So
every brief must be self-contained: what to teach, for whom, at what level, what the
reader ALREADY established in the earlier modules (name them and what they built), what
this notebook must end with, and anything to avoid because a later module owns it. Write
it as an instruction to the generator, not as a description of the module.

Never invent a citation. Never plan a module that needs credentials, the network, or
more than about 60 seconds of CPU per notebook — a hardware module ships credential-free
cells the reader runs where their own account lives.
"""


REVISE_PLAN_SYSTEM_PROMPT = """\
You are Nala, editing a course plan with its reader in a chat. You are given the current
plan and the reader's message. Return JSON only, with three keys:

  {"reply": "<what you say to the reader>",
   "summary": "<one line naming the change>",
   "plan": <a complete CoursePlan object>}

Return the WHOLE plan every time, not a patch — plans are small. The rules that make the
rewrite safe:

- **Keep the slug of every module the reader did not ask you to change, byte-identical.**
  A module whose slug survives keeps the notebook already generated for it; a module
  whose slug changes is treated as a new module and loses that work. Never renumber or
  re-slug modules just because their position moved.
- Give a genuinely new module a new slug that does not collide with any existing one.
- Keep `prerequisites` pointing only at modules that come EARLIER in the returned order.
- Keep every brief self-contained, and update the briefs of any modules whose earlier
  context changed because of this edit.
- If the request would break the course (a module that now depends on one you removed),
  say so in `reply` and make the nearest sound change you can.
- If the message is a question rather than an edit, answer it in `reply` and return the
  current plan unchanged.
"""


def _plan_json_schema() -> str:
    return json.dumps(CoursePlan.model_json_schema(), ensure_ascii=False)


def _framework_facts(framework: Framework | None) -> str:
    """The verified framework-facts block, imported from `prompts.py` rather than
    restated. `prompts` imports nothing from this module, so there is no cycle."""
    from leona_notebooks.prompts import FRAMEWORK_FACTS

    name = (framework or Framework()).name
    return FRAMEWORK_FACTS.get(name, "")


def _kinds_text() -> str:
    from leona_notebooks.templates import KIND_DESCRIPTIONS

    return "\n".join(f"- {kind.value}: {text}" for kind, text in KIND_DESCRIPTIONS.items())


def plan_prompt(
    *,
    brief: str,
    audience: Audience | None = None,
    style: Style | None = None,
    framework: Framework | None = None,
    module_count: int | None = None,
    response_locale: str = "en",
    seed_material: str = "",
) -> tuple[str, str]:
    """`(system, user)` for the course-planning call.

    `module_count` of `None` leaves the length to the planner within the cap; a
    number asks for exactly that many, which is what a reader who typed "an
    eight-week course" means.
    """
    length = (
        f"Plan EXACTLY {module_count} modules."
        if module_count is not None
        else (
            "Choose the number of modules the brief actually needs — as few as 2, never "
            f"more than {MAX_COURSE_MODULES}. A short ask gets a short course."
        )
    )
    payload = {
        "brief": brief,
        "audience": (audience or Audience()).model_dump(),
        "style": (style or Style()).model_dump(),
        "framework": (framework or Framework()).model_dump(),
        "response_language": response_locale,
        "module_count": module_count,
    }
    user = "\n\n".join(
        part
        for part in [
            "READER'S BRIEF (their own words):\n" + brief,
            "READER'S PREFERENCES (JSON):\n" + json.dumps(payload, ensure_ascii=False, indent=2),
            (
                "SEED MATERIAL (verbatim — cite it, never invent beyond it):\n" + seed_material
                if seed_material
                else ""
            ),
            "LENGTH:\n" + length,
            "NOTEBOOK KINDS you may give a module:\n" + _kinds_text(),
            "FRAMEWORK FACTS (a module must be plannable against these):\n"
            + _framework_facts(framework),
            (
                "OUTPUT: one JSON object matching this schema and nothing else.\n"
                "COURSE PLAN JSON SCHEMA:\n" + _plan_json_schema()
            ),
            (
                "Every module's `slug` is lowercase letters, digits and hyphens "
                "(e.g. `week-01-circuits`). Each `duration_minutes` is between 1 and "
                f"{MAX_MODULE_MINUTES}. Write `title`, `summary`, `topic`, `objectives`, "
                "`deliverable` and every `brief` in "
                f"{'Japanese (です・ます体)' if response_locale == 'ja' else 'English'}."
            ),
        ]
        if part
    )
    return PLAN_SYSTEM_PROMPT, user


def revise_plan_prompt(
    current_plan: CoursePlan,
    message: str,
    *,
    response_locale: str = "en",
    framework: Framework | None = None,
) -> tuple[str, str]:
    """`(system, user)` for a chat revision of the plan (not of any notebook)."""
    generated = [m.slug for m in current_plan.modules]
    user = "\n\n".join(
        [
            "CURRENT PLAN (JSON):\n" + current_plan.model_dump_json(indent=2),
            "MODULE SLUGS IN THE CURRENT PLAN (keep these unless asked to change them):\n"
            + ", ".join(generated),
            "READER'S MESSAGE:\n" + message,
            "FRAMEWORK FACTS:\n" + _framework_facts(framework),
            "COURSE PLAN JSON SCHEMA (the `plan` key):\n" + _plan_json_schema(),
            f"Reply language: {'Japanese' if response_locale == 'ja' else 'English'}.",
        ]
    )
    return REVISE_PLAN_SYSTEM_PROMPT, user


# ----------------------------------------------------------------------------- checks


def check_plan(plan: CoursePlan) -> list[str]:
    """The requirements this plan fails, as sentences. Empty means it holds.

    Two of these — unique slugs, prerequisites earlier-only — are also enforced by
    `CoursePlan`'s own validator, so a plan that came out of `model_validate`
    cannot fail them and those branches are unreachable on that path. They are
    restated because a plan does not always come from there: one rebuilt
    field-by-field from stored `course_modules` rows goes through
    `model_construct`, which runs no validator at all, and that is the shape the
    revise handler compares against. The checks that exist ONLY here are the
    pedagogical ones — a plan can be perfectly well-formed and still be useless.
    `tests/test_courses_core.py` drives every branch through `model_construct` so
    each has been seen to fail.
    """
    failures: list[str] = []
    modules = list(plan.modules)
    if not modules:
        failures.append("A course needs at least one module.")
        return failures
    if len(modules) > MAX_COURSE_MODULES:
        failures.append(f"A course may have at most {MAX_COURSE_MODULES} modules.")

    seen: set[str] = set()
    for module in modules:
        if module.slug in seen:
            failures.append(f"Module slug {module.slug!r} appears twice; every slug must differ.")
        for prerequisite in module.prerequisites:
            if prerequisite not in seen:
                failures.append(
                    f"Module {module.slug!r} lists prerequisite {prerequisite!r}, which is not "
                    "an EARLIER module. A prerequisite may only name a module before it."
                )
        seen.add(module.slug)

    for module in modules:
        if not module.brief.strip():
            failures.append(
                f"Module {module.slug!r} has an empty brief. Every module's brief must be "
                "self-contained: it is handed to the notebook generator on its own."
            )
        if not module.objectives:
            failures.append(
                f"Module {module.slug!r} has no objectives. State at least one thing the "
                "reader can do after this module."
            )
        if not isinstance(module.kind, NotebookKind):
            failures.append(f"Module {module.slug!r} has an unknown kind {module.kind!r}.")

    total = sum(module.duration_minutes or 0 for module in modules)
    cap = MAX_MODULE_MINUTES * MAX_COURSE_MODULES
    if total > cap:
        failures.append(
            f"The course totals {total} minutes, past the {cap}-minute ceiling. "
            "Shorten modules or drop one."
        )
    return failures


# ----------------------------------------------------------------------------- export


def _module_readme(module: PlannedModule, *, seq: int) -> str:
    lines = [f"# Module {seq}: {module.title}", ""]
    if module.topic:
        lines += [module.topic, ""]
    if module.objectives:
        lines += ["## What you will be able to do", ""]
        lines += [f"- {item}" for item in module.objectives]
        lines += [""]
    if module.key_concepts:
        lines += ["## Key concepts", ""]
        lines += [f"- {item}" for item in module.key_concepts]
        lines += [""]
    if module.deliverable:
        lines += ["## Deliverable", "", module.deliverable, ""]
    if module.prerequisites:
        lines += [
            "## Before this module",
            "",
            "Finish: " + ", ".join(f"`{slug}`" for slug in module.prerequisites),
            "",
        ]
    if module.duration_minutes:
        lines += [f"_About {module.duration_minutes} minutes._", ""]
    return "\n".join(lines).rstrip("\n") + "\n"


def _course_readme(plan: CoursePlan, *, framework: Framework | None = None) -> str:
    """The top-level README, in the shape of the Quanmatic study-group README:
    what it is, who it is for, a Week/Topic/Key concepts/Deliverable table, and a
    quick start with `uv`."""
    fw = framework or Framework()
    rows = []
    for index, module in enumerate(plan.modules, start=1):
        concepts = ", ".join(module.key_concepts) or "—"
        rows.append(
            f"| {index} | [{module.title}]({module.slug}/) | {module.topic or '—'} | "
            f"{concepts} | {module.deliverable or '—'} |"
        )
    lines = [
        f"# {plan.title}",
        "",
        plan.summary or "",
        "",
        "## Who this is for",
        "",
        "Anyone working through the modules in order. Each module is one notebook you run",
        "and edit; each assumes only what the modules before it established.",
        "",
        "## The plan",
        "",
        "| # | Module | Topic | Key concepts | Deliverable |",
        "| --- | --- | --- | --- | --- |",
        *rows,
        "",
        "## Quick start",
        "",
        "```bash",
        "uv sync",
        "uv run jupyter lab",
        "```",
        "",
        f"Notebooks run against {fw.name} `{fw.version}` on Python 3.11 or newer.",
        "Open a module's directory and run its notebook top to bottom.",
        "",
        "---",
        "",
        "Built by Nala, Leona Quantum's teaching assistant.",
    ]
    return "\n".join(lines).rstrip("\n") + "\n"


def _curriculum_yaml(plan: CoursePlan, slug: str, *, framework: Framework | None = None) -> str:
    fw = framework or Framework()
    data = {
        "slug": slug,
        "title": plan.title,
        "description": plan.summary,
        "framework": fw.name,
        "framework_version": fw.version,
        "units": [
            {
                "id": module.slug,
                "directory": module.slug,
                "title": module.title,
                "topic": module.topic,
                "key_concepts": list(module.key_concepts),
                "deliverable": module.deliverable,
                "order": index,
            }
            for index, module in enumerate(plan.modules, start=1)
        ],
    }
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=88)


def course_to_curriculum_sources(
    course_plan: CoursePlan,
    notebook_specs: dict[str, NotebookSpec],
    *,
    slug: str = "course",
    framework: Framework | None = None,
) -> dict[Path, str]:
    """The source tree `build_curriculum` expects, keyed by relative path.

    One directory per module, each with a `README.md` written from the module's own
    topic/concepts/objectives/deliverable and a `<kind>.nb.py` rendered from the
    notebook that module generated. A module with no generated notebook is skipped:
    `build_curriculum` compiles sources, and there is nothing honest to compile from
    a module that was only ever planned.
    """
    files: dict[Path, str] = {
        Path("README.md"): _course_readme(course_plan, framework=framework),
        Path("curriculum.yaml"): _curriculum_yaml(course_plan, slug, framework=framework),
    }
    for index, module in enumerate(course_plan.modules, start=1):
        spec = notebook_specs.get(module.slug)
        if spec is None:
            continue
        directory = Path(module.slug)
        files[directory / "README.md"] = _module_readme(module, seq=index)
        files[directory / module_filename(module.kind)] = render_source(spec)
    return files


def export_course_zip(
    course_plan: CoursePlan,
    notebook_specs: dict[str, NotebookSpec],
    *,
    slug: str = "course",
    framework: Framework | None = None,
) -> bytes:
    """Build the course through `build_curriculum` (never executing) and zip it.

    The zip is what the reader downloads: the compiled `.ipynb` files, the READMEs
    and the `curriculum.yaml`, laid out exactly as `build_curriculum` writes them.
    Nothing is executed here — the notebooks were already executed in the sandbox
    when their versions were generated, and `execute=True` would want a kernel this
    process is not entitled to start.
    """
    with tempfile.TemporaryDirectory(prefix="leona-course-") as tmp:
        source_root = Path(tmp) / "src"
        out_root = Path(tmp) / "out"
        for relative, text in course_to_curriculum_sources(
            course_plan, notebook_specs, slug=slug, framework=framework
        ).items():
            target = source_root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
        manifest = build_curriculum(source_root, out_root, execute=False)
        # `build_curriculum` deliberately does NOT copy `curriculum.yaml` into the
        # build — for the hand-authored Quanmatic curriculum it is the build's input,
        # not part of the deliverable. A downloaded course is different: the yaml IS
        # the reader's table of contents and the thing that lets them rebuild the
        # course themselves, so it is written across explicitly rather than by
        # loosening the builder for both callers.
        (out_root / "curriculum.yaml").write_text(
            (source_root / "curriculum.yaml").read_text(encoding="utf-8"), encoding="utf-8"
        )
        # A builder that compiled nothing must not be zipped into a plausible-looking
        # archive of READMEs. Structure failures do NOT stop the export (the notebooks
        # already ran; `manifest.failures()` is advice, not a gate) — an empty build is
        # a different thing, and it is the one that would ship silently.
        if not manifest.notebooks or not any(nb.outputs for nb in manifest.notebooks):
            raise RuntimeError("course export produced no notebooks")
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(out_root.rglob("*")):
                if path.is_file():
                    archive.write(path, arcname=path.relative_to(out_root).as_posix())
        return buffer.getvalue()


# --------------------------------------------------------------------------- starters

#: Starting points the composer offers for a COURSE, the way `templates.STARTER_BRIEFS`
#: does for one notebook. `kind` is the notebook kind the course's modules mostly are —
#: a hint for the card, not a constraint: the planner picks each module's kind itself.
COURSE_STARTERS: tuple[dict[str, str], ...] = (
    {
        "id": "qiskit-study-group",
        "kind": "lab",
        "title": "An 8-week Qiskit study group",
        "brief": (
            "An eight-week, code-first Qiskit 2.x study group for Python engineers with no "
            "quantum background. One session per week, each a lab they run end to end, "
            "building from a single qubit to a small algorithm. Minimal maths, every idea "
            "met as running code first, and a checkpoint each week they can fail."
        ),
    },
    {
        "id": "grover-weekend",
        "kind": "lesson",
        "title": "A weekend crash course on Grover",
        "brief": (
            "A weekend crash course on Grover's algorithm for someone who knows Python and "
            "linear algebra but no quantum computing. Take me from what an oracle is to "
            "running a 3-qubit search and understanding why the number of iterations "
            "matters. Four short modules I can finish in two days."
        ),
    },
    {
        "id": "vqe-onboarding",
        "kind": "walkthrough",
        "title": "Research onboarding: VQE",
        "brief": (
            "A research-onboarding sequence on VQE for a new PhD student who knows quantum "
            "mechanics but has not written quantum software. Cover ansatz design, "
            "Hamiltonian construction, the estimator primitive, classical optimisation and "
            "what the barren-plateau result does and does not say. Full maths, papers cited."
        ),
    },
    {
        "id": "qec-from-zero",
        "kind": "lesson",
        "title": "Quantum error correction from zero, no maths",
        "brief": (
            "Quantum error correction from zero for a curious reader who is uncomfortable "
            "with maths. Use analogies and pictures, keep every formula out unless it is "
            "the point, and build up from a repetition code to why the surface code is the "
            "one everybody talks about. Each module short."
        ),
    },
)
