import type { PublicLocale } from "./public-locale";

/**
 * Every fixed sentence the Qapp surfaces show a reader, in both languages.
 *
 * The gallery was bilingual from the start; the private workspace, the runtime
 * status line and the public `/q/<slug>` chrome were English only, so a Japanese
 * reader met a bilingual list and then an English app page behind it. The
 * generated app's own copy is whatever the creator asked for and is not touched
 * here, and the worker's range-smoke `detail` sentences arrive in English and
 * are passed through as they are.
 *
 * In `lib/` so the required `node --test` job checks the two locales keep the
 * same keys (`qapp-copy.test.ts`); a key added to one language and not the
 * other would otherwise render as `undefined` in the one nobody tested.
 */
export const QAPP_COPY = {
  en: {
    runtime: {
      frameTitle: "Qapp",
      busy: "Another execution is already running.",
      signInToRun: "Sign in to run this Qapp.",
      signInToExecute: "Sign in to execute this Qapp.",
      submitting: "Submitting execution…",
      submitFailed: "Execution could not be submitted.",
      complete: "Execution complete.",
      paused: "Automatic updates paused. The execution may still be running.",
      queued: "Queued. Waiting for execution to start.",
      stillRunning: "Still running. Results will appear here when ready.",
      running: "Running. Results will appear here.",
      interrupted: "Connection interrupted. The execution may still be running.",
      chooseInputs: "Choose inputs in the Qapp to run it.",
      retryStatus: "Retry status",
      signInLink: "Sign in to run",
    },
    workspace: {
      loadFailed: "Qapp could not be loaded.",
      loading: "Loading Qapp…",
      tryAgain: "Try again",
      all: "All Qapps",
      kicker: (framework: string) => `Qapp · ${framework} · private workspace`,
      openPublic: "Open public page ↗",
      saving: "Saving…",
      makePrivate: "Make private",
      publish: "Publish Qapp",
      visibilityFailed: "Visibility could not be changed.",
      published: "Qapp published. Anyone with its public link can view it.",
      madePrivate: "Qapp is private.",
      copyLink: "Copy public link",
      linkCopied: "Link copied.",
      linkCopyFailed: "The link could not be copied. It is the address of the public page.",
      deleteQapp: "Delete Qapp",
      deleteConfirm: "Delete for good",
      deleteCancel: "Keep it",
      deleting: "Deleting…",
      deleteWarning: "This removes the Qapp from your list and takes its public page down. It cannot be undone.",
      deleteFailed: "The Qapp could not be deleted.",
      smokeWarnHeading: "At its largest inputs",
      smokeOkHeading: "Checked at both ends",
      versionsHeading: "Versions",
      versionsLoadFailed: "Version history could not be loaded.",
      versionCurrent: "Live now",
      versionRolledBackNotice: (seq: number) => `Version ${seq} is now live.`,
      versionDemotedNotice: (seq: number) =>
        `Version ${seq} is now live, but it has never run successfully — the Qapp is private until you run it and publish again.`,
      rollBackAction: "Make this version live",
      rollingBack: "Making it live…",
      rollBackFailed: "The live version could not be changed.",
      versionSeq: (seq: number) => `Version ${seq}`,
      versionNeverRun: "Has never run successfully",
      usageHeading: "Usage",
      usageLoadFailed: "Usage could not be loaded.",
      usageEmpty: "No executions yet.",
      usageTotal: "Executions",
      usageSucceeded: "Succeeded",
      usageFailed: "Failed",
      usageLastRun: "Last run",
      usageNoRun: "Never run",
    },
    public: {
      brand: "Leona Quantum",
      badge: "Public Qapp",
      buildYourOwn: "Build your own",
      kicker: (framework: string, qubits: number) => `Qapp · ${framework} · up to ${qubits} qubits`,
      forkAction: "Fork this Qapp",
      forking: "Forking…",
      forkFailed: "This Qapp could not be forked.",
      forkSignIn: "Sign in to fork this Qapp.",
      recordHeading: "How this Qapp was checked",
      recordRanSuccessfully: "This Qapp's current version has completed a successful run.",
      recordQubits: (qubits: number) => `Declares up to ${qubits} qubits.`,
      recordNote: "This is a record that the Qapp runs, not a check of its physics.",
      forkedFrom: "Forked from another Qapp",
    },
    gallery: {
      title: "Explore Qapps",
      lede: "Published, interactive quantum applications anyone can run.",
      searchPlaceholder: "Search by title or description",
      searchAction: "Search",
      empty: "No public Qapps have been published yet.",
      noMatch: "No Qapps match this search.",
      clear: "Clear search",
      next: "Next page",
      open: "Open Qapp",
      qubits: (value: number) => `${value} qubits`,
      version: (value: number) => `Version ${value}`,
      publishedOn: "Published",
    },
  },
  ja: {
    runtime: {
      frameTitle: "Qapp",
      busy: "別の実行がまだ進行中です。",
      signInToRun: "このQappを実行するにはサインインしてください。",
      signInToExecute: "このQappを実行するにはサインインが必要です。",
      submitting: "実行を送信しています…",
      submitFailed: "実行を送信できませんでした。",
      complete: "実行が完了しました。",
      paused: "自動更新を一時停止しました。実行はまだ続いている可能性があります。",
      queued: "待機中です。実行の開始を待っています。",
      stillRunning: "まだ実行中です。準備ができ次第、結果がここに表示されます。",
      running: "実行中です。結果はここに表示されます。",
      interrupted: "接続が中断されました。実行はまだ続いている可能性があります。",
      chooseInputs: "Qappで入力を選んで実行してください。",
      retryStatus: "状態を再取得",
      signInLink: "サインインして実行",
    },
    workspace: {
      loadFailed: "Qappを読み込めませんでした。",
      loading: "Qappを読み込んでいます…",
      tryAgain: "再試行",
      all: "すべてのQapp",
      kicker: (framework: string) => `Qapp · ${framework} · 非公開ワークスペース`,
      openPublic: "公開ページを開く ↗",
      saving: "保存中…",
      makePrivate: "非公開にする",
      publish: "Qappを公開する",
      visibilityFailed: "公開設定を変更できませんでした。",
      published: "Qappを公開しました。公開リンクを知っている人なら誰でも閲覧できます。",
      madePrivate: "Qappは非公開です。",
      copyLink: "公開リンクをコピー",
      linkCopied: "リンクをコピーしました。",
      linkCopyFailed: "リンクをコピーできませんでした。公開ページのアドレスがそのリンクです。",
      deleteQapp: "Qappを削除",
      deleteConfirm: "完全に削除する",
      deleteCancel: "残しておく",
      deleting: "削除中…",
      deleteWarning: "Qappが一覧から消え、公開ページも閉じられます。元に戻すことはできません。",
      deleteFailed: "Qappを削除できませんでした。",
      smokeWarnHeading: "最大の入力では",
      smokeOkHeading: "両端で確認済み",
      versionsHeading: "バージョン",
      versionsLoadFailed: "バージョン履歴を読み込めませんでした。",
      versionCurrent: "現在公開中",
      versionRolledBackNotice: (seq: number) => `バージョン${seq}が公開中になりました。`,
      versionDemotedNotice: (seq: number) =>
        `バージョン${seq}が公開中になりましたが、一度も実行に成功していません。実行して再度公開するまでQappは非公開になります。`,
      rollBackAction: "このバージョンを公開中にする",
      rollingBack: "切り替えています…",
      rollBackFailed: "公開中のバージョンを変更できませんでした。",
      versionSeq: (seq: number) => `バージョン${seq}`,
      versionNeverRun: "一度も実行に成功していません",
      usageHeading: "利用状況",
      usageLoadFailed: "利用状況を読み込めませんでした。",
      usageEmpty: "まだ実行がありません。",
      usageTotal: "実行回数",
      usageSucceeded: "成功",
      usageFailed: "失敗",
      usageLastRun: "最終実行",
      usageNoRun: "未実行",
    },
    public: {
      brand: "Leona Quantum",
      badge: "公開Qapp",
      buildYourOwn: "自分のQappを作る",
      kicker: (framework: string, qubits: number) => `Qapp · ${framework} · 最大${qubits}量子ビット`,
      forkAction: "このQappをフォークする",
      forking: "フォークしています…",
      forkFailed: "このQappをフォークできませんでした。",
      forkSignIn: "このQappをフォークするにはサインインしてください。",
      recordHeading: "このQappの確認内容",
      recordRanSuccessfully: "このQappの現在のバージョンは実行に成功しています。",
      recordQubits: (qubits: number) => `最大${qubits}量子ビットを使用します。`,
      recordNote: "これはQappが動作することの記録であり、物理的な正しさの検証ではありません。",
      forkedFrom: "別のQappからフォークされました",
    },
    gallery: {
      title: "Qappを探す",
      lede: "誰でも実行できる、公開済みの対話型量子アプリケーションです。",
      searchPlaceholder: "タイトルや説明で検索",
      searchAction: "検索",
      empty: "公開されているQappはまだありません。",
      noMatch: "検索条件に一致するQappはありません。",
      clear: "検索をクリア",
      next: "次のページ",
      open: "Qappを開く",
      qubits: (value: number) => `${value}量子ビット`,
      version: (value: number) => `バージョン${value}`,
      publishedOn: "公開",
    },
  },
} as const satisfies Record<PublicLocale, unknown>;

export function qappCopy(locale: PublicLocale | undefined) {
  return QAPP_COPY[locale ?? "en"];
}
