// Renders `block-audit.ts`'s rows as the generated report committed at
// docs/atlas/block-audit.md. A pure function of `auditBlocks()`'s own output
// (no timestamp, no commit hash) so the committed file is a stable snapshot:
// regenerate with `node scripts/generate-block-audit-report.mjs`, and
// `lib/workflow-planner-block-audit.test.ts` asserts the committed file is
// current, the same way `check-test-list.mjs`'s own doc comment explains why
// an un-run test file goes unnoticed — an un-checked generated doc rots the
// same way.
import type { AuditRow, AuditSummary, AuditVerdict, StageCoverage } from "./block-audit.ts";

const VERDICT_LABEL: Readonly<Record<AuditVerdict, string>> = {
  match: "MATCH",
  gap: "GAP",
  "not-countable": "NOT COUNTABLE",
};

function formatOps(countedOps: Readonly<Record<string, number>>): string {
  const entries = Object.entries(countedOps).sort(([a], [b]) => a.localeCompare(b));
  return entries.length ? entries.map(([gate, count]) => `${gate}:${count}`).join(", ") : "—";
}

function escapeCell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderRow(row: AuditRow): string {
  const predicted = row.predicted === null ? "—" : String(row.predicted);
  const counted = row.counted === null ? "—" : String(row.counted);
  return `| ${row.stage} | ${row.block} | ${row.costLineId} | ${row.n} | ${predicted} | ${counted} | ${formatOps(row.countedOps)} | ${VERDICT_LABEL[row.verdict]} | ${escapeCell(row.explanation)} |`;
}

function renderCoverageRow(row: StageCoverage): string {
  const reason = row.status === "not-countable" ? escapeCell(row.reason ?? "") : "—";
  return `| ${row.stage} | ${row.status === "audited" ? "audited" : "not countable"} | ${reason} |`;
}

/** The full markdown doc. Pure in `rows`/`coverage`/`summary` — see the
 * module comment on why that matters for the currency test. */
export function renderReport(rows: readonly AuditRow[], coverage: readonly StageCoverage[], summary: AuditSummary): string {
  const lines: string[] = [];
  lines.push("# Block audit: cost formulas against the circuits Leona builds");
  lines.push("");
  lines.push(
    "Generated by `apps/web/lib/workflow-planner/block-audit.ts` — do not hand-edit. " +
      "Regenerate with `node scripts/generate-block-audit-report.mjs`; `--check` runs in CI " +
      "and `apps/web/lib/workflow-planner-block-audit.test.ts` asserts this file is current.",
  );
  lines.push("");
  lines.push(
    "For each Studio block the workflow planner pairs with an Atlas method " +
      "(`apps/web/lib/workflow-planner/stage-blocks.ts`), this counts the block's own gates " +
      "at small problem sizes and compares the count with the planner's paper-sourced cost " +
      "formulas (`costs.ts`), evaluated at the same parameters. Plan: " +
      "`~/Developer/ai-ops/desk/leona/plans/platform-vision-20260924/phase-b/PLAN.md` " +
      "(\"S1-part-1\"); kill criterion: VISION.md §10, \"the small-instance cross-check finds " +
      "nothing.\"",
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **${summary.total}** rows across **${coverage.length}** planner stages.`);
  lines.push(`- **${summary.matches}** MATCH — the built circuit's gate count matches the formula exactly.`);
  lines.push(`- **${summary.gaps}** GAP — they disagree; see each row's explanation for why.`);
  lines.push(
    `- **${summary.notCountable}** NOT COUNTABLE — the cost line states no gate name to count ` +
      "(a qubit count, a probability, an abstract oracle-call count, a reader-supplied number, " +
      "or a formula for a different, larger construction than the demonstration block builds), " +
      "or the line is scoped to a different block sharing the same stage. This is not a failure " +
      "reading: a line whose own source states no gate vocabulary is not one this audit may " +
      "guess a count for (`apps/web/lib/workflow-planner/types.ts`, `CostLine.counts`).",
  );
  lines.push("");
  lines.push("## Stage coverage");
  lines.push("");
  lines.push("Every method `stage-blocks.ts` pairs with Studio blocks, either genuinely audited");
  lines.push("(at least one MATCH or GAP below) or not countable, with why.");
  lines.push("");
  lines.push("| Stage | Status | Reason (when not countable) |");
  lines.push("|---|---|---|");
  for (const row of coverage) lines.push(renderCoverageRow(row));
  lines.push("");
  lines.push("## Every row");
  lines.push("");
  lines.push("| Stage | Block | Cost line | n | Predicted | Counted | Counted gates | Verdict | Explanation |");
  lines.push("|---|---|---|---|---|---|---|---|---|");
  for (const row of rows) lines.push(renderRow(row));
  lines.push("");
  return lines.join("\n");
}
