import { escapeHtml as e } from './render.mjs';
const categories={research:'研究・論文',industry:'産業・ビジネス',policy:'政策・社会',products:'製品・開発',guide:'基礎から学ぶ'};
export function createNewsClient({apiUrl,token='',editor=false,fetchImpl=fetch}) {
  const base=new URL(apiUrl);
  if(base.protocol!=='https:' && !(base.protocol==='http:' && ['localhost','127.0.0.1','[::1]'].includes(base.hostname)))throw new Error('News API requires HTTPS outside localhost');
  return async function request(path,{method='GET',body,key}={}) {
    const headers={'Accept':'application/json'};
    if(editor){if(!token)throw new Error('Editorial API token missing');headers.Authorization=`Bearer ${token}`;}
    if(body)headers['Content-Type']='application/json';
    if(key)headers['Idempotency-Key']=key;
    const response=await fetchImpl(new URL('/v1/news'+path,base),{method,headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000),redirect:'error'});
    if(!response.ok){const error=new Error(`News API HTTP ${response.status}`);error.status=response.status;throw error;}
    const reader=response.body.getReader(),chunks=[];let size=0;
    try {while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2_000_000){await reader.cancel();throw new Error('News API response too large');}chunks.push(Buffer.from(value));}}finally{reader.releaseLock();}
    const buffer=Buffer.concat(chunks);
    return path.endsWith('/image')?buffer:JSON.parse(buffer.toString('utf8'));
  };
}
function layout(title,body,{editor=false,siteUrl,path='/',noindex=false,description='世界の量子ニュースを、日本語でわかりやすく。',imageUrl=''}={}) {
 const canonical=new URL(path,siteUrl).href;
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | Leona Quantum News</title><meta name="description" content="${e(description)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:site_name" content="Leona Quantum News">${imageUrl?`<meta property="og:image" content="${e(new URL(imageUrl,siteUrl).href)}"><meta name="twitter:card" content="summary_large_image">`:''}${editor||noindex?'<meta name="robots" content="noindex,nofollow">':`<link rel="canonical" href="${e(canonical)}"><link rel="alternate" type="application/rss+xml" title="Leona Quantum News" href="/feed.xml">`}<link rel="stylesheet" href="/assets/style.css">${editor?'<script src="/assets/editor.js" defer></script>':''}</head><body data-theme="b"><a class="skip" href="#main">本文へ移動</a>${editor?'<div class="preview-notice">編集用プレビュー — 下書きは一般公開されません。</div>':''}<div class="wrap"><div class="utility"><span>世界の量子ニュースを、日本語で。</span><a href="/about">編集方針</a></div><header class="masthead"><a class="brand" href="/"><img src="/assets/leona-wordmark.png" alt="Leona Quantum" width="225" height="60"><em>News</em></a><span class="tagline">量子のいま。その先まで。</span></header><nav class="nav" aria-label="カテゴリ"><div class="nav-tabs"><a href="/">すべて</a>${Object.entries(categories).map(([k,v])=>`<a href="/?category=${k}">${v}</a>`).join('')}</div></nav><main id="main">${body}</main><footer class="footer"><a href="/">Leona Quantum News</a><a href="/about">編集方針・訂正について</a>${editor?'<a href="/editor">編集画面</a>':'<a href="/feed.xml">RSS</a>'}</footer></div></body></html>`;
}
const dateLabel=a=>a.published_at?new Intl.DateTimeFormat('ja-JP',{dateStyle:'long',timeZone:'Asia/Tokyo'}).format(new Date(a.published_at)):'下書き';
const image=a=>a.image?`<img src="/media/${e(a.id)}" alt="${e(a.image.alt)}" width="1536" height="1024" loading="lazy">`:'<div class="image-pending">画像の準備中</div>';
function card(a){return `<article class="story"><a class="thumbnail" href="/articles/${e(a.id)}">${image(a)}</a><div class="story-copy"><div class="category">${categories[a.document.category]||''}</div><a href="/articles/${e(a.id)}"><h3>${e(a.document.title)}</h3></a><p>${e(a.document.lead)}</p><div class="meta">${dateLabel(a)}</div></div></article>`;}
export function listing(data,params,config){const filter=params.get('category'),q=(params.get('q')||'').trim();const list=data.items;const [lead,...rest]=list;const hero=lead&&!filter&&!q&&!params.get('before');return layout('世界の量子を、読み解く。',`<div class="b-banner"><strong>Quantum, in perspective.</strong><p>研究の先端から、社会への実装まで。<br>量子の現在地を読み解くメディア。</p></div>${hero?`<section class="hero"><div><p class="kicker">${categories[lead.document.category]} / ${dateLabel(lead)}</p><h1>${e(lead.document.title)}</h1><p class="hero-description">${e(lead.document.lead)}</p><a class="read-link" href="/articles/${e(lead.id)}">記事を読む</a></div><figure class="figure"><a class="art-panel" href="/articles/${e(lead.id)}">${image(lead)}</a><figcaption>${e(lead.image?.credit||'')}</figcaption></figure></section>`:''}<section><div class="section-head"><h2>${q?`「${e(q)}」の検索結果`:categories[filter]||'記事一覧'}</h2></div><div class="cards">${(hero?rest:list).map(card).join('')}</div>${!list.length?'<div class="empty-state"><h2>記事はまだありません</h2><p>公開の準備が整った記事から、順にお届けします。</p></div>':''}${data.next_cursor?`<p><a class="back-link" href="/?${e(new URLSearchParams({...Object.fromEntries(params),before:data.next_cursor}).toString())}">次の記事を読む</a></p>`:''}</section><form class="site-search" action="/" role="search"><label for="q">記事を探す</label><div><input type="search" id="q" name="q" maxlength="100" value="${e(q)}"><button>検索</button></div></form>`,{...config,noindex:!!q||!!filter||params.has('before')});}
export function articleView(a,config){const d=a.document;return layout(d.title,`<article class="article-page"><a class="back-link" href="/">記事一覧へ</a><header class="article-heading"><p class="kicker">${categories[d.category]} / ${dateLabel(a)}</p><h1>${e(d.title)}</h1><p class="article-lead">${e(d.lead)}</p><p class="sample-note">Leona Quantum News 編集部 / AIによる検索・執筆支援を使用</p></header><figure class="article-figure">${image(a)}<figcaption>${e(a.image?.credit||'画像未設定')}${a.image?.source_url?` / <a href="${e(a.image.source_url)}" rel="noopener noreferrer">画像の出典</a>`:''}${a.image?.license_url?` / <a href="${e(a.image.license_url)}" rel="noopener noreferrer">利用条件</a>`:''}</figcaption></figure><div class="article-columns"><aside class="contents"><p>この記事で読むこと</p>${d.sections.map((s,i)=>`<a href="#section-${i}">${e(s.heading)}</a>`).join('')}</aside><div class="article-body">${d.sections.map((s,i)=>`<section id="section-${i}"><h2>${e(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${e(p.text)} <span class="citations">${p.sources.map(id=>{const source=d.sources.find(s=>s.id===id);return source?`<a href="${e(source.url)}" title="${e(source.title)}" rel="noopener noreferrer">[${e(id.slice(1))}]</a>`:'';}).join(' ')}</span></p>`).join('')}</section>`).join('')}${(a.corrections||[]).length?`<aside class="source-note"><h2>訂正・更新</h2>${a.corrections.map(c=>`<p>${e(c.at.slice(0,10))}：${e(c.note)}</p>`).join('')}</aside>`:''}<aside class="source-note"><h2>出典・参考資料</h2><ol>${d.sources.map(s=>`<li><a href="${e(s.url)}" rel="noopener noreferrer">${e(s.title)}</a><p>${e(s.publisher)} / ${e(s.locator)}</p></li>`).join('')}</ol></aside></div></div></article>${config.editor?`<p><a class="back-link" href="/editor/articles/${e(a.id)}">この記事を確認する</a></p>`:''}`,{...config,path:`/articles/${a.id}`,description:d.lead,imageUrl:a.image?`/media/${a.id}`:''});}
export function editorView(data,csrf,config){return layout('編集画面',`<section class="about-page"><h1>ニュース編集室</h1><p>収集した記事は下書きとして保存されます。本文、出典、画像を確認してから公開してください。</p><form class="editor-form" method="post" action="/editor/collect"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="collection_key" value=""><label>探したいニュース<textarea name="brief" minlength="10" maxlength="1000" required>世界の量子コンピュータに関する、直近72時間の重要で面白いニュースを選んでください。</textarea></label><label><input type="checkbox" name="generate_image" checked> 概念イラストも生成する（API利用料がかかります）</label><button>収集して下書きを作る</button></form><h2>記事の確認</h2>${data.items.map(a=>`<p><a href="/editor/articles/${e(a.id)}">${e(a.document.title)}</a><br><small>${e(a.status)} / 検証：${e(a.review?.result?.verdict||'未完了')}</small></p>`).join('')||'<p>下書きはまだありません。</p>'}</section>`,config);}
export function reviewView(a,csrf,config){return layout('記事の公開確認',`<article class="about-page"><h1>${e(a.document.title)}</h1><p><a class="back-link" href="/articles/${e(a.id)}">本文と出典を読む</a></p>${a.status!=='published'?`<details><summary>本文を修正する</summary><form class="editor-form" method="post" action="/editor/articles/${e(a.id)}/revise"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="expected_digest" value="${e(a.digest)}"><label>タイトル<input name="title" value="${e(a.document.title)}" maxlength="100" required></label><label>リード<textarea name="lead" required>${e(a.document.lead)}</textarea></label>${a.document.sections.map((s,i)=>`<label>見出し<input name="heading_${i}" value="${e(s.heading)}" required></label>${s.paragraphs.map((p,j)=>`<label>本文（出典：${e(p.sources.join(', '))}）<textarea name="paragraph_${i}_${j}" required>${e(p.text)}</textarea></label>`).join('')}`).join('')}<label>変更の理由<textarea name="note" minlength="5" required></textarea></label><p>修正後は再検証します。画像も再設定されます。</p><button>修正して再検証する</button></form></details><details><summary>実際の写真を登録する</summary><form id="image-upload" class="editor-form" method="post" action="/editor/articles/${e(a.id)}/image"><input type="hidden" name="csrf" value="${csrf}"><label>画像（550 KB以下）<input type="file" accept="image/png,image/jpeg,image/webp" required></label><label>画像の説明<input name="alt" minlength="3" maxlength="180" required></label><label>クレジット<input name="credit" minlength="3" maxlength="300" required></label><label>画像の出典URL<input type="url" name="source_url" required></label><label>利用条件・許諾を確認できるURL<input type="url" name="license_url" required></label><label>確認した利用条件<textarea name="permission_note" minlength="10" maxlength="1000" required></textarea></label><button>利用条件を確認して画像を保存する</button><p role="status"></p></form></details>`:''}<h2>検証結果</h2><p>${e(a.review?.result?.notes||'検証待ち')}</p><ul>${(a.review?.result?.blockers||[]).map(b=>`<li>${e(b)}</li>`).join('')}</ul><p>画像：${e(a.image?.credit||'未設定')}</p><form class="editor-form" method="post" action="/editor/articles/${e(a.id)}/${a.status==='published'?'withdraw':'publish'}"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="expected_digest" value="${e(a.digest)}"><input type="hidden" name="expected_image_digest" value="${e(a.image_digest||'')}"><label>確認・変更の記録<textarea name="note" minlength="5" maxlength="1000" required placeholder="確認した内容や、公開を取り下げる理由"></textarea></label><button ${a.status!=='published'&&(!a.image||a.review?.result?.verdict!=='pass')?'disabled':''}>${a.status==='published'?'公開を取り下げる':'この記事を公開する'}</button></form></article>`,config);}
export function messagePage(title,message,config){return layout(title,`<div class="empty-state"><h1>${e(title)}</h1><p>${e(message)}</p><a class="back-link" href="${config.editor?'/editor':'/'}">${config.editor?'編集画面':'トップ'}へ戻る</a></div>`,{...config,noindex:true});}
export function aboutLive(config){return layout('編集方針',`<article class="about-page"><h1>量子のいまを、<br>ちゃんとわかる言葉で。</h1><p>世界の量子コンピュータのニュースを、研究、製品、産業、政策の背景とともに伝えます。</p><h2>出典から確かめられる記事に</h2><p>発表された事実、発表者の主張、将来の予測を分け、論文や公式発表へたどれるリンクを添えます。AIによる検索と執筆支援を使い、根拠が揃わない記事は公開を保留します。</p><h2>画像の扱い</h2><p>利用条件を確認できる実際の画像を優先します。生成画像は概念イラストとして明記し、実際の製品や実験結果と混同しない表現にします。</p><h2>訂正と更新</h2><p>誤りが判明した記事は必要に応じて公開を取り下げ、出典から再確認します。内容を修正した場合は、記事に変更点を記載します。</p></article>`,{...config,path:'/about'});}
export function rss(items,siteUrl){return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Leona Quantum News</title><link>${e(siteUrl)}</link><description>世界の量子ニュースを、日本語で。</description><language>ja</language>${items.map(a=>`<item><title>${e(a.document.title)}</title><link>${e(new URL('/articles/'+a.id,siteUrl).href)}</link><guid isPermaLink="true">${e(new URL('/articles/'+a.id,siteUrl).href)}</guid><description>${e(a.document.lead)}</description><pubDate>${new Date(a.published_at).toUTCString()}</pubDate></item>`).join('')}</channel></rss>`;}
