import { articles, categories } from './content/articles.mjs';
export const escapeHtml = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHtml;
const articleUrl = a => `/articles/${a.slug}`;
function picture(a, hero = false) {
  return `<img src="/assets/${a.image}.png" alt="${a.image === 'hero' ? '点が輪を形づくる、量子をイメージしたイラスト' : a.image === 'research' ? '格子状に並ぶ点のイラスト' : a.image === 'industry' ? '高さの異なる構造物のイラスト' : '重なり合う波のイラスト'}" ${hero ? 'fetchpriority="high"' : 'loading="lazy"'} width="800" height="500">`;
}
function card(a) { return `<article class="story"><a class="thumbnail" href="${articleUrl(a)}" aria-label="${e(a.title)}">${picture(a)}</a><div class="story-copy"><div class="category">${categories[a.category]}</div><a href="${articleUrl(a)}"><h3>${e(a.title)}</h3></a><p>${e(a.lead)}</p><div class="meta">サンプル記事</div></div></article>`; }
function shell(title, content, {q = '', category = ''} = {}) {
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="世界の量子ニュースを、自然な日本語でわかりやすく。Leona Quantum Newsの開発プレビュー。"><title>${e(title)} | Leona Quantum News</title><link rel="icon" href="/assets/guide.png"><link rel="stylesheet" href="/assets/style.css"></head><body data-theme="b"><a class="skip" href="#main">本文へ移動</a><div class="preview-notice">公開前プレビュー <span>掲載内容は、デザインと文体を確認するためのサンプルです。</span></div><div class="wrap"><div class="utility"><span>世界の量子ニュースを、日本語で。</span><a href="/about">このメディアについて</a></div><header class="masthead"><a class="brand" href="/" aria-label="Leona Quantum News トップ"><img src="/assets/leona-wordmark.png" alt="Leona Quantum" width="225" height="60"><em>News</em></a><span class="tagline">量子のいま。その先まで。</span></header><nav class="nav" aria-label="記事のカテゴリ"><div class="nav-tabs"><a href="/" ${!category ? 'aria-current="page"' : ''}>すべて</a>${Object.entries(categories).map(([k,v])=>`<a href="/?category=${k}#stories" ${category===k?'aria-current="page"':''}>${v}</a>`).join('')}</div><a class="search-toggle" href="#search">記事を探す</a></nav><main id="main">${content}<form id="search" class="site-search" action="/" method="get" role="search"><label for="q">記事を探す</label><div><input id="q" name="q" type="search" value="${e(q)}" placeholder="量子ビット、実用化、重ね合わせ…" maxlength="200">${category?`<input type="hidden" name="category" value="${e(category)}">`:''}<button type="submit">検索</button></div></form></main><footer class="footer"><a href="/">© ${new Date().getFullYear()} Leona Quantum News</a><a href="/about">編集方針</a><span>news.leonaquantum.com</span></footer></div></body></html>`;
}
export function home(searchParams = new URLSearchParams()) {
 const q = (searchParams.get('q') || '').trim().slice(0,200);
 const requested = searchParams.get('category');
 const category = Object.hasOwn(categories, requested) ? requested : '';
 const listing = !!q || !!category;
 const normalized = q.normalize('NFKC').toLocaleLowerCase('ja');
 const filtered = articles.filter(a=>(!category || a.category===category) && `${a.title} ${a.lead} ${a.sections.flat().join(' ')}`.normalize('NFKC').toLocaleLowerCase('ja').includes(normalized));
 const hero = articles[0];
 const top = listing ? '' : `<div class="b-banner"><strong>Quantum, in perspective.</strong><p>研究の先端から、社会への実装まで。<br>量子の現在地を読み解くメディア。</p></div><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="kicker">注目の解説 / サンプル</p><h1 id="hero-title">量子コンピュータは、<br>「間違い」をどう<br>乗り越えるのか。</h1><p class="hero-description">${e(hero.lead)}</p><a class="read-link" href="${articleUrl(hero)}">特集を読む <span aria-hidden="true">↗</span></a></div><figure class="figure"><a class="art-panel" href="${articleUrl(hero)}" aria-label="${e(hero.title)}">${picture(hero,true)}</a><figcaption>Illustration / Leona — デザイン検討用イラスト</figcaption></figure></section><section class="ticker" aria-label="読み解くヒント"><div class="ticker-title">ニュースの視点<small>知っておきたいこと</small></div><a class="brief" href="${articleUrl(articles[1])}"><span>研究・論文</span>量子ビットの数。その数字は、<br>何を教えてくれるのか。</a><a class="brief" href="${articleUrl(articles[2])}"><span>産業・ビジネス</span>未来のロードマップと、<br>今日使える技術を見分ける。</a></section>`;
 return shell(listing ? (q ? `「${q}」の検索結果` : categories[category]) : '世界の量子を、読み解く。', `${top}<section id="stories"><div class="section-head"><h2>${q?`「${e(q)}」の検索結果`:category?categories[category]:'視点を広げる'}</h2><span>${listing?`${filtered.length}件`:'サンプル記事'}</span></div>${listing?'<p class="listing-back"><a href="/">すべての記事に戻る</a></p>':''}<div class="cards">${(listing?filtered:articles.slice(1)).map(card).join('')}</div>${filtered.length===0?'<div class="empty-state"><h3>一致する記事がありません</h3><p>短い言葉や別のキーワードで検索してみてください。</p><a href="/">すべての記事を見る</a></div>':''}</section>${listing?'':`<aside class="editor-note"><h2>世界で起きたことを、<br>自分の言葉で理解する。</h2><p>研究成果も、企業の動きも、技術をめぐる議論も。<br>何が起きて、なぜ気になるのか。背景とともに、丁寧に伝えます。</p><a href="/about">私たちの編集方針</a></aside>`}`,{q,category});
}
export function articlePage(slug) {
 const a = articles.find(a=>a.slug===slug); if (!a) return null;
 return shell(a.title, `<article class="article-page"><a class="back-link" href="/?category=${a.category}">${categories[a.category]}の記事一覧</a><header class="article-heading"><p class="kicker">${categories[a.category]} / サンプル記事</p><h1>${e(a.title)}</h1><p class="article-lead">${e(a.lead)}</p><p class="sample-note">デザイン・文体の確認用です。取材済みのニュース記事ではありません。</p></header><figure class="article-figure ${a.image==='hero'?'blue-image':''}">${picture(a,true)}<figcaption>Illustration / Leona — デザイン検討用イラスト</figcaption></figure><div class="article-columns"><aside class="contents"><p>この記事で読むこと</p><nav aria-label="記事の目次">${a.sections.map(([title],i)=>`<a href="#section-${i}">${e(title)}</a>`).join('')}</nav></aside><div class="article-body">${a.sections.map(([title,text],i)=>`<section id="section-${i}"><h2>${e(title)}</h2><p>${e(text)}</p></section>`).join('')}<aside class="source-note"><h2>この記事について</h2><p>このサンプルでは、特定の研究成果や企業発表を報道していません。実際の記事には、内容を確認した論文・公式発表などへのリンクと、画像の出典を掲載します。</p><a href="/about">編集方針を読む</a></aside></div></div></article><section><div class="section-head"><h2>あわせて読みたい</h2></div><div class="cards">${articles.filter(b=>b!==a).map(card).join('')}</div></section>`,{category:a.category});
}
export function about() { return shell('このメディアについて', `<article class="about-page"><p class="kicker">Leona Quantum News</p><h1>量子のいまを、<br>ちゃんとわかる言葉で。</h1><p class="article-lead">世界で起きている量子コンピュータのニュースを、背景から丁寧に伝える日本語メディアを準備しています。</p><h2>論文の、その外側も。</h2><p>研究の進歩に加えて、新製品、企業の動き、政策、開発者の取り組みまで。量子技術の面白さと、社会とのつながりを取り上げます。</p><h2>驚きは大切に。根拠は確かに。</h2><p>発表された事実、発表者の主張、将来の予測を分けて書きます。一次情報へたどれるリンクを添え、成果の条件や残された課題も伝えます。</p><h2>写真も、記事の一部。</h2><p>関連する実際の画像を優先し、利用条件と出典を確認します。生成画像を使う場合は、そのことを明記し、実物や実験結果と誤解されない表現にします。</p><h2>AIの使い方</h2><p>検索や執筆の補助にAIを使う構成を予定しています。根拠の不足や情報の食い違いが見つかった記事は公開を保留し、訂正時には変更点を読者に示します。</p><div class="source-note"><p>現在は公開前のサンプルサイトです。ニュースの自動収集・配信はまだ稼働していません。</p></div><a class="back-link" href="/">記事を読む</a></article>`); }
export function notFound() { return shell('ページが見つかりません', '<div class="empty-state"><h1>ページが見つかりません</h1><p>URLを確認するか、トップページから記事を探してください。</p><a href="/">トップページへ戻る</a></div>'); }
