"""majorana-verification — the verify stage's toolbox.

Framework-native re-execution checks plus optional OpenQASM conversion checks and
return-contract checks. Every primitive maps to the
contracts VerificationMethod/VerificationResultKind taxonomy and fails rather than
fabricates when it cannot run (plans/rebuild/08-phases.md §Phase 2 step 4)."""

from majorana_verification.baseline import (
    BRUTE_FORCE_MAX_VARIABLES,
    BaselineProblemError,
    objective_comparison,
    objective_tolerance,
    objective_values,
    optimal_objective,
)
from majorana_verification.hamiltonian import (
    EXACT_DIAG_MAX_QUBITS,
    HamiltonianError,
    energy_tolerance,
    ground_state_comparison,
    ground_state_energy,
    hamiltonian_matrix,
)
from majorana_verification.methods import (
    VerificationOutcome,
    extract_counts,
    verify_brute_force,
    verify_bell_state_property,
    verify_exact,
    verify_exact_diag,
    verify_exact_native,
    verify_ghz_state_property,
    verify_native_sampled_counts,
    verify_native_statistical_counts,
    verify_qasm_parse,
    verify_return_contract,
    verify_statistical,
    verify_statistical_counts,
    verify_statistical_counts_pair,
)
from majorana_verification.native import (
    ENTANGLED_STATE_TOLERANCE,
    NATIVE_STATEVECTOR_MAX_QUBITS,
    entangled_state_property,
    native_counts_vs_ideal,
    sampled_counts_comparison,
    statevector_from_evidence,
)
from majorana_verification.policy import EvidenceSufficiency, assess_evidence_sufficiency
from majorana_verification.statevector import (
    IDEAL_DISTRIBUTION_MAX_QUBITS,
    STATEVECTOR_MAX_QUBITS,
    UNITARY_MAX_QUBITS,
    EquivalenceReport,
    MethodCeilingExceeded,
    StatevectorIncapable,
    counts_vs_ideal,
    exact_equivalence,
    ideal_distribution,
    simulate_statevector,
    statistical_equivalence,
    unitary,
)

__all__ = [
    "BRUTE_FORCE_MAX_VARIABLES",
    "BaselineProblemError",
    "EXACT_DIAG_MAX_QUBITS",
    "ENTANGLED_STATE_TOLERANCE",
    "HamiltonianError",
    "objective_comparison",
    "objective_tolerance",
    "objective_values",
    "optimal_objective",
    "verify_brute_force",
    "verify_bell_state_property",
    "NATIVE_STATEVECTOR_MAX_QUBITS",
    "StatevectorIncapable",
    "VerificationOutcome",
    "extract_counts",
    "native_counts_vs_ideal",
    "entangled_state_property",
    "sampled_counts_comparison",
    "statevector_from_evidence",
    "energy_tolerance",
    "ground_state_comparison",
    "ground_state_energy",
    "hamiltonian_matrix",
    "verify_exact",
    "verify_exact_diag",
    "verify_exact_native",
    "verify_ghz_state_property",
    "verify_native_sampled_counts",
    "verify_native_statistical_counts",
    "verify_statistical",
    "verify_statistical_counts",
    "verify_statistical_counts_pair",
    "verify_return_contract",
    "verify_qasm_parse",
    "EquivalenceReport",
    "IDEAL_DISTRIBUTION_MAX_QUBITS",
    "MethodCeilingExceeded",
    "STATEVECTOR_MAX_QUBITS",
    "UNITARY_MAX_QUBITS",
    "counts_vs_ideal",
    "exact_equivalence",
    "ideal_distribution",
    "statistical_equivalence",
    "simulate_statevector",
    "unitary",
    "EvidenceSufficiency",
    "assess_evidence_sufficiency",
]
