import type { PublicLocale } from "../../../../../lib/public-locale";
import type { VqeComparisonRecord, VqePaperRecord } from "../../../../../lib/atlas-vqe/types";

const COPY = {
  en: {
    back: "← Atlas",
    classification: "Classification",
    generatedBy: (method: string, version: string) => `Generated by ${method} (v${version})`,
    manualGold: "is_manual_gold: false — this is a machine classification, not human-curated gold",
    humanValidated: "human_validated: false — no human has confirmed this comparison",
    humanValidatedTrue: "human_validated: true",
    dimension: "Dimension",
    status: "Status",
    detail: "Detail",
    evidence: "Evidence locator",
    unresolvedConflicts: "Unresolved conflicts",
    none: "none recorded",
    unknown: "unknown",
    sourcePapers: "Comparing",
  },
  ja: {
    back: "← Atlas",
    classification: "分類",
    generatedBy: (method: string, version: string) => `生成方法: ${method} (v${version})`,
    manualGold: "is_manual_gold: false — 機械による分類であり、人手によるgoldラベルではありません",
    humanValidated: "human_validated: false — 人手による検証は行われていません",
    humanValidatedTrue: "human_validated: true",
    dimension: "比較軸",
    status: "状態",
    detail: "詳細",
    evidence: "根拠箇所",
    unresolvedConflicts: "未解決の対立点",
    none: "記録なし",
    unknown: "不明",
    sourcePapers: "比較対象",
  },
} as const;

function statusTone(status: string): "ok" | "warn" | "neutral" {
  if (status === "fixed") return "ok";
  if (status === "changed") return "warn";
  return "neutral";
}

function classificationTone(classification: string): "ok" | "warn" | "neutral" {
  if (classification === "strict") return "ok";
  if (classification === "invalid") return "warn";
  return "neutral";
}

export function VqeComparisonDetail({
  comparison,
  papers,
  locale,
}: {
  comparison: VqeComparisonRecord;
  papers: VqePaperRecord[];
  locale: PublicLocale;
}) {
  const copy = COPY[locale];

  return (
    <>
      <section className="mj-repo-detail-hero">
        <a className="mj-back-link" href="/repository">{copy.back}</a>
        <div className="mj-repository-detail-kicker">
          <span className="mj-vqe-badge" data-tone={classificationTone(comparison.classification)}>
            {comparison.classification}
          </span>
          <span className="mj-vqe-badge" data-tone="neutral">is_manual_gold: {String(comparison.is_manual_gold)}</span>
          <span className="mj-vqe-badge" data-tone={comparison.human_validated ? "ok" : "neutral"}>
            human_validated: {String(comparison.human_validated)}
          </span>
        </div>
        <h1>{papers.map((paper) => paper.title).join(" vs. ") || comparison.comparison_id}</h1>
        <p>{copy.sourcePapers}: {papers.map((paper) => paper.title).join(", ") || comparison.source_record_ids.join(", ")}</p>
        <p className="mj-vqe-validation-note">{copy.generatedBy(comparison.generation_method, comparison.generator_version)}</p>
        <p className="mj-vqe-validation-note">{copy.manualGold}</p>
        <p className="mj-vqe-validation-note">{comparison.human_validated ? copy.humanValidatedTrue : copy.humanValidated}</p>
      </section>

      <div className="mj-repository-detail-main">
        <table className="mj-repo-comparison-table">
          <thead>
            <tr>
              <th>{copy.dimension}</th>
              <th>{copy.status}</th>
              <th>{copy.detail}</th>
              <th>{copy.evidence}</th>
            </tr>
          </thead>
          <tbody>
            {comparison.dimensions.map((dimension) => (
              <tr key={dimension.name}>
                <td>{dimension.name}</td>
                <td>
                  <span className="mj-vqe-badge" data-tone={statusTone(dimension.status)}>
                    {dimension.status === "unknown" ? copy.unknown : dimension.status}
                  </span>
                </td>
                <td>{dimension.detail ?? copy.unknown}</td>
                <td>{dimension.evidence_locator ?? copy.unknown}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <details className="mj-repo-section" open>
          <summary>{copy.unresolvedConflicts}</summary>
          <div className="mj-repo-section-body">
            {comparison.unresolved_conflicts.length ? (
              <ul className="mj-vqe-plain-list">
                {comparison.unresolved_conflicts.map((conflict) => <li key={conflict}>{conflict}</li>)}
              </ul>
            ) : (
              <p>{copy.none}</p>
            )}
          </div>
        </details>
      </div>
    </>
  );
}
