#!/usr/bin/env python3
"""CI gate: every notebook grader must be able to fail, and must pass the answer.

A `Cell.check` is the assertion that decides whether a reader got an exercise right.
Two ways it can be worthless, and neither shows up as an error anywhere else:

* it passes against the STUB — the unfilled placeholder the reader starts from. Then
  the exercise is marked correct before anyone attempts it, and the notebook reports
  itself complete on open. This is the failure that shipped in the first draft of
  `spec_with_graders` and was caught only by running it: an `assert double(3) == 6`
  is a perfectly good assertion, and it still grades nothing if the thing it runs
  against is already the solution.
* it fails against the author's own SOURCE. Then the exercise cannot be passed at all,
  and every reader is told they are wrong for writing the intended answer.

So each grader is run twice, and both arms must come out the expected way. A grader
that cannot be seen going red is not evidence, which is the same rule the rest of this
repo's checkers are held to — `--self-test` below is that rule applied to this script.

An audit that finds no specs REFUSES rather than reporting clean. The first version of
this script was wired into CI against `packages/py/notebooks/tests`, which contains no
`.json` at all: it printed `clean (0 grader(s) across 0 spec(s), both arms checked)` and
exited 0 on every run. "Both arms checked" was false, and a green check named "notebook
graders can actually fail" checked nothing — the exact shape of failure this script was
written to catch, in the script itself.

**What this covers, and what covers the rest.** This gate holds the specs COMMITTED to
this repository. Every graded notebook a reader opens is generated by the model at
request time and never passes through here — that half is now held by
`leona_notebooks.grader_audit`, which runs these same two arms inside the pipeline
(`notebook.graders`, after execute-and-repair) and strips the check off any grader that
fails either one. Owner ruling ai-ops#258. The two share `spec_with_graders` and
`grades_from_report`, so both measure the grade a READER would be given rather than
something adjacent to it; they differ only in what they do about a defect, because a
fixture can fail CI and a reader's notebook cannot.

**Answer keys too, since 2026-09-05.** A `role=question` cell's `answer` decides a
verdict exactly as a `check` does, and the same two failure directions exist in it: a
numeric tolerance that accepts 0 marks a reader correct for typing nothing, a text key
whose answer is printed in the question gives itself away. Those are decidable by
READING the key, so `leona_notebooks.answer_audit` judges them without executing
anything, and this gate calls it on the committed specs. The count is reported even when
it is zero — no committed fixture carries a question yet, and a line saying so is what
stops the next reader assuming this arm has been exercising something.

Usage:
  python scripts/check_graders.py [PATH ...]   # .json specs, or dirs to walk
  python scripts/check_graders.py --self-test  # prove the two arms actually discriminate
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "packages/py/notebooks/src"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "packages/py/contracts/src"))

from majorana_contracts.notebooks import Cell, NotebookSpec  # noqa: E402
from leona_notebooks.answer_audit import (  # noqa: E402
    GUESSABLE_MAX_SHARE,
    audit_answers,
    guessability,
)
from leona_notebooks.grading import (  # noqa: E402
    GradedAttempt,
    grades_from_report,
    spec_with_graders,
)
from leona_notebooks.local_runner import execute_in_local_sandbox  # noqa: E402
from leona_notebooks.source import parse_source  # noqa: E402


def _grade(spec: NotebookSpec, cell_id: str, code: str) -> str:
    attempt = GradedAttempt(code={cell_id: code}, answers={})
    report = execute_in_local_sandbox(spec_with_graders(spec, attempt))
    grade = grades_from_report(spec, report, attempt).by_id().get(cell_id)
    return grade.status if grade else "missing"


def audit_keys(spec: NotebookSpec) -> list[str]:
    """Failures in `spec`'s ANSWER keys, as reader-facing lines. Executes nothing."""
    problems = [f"  {spec.slug}/{verdict.describe()}" for verdict in audit_answers(spec).unsound]
    # Set-level, and invisible to the loop above: every key in both certification quizzes
    # was individually sound while 21 of 25 answers in the mock exam were option B.
    guess = guessability(spec)
    if guess is not None:
        index, hits, share = guess
        if share > GUESSABLE_MAX_SHARE:
            problems.append(
                f"  {spec.slug}: answering option {chr(ord('A') + index)} to every question "
                f"scores {hits} of the choice questions ({share:.0%}) — reshuffle the "
                f"options; the answers are right, their POSITIONS are not"
            )
    return problems


def audit(spec: NotebookSpec) -> list[str]:
    """Failures in `spec`'s graders, as reader-facing lines."""
    problems: list[str] = []
    for cell in spec.cells:
        if cell.check is None:
            continue
        stub = cell.stub or ""
        on_stub = _grade(spec, cell.id, stub)
        if on_stub == "passed":
            problems.append(
                f"  {spec.slug}/{cell.id}: the check PASSES against the stub — it grades nothing, "
                f"and the reader is marked correct before attempting it"
            )
        on_source = _grade(spec, cell.id, cell.source)
        if on_source != "passed":
            problems.append(
                f"  {spec.slug}/{cell.id}: the check does not pass against the cell's own "
                f"solution (got {on_source!r}) — the exercise cannot be completed"
            )
    return problems


def _self_test() -> int:
    """Both arms must discriminate. A checker whose arms cannot go red proves nothing."""
    honest = NotebookSpec(
        slug="self-test-honest",
        title="Honest grader",
        cells=[
            Cell(
                id="ex",
                kind="code",
                source="def f(x):\n    return x + 1",
                stub="def f(x):\n    ...",
                check="assert f(1) == 2",
            )
        ],
    )
    # Passes on the stub: `...` makes f return None, and the check only asserts it exists.
    vacuous = NotebookSpec(
        slug="self-test-vacuous",
        title="Grader that cannot fail",
        cells=[
            Cell(
                id="ex",
                kind="code",
                source="def f(x):\n    return x + 1",
                stub="def f(x):\n    ...",
                check="assert callable(f)",
            )
        ],
    )
    # Fails on the author's own solution.
    impossible = NotebookSpec(
        slug="self-test-impossible",
        title="Grader nobody can pass",
        cells=[
            Cell(
                id="ex",
                kind="code",
                source="def f(x):\n    return x + 1",
                stub="def f(x):\n    ...",
                check="assert f(1) == 99",
            )
        ],
    )

    # The answer-key arm. Same discipline: a sound key must survive, and each defect
    # must be caught, or `audit_keys` is a call this script makes and learns nothing
    # from. Cheap enough to prove here because nothing executes.
    def _question(slug: str, answer: dict, source: str = "Which gate?") -> NotebookSpec:
        return NotebookSpec(
            slug=slug,
            title=slug,
            cells=[Cell(id="q", kind="markdown", role="question", source=source, answer=answer)],
        )

    def _quiz(slug: str, positions: list[int]) -> NotebookSpec:
        return NotebookSpec(
            slug=slug,
            title=slug,
            cells=[
                Cell(
                    id=f"q{i}",
                    kind="markdown",
                    role="question",
                    source=f"Question {i}?",
                    answer={"kind": "choice", "options": ["w", "x", "y", "z"], "correct": c},
                )
                for i, c in enumerate(positions)
            ],
        )

    # 16 evenly spread, which must survive; and 16 where 12 share one position, which is
    # 75%. Every key in the second is individually sound, so only the set-level check sees
    # it — the arm that would otherwise be added and never exercised.
    balanced_quiz = _quiz("self-test-quiz-balanced", [0, 1, 2, 3] * 4)
    guessable_quiz = _quiz("self-test-quiz-guessable", [1] * 12 + [0, 2, 3, 0])

    sound_key = _question(
        "self-test-key-sound", {"kind": "numeric", "value": 2.0, "tolerance": 0.1}
    )
    lazy_key = _question("self-test-key-lazy", {"kind": "numeric", "value": 2.0, "tolerance": 3.0})
    leaked_key = _question(
        "self-test-key-leaked",
        {"kind": "text", "accept": ["Hadamard"]},
        source="The Hadamard gate. Which gate was that?",
    )

    failures: list[str] = []
    if audit(honest):
        failures.append("an honest grader was reported as a problem")
    if audit_keys(sound_key):
        failures.append("a sound answer key was reported as a problem")
    if not any("cannot-fail" in p for p in audit_keys(lazy_key)):
        failures.append("a tolerance that accepts 0 was NOT caught")
    if not any("cannot-fail" in p for p in audit_keys(leaked_key)):
        failures.append("an answer printed in its own question was NOT caught")
    if audit_keys(balanced_quiz):
        failures.append("an evenly spread quiz was reported as a problem")
    if not any("to every question" in p for p in audit_keys(guessable_quiz)):
        failures.append("a quiz answerable by one repeated option was NOT caught")
    if not any("grades nothing" in p for p in audit(vacuous)):
        failures.append("a grader that passes on the stub was NOT caught")
    if not any("cannot be completed" in p for p in audit(impossible)):
        failures.append("a grader that fails on its own solution was NOT caught")
    # The third arm, and the one this script itself failed: an audit over nothing must
    # refuse. Proven against a real empty directory rather than asserted in a comment.
    with tempfile.TemporaryDirectory() as empty:
        if main([empty]) == 0:
            failures.append("an audit that discovered ZERO specs reported success")
    if failures:
        print("grader self-test FAILED:")
        for line in failures:
            print(f"  {line}")
        return 1
    print(
        "check_graders self-test passed (honest grader and sound key accepted; "
        "vacuous, impossible, lazy-tolerance, leaked-answer and one-key-passes all caught)"
    )
    return 0


def _specs(paths: list[str]) -> list[tuple[Path, NotebookSpec]]:
    """Every committed spec under `paths`, in both forms it is committed in.

    `.nb.py` is here because it is where the notebooks a reader actually works through
    live — the whole `curricula/` tree — and reading only `.json` meant this gate covered
    one fixture. It reported `0 answer key(s) read` while 57 keys sat in the certification
    quizzes, which is the shape of green this script was written to stop: a count of zero
    over a directory the checker could not see into reads exactly like a clean audit.
    """
    out: list[tuple[Path, NotebookSpec]] = []
    for raw in paths:
        p = Path(raw)
        files = sorted([*p.rglob("*.json"), *p.rglob("*.nb.py")]) if p.is_dir() else [p]
        for f in files:
            if f.name.endswith(".nb.py"):
                try:
                    out.append((f, parse_source(f.read_text(encoding="utf-8"))))
                except (OSError, ValueError) as exc:
                    print(f"  {f}: not a parseable notebook source — {exc}")
                continue
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            if not (isinstance(data, dict) and "cells" in data and "slug" in data):
                continue
            try:
                out.append((f, NotebookSpec.model_validate(data)))
            except ValueError as exc:
                print(f"  {f}: not a valid notebook spec — {exc}")
    return out


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return _self_test()
    targets = [a for a in argv if not a.startswith("-")] or ["packages/py/notebooks/fixtures"]
    specs = _specs(targets)
    if not specs:
        print(
            "check_graders: NO notebook specs found under "
            + ", ".join(targets)
            + " — refusing to report a clean audit over nothing. Point this at specs, or "
            "drop the step; a gate that passes on an empty set is worse than no gate."
        )
        return 1
    problems: list[str] = []
    for _, spec in specs:
        problems.extend(audit(spec))
        problems.extend(audit_keys(spec))
    if problems:
        print("Graders that do not grade:")
        print("\n".join(problems))
        return 1
    graded = sum(1 for _, s in specs for c in s.cells if c.check is not None)
    keyed = sum(1 for _, s in specs for c in s.cells if c.answer is not None)
    print(
        f"check_graders: clean ({graded} grader(s), both arms checked, and {keyed} answer "
        f"key(s) read, across {len(specs)} spec(s))"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
