"""Provider clients and structured prompts for chat and the circuit agent."""

from majorana_llm.client import (
    AnthropicLLM,
    LLMClient,
    LLMMessage,
    LLMRequest,
    LLMResponse,
    OpenAICompatibleLLM,
    RetryingLLM,
    default_llm,
    endpoint_for,
)
from majorana_llm.models import AnalysisOutput, model_for, resolve_provider
from majorana_llm.parsing import (
    StageOutputError,
    extract_code,
    extract_json,
    parse_analysis,
    parse_plan,
)
from majorana_llm.prompts import (
    CRITIC_SYSTEM_PROMPT,
    CONVERSATION_SYSTEM_PROMPT,
    FRAMEWORK_DIRECTIVE,
    GENERATE_SYSTEM_PROMPT,
    INTENT_ROUTER_SYSTEM_PROMPT,
    PLAN_SYSTEM_PROMPT,
    QUANTUM_AGENT_SYSTEM_PROMPT,
    RenderedPrompt,
    STAGE_PROMPTS,
    WRITEBACK_SYSTEM_PROMPT,
    render_analysis_prompt,
    render_conversation_prompt,
    render_generate_prompt,
    render_intent_prompt,
    render_plan_prompt,
)
from majorana_llm.research import ResearchResult, ResearchSource, research_for_prompt

__all__ = [
    "LLMClient",
    "LLMMessage",
    "LLMRequest",
    "LLMResponse",
    "AnthropicLLM",
    "OpenAICompatibleLLM",
    "RetryingLLM",
    "default_llm",
    "endpoint_for",
    "model_for",
    "resolve_provider",
    "AnalysisOutput",
    "parse_plan",
    "extract_code",
    "extract_json",
    "StageOutputError",
    "parse_analysis",
    "PLAN_SYSTEM_PROMPT",
    "GENERATE_SYSTEM_PROMPT",
    "CRITIC_SYSTEM_PROMPT",
    "INTENT_ROUTER_SYSTEM_PROMPT",
    "CONVERSATION_SYSTEM_PROMPT",
    "QUANTUM_AGENT_SYSTEM_PROMPT",
    "WRITEBACK_SYSTEM_PROMPT",
    "FRAMEWORK_DIRECTIVE",
    "STAGE_PROMPTS",
    "RenderedPrompt",
    "render_plan_prompt",
    "render_generate_prompt",
    "render_analysis_prompt",
    "render_conversation_prompt",
    "render_intent_prompt",
    "ResearchResult",
    "ResearchSource",
    "research_for_prompt",
]
