"""Provider clients and structured prompts for chat and the circuit agent."""

from majorana_llm.client import (
    AnthropicLLM,
    LLMClient,
    LLMMessage,
    LLMProviderError,
    LLMRequest,
    LLMResponse,
    OpenAICompatibleLLM,
    RetryingLLM,
    default_llm,
    endpoint_for,
    classify_provider_error,
    attempt_timeout_seconds,
    conversation_request_messages,
    missing_provider_keys,
    provider_timeout_seconds,
    request_messages,
    stage_budget,
)
from majorana_llm.models import model_for, resolve_provider, roles_for_profile
from majorana_llm.parsing import (
    StageOutputError,
    extract_json,
)
from majorana_llm.prompt_locale import (
    ResponseLocale,
    normalize_response_locale,
    with_response_locale,
)

from majorana_llm.prompts import (
    CHAT_SYSTEM_PROMPT,
    AI_ASSUMPTION_MODE_DIRECTIVE,
    CONVERSATION_TITLE_SYSTEM_PROMPT,
    FRAMEWORK_DIRECTIVE,
    INTENT_ROUTER_SYSTEM_PROMPT,
    QAPP_GENERATION_SYSTEM_PROMPT,
    RUN_EXPLANATION_SYSTEM_PROMPT,
    SIMPLE_ARTIFACT_REVIEW_SYSTEM_PROMPT,
    SIMPLE_BUSINESS_REFERENCE_EXTRACTION_SYSTEM_PROMPT,
    SIMPLE_CONVERSATION_PLAN_ALIGNMENT_SYSTEM_PROMPT,
    SIMPLE_DYNAMICS_REFERENCE_AUDIT_SYSTEM_PROMPT,
    SIMPLE_GENERATION_SYSTEM_PROMPT,
    SIMPLE_LINDBLAD_REFERENCE_EXTRACTION_SYSTEM_PROMPT,
    SIMPLE_LINEAR_SYSTEM_REFERENCE_EXTRACTION_SYSTEM_PROMPT,
    SIMPLE_PLAN_SYSTEM_PROMPT,
    SIMPLE_REFERENCE_AUDIT_SYSTEM_PROMPT,
    SIMPLE_REVIEW_SYSTEM_PROMPT,
    RESEARCH_TRIAGE_SYSTEM_PROMPT,
    RenderedPrompt,
    render_conversation_title_prompt,
    render_intent_prompt,
    simple_generation_system_prompt,
    with_execution_conversation_context,
)

__all__ = [
    "LLMClient",
    "attempt_timeout_seconds",
    "provider_timeout_seconds",
    "stage_budget",
    "LLMMessage",
    "LLMProviderError",
    "LLMRequest",
    "LLMResponse",
    "AnthropicLLM",
    "OpenAICompatibleLLM",
    "RetryingLLM",
    "default_llm",
    "endpoint_for",
    "classify_provider_error",
    "conversation_request_messages",
    "request_messages",
    "missing_provider_keys",
    "model_for",
    "resolve_provider",
    "roles_for_profile",
    "extract_json",
    "StageOutputError",
    "INTENT_ROUTER_SYSTEM_PROMPT",
    "QAPP_GENERATION_SYSTEM_PROMPT",
    "RUN_EXPLANATION_SYSTEM_PROMPT",
    "CHAT_SYSTEM_PROMPT",
    "AI_ASSUMPTION_MODE_DIRECTIVE",
    "CONVERSATION_TITLE_SYSTEM_PROMPT",
    "SIMPLE_ARTIFACT_REVIEW_SYSTEM_PROMPT",
    "SIMPLE_GENERATION_SYSTEM_PROMPT",
    "SIMPLE_LINDBLAD_REFERENCE_EXTRACTION_SYSTEM_PROMPT",
    "SIMPLE_LINEAR_SYSTEM_REFERENCE_EXTRACTION_SYSTEM_PROMPT",
    "SIMPLE_BUSINESS_REFERENCE_EXTRACTION_SYSTEM_PROMPT",
    "SIMPLE_CONVERSATION_PLAN_ALIGNMENT_SYSTEM_PROMPT",
    "SIMPLE_DYNAMICS_REFERENCE_AUDIT_SYSTEM_PROMPT",
    "SIMPLE_PLAN_SYSTEM_PROMPT",
    "SIMPLE_REFERENCE_AUDIT_SYSTEM_PROMPT",
    "SIMPLE_REVIEW_SYSTEM_PROMPT",
    "RESEARCH_TRIAGE_SYSTEM_PROMPT",
    "FRAMEWORK_DIRECTIVE",
    "RenderedPrompt",
    "render_conversation_title_prompt",
    "render_intent_prompt",
    "simple_generation_system_prompt",
    "with_execution_conversation_context",
    "ResponseLocale",
    "normalize_response_locale",
    "with_response_locale",
]
